force-app/main/default/objects/IPIA_Acknowledgement__c/IPIA_Acknowledgement__c.object-meta.xml
<CustomObject>
    <label>IPIA Acknowledgement</label>
    <nameField>
        <label>IPIA Acknowledgement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPIA Acknowledgements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Acknowledgement__c/fields/Acknowledged__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Acknowledged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IPIA_Acknowledgement__c/fields/Date_Acknowledged__c.field-meta.xml
<CustomField>
    <fullName>Date_Acknowledged__c</fullName>
    <label>Date Acknowledged</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IPIA_Acknowledgement__c/fields/MIT_Id__c.field-meta.xml
<CustomField>
    <fullName>MIT_Id__c</fullName>
    <externalId>true</externalId>
    <label>MIT Id</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IpiaRecordFetch.cls
public with sharing class IpiaRecordFetch {

    @AuraEnabled(cacheable=true)
    public static IPIA_Acknowledgement__c getIpiaAckByMitId(String mitid) {
        System.debug('**IPIA Get**');
        System.debug(mitid);

        IPIA_Acknowledgement__c ipiaAck = [
            SELECT
                Name,
                Date_Acknowledged__c,
                Acknowledged__c,
                Mit_Id__c
            FROM IPIA_Acknowledgement__c
            WHERE Mit_Id__c = :mitid
            LIMIT 1
        ];

        return ipiaAck;
    }

    @AuraEnabled
    public static String deleteIpiaRecords(String recordId) {
        try {
            IPIA_Record__c ipiaRecord = [
                SELECT Id 
                FROM IPIA_Record__c 
                WHERE Id = :recordId
                LIMIT 1
            ];

            delete ipiaRecord;

            return 'Success';
        } catch (DmlException e) {
            String errorMessage = '';
            for (Integer i = 0; i < e.getNumDml(); i++) {
                errorMessage += e.getDmlMessage(i) + ' ';
            }

            // Return error message if the deletion fails
            return errorMessage;
        }
    }
    
}