force-app/main/default/objects/TLO_Contact_Update_Request__c/TLO_Contact_Update_Request__c.object-meta.xml
<CustomObject>
    <description>Holds requested / recommended updates for a TLO Contact</description>
    <label>TLO Contact Update Request</label>
    <nameField>
        <displayFormat>CRU-{000000}</displayFormat>
        <label>TLO Contact Update Requests ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TLO_Contact Update Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>TLO_Contact_Update_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Current_Email__c.field-meta.xml
<CustomField>
    <fullName>Current_Email__c</fullName>
    <formula>Contact__r.PersonEmail</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Current_Institution__c.field-meta.xml
<CustomField>
    <fullName>Current_Institution__c</fullName>
    <formula>Contact__r.Institution__pc</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Institution</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Update_Status__c.field-meta.xml
<CustomField>
    <fullName>Update_Status__c</fullName>
    <description>Status indication whether TLO Ops has updated the Contact details or not. Defaults to Pending</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TLOContactUpdateRequestTriggerHandler.cls
public class TLOContactUpdateRequestTriggerHandler {
    /**
     * Trigger handler for TLO_Contact_Update_Request__c before update events
     * @param tloContactUpdateRequestList List of new TLO_Contact_Update_Request__c objects to be processed
     */
    public static void onBeforeUpdate(
        List<TLO_Contact_Update_Request__c> tloContactUpdateRequestList
    ) {
        validateStatusChange(tloContactUpdateRequestList);
    }

    /**
     * Validate an TLO_Contact_Update_Request__c object
     * @param tloContactUpdateRequestList List of TLO_Contact_Update_Request__c objects to be processed
     */
    private static void validateStatusChange(
        List<TLO_Contact_Update_Request__c> tloContactUpdateRequestList
    ) {
        Set<Id> contactIds = new Set<Id>();
        for (
            TLO_Contact_Update_Request__c tloCur : tloContactUpdateRequestList
        ) {
            contactIds.add(tloCur.Contact__c);
        }

        List<Account> contactList = [
            SELECT Id, MoiraStatus__pc, PersonEmail, Institution__pc
            FROM Account
            WHERE Id = :contactIds AND IsPersonAccount = TRUE
        ];
        Map<Id, Account> contactLookup = new Map<Id, Account>(contactList);

        for (
            TLO_Contact_Update_Request__c contactUpReq : tloContactUpdateRequestList
        ) {
            if (contactUpReq.Update_Status__c != 'Pending') {
                if (String.isBlank(contactUpReq.Current_Email__c)) {
                    contactUpReq.Current_Email__c.addError(
                        label.ChangedContactUpdateReqStatusValidation
                    );
                }

                if (String.isBlank(contactUpReq.Current_Institution__c)) {
                    contactUpReq.Current_Institution__c.addError(
                        label.ChangedContactUpdateReqStatusInstitutionValidation
                    );
                }

                //TODO do we need to do the query & check contact itself if there are formula fields on this object back to the contact already?
                Account contact = contactLookup.get(contactUpReq.Contact__c);
                if (contact.PersonEmail != null) {
                    Boolean contactContainsMitEmail = Helpers.isMitEmailAddress(
                        contact.PersonEmail
                    );
                    if (
                        !Helpers.isActiveKerb(contact.MoiraStatus__pc) &&
                        contactContainsMitEmail
                    ) {
                        contactUpReq.Update_Status__c.addError(
                            label.ChangedContactUpdateReqEmailValidation
                        );
                    }
                }
            }
        }
    }
}