force-app/main/default/objects/Cleanup_Config__c/Cleanup_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Cleanup Config</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Config__c/fields/Older_Than_x_Days__c.field-meta.xml
<CustomField>
    <fullName>Older_Than_x_Days__c</fullName>
    <label>Older Than x Days</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Config__c/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Config__c/fields/Unit_of_Time__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Time__c</fullName>
    <label>Unit of Time</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CleanupRecordBatchSchedule.cls
public with sharing class CleanupRecordBatchSchedule implements Schedulable {
    
    public final static String CLEANUP_JOB_NAME_INITIAL = 'RECORD CLEANUP';
    
    public String sObjectName {get; set;}
    public Integer numberOfDays{get;set;} 
    public String olderThan{get;set;} 
    
    public CleanupRecordBatchSchedule(String sObjectName, Integer numberOfDays, String olderThan) {
        this.sObjectName = sObjectName;
        this.numberOfDays = numberOfDays;
        this.olderThan = this.olderThan;
    }
    
    public static void scheduleMeForCleanUp() {
        List<Cleanup_Config__c> configList = [SELECT Id, 
                                                Older_Than_x_days__c, 
                                                sObject_Name__c, 
                                                Unit_of_Time__c 
                                            FROM 
                                                Cleanup_Config__c 
                                            LIMIT 100];
        if(configList != null && !configList.isEmpty()) {
            for(Cleanup_Config__c config:configList) {
                CleanupRecordBatchSchedule sch = new CleanupRecordBatchSchedule(config.sObject_Name__c, Integer.valueOf(config.Older_Than_x_days__c), config.Unit_of_Time__c);
                System.schedule(CLEANUP_JOB_NAME_INITIAL + config.sObject_Name__c, config.Older_Than_x_days__c, sch);
            }
        }
    }
    
    public static void abortSchedule() {
        List<CronTrigger> triggers = [SELECT  Id, CronJobDetailId, State, CronExpression, OwnerId ,CronJobDetail.Name FROM CronTrigger];
        for(CronTrigger delCron: triggers)  {
            String cronJobName = delCron.CronJobDetail.Name;
            if(cronJobName != null && cronJobName.startsWith(CLEANUP_JOB_NAME_INITIAL)) {
                System.abortJob(delCron.Id);
            }
        }
    }
    public void execute(SchedulableContext sc) {
        CleanupRecordBatch sfu = new CleanupRecordBatch(sObjectName, numberOfDays, olderThan);
        Database.executeBatch(sfu, 200);        
    }
}