force-app/main/default/objects/Utilization_Licensee__c/Utilization_Licensee__c.object-meta.xml
<CustomObject>
    <description>Licensee with license counts</description>
    <label>Utilization Licensee</label>
    <nameField>
        <label>Licensee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipName>Utilization_Licensee_Counts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Case_RecId__c.field-meta.xml
<CustomField>
    <fullName>Case_RecId__c</fullName>
    <label>Case</label>
    <length>24</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>Utilization Reports</relationshipLabel>
    <relationshipName>Utilization_Reports_Case</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Case_RecId_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>Case_RecId_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Case RecId ExternalId</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Commercialization_Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Commercialization_Plan_Id__c</fullName>
    <label>Commercialization Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Seeking additional funding to further develop this invention</label>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>Marketing and/or furthering development of this invention to attract commercial
                    partners</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Developing and/or using this invention for internal purposes only</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Developing and/or preparing this invention with intent to commercialize ourselves</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Making available for distribution and/or licensing for research purposes only</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>No current commercialization plan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/DOE_S_number__c.field-meta.xml
<CustomField>
    <fullName>DOE_S_number__c</fullName>
    <description>DOE S-number</description>
    <label>DOE S Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Election_Status__c.field-meta.xml
<CustomField>
    <fullName>Election_Status__c</fullName>
    <label>Election Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elect to Retain Title</fullName>
            </value>
            <value>
                <fullName>Does Not Retain Title</fullName>
            </value>
            <value>
                <fullName>Designated as Unpatented Biological Material or Research Tool</fullName>
            </value>
            <value>
                <fullName>Under Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/First_Commercial_Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>First_Commercial_Year_of_Sale__c</fullName>
    <label>First Commercial Year of Sale</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_First_Commercial_Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>Forrester_First_Commercial_Year_of_Sale__c</fullName>
    <label>Forrester First Commercial Year of Sale</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Forrester_Latest_Stage_of_Development__c</fullName>
    <label>Forrester Latest Stage of Development</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Docket_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Docket_Number__c</fullName>
    <description>Invention Docket Number</description>
    <label>Invention Docket Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Invention_Report_Date__c</fullName>
    <label>Invention Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Report_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Report_Number__c</fullName>
    <label>Invention Report Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Title__c.field-meta.xml
<CustomField>
    <fullName>Invention_Title__c</fullName>
    <label>Invention Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_1__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_1__c</fullName>
    <label>Is US Manufacturing Required 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_2__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_2__c</fullName>
    <label>Is US Manufacturing Required 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_3__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_3__c</fullName>
    <label>Is US Manufacturing Required 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Latest_Stage_of_Development__c</fullName>
    <label>Latest Stage of Development</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Commercialized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Companies__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Companies__c</fullName>
    <label>New US Companies</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Jobs__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Jobs__c</fullName>
    <label>New US Jobs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <label>Reporting Year</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Status__c</fullName>
    <description>Status</description>
    <label>Utilization Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Include for Utilization</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Title__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Title__c</fullName>
    <formula>Name &amp; &quot; - &quot; &amp; Invention_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Utilization Report Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report_Config__c/Utilization_Report_Config__c.object-meta.xml
<CustomObject>
    <label>Utilization Reports FY Config</label>
    <nameField>
        <displayFormat>URC-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports FY Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report_Config__c/fields/Agreement_Types__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Types__c</fullName>
    <label>Agreement Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AGENCY</fullName>
                <label>Agency</label>
            </value>
            <value>
                <fullName>ASSIGN</fullName>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>GOVUSE</fullName>
                <label>Government Use License</label>
            </value>
            <value>
                <fullName>INST</fullName>
                <label>Institution</label>
            </value>
            <value>
                <fullName>JOI NO</fullName>
                <label>Joint - No Purple File</label>
            </value>
            <value>
                <fullName>JOINT</fullName>
                <label>Joint Ownership</label>
            </value>
            <value>
                <fullName>LIC</fullName>
                <label>License</label>
            </value>
            <value>
                <fullName>BY-AGT</fullName>
                <label>License by Agent</label>
            </value>
            <value>
                <fullName>LIC NO</fullName>
                <label>License - No Purple File</label>
            </value>
            <value>
                <fullName>MASTER</fullName>
                <label>Master Agreement</label>
            </value>
            <value>
                <fullName>MTA</fullName>
                <label>Material Transfer Agreement</label>
            </value>
            <value>
                <fullName>MOU</fullName>
                <label>Memo of Understanding</label>
            </value>
            <value>
                <fullName>OPT</fullName>
                <label>Option</label>
            </value>
            <value>
                <fullName>OBYAGN</fullName>
                <label>Option by Agent</label>
            </value>
            <value>
                <fullName>PUBL</fullName>
                <label>Publishing</label>
            </value>
            <value>
                <fullName>SW-EU</fullName>
                <label>Software End Use</label>
            </value>
            <value>
                <fullName>SW-LIC</fullName>
                <label>Software End Use Licenses &gt; 1K</label>
            </value>
            <value>
                <fullName>SUBLIC</fullName>
                <label>Sublicense</label>
            </value>
            <value>
                <fullName>TECHTR</fullName>
                <label>Tech Transfer</label>
            </value>
            <value>
                <fullName>TRACKG</fullName>
                <label>Tracking</label>
            </value>
            <value>
                <fullName>TM</fullName>
                <label>Trademark</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report_Config__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EdisonInventionSearchJob.cls
public with sharing class EdisonInventionSearchJob implements Queueable, Database.AllowsCallouts  {
    private Boolean onlyErrorItems;
    
    public EdisonInventionSearchJob(Boolean onlyErrors) {
        onlyErrorItems = onlyErrors;
    }

    public void start(QueueableContext ctx) {
        System.debug('EdisonInventionSearchJob:start ' + ctx.getJobId());
    }

    public void execute(QueueableContext ctx) {
        IEdisonService iEdisonService = new IEdisonService();
        Integer batchSize = 100;
        Integer r_limit = 100;
        Integer offset  = 0;
        Integer totalRecords = 0;
        IEdisonInventionSearchResponse responseInvention;
        IEdisonUtilizationSearchResponse responseCurrentYearUtilization;
        IEdisonUtilizationSearchResponse responsePreviousYearUtilization;
        List<IEdisonInventionResponse> inventions = new List<IEdisonInventionResponse>();
        List<ForresterDto.UtilizationDto> forresterUtilizations = new List <ForresterDto.UtilizationDto>();
        List<IEdisonUtilizationResponse> currentYearUtilizations = new List<IEdisonUtilizationResponse>();
        List<IEdisonUtilizationResponse> previousYearUtilizations = new List<IEdisonUtilizationResponse>();
        List<Utilization_Report__c> insertList = new List<Utilization_Report__c>();
        List<Utilization_Report__c> updateList = new List<Utilization_Report__c>();
        List<Utilization_Licensee__c> insertLicenseeList = new List<Utilization_Licensee__c>();
        List<String> inventionReportNumbers = new List<String>();
        List<String> inventionDocketNumbers = new List<String>();
        List<String> forresterUtilizationsCaseNumbers = new List<String>();
        List<String> currentYearUtilizationReportNumbers = new List<String>();
        List<String> previousYearUtilizationReportNumbers = new List<String>();
        List<String> titleElectionStatus = new List<String>();
        List<Exception> exceptions =  new List<Exception>();
        titleElectionStatus.add('Elect to Retain Title');
        titleElectionStatus.add('Designated as Unpatented Biological Material or Research Tool');
        String granteeOrganizationName  = 'MASSACHUSETTS INSTITUTE OF TECHNOLOGY';
        try {

            Utilization_Report_Config__c  fyConfig = [
                SELECT
                    Name,
                    Fiscal_Year__c,
                    Start_Date__c,
                    End_Date__c,
                    Agreement_Types__c
                FROM Utilization_Report_Config__c
                ORDER BY Fiscal_Year__c DESC , LastModifiedDate DESC
                LIMIT 1
            ];

            List<String>  existingReportNumbers = new List<String>();
            Map<String,Id>  existingReportIds = new Map<String,Id>();
            List<SObject> repNumbers;
            if (onlyErrorItems) {
                repNumbers = new Map<String,SObject> (
                    [
                    SELECT Id, Invention_Report_Number__c
                    FROM Utilization_Report__c
                    WHERE Reporting_Year__c = :fyConfig.Fiscal_Year__c
                    AND Case_RecId__c = '' and Utilization_Report_Status__c = 'Error'
                    ORDER BY LastModifiedDate
                    LIMIT :batchSize 
                    ]
                ).values();
            } else {
                repNumbers = new Map<String,SObject> (
                    [
                    SELECT Id, Invention_Report_Number__c
                    FROM Utilization_Report__c
                    WHERE Reporting_Year__c = :fyConfig.Fiscal_Year__c
                    ]
                ).values();
            }
            for(SObject item : repNumbers) {
                String repNumber = (String)item.get('Invention_Report_Number__c');
                Id reportId = (Id)item.get('Id');
                existingReportNumbers.Add(repNumber);
                existingReportIds.put(repNumber, reportId);
            }

            offset = 0;
            do {
                responseInvention = iEdisonService.searchInvention(r_limit, offset, '', '', titleElectionStatus, '', granteeOrganizationName);
                offset = offset + 1;
                totalRecords = r_limit * offset;
                
                for (IEdisonInventionResponse invention : responseInvention.inventions) {
                    if (onlyErrorItems) {
                        if (existingReportNumbers.contains(invention.inventionReportNumber)) {
                            inventions.add(invention);
                            inventionReportNumbers.add(invention.inventionReportNumber);
                            inventionDocketNumbers.add(invention.inventionDocketNumber);
                        }
                    } else {
                        if (!existingReportNumbers.contains(invention.inventionReportNumber)) {
                            inventions.add(invention);
                            inventionReportNumbers.add(invention.inventionReportNumber);
                            inventionDocketNumbers.add(invention.inventionDocketNumber);
                        }
                    }
                    if (inventions.size() >= batchSize) {
                        break;
                    }
                }
            }   
            while (totalRecords < responseInvention.totalRecords && inventions.size() < batchSize );
            System.debug('inventionReportNumbers:' + JSON.serialize(inventionReportNumbers));

            totalRecords = 0;
            List<String> queryParamCaseNumbers = new List<String>();
            do {
                queryParamCaseNumbers.clear();
                for (Integer i = totalRecords; i < inventionDocketNumbers.size(); i++) {
                    totalRecords = totalRecords + 1;
                    String inventionDocketNumber = inventionDocketNumbers[i];
                    if (queryParamCaseNumbers.size() < 25) {
                        queryParamCaseNumbers.add(inventionDocketNumber);
                    } else {
                        break;
                    }
                }
                if (queryParamCaseNumbers.size() > 0) {
                    ForresterDto.UtilizationListDto utilizationData = iEdisonService.getForresterUtilizationData(queryParamCaseNumbers, Helpers.formatDate(fyConfig.Start_Date__c), Helpers.formatDate(fyConfig.End_Date__c), fyConfig.Agreement_Types__c);
                    if (utilizationData == null) {
                        break;
                    }
                    if (utilizationData.results == null) {
                        break;
                    }
                    if (utilizationData.results.size() == 0) {
                        break;
                    }
                    forresterUtilizations.addAll(utilizationData.results);
                    for (ForresterDto.UtilizationDto utilizationDto : utilizationData.results) {
                        if ( utilizationDto.caseNumber != null) {
                            forresterUtilizationsCaseNumbers.add(StringUtils.removeNonNumericCharacters(utilizationDto.caseNumber));
                        } else {
                            //Error
                            forresterUtilizationsCaseNumbers.add(IEdisonServiceResponseToReport.GetCaseNumberFromError(utilizationDto.message));
                        }
                    }
                }
            }
            while (totalRecords <  inventionDocketNumbers.size());
 
            offset = 0;
            do {
                responseCurrentYearUtilization = iEdisonService.searchUtilization(r_limit, offset, '', '', new List<String>(), Integer.valueOf(fyConfig.Fiscal_Year__c), '');
                offset = offset + 1;
                totalRecords = r_limit * offset;
                currentYearUtilizations.addAll(responseCurrentYearUtilization.utilizations);
                for (IEdisonUtilizationResponse utilization : responseCurrentYearUtilization.utilizations) {
                    currentYearUtilizationReportNumbers.add(utilization.inventionReportNumber);
                }
            }   
            while (totalRecords < responseCurrentYearUtilization.totalRecords);
            System.debug('currentYearUtilizationReportNumbers:' + JSON.serialize(currentYearUtilizationReportNumbers));

            //Removed as no data from previous reports are required
            // offset = 0;
            // do {
            //     responsePreviousYearUtilization = iEdisonService.searchUtilization(r_limit, offset, '', '', new List<String>(), Integer.valueOf(fyConfig.Fiscal_Year__c) - 1, '');
            //     offset = offset + 1;
            //     totalRecords = r_limit * offset;
            //     previousYearUtilizations.addAll(responsePreviousYearUtilization.utilizations);
            //     for (IEdisonUtilizationResponse utilization : responsePreviousYearUtilization.utilizations) {
            //         previousYearUtilizationReportNumbers.add(utilization.inventionReportNumber);
            //     }
            // }   
            // while (totalRecords < responsePreviousYearUtilization.totalRecords);
            // System.debug('previousYearUtilizationReportNumbers:' + JSON.serialize(previousYearUtilizationReportNumbers));
           
            if (!inventions.isEmpty()) {
                System.debug('inventions_size:-' + inventions.size().toString());
                for (IEdisonInventionResponse invention : inventions) {
                    System.debug('invention:' + JSON.serialize(invention));
                    try {
                        Utilization_Report__c report = new Utilization_Report__c();
                        if (onlyErrorItems) {
                            if (existingReportIds.containsKey(invention.inventionReportNumber)) {
                            Id reportId = existingReportIds.get(invention.inventionReportNumber);
                            report = [SELECT 
                                    Id, 
                                    Name,
                                    Invention_Docket_Number__c,
                                    Invention_Report_Number__c,
                                    Invention_Report_Date__c,
                                    Invention_Title__c,
                                    Reporting_Year__c,
                                    Latest_Stage_of_Development__c,
                                    Forrester_Latest_Stage_of_Development__c,
                                    Utilization_Report_Status__c,
                                    Utilization_Report_Title__c,
                                    First_Commercial_Year_of_Sale__c,
                                    Forrester_First_Commercial_Year_of_Sale__c,
                                    Total_Income__c,
                                    New_Us_Jobs__c,
                                    New_Us_Companies__c,
                                    Notes__c,
                                    Commercialization_Plan_Id__c,
                                    Is_US_Manufacturing_Required_1__c,
                                    Is_US_Manufacturing_Required_2__c,
                                    Is_US_Manufacturing_Required_3__c,
                                    Error_Messages__c,
                                    Case_RecId__c,
                                    Case_RecId_ExternalId__c,
                                    DOE_S_number__c,
                                    Election_Status__c,
                                    Exclusive_Licenses_Name__c,
                                    Forrester_Exclusive_Optionee_Name__c,
                                    Forrester_Non_Exclusive_Optionee_Name__c,
                                    Forrester_Small_Business_Optionee_Name__c,
                                    Forrester_Other_Income_and_Equity__c,
                                    Forrester_Royalties_on_Sales__c,
                                    Forrester_Summarized_Agreement_Income__c,
                                    Funding_Agency__c,
                                    Funding_Grant_Number__c,
                                    Grantee_Organization_Name__c,
                                    Non_Exclusive_Licenses_Name__c,
                                    Primary_Agency__c,
                                    Product_Name__c,
                                    Small_Business_Licenses_Name__c,
                                    Title_Election_Date__c,
                                    Utilization_Created_Date__c,
                                    Utilization_Submitted_Date__c,
                                    Utilization_Updated_Date__c
                                FROM Utilization_Report__c
                                WHERE Id = :reportId LIMIT 1];
                            }
                        }
                        report.Utilization_Report_Status__c = 'New';
                        report.Error_Messages__c = '';
                        report.Reporting_Year__c = fyConfig.Fiscal_Year__c;

                        Integer listIndex = 0;

                        //Removed as no data from previous reports are required
                        // listIndex = previousYearUtilizationReportNumbers.indexOf(invention.inventionReportNumber);
                        // if (listIndex >= 0) {
                        //     IEdisonUtilizationResponse  previousYearUtilization = previousYearUtilizations.get(listIndex);
                        //     iEdisonService.mapPreviousYearUtilizationToReport(report, previousYearUtilization);
                        // }

                        listIndex = currentYearUtilizationReportNumbers.indexOf(invention.inventionReportNumber);
                        if (listIndex >= 0) {
                            IEdisonUtilizationResponse  currentYearUtilization =  currentYearUtilizations.get(listIndex);
                            if (currentYearUtilization != null) {
                                report.Utilization_Report_Status__c = 'Completed';
                            }
                        }

                        listIndex = forresterUtilizationsCaseNumbers.indexOf(invention.inventionDocketNumber.removeEndIgnoreCase('L'));
                        if (listIndex >= 0) {
                            ForresterDto.UtilizationDto forresterUtilization =  forresterUtilizations.get(listIndex);
                            if (forresterUtilization.status == 'SUCCESS') {
                                iEdisonService.mapForresterUtilizationToReport(report, forresterUtilization);
                                if (report.Utilization_Report_Status__c != 'Completed') {
                                    iEdisonService.mapInitialForresterUtilizationToReport(report, forresterUtilization);
                                }
                            } else {
                                report.Utilization_Report_Status__c = 'Error';
                                if (forresterUtilization.responseCode == 400 ) {
                                    report.Error_Messages__c = JSON.serialize(forresterUtilization, true);
                                }
                            }
                        } else {
                            if (report.Utilization_Report_Status__c != 'Completed') {
                                report.Utilization_Report_Status__c = 'Error';
                            }
                        }

                        iEdisonService.mapInventionToReport(report, invention);
                        
                        insertList.add(report);
                        if (insertList.size() >= batchSize) {
                            break;
                        }
                    } catch (Exception e) {
                        System.debug('inner:-' + e.getMessage());
                        exceptions.add(e);
                        
                    }
                }

                if (insertList.size() > 0) {
                    // Save the parent objects
                    if (onlyErrorItems) {
                        //preivous error items already exist, thus always just update
                        update insertList;
                    } else {
                        insert insertList; 
                    }
                    System.debug('insertList:' + JSON.serialize(insertList));

                    //Add the children
                    for (Utilization_Report__c report : insertList) {
                        Integer listIndex;
                        listIndex = forresterUtilizationsCaseNumbers.indexOf(report.Invention_Docket_Number__c.removeEndIgnoreCase('L'));
                        if (listIndex >= 0) {
                            updateList.Add(report);
                            ForresterDto.UtilizationDto forresterUtilization =  forresterUtilizations.get(listIndex);
                            if (report.Utilization_Report_Status__c != 'Completed') {
                                List<Utilization_Licensee__c> licenseeList =  iEdisonService.mapInitalLicenseeNameAndCounts(report, forresterUtilization);                     
                                insertLicenseeList.addAll(licenseeList);
                            } 
                        }
                    }
                }

                if (insertLicenseeList.size() > 0) {
                    insert insertLicenseeList;
                }
                if (updateList.size() > 0) {
                    update updateList;
                }

                // Update from already captured reports in iEdison
                for (Utilization_Report__c report : insertList) {
                    Integer forresterlistIndex;
                    ForresterDto.UtilizationDto forresterUtilization = null;
                    forresterlistIndex = forresterUtilizationsCaseNumbers.indexOf(report.Invention_Docket_Number__c.removeEndIgnoreCase('L'));
                    if (forresterlistIndex >= 0) {
                        forresterUtilization =  forresterUtilizations.get(forresterlistIndex);
                    }
                    Integer listIndex;
                    if (report.Utilization_Report_Status__c == 'Completed') {
                        listIndex = currentYearUtilizationReportNumbers.indexOf(report.Invention_Report_Number__c);
                        if (listIndex >= 0) {
                            IEdisonUtilizationResponse  currentYearUtilization =  currentYearUtilizations.get(listIndex);
                            if (currentYearUtilization != null) {
                                IEdisonServiceResponseToReport.mapUtilizationResponseToReport(report, currentYearUtilization, forresterUtilization);
                            }
                        }
                    }
                }
            }
 
            for (Exception e : exceptions) {
                HandleLogException.logException(e);
            }

        } catch (Exception e) {
            System.debug(e.getMessage());
            HandleLogException.logException(e);
        }
    }
}