force-app/main/default/objects/BioTang_Disclosure__c/BioTang_Disclosure__c.object-meta.xml
<CustomObject>
    <label>BioTang Disclosure</label>
    <nameField>
        <label>BioTang Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BioTang Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BioTang_Disclosure__c/fields/disclosure__c.field-meta.xml
<CustomField>
    <fullName>disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match BioTang Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BioTang_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>BioTang Disclosure</relationshipLabel>
    <relationshipName>BioTang_Disclosure</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BioTang_Disclosure__c/recordTypes/cellLine.recordType-meta.xml
<RecordType>
    <fullName>cellLine</fullName>
    <active>true</active>
    <label>Cell Line</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Signing_Envelop_Id__c.field-meta.xml
<CustomField>
    <fullName>Signing_Envelop_Id__c</fullName>
    <description>This field contains the envelopId from DocuSign which is unique to this Disclosure.</description>
    <externalId>true</externalId>
    <label>Signing Envelop Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/BioTang_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>BioTang_Disclosure</fullName>
    <active>true</active>
    <label>Biological and Tangible Property</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DocumentGenerateEmbeddedSigningAPITest.cls
@IsTest
public class DocumentGenerateEmbeddedSigningAPITest {
    private static String disclosureName = '';

    @TestSetup
    static void setupTestData() {
        TestSetup.defaultDocTemplatesConfiguration();
        TestSetup.defaultConfiguration();
    }

    @IsTest
    public static void testGenerateEmbeddedSigningUrl() {
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Id recordTypeIdCellLine = Schema.SObjectType.BioTang_Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('cellLine')
            .getRecordTypeId();

        Account inventorContact = SampleDataFactory.createContact(
            'Peter',
            true,
            '777777777'
        );
        Account mitShipperContact = SampleDataFactory.createContact(
            'John',
            false,
            '12345678'
        );
        Account piContact = SampleDataFactory.createContact(
            'Paul',
            true,
            '77777700'
        );
        Account fundingPiContact = SampleDataFactory.createContact(
            'Henry',
            true,
            '23200'
        );

        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'Sample Draft BioTang',
            'Draft',
            inventorContact
        );
        SampleDataFactory.createDisclosureExternalFunding(
            disclosure,
            '12345',
            '6789',
            fundingPiContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosure,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(disclosure);
        BioTang_Disclosure__c newDraftBioSample = SampleDataFactory.createBioTang(
            'Sample Draft BioTang',
            disclosure,
            recordTypeIdCellLine,
            piContact,
            mitShipperContact
        );
        SampleDataFactory.createCellLine('Cell Line Sample', newDraftBioSample);
        SampleDataFactory.createLabMaterials(
            'Lab Material 1',
            newDraftBioSample
        );
        SampleDataFactory.createLabMaterials(
            'Lab Material 2',
            newDraftBioSample
        );

        DisclosureInventor__c inventor = SampleDataFactory.createInventor(
            disclosure,
            true,
            inventorContact
        );

        // Fake that envelop has been created and set against the disclosure
        Disclosure__c disclosureToUpdate = [
            SELECT Id
            FROM Disclosure__c
            WHERE Id = :disclosure.Id
        ];
        disclosureToUpdate.Signing_Envelop_Id__c = '123456789';
        update disclosureToUpdate;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = 'api/embedded-signing/v1';
        req.httpMethod = 'GET';
        req.params.put('disclosureId', disclosure.Id);
        req.params.put('inventorId', inventor.Id);

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        DocuSignApiMock docuSignApiMock = new DocuSignApiMock();
        docuSignApiMock.inventorId = inventor.Id;

        Test.setMock(HttpCalloutMock.class, docuSignApiMock);

        String result = DocumentGenerateEmbeddedSigningAPI.generateEmbeddedSigningUrl();
        Map<String, Object> inventorSigningUrlMap = (Map<String, Object>) JSON.deserializeUntyped(
            result
        );
        String embeddedSigningUrlResponse = String.valueOf(
            inventorSigningUrlMap.get('url')
        );
        System.debug(
            'embeddedSigningUrlResponse: ' + embeddedSigningUrlResponse
        );
        Test.stopTest();

        String expectedStr = 'http://www.google.com';
        System.assertEquals(
            expectedStr,
            embeddedSigningUrlResponse,
            'Embedded URL should have been set correctly here.'
        );
    }
}