force-app/main/default/objects/BioTang_Disclosure__c/BioTang_Disclosure__c.object-meta.xml
<CustomObject>
    <label>BioTang Disclosure</label>
    <nameField>
        <label>BioTang Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BioTang Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BioTang_Disclosure__c/fields/disclosure__c.field-meta.xml
<CustomField>
    <fullName>disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match BioTang Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BioTang_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>BioTang Disclosure</relationshipLabel>
    <relationshipName>BioTang_Disclosure</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BioTang_Disclosure__c/recordTypes/antibody.recordType-meta.xml
<RecordType>
    <fullName>antibody</fullName>
    <active>true</active>
    <label>Antibody</label>
</RecordType>

force-app/main/default/objects/BioTang_Disclosure__c/recordTypes/cellLine.recordType-meta.xml
<RecordType>
    <fullName>cellLine</fullName>
    <active>true</active>
    <label>Cell Line</label>
</RecordType>

force-app/main/default/objects/BioTang_Disclosure__c/recordTypes/mouseStrain.recordType-meta.xml
<RecordType>
    <fullName>mouseStrain</fullName>
    <active>true</active>
    <label>Mouse Strain</label>
</RecordType>

force-app/main/default/objects/BioTang_Disclosure__c/recordTypes/otherMaterial.recordType-meta.xml
<RecordType>
    <fullName>otherMaterial</fullName>
    <active>true</active>
    <label>Other Material</label>
</RecordType>

force-app/main/default/objects/BioTang_Disclosure__c/recordTypes/plasmid.recordType-meta.xml
<RecordType>
    <fullName>plasmid</fullName>
    <active>true</active>
    <label>Plasmid</label>
</RecordType>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/recordTypes/BioTang_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>BioTang_Disclosure</fullName>
    <active>true</active>
    <label>Biological and Tangible Property</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BioTangDocGenAPITest.cls
@IsTest
public class BioTangDocGenAPITest {
    @TestSetup
    static void setup(){
        TestSetup.defaultDocTemplatesConfiguration();
        TestSetup.defaultConfiguration();
    }

    @IsTest
    static void test_generateDocumentCellLine() {
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Id recordTypeIdSub = Schema.SObjectType.BioTang_Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('cellLine')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'CellLine-Joe',
            true,
            '900000001'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'Sample Inventor Submitted Disclosure for CellLine',
            'Inventor Submitted',
            cont
        );

        BioTang_Disclosure__c bioTangDisclosure = test_generateDocumentCommon(
            disclosure,
            recordTypeIdSub
        );
        SampleDataFactory.createCellLine('Test CellLine', bioTangDisclosure);

        Account inventorContact3 = SampleDataFactory.createContact(
            'Inventor3',
            true,
            '900000008'
        );
        DisclosureInventor__c inventor3 = SampleDataFactory.createInventor(
            disclosure,
            true,
            inventorContact3
        );
        SampleDataFactory.addInventorExtraQuestion(inventor3);

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = 'api/disclosure-doc-gen/v1';
        req.httpMethod = 'GET';
        req.params.put('disclosureId', disclosure.Id);
        req.params.put('inventorId', inventor3.Id);

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Test.setMock(
            HttpCalloutMock.class,
            new DocGenApiMock()
                .setInventorId(inventor3.Id)
                .setRaiseDocuSignException(true)
        );

        String result = DisclosureDocGenAPI.generateDocument();
        Test.stopTest();
    }

    @IsTest
    static void test_generateDocumentPlasmid() {
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Id recordTypeIdSub = Schema.SObjectType.BioTang_Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('plasmid')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'Plasmid-Pete',
            true,
            '900000001'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'Sample Draft Disclosure for Plasmid',
            'Draft',
            cont
        );

        BioTang_Disclosure__c bioTangDisclosure = test_generateDocumentCommon(
            disclosure,
            recordTypeIdSub
        );
        SampleDataFactory.createPlasmid('Test Plasmid', bioTangDisclosure);
        performTest(disclosure);
    }

    @IsTest
    static void test_generateDocumentOtherMaterial() {
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Id recordTypeIdSub = Schema.SObjectType.BioTang_Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('otherMaterial')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'OtherMaterial-Odie',
            true,
            '900000001'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'Sample Draft Disclosure for OtherMaterial',
            'Draft',
            cont
        );

        BioTang_Disclosure__c bioTangDisclosure = test_generateDocumentCommon(
            disclosure,
            recordTypeIdSub
        );
        SampleDataFactory.createOtherMaterial(
            'Test OtherMaterial',
            bioTangDisclosure
        );
        performTest(disclosure);
    }

    @IsTest
    static void test_generateDocumentMouseStrain() {
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Id recordTypeIdSub = Schema.SObjectType.BioTang_Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('mouseStrain')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'MouseStrain-Mickey',
            true,
            '900000001'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'Sample Draft Disclosure for MouseStrain',
            'Draft',
            cont
        );

        BioTang_Disclosure__c bioTangDisclosure = test_generateDocumentCommon(
            disclosure,
            recordTypeIdSub
        );
        SampleDataFactory.createMouseStrain(
            'Test MouseStrain',
            bioTangDisclosure
        );
        performTest(disclosure);
    }

    @IsTest
    static void test_generateDocumentAntibody() {
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Id recordTypeIdSub = Schema.SObjectType.BioTang_Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('antibody')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'Antibody-Andy',
            true,
            '900000001'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'Sample Draft Disclosure for Antibody',
            'Draft',
            cont
        );

        BioTang_Disclosure__c bioTangDisclosure = test_generateDocumentCommon(
            disclosure,
            recordTypeIdSub
        );
        SampleDataFactory.createAntibody('Test Antibody', bioTangDisclosure);
        performTest(disclosure);
    }

    static BioTang_Disclosure__c test_generateDocumentCommon(
        Disclosure__c disclosure,
        Id recordTypeIdSub
    ) {
        Account inventorContact1 = SampleDataFactory.createContact(
            'Inventor1',
            true,
            '900000002'
        );
        Account inventorContact2 = SampleDataFactory.createContact(
            'Inventor2',
            true,
            '900000003'
        );
        DisclosureInventor__c inventor1 = SampleDataFactory.createInventor(
            disclosure,
            true,
            inventorContact1
        );
        DisclosureInventor__c inventor2 = SampleDataFactory.createInventor(
            disclosure,
            false,
            inventorContact2
        );
        SampleDataFactory.addInventorExtraQuestion(inventor1);
        SampleDataFactory.addInventorExtraQuestion(inventor2);
        Account piContact = SampleDataFactory.createContact(
            'PI1',
            true,
            '900000006'
        );
        SampleDataFactory.createDisclosureExternalFunding(
            disclosure,
            'grantNum1',
            'AwardId1',
            piContact,
            'sponsor1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosure,
            'Yes',
            'costObjectNumber1',
            'fundingDetails1'
        );
        Account dHeadContact = SampleDataFactory.createContact(
            'DepHead1',
            true,
            '900000007'
        );
        Department_Head__c departmentHead = SampleDataFactory.createDepartmentHead(
            disclosure,
            dHeadContact
        );

        Account shipper = SampleDataFactory.createContact(
            'Shipper',
            true,
            '900000004'
        );
        Account pointOfContact = SampleDataFactory.createContact(
            'PointOfContact',
            true,
            '900000005'
        );

        BioTang_Disclosure__c bioTangDisclosure = SampleDataFactory.createBioTang(
            'Test BioTang',
            disclosure,
            recordTypeIdSub,
            pointOfContact,
            shipper
        );
        SampleDataFactory.createLabMaterials(
            'Lab Material 1',
            bioTangDisclosure
        );
        SampleDataFactory.createLabMaterials(
            'Lab Material 2',
            bioTangDisclosure
        );

        String subTypeName = Schema.SObjectType.BioTang_Disclosure__c.getRecordTypeInfosById()
            .get(bioTangDisclosure.RecordTypeId)
            .getName();
        SampleDataFactory.createTechnicalDocument(
            ContentVersionClassification.PUBLICATION_MANUSCRIPTS,
            subTypeName + '1.docx',
            'docx',
            disclosure
        );
        SampleDataFactory.createTechnicalDocument(
            ContentVersionClassification.PUBLICATION_MANUSCRIPTS,
            subTypeName + '2.docx',
            'docx',
            disclosure
        );
        SampleDataFactory.createTechnicalDocument(
            ContentVersionClassification.TECHNICAL_DESCRIPTION,
            'Technical_Description_' + subTypeName + '1.docx',
            'docx',
            disclosure
        );
        SampleDataFactory.createTechnicalDocument(
            ContentVersionClassification.TECHNICAL_DESCRIPTION,
            'Technical_Description_' + subTypeName + '2.docx',
            'docx',
            disclosure
        );
        SampleDataFactory.createCommercialInterest(disclosure);

        return bioTangDisclosure;
    }

    static void performTest(Disclosure__c disclosure) {
        List<DisclosureInventor__c> inventors = DisclosureRecordFetch.getDisclosureInventorsWithContactByDisclosureId(
            disclosure.Id
        );
        DisclosureInventor__c inventor = !inventors.isEmpty()
            ? inventors[0]
            : null;
        String inventorId = inventor != null ? inventor.Id : null;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = 'api/disclosure-doc-gen/v1';
        req.httpMethod = 'GET';
        req.params.put('disclosureId', disclosure.Id);
        req.params.put('inventorId', inventorId);

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Test.setMock(
            HttpCalloutMock.class,
            new DocGenApiMock()
                .setInventorId(inventorId)
                .setRaiseDocuSignException(true)
        );

        String result = DisclosureDocGenAPI.generateDocument();
        Test.stopTest();
    }
}