force-app/main/default/objects/Email_Templates__c/Email_Templates__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for storing Email Template Configurations</description>
    <label>Email Templates</label>
</CustomObject>

force-app/main/default/objects/Email_Templates__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Template Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email_Templates__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Email Template Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Failure_Count__c.field-meta.xml
<CustomField>
    <fullName>Failure_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Failure Count</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Email.cls
public with sharing class Email {
    public class EmailBody {
        public List<String> to;
        public String template;
        public Map<String, Object> variables;
        public List<String> cc;
        public List<String> bcc;

        public EmailBody(List<String> to, String template, Map<String, Object> variables, List<String> cc, List<String> bcc) {
            this.to = to;
            this.template = template;
            this.variables = variables;
            this.cc = cc;
            this.bcc = bcc;
        }
    }

    public static void sendEmail(List<String> to, String template, Map<String, Object> variables, List<String> cc, List<String> bcc, Id EmailId) {
        Map<String, String> headers = new Map<String, String>();
        headers.put('Content-Type', 'application/json;charset=UTF-8');
        
        Email_Templates__c emailTemplateSettings = NotificationBuilder.getEmailTemplateCustomSettings(template);
        EmailBody body = new EmailBody(to, emailTemplateSettings.Template__c, variables, cc, bcc);
        String bodyStringified = JSON.serialize(body).replace('sender', 'from');  //TODO what is this
        System.debug(bodyStringified);
        
        if(!emailTemplateSettings.Enabled__c ){
            Notification__c notification = [SELECT Status__c, Failure_Count__c FROM Notification__c WHERE Id = :EmailId];
            update new Notification__c(Id = EmailId, Status__c = 'Disabled');

        } else {
            String apiName = 'notificationApi';
            String response = AwsApiCall.restPost(apiName, '/usernotification', headers, bodyStringified);
            System.debug(response);
        
            if (response.contains('message')) {
                Notification__c notification = [SELECT Status__c, Failure_Count__c FROM Notification__c WHERE Id = :EmailId];
                if (notification.Failure_Count__c < 5) {
                    update new Notification__c(Id = EmailId, Failure_Count__c = notification.Failure_Count__c + 1);
                } else {
                    update new Notification__c(Id = EmailId, Status__c = 'Failed');
                }
                
            } else {
                update new Notification__c(Id = EmailId, Status__c = 'Successful');
            }
        }
    }
}