force-app/main/default/objects/Utilization_Commercial_Prods__c/Utilization_Commercial_Prods__c.object-meta.xml
<CustomObject>
    <description>The FDA Approved Commercial products for the utilization with fiscal year prior 2023.</description>
    <label>Utilization Commercial Prod</label>
    <nameField>
        <label>Utilization Commercial Prods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Commercial Prods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Commercial_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Name__c</fullName>
    <label>Commercial Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Fda_Approval_Number__c.field-meta.xml
<CustomField>
    <fullName>Fda_Approval_Number__c</fullName>
    <label>Fda Approval Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Fda_Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Fda_Approval_Type__c</fullName>
    <label>Fda Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biologic</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>Drug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Govt_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Govt_Review_Status__c</fullName>
    <label>Govt Review Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Public_Ind__c.field-meta.xml
<CustomField>
    <fullName>Public_Ind__c</fullName>
    <label>Public Ind</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipLabel>Utilization Commercial Prods</relationshipLabel>
    <relationshipName>Utilization_Commercial_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/Utilization_Licensee__c.object-meta.xml
<CustomObject>
    <description>Licensee with license counts</description>
    <label>Utilization Licensee</label>
    <nameField>
        <label>Licensee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee__c/fields/Licensee_Name__c.field-meta.xml
<CustomField>
    <fullName>Licensee_Name__c</fullName>
    <label>Licensee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipName>Utilization_Licensee_Counts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/Utilization_Licensee_Man_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>Junction box object to link (many to many) licensees with m Manufaturing Comm Prods</description>
    <label>Utilization Licensee Man Comm Prod</label>
    <nameField>
        <label>Utilization Licensee Man Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensee Man Comm Prod</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/fields/Utilization_Licensee__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Licensee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Licensee</label>
    <referenceTo>Utilization_Licensee__c</referenceTo>
    <relationshipName>Utilization_Licensees1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/fields/Utilization_Manufacturing_Comm_Prod__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Manufacturing_Comm_Prod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Manufacturing Comm Prod</label>
    <referenceTo>Utilization_Manufacturing_Comm_Prod__c</referenceTo>
    <relationshipName>Utilization_Manufacturing_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturers__c/Utilization_Manufacturers__c.object-meta.xml
<CustomObject>
    <description>The manufacturers for the manufacturing commercial product</description>
    <label>Utilization Manufacturer</label>
    <nameField>
        <label>Utilization Manufacturers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Manufacturers__c/fields/Manufacturer_Name__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Name__c</fullName>
    <label>Manufacturer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturers__c/fields/Utilization_Licensee_Man_Comm_Prod__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Licensee_Man_Comm_Prod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Manufaturing Comm Prod</label>
    <referenceTo>Utilization_Licensee_Man_Comm_Prod__c</referenceTo>
    <relationshipLabel>Utilization Licensee Man Comm Prod</relationshipLabel>
    <relationshipName>Utilization_Licensee_Man_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/Utilization_Manufacturing_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>The manufacturing commercial products</description>
    <label>Utilization Manufacturing Comm Prod</label>
    <nameField>
        <label>Utilization Manufacturing Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturing Comm Prods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/fields/Naics_Code__c.field-meta.xml
<CustomField>
    <fullName>Naics_Code__c</fullName>
    <label>Naics Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipLabel>Utilization Manufacturing Comm Prods</relationshipLabel>
    <relationshipName>Utilization_Manufacturing_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Commercialization_Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Commercialization_Plan_Id__c</fullName>
    <label>Commercialization Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Seeking additional funding to further develop this invention</label>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>Marketing and/or furthering development of this invention to attract commercial
                    partners</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Developing and/or using this invention for internal purposes only</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Developing and/or preparing this invention with intent to commercialize ourselves</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Making available for distribution and/or licensing for research purposes only</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>No current commercialization plan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/First_Commercial_Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>First_Commercial_Year_of_Sale__c</fullName>
    <label>First Commercial Year of Sale</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_First_Commercial_Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>Forrester_First_Commercial_Year_of_Sale__c</fullName>
    <label>Forrester First Commercial Year of Sale</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_Summarized_Agreement_Income__c.field-meta.xml
<CustomField>
    <fullName>Forrester_Summarized_Agreement_Income__c</fullName>
    <label>Summarized Agreement Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Invention_Report_Date__c</fullName>
    <label>Invention Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Report_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Report_Number__c</fullName>
    <label>Invention Report Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_1__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_1__c</fullName>
    <label>Is US Manufacturing Required 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_2__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_2__c</fullName>
    <label>Is US Manufacturing Required 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_3__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_3__c</fullName>
    <label>Is US Manufacturing Required 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Latest_Stage_of_Development__c</fullName>
    <label>Latest Stage of Development</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Commercialized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Companies__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Companies__c</fullName>
    <label>New US Companies</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Jobs__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Jobs__c</fullName>
    <label>New US Jobs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name(s)</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <label>Reporting Year</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IEdisonServiceReportToRequest.cls
public with sharing class IEdisonServiceReportToRequest {
    public static void mapReportToUtilizationRequest (Utilization_Report__c report, IEdisonUtilizationRequest request) {
        //Always submit the Forrester value for these fields
        report.First_Commercial_Year_of_Sale__c = report.Forrester_First_Commercial_Year_of_Sale__c;
        report.Total_Income__c = report.Forrester_Summarized_Agreement_Income__c;

        request.inventionReportNumber = report.Invention_Report_Number__c;
        request.reportingYear = integer.valueof(report.Reporting_Year__c);
        request.latestStageDev = report.Latest_Stage_of_Development__c;
                
        if (report.Invention_Report_Date__c != null) {
            if (String.isNotBlank(report.First_Commercial_Year_of_Sale__c)) {
                if (Integer.valueOf(report.First_Commercial_Year_of_Sale__c) < report.Invention_Report_Date__c.year() - 5) {
                    report.First_Commercial_Year_of_Sale__c = String.valueOf(report.Invention_Report_Date__c.year() - 5);
                } 
            }
        }

        if (report.First_Commercial_Year_of_Sale__c != null) {
            request.firstCommercialSaleYear = Integer.valueOf(report.First_Commercial_Year_of_Sale__c);
        }

        request.totalIncome = report.Total_Income__c;
        if (report.New_Us_Jobs__c != null) {
            request.newUsJobs = report.New_Us_Jobs__c.intValue();
        }
        if (report.New_Us_Companies__c != null) {
            request.newUsCompanies = report.New_Us_Companies__c.intValue();
        }
        request.notes = report.Notes__c;

        request.commercialProds = getIEdisonCommercialProds(report.Id);

        request.manufacturingCommProds = getIEdisonManufacturingCommProds(report.Id);

        request.licensees = getIEdisonLicensees(report.Id);

        if (String.isNotBlank(report.Commercialization_Plan_Id__c)) {
            request.commercializationPlanId = Integer.valueOf(report.Commercialization_Plan_Id__c);
        }

        request.isUSManufacturingRequired1 = report.Is_US_Manufacturing_Required_1__c;
        request.isUSManufacturingRequired2 = report.Is_US_Manufacturing_Required_2__c;
        request.isUSManufacturingRequired3 = report.Is_US_Manufacturing_Required_3__c;
    }

    public static List<IEdisonCommercialProds> getIEdisonCommercialProds(Id parentId) {
        List<IEdisonCommercialProds> commercialProds = new List<IEdisonCommercialProds>();
        List<Utilization_Commercial_Prods__c> recordsCommercialProds = [SELECT Id, Commercial_Name__c, Fda_Approval_Number__c, Fda_Approval_Type__c, Govt_Review_Status__c, Public_Ind__c FROM Utilization_Commercial_Prods__c WHERE Utilization_Report__c = :parentId];
        if (recordsCommercialProds.size() > 0) {
            for (Utilization_Commercial_Prods__c record : recordsCommercialProds) {
                IEdisonCommercialProds commercialProd = new IEdisonCommercialProds();
                commercialProd.commercialName = record.Commercial_Name__c;
                commercialProd.fdaApprovalNumber = record.Fda_Approval_Number__c;
                commercialProd.fdaApprovalType = record.Fda_Approval_Type__c;
                commercialProd.govtReviewStatus = record.Govt_Review_Status__c;
                commercialProd.publicInd = record.Public_Ind__c;
                commercialProds.Add(commercialProd);
            }
        }
        return commercialProds;
    }

    public static List<IEdisonManufacturingCommProds> getIEdisonManufacturingCommProds(Id parentId) {
        List<Utilization_Manufacturing_Comm_Prod__c> recordsManufacturingCommProds = [SELECT Id, Product_Name__c, Naics_Code__c FROM Utilization_Manufacturing_Comm_Prod__c WHERE Utilization_Report__c = :parentId];
        List<IEdisonManufacturingCommProds> manufacturingCommProds = new List<IEdisonManufacturingCommProds>();
        if (recordsManufacturingCommProds.size() > 0) {
            for (Utilization_Manufacturing_Comm_Prod__c record : recordsManufacturingCommProds) {
                IEdisonManufacturingCommProds manufacturingCommProd = new IEdisonManufacturingCommProds();
                manufacturingCommProd.productName = record.Product_Name__c;
                manufacturingCommProd.naicsCode = record.Naics_Code__c;
                manufacturingCommProd.licensees = getIEdisonLicenseeCommProds(record.Id);
                manufacturingCommProds.Add(manufacturingCommProd);
            }
        }
        return manufacturingCommProds;
    }

    public static List<IEdisonLicenceeManCommProds> getIEdisonLicenseeCommProds(Id parentId) {
        List<Utilization_Licensee_Man_Comm_Prod__c> recordsLicenseeManCommProds = [SELECT Id, Utilization_Licensee__c, Utilization_Licensee__r.Licensee_Name__c FROM Utilization_Licensee_Man_Comm_Prod__c WHERE Utilization_Manufacturing_Comm_Prod__c = :parentId];
        List<IEdisonLicenceeManCommProds> licensees = new List<IEdisonLicenceeManCommProds>();
        if (recordsLicenseeManCommProds.size() > 0) {
            for (Utilization_Licensee_Man_Comm_Prod__c record : recordsLicenseeManCommProds) {
                IEdisonLicenceeManCommProds licensee = new IEdisonLicenceeManCommProds();
                licensee.licenseeName = record.Utilization_Licensee__r.Licensee_Name__c;
                licensee.manufacturers = getIEdisonManufacturers(record.Id);
                licensees.add(licensee);
            }
        }
        return licensees;
    }

    public static List<IEdisonManufacturers> getIEdisonManufacturers(Id parentId) {
        List<Utilization_Manufacturers__c> recordsManufactures = [SELECT Id, Manufacturer_Name__c FROM Utilization_Manufacturers__c WHERE Utilization_Licensee_Man_Comm_Prod__c = :parentId];
        List<IEdisonManufacturers> manufactures = new List<IEdisonManufacturers>();
        if (recordsManufactures.size() > 0) {
            for (Utilization_Manufacturers__c record : recordsManufactures) {
                IEdisonManufacturers manufacturer = new IEdisonManufacturers();
                manufacturer.manufacturerName = record.Manufacturer_Name__c;
                manufacturer.productLocation = getIEdisonProductLocations(record.Id);
                manufactures.add(manufacturer);
            }
        }
        return manufactures;
    }

    public static List<IEdisonProductLocation> getIEdisonProductLocations(Id parentId) {
        Schema.DescribeFieldResult describeCountry = Utilization_Product_Location__c.Country__c.getDescribe();
        Map<String, String> countryMap = new Map<String, String>();
        for(PicklistEntry picklistEntry : describeCountry.getPicklistValues()) {
            countryMap.put(picklistEntry.getValue(), picklistEntry.getLabel());
        }

        Schema.DescribeFieldResult describeState = Utilization_Product_Location__c.State__c.getDescribe();
        Map<String, String> stateMap = new Map<String, String>();
        for(PicklistEntry picklistEntry : describeState.getPicklistValues()) {
            stateMap.put(picklistEntry.getValue(), picklistEntry.getLabel());
        }

        List<Utilization_Product_Location__c> recordsProductLocations = [SELECT Id, Country__c, First_Date__c, First_Date_Type__c, Product_Quantity__c, State__c FROM Utilization_Product_Location__c WHERE Utilization_Manufacturer__c = :parentId];
        List<IEdisonProductLocation> productLocations = new List<IEdisonProductLocation>();
        if (recordsProductLocations.size() > 0) {
            for (Utilization_Product_Location__c record : recordsProductLocations) {
                IEdisonProductLocation productLocation = new IEdisonProductLocation();
                productLocation.country = countryMap.get(record.Country__c);
                if (record.First_Date__c != null) {
                    productLocation.firstDate = DateToIEdisonString(record.First_Date__c);
                }
                productLocation.firstDateType = record.First_Date_Type__c;
                if (record.Product_Quantity__c != null) {
                    productLocation.productQuantity = record.Product_Quantity__c.intValue();
                }
                productLocation.state =  stateMap.get(record.State__c);
                productLocations.add(productLocation);
            }
        }
        return productLocations;
    }

    public static List<IEdisonLicensees> getIEdisonLicensees(Id parentId) {
        List<Utilization_Licensee__c> recordsLicensees = [SELECT Id, Licensee_Name__c, Exclusive_Count__c, Non_Exclusive_Count__c, Small_Business__c FROM Utilization_Licensee__c WHERE Utilization_Report__c = :parentId];
        List<IEdisonLicensees> licensees = new List<IEdisonLicensees>();
        if (recordsLicensees.size() > 0) {
            for (Utilization_Licensee__c record : recordsLicensees) {
                IEdisonLicensees licensee = new IEdisonLicensees();
                licensee.licenseeName = record.Licensee_Name__c;
                if (record.Exclusive_Count__c != null) {
                    licensee.exclusiveCount = record.Exclusive_Count__c.intValue();
                }
                if (record.Non_Exclusive_Count__c != null) {
                    licensee.nonExclusiveCount = record.Non_Exclusive_Count__c.intValue();
                }
                licensee.smallBusiness = record.Small_Business__c;
                licensees.add(licensee);
            }
        }
        return licensees;
    }

    public static String DateToIEdisonString(Date input) {
        DateTime dt = DateTime.newInstance(input.year(), input.month(), input.day());
        return dt.format('MM/dd/yyyy');
    }
}