force-app/main/default/objects/Utilization_Commercial_Prods__c/Utilization_Commercial_Prods__c.object-meta.xml
<CustomObject>
    <description>The FDA Approved Commercial products for the utilization with fiscal year prior 2023.</description>
    <label>Utilization Commercial Prod</label>
    <nameField>
        <label>Utilization Commercial Prods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Commercial Prods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Commercial_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Name__c</fullName>
    <label>Commercial Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipLabel>Utilization Commercial Prods</relationshipLabel>
    <relationshipName>Utilization_Commercial_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/Utilization_Licensee__c.object-meta.xml
<CustomObject>
    <description>Licensee with license counts</description>
    <label>Utilization Licensee</label>
    <nameField>
        <label>Licensee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee__c/fields/Licensee_Name__c.field-meta.xml
<CustomField>
    <fullName>Licensee_Name__c</fullName>
    <label>Licensee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipName>Utilization_Licensee_Counts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/Utilization_Licensee_Man_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>Junction box object to link (many to many) licensees with m Manufaturing Comm Prods</description>
    <label>Utilization Licensee Man Comm Prod</label>
    <nameField>
        <label>Utilization Licensee Man Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensee Man Comm Prod</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/fields/Utilization_Licensee__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Licensee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Licensee</label>
    <referenceTo>Utilization_Licensee__c</referenceTo>
    <relationshipName>Utilization_Licensees1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/fields/Utilization_Manufacturing_Comm_Prod__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Manufacturing_Comm_Prod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Manufacturing Comm Prod</label>
    <referenceTo>Utilization_Manufacturing_Comm_Prod__c</referenceTo>
    <relationshipName>Utilization_Manufacturing_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturers__c/Utilization_Manufacturers__c.object-meta.xml
<CustomObject>
    <description>The manufacturers for the manufacturing commercial product</description>
    <label>Utilization Manufacturer</label>
    <nameField>
        <label>Utilization Manufacturers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Manufacturers__c/fields/Manufacturer_Name__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Name__c</fullName>
    <label>Manufacturer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturers__c/fields/Utilization_Licensee_Man_Comm_Prod__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Licensee_Man_Comm_Prod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Manufaturing Comm Prod</label>
    <referenceTo>Utilization_Licensee_Man_Comm_Prod__c</referenceTo>
    <relationshipLabel>Utilization Licensee Man Comm Prod</relationshipLabel>
    <relationshipName>Utilization_Licensee_Man_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/Utilization_Manufacturing_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>The manufacturing commercial products</description>
    <label>Utilization Manufacturing Comm Prod</label>
    <nameField>
        <label>Utilization Manufacturing Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturing Comm Prods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipLabel>Utilization Manufacturing Comm Prods</relationshipLabel>
    <relationshipName>Utilization_Manufacturing_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Product_Location__c/Utilization_Product_Location__c.object-meta.xml
<CustomObject>
    <description>The manufacturing production location(s)</description>
    <label>Utilization Product Location</label>
    <nameField>
        <label>Utilization Product Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Product Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Product_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>OAPI</fullName>
                <label>African Manufacturer Intellectual Property Organization</label>
            </value>
            <value>
                <fullName>ARIPO</fullName>
                <label>African Regional Manufacturer Intellectual Property Organization</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AV</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AC</fullName>
                <label>Antigua/Barbud</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AA</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AJ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BK</fullName>
                <label>Bosnia/Herzeg</label>
            </value>
            <value>
                <fullName>BC</fullName>
                <label>Botswana</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>VI</fullName>
                <label>British Vi Iss</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Product_Location__c/fields/Utilization_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Manufacturer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Manufacturer</description>
    <label>Utilization Manufacturer</label>
    <referenceTo>Utilization_Manufacturers__c</referenceTo>
    <relationshipLabel>Utilization Product Locations</relationshipLabel>
    <relationshipName>Utilization_Product_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Commercialization_Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Commercialization_Plan_Id__c</fullName>
    <label>Commercialization Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Seeking additional funding to further develop this invention</label>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>Marketing and/or furthering development of this invention to attract commercial
                    partners</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Developing and/or using this invention for internal purposes only</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Developing and/or preparing this invention with intent to commercialize ourselves</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Making available for distribution and/or licensing for research purposes only</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>No current commercialization plan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_1__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_1__c</fullName>
    <label>Is US Manufacturing Required 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Latest_Stage_of_Development__c</fullName>
    <label>Latest Stage of Development</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Commercialized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name(s)</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <label>Reporting Year</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IEdisonServiceResponseToReportTest.cls
@isTest
public with sharing class IEdisonServiceResponseToReportTest {
    @TestSetup
    static void setupTestData() {
        TestSetup.defaultConfiguration();
    }


    @IsTest
    static void testCreateUtilizationReport() {
        IEdisonApiMock iEdisonApiMock = new IEdisonApiMock();
        Test.setMock(HttpCalloutMock.class, iEdisonApiMock);

        Utilization_Report__c utilizationReport = SampleDataFactory.createUtilizationReportForSubmit('4911501-16-0003', '18436', 2024, 'Include for Utilization');
        IEdisonUtilizationResponse response = IEdisonUtilizationResponse.getExample();
        response.reportingYear = 2024;
        response.commercializationPlanId = 3;
        response.latestStageDev = 'Not Licensed';
        response.isUSManufacturingRequired1 = 'Y';
        response.commercialProds[0].commercialName = 'NIH Product A';
        response.licensees[0].licenseeName = 'Test licensee 1';
        response.manufacturingCommProds[0].productName = 'Processor';
        response.manufacturingCommProds[0].licensees[0].licenseeName = 'Test licensee 1';
        response.manufacturingCommProds[0].licensees[0].manufacturers[0].manufacturerName = 'Test Maufacturer1';
        response.manufacturingCommProds[0].licensees[0].manufacturers[0].productLocation[0].country = 'UNITED STATES';


        Test.startTest();
        IEdisonServiceResponseToReport.mapUtilizationResponseToReport(utilizationReport, response, null);

        System.assert(utilizationReport != null, 'utilizationReport object is null');
        System.assert(utilizationReport.Reporting_Year__c == '2024', 'Reporting_Year__c error');
        System.assert(utilizationReport.Total_Income__c == 1.3579, 'Total_Income__c error');
        System.assert(utilizationReport.Latest_Stage_of_Development__c == 'Not Licensed', 'Latest_Stage_of_Development__c error');
        System.assert(utilizationReport.Commercialization_Plan_Id__c == '3', 'Commercialization_Plan_Id__c error');
        System.assert(utilizationReport.Is_US_Manufacturing_Required_1__c == 'Y', 'Is_US_Manufacturing_Required_1__c error');

        Utilization_Commercial_Prods__c  commercialProd = [SELECT Id, Commercial_Name__c from Utilization_Commercial_Prods__c WHERE Utilization_Report__c = :utilizationReport.Id LIMIT 1];
        System.assert(commercialProd.Commercial_Name__c == 'NIH Product A', 'Commercial_Name__c error');

        Utilization_Licensee__c  licensee = [SELECT Id, Licensee_Name__c from Utilization_Licensee__c WHERE Utilization_Report__c = :utilizationReport.Id LIMIT 1];
        System.assert(licensee.Licensee_Name__c == 'Test licensee 1', 'Licensee_Name__c error');

        Utilization_Manufacturing_Comm_Prod__c  manufacturingCommProd = [SELECT Id, Product_Name__c from Utilization_Manufacturing_Comm_Prod__c WHERE Utilization_Report__c = :utilizationReport.Id LIMIT 1];
        System.assert(manufacturingCommProd.Product_Name__c == 'Processor', 'Product_Name__c error');

        Utilization_Licensee_Man_Comm_Prod__c  licenseeManCommProd = [SELECT Id, Utilization_Licensee__c, Utilization_Manufacturing_Comm_Prod__c from Utilization_Licensee_Man_Comm_Prod__c WHERE Utilization_Licensee__c = :licensee.Id  AND Utilization_Manufacturing_Comm_Prod__c = :manufacturingCommProd.Id LIMIT 1];
        System.assert(licenseeManCommProd.Utilization_Licensee__c != null, 'Utilization_Licensee__c error');
        System.assert(licenseeManCommProd.Utilization_Manufacturing_Comm_Prod__c != null, 'Utilization_Manufacturing_Comm_Prod__c error');

        Utilization_Manufacturers__c manufacturer = [SELECT Id, Manufacturer_Name__c from Utilization_Manufacturers__c WHERE Utilization_Licensee_Man_Comm_Prod__c = :licenseeManCommProd.Id LIMIT 1];
        System.assert( manufacturer.Manufacturer_Name__c == 'Test Maufacturer1', 'Manufacturer_Name__c error');

        Utilization_Product_Location__c productLocation  = [SELECT Id, Country__c from Utilization_Product_Location__c WHERE Utilization_Manufacturer__c = :manufacturer.Id LIMIT 1];
        System.assert( productLocation.Country__c == 'US', 'Country__c error');

        Test.stopTest();
    }

}