force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Entity_Recid__c.field-meta.xml
<CustomField>
    <fullName>Entity_Recid__c</fullName>
    <description>External Reference to Forrester Oracle RecIds for multiple tables. eg: Case table PK case_recid. Agreement table PK agreement_recid. The Record type with the classification need to be considered</description>
    <label>Entity Recid</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/CRDR.recordType-meta.xml
<RecordType>
    <fullName>CRDR</fullName>
    <active>true</active>
    <description>CRDR Worksheets, Correspondence and CRDR Finacial Documents</description>
    <label>CRDR</label>
</RecordType>

force-app/main/default/classes/CRDRDocumentUploadJob.cls
public with sharing class CRDRDocumentUploadJob implements Queueable, Database.AllowsCallouts  {

    public final List<Id> cvIds;

    public CRDRDocumentUploadJob(List<Id> cvList) {
        this.cvIds = cvList;
    }

    public List<ContentVersion> start(QueueableContext ctx) {
        System.debug('CreateDocumentLinkJob:start ' + ctx.getJobId());

        if (cvIds != null && !cvIds.isEmpty()) {
            Id recordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName().get('CRDR').getRecordTypeId();
            return [ SELECT Id, Title, Description, PathOnClient, TagCsv,  Document_Classification__c, ContentSize, VersionNumber,
                                                                     IsLatest,
                                                                     RecordType.Name,
                                                                     ContentDocumentId,
                                                                     Entity_RecId__c
                                                        FROM ContentVersion WHERE Id IN :this.cvIds AND RecordTypeId = :recordTypeId  ];
        } else {
            return null;
        }
    }

    public void execute(QueueableContext ctx) {
        try {
            List<ContentVersion> scope = start(ctx);
            System.debug('CRDRDocumentUploadJob.execute');
            if(scope != null && !scope.isEmpty()) {
                System.debug('CreateDocumentLinkJob:scope ' + scope.size() );
                List<ContentVersion> caseCRDRs = new List<ContentVersion>();

                for(ContentVersion contentVersion : scope) {
                    if (contentVersion.RecordType.Name == 'CRDR' && contentVersion.Document_Classification__c.contains('CRDR')) {
                        caseCRDRs.add(contentVersion);
                    }
                }
            }
        } catch(Exception ex) {
            System.debug(ex);
            HandleLogException.logException(ex);
            throw ex;
        }
    }
}