force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Entity_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Sub_Type__c</fullName>
    <label>Data Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N_A</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>KUALI</fullName>
                <label>Kuali</label>
            </value>
            <value>
                <fullName>AGENCY</fullName>
                <label>Agency</label>
            </value>
            <value>
                <fullName>ASSIGN</fullName>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>BY-AGT</fullName>
                <label>License by Agent</label>
            </value>
            <value>
                <fullName>GOVUSE</fullName>
                <label>Government Use License</label>
            </value>
            <value>
                <fullName>INST</fullName>
                <label>Institution</label>
            </value>
            <value>
                <fullName>JOI NO</fullName>
                <label>Joint - No Purple File</label>
            </value>
            <value>
                <fullName>JOINT</fullName>
                <label>Joint Ownership</label>
            </value>
            <value>
                <fullName>LIC</fullName>
                <label>License</label>
            </value>
            <value>
                <fullName>LIC NO</fullName>
                <label>License - No Purple File</label>
            </value>
            <value>
                <fullName>MASTER</fullName>
                <label>Master Agreement</label>
            </value>
            <value>
                <fullName>MOU</fullName>
                <label>Memo of Understanding</label>
            </value>
            <value>
                <fullName>MTA</fullName>
                <label>Outgoing Material Transfer Agreement</label>
            </value>
            <value>
                <fullName>OBYAGN</fullName>
                <label>Option by Agent</label>
            </value>
            <value>
                <fullName>OPT</fullName>
                <label>Option</label>
            </value>
            <value>
                <fullName>PUBL</fullName>
                <label>Publishing</label>
            </value>
            <value>
                <fullName>SUBLIC</fullName>
                <label>Sublicense</label>
            </value>
            <value>
                <fullName>SW-EU</fullName>
                <label>Software End Use</label>
            </value>
            <value>
                <fullName>SW-LIC</fullName>
                <label>Software End Use Licenses &gt; 1K</label>
            </value>
            <value>
                <fullName>TECHTR</fullName>
                <label>Tech Transfer</label>
            </value>
            <value>
                <fullName>TM</fullName>
                <label>Trademark</label>
            </value>
            <value>
                <fullName>TRACKG</fullName>
                <label>Tracking</label>
            </value>
            <value>
                <fullName>SRA</fullName>
                <label>Sponsor Research Agreement</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Sponsor Agreement</label>
            </value>
            <value>
                <fullName>CONSORTIUM</fullName>
                <label>Consortium</label>
            </value>
            <value>
                <fullName>SUB_AWARD</fullName>
                <label>Subaward Document</label>
            </value>
            <value>
                <fullName>ASSIGNMENT</fullName>
                <label>Assignment</label>
            </value>
            <value>
                <fullName>AGREEMENT</fullName>
                <label>Agreement</label>
            </value>
            <value>
                <fullName>NDA</fullName>
                <label>Non-Disclosure Agreement (NDA)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <label>Note</label>
</RecordType>

force-app/main/default/classes/CsvUtils.cls
public class CsvUtils {


    // Method to convert a list of SObjects to CSV
    public static String toCSV(List<SObject> records, List<String> fieldNames) {
        List<String> csvContent = new List<String>();

        // Add CSV rows
        for (SObject record : records) {
            List<String> row = new List<String>();

            for (String fieldName : fieldNames) {
                Object fieldValue = extractFieldValues(record, fieldName);
                String csvField = fieldValue == null ? '' : String.valueOf(fieldValue);
                row.add(csvField.escapeCsv());
            }
            csvContent.add(String.join(row, ','));
        }
        return String.join(csvContent,'\n');
    }

    public static void sendCSVFile(String htmlBody, String csvContent, String title, String subscriber) {
        Blob csvBlob = Blob.valueOf(csvContent);

        Messaging.EmailFileAttachment emailAttachment = new Messaging.EmailFileAttachment();
        emailAttachment.setFileName(title+'.csv');
        emailAttachment.setBody(csvBlob);
        emailAttachment.setContentType('text/csv');

        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>() ;
        attachments.add(emailAttachment);

        List<String> toAddresses = subscriber.split(',');

        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setFileAttachments(attachments);
        email.setSubject('Report results (' + title + ')');
        email.setToAddresses(toAddresses);
        email.setSenderDisplayName('Salesforce');

        email.setHtmlBody(htmlBody);

        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        for (Messaging.SendEmailResult result : r) {
            System.debug('Email result ' + result.isSuccess());
            if (!result.isSuccess()) {
                for (Messaging.SendEmailError sendError : result.getErrors()) {
                    System.debug('Email message ' + sendError.getMessage());
                }
            }
        }
        System.debug('Email sent');

    }

    // Method to save CSV content to a file in Salesforce
    public static void saveCSVFile(String csvContent, String title) {
        Id recordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName().get('Note').getRecordTypeId();

        ContentVersion conVer = new ContentVersion();
        conVer.Title = title + '.csv';
        conVer.ContentLocation = 'S';
        conVer.PathOnClient = title + '.csv';
        conVer.RecordTypeId = recordTypeId;
        conVer.Document_Classification__c = 'Original_Document';
        conVer.Entity_Sub_Type__c = 'N_A';
        conVer.VersionData = Blob.valueOf(csvContent);
        insert conVer;

    }


    public static string extractFieldValues(sObject sb, string fieldAPIName){
    	String fValue = '';
    	if(fieldAPIName.contains('.')){
    		List<string> splitFields = fieldAPIName.split('\\.');
    		try {
    			for(integer i=0; i < splitFields.size()-1; i++){
    				sb=sb.getSObject(splitFields[i]);
    			}
    			fValue = String.valueOf(sb.get(splitFields[splitFields.size() -1]));
    		}catch(Exception ex){
    		   System.debug('Exception while fetching fieldValues as relationship ' + fieldAPIName + '  value is blank.' + ex.getMessage());
    		   fValue='';
    		}

    	}else if(sb.get(fieldAPIName)!=null){
    		fValue = string.valueOf(sb.get(fieldAPIName));
    	}
    	return fValue;
    }
}