force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/IPIA.recordType-meta.xml
<RecordType>
    <fullName>IPIA</fullName>
    <active>true</active>
    <label>IPIA</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/IPIA_Type_Template.recordType-meta.xml
<RecordType>
    <fullName>IPIA_Type_Template</fullName>
    <active>true</active>
    <label>IPIA Type Template</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Other_Agreement.recordType-meta.xml
<RecordType>
    <fullName>Other_Agreement</fullName>
    <active>true</active>
    <description>Agreements ossociated with a Case</description>
    <label>Other Agreement</label>
</RecordType>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Record__c/fields/DocusignEnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>DocusignEnvelopeId__c</fullName>
    <label>Docusign Envelope Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/DocusignTemplate__c.field-meta.xml
<CustomField>
    <fullName>DocusignTemplate__c</fullName>
    <label>Docusign Template</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/FormName__c.field-meta.xml
<CustomField>
    <fullName>FormName__c</fullName>
    <label>Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/IPIA_Type__c.field-meta.xml
<CustomField>
    <fullName>IPIA_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IPIA Type</label>
    <referenceTo>IPIA_Type__c</referenceTo>
    <relationshipLabel>IPIAs</relationshipLabel>
    <relationshipName>IPIA_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <label>MIT ID</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Type__c/IPIA_Type__c.object-meta.xml
<CustomObject>
    <label>IPIA Type</label>
    <nameField>
        <label>IPIA Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPIA Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Form Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IPIA_Type__c/fields/DocusignTemplate__c.field-meta.xml
<CustomField>
    <fullName>DocusignTemplate__c</fullName>
    <label>DocuSign Template ID</label>
    <length>64</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IPIA_Type__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>IPIA Type Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Needs TLO Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentTriggerHandlerTest.cls
/**
 * Created by Andreas du Preez on 2024/09/23.
 */

@IsTest
public with sharing class ContentDocumentTriggerHandlerTest {

    @IsTest
    public static void preventsDeletionOfIPIATypeTemplateLinkedToIPIAType() {
        String ipiaTypeName = 'Test IPIA Type';
        String ipiaTypeDescription = 'Test Description';
        String ipiaStatus = 'Active';
        String fileName = 'Test File';
        String fileBase64 = 'VGhpcyBpcyBhIHRlc3QgZmlsZSBiYXNlNjQ=';

        IPIA_Type__c ipiaType = new IPIA_Type__c(Name = ipiaTypeName, Description__c = ipiaTypeDescription, Status__c = ipiaStatus);
        IPIA_Type__c result = IPIAController.createIPIAType(ipiaType, fileName, fileBase64);

        ContentDocumentLink contentDocumentLink = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :result.Id];
        ContentDocument contentDocumentToDelete = new ContentDocument(Id = contentDocumentLink.ContentDocumentId);

        Test.startTest();
        try {
            delete contentDocumentToDelete;
            System.assert(false, 'Expected DMLException was not thrown');
        } catch (DmlException e) {
            System.assert(e.getMessage().contains(Label.IPIA_Type_Template_Delete_Error), 'Expected error message not found');
        }
        Test.stopTest();
    }

    @IsTest
    public static void allowsDeletionOfContentDocumentNotLinkedToIPIAType() {
        String fileName = 'Test File';
        String fileBase64 = 'VGhpcyBpcyBhIHRlc3QgZmlsZSBiYXNlNjQ=';

        Id otherContentVersionRecordType = Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName().get('Other_Agreement').getRecordTypeId();

        ContentVersion version = new ContentVersion(
                Title = fileName,
                PathOnClient = fileName,
                Document_Classification__c = 'Original_Document',
                VersionData = EncodingUtil.base64Decode(String.valueOf(fileBase64)),
                RecordTypeId = otherContentVersionRecordType,
                IsMajorVersion = false
        );
        insert version;

        ContentVersion insertedContentVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :version.Id];
        ContentDocument contentDocumentToDelete = new ContentDocument(Id = insertedContentVersion.ContentDocumentId);

        Test.startTest();
        delete contentDocumentToDelete;
        Test.stopTest();

        List<ContentDocument> deletedDocument = [SELECT Id FROM ContentDocument WHERE Id = :contentDocumentToDelete.Id];
        System.assertEquals(0, deletedDocument.size(), 'ContentDocument should be deleted');
    }

    @IsTest
    public static void allowsDeletionOfContentDocumentWithNoLinks() {
        String fileName = 'Test File';
        String fileBase64 = 'VGhpcyBpcyBhIHRlc3QgZmlsZSBiYXNlNjQ=';

        Id ipiaContentVersionRecordType = Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName().get('IPIA_Type_Template').getRecordTypeId();

        ContentVersion version = new ContentVersion(
                Title = fileName,
                PathOnClient = fileName,
                Document_Classification__c = 'IPIA_Type_Template',
                VersionData = EncodingUtil.base64Decode(String.valueOf(fileBase64)),
                RecordTypeId = ipiaContentVersionRecordType,
                IsMajorVersion = false
        );
        insert version;

        ContentVersion insertedContentVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :version.Id];
        ContentDocument contentDocumentToDelete = new ContentDocument(Id = insertedContentVersion.ContentDocumentId);

        Test.startTest();
        delete contentDocumentToDelete;
        Test.stopTest();

        List<ContentDocument> deletedDocument = [SELECT Id FROM ContentDocument WHERE Id = :contentDocumentToDelete.Id];
        System.assertEquals(0, deletedDocument.size(), 'ContentDocument should be deleted');
    }

    // =======================================================
    // TESTS FOR:- 
    //      Prevent deletion of IPIA ContentDocument if it is linked to an IPIA_Record that has DocuSign meta data against it
    // =======================================================
    @IsTest
    public static void preventsDeletionOfIPIADocLinkedToIPIARecordWithDocuSignMetaData() {
        String fileName = 'Test File';
        String fileBase64 = 'VGhpcyBpcyBhIHRlc3QgZmlsZSBiYXNlNjQ=';

        IPIA_Record__c ipiaRecord = new IPIA_Record__c(MitId__c = '912345456', FormName__c = 'Test Form', 
                                                       DocusignTemplate__c = '390847530986738957', DocusignEnvelopeId__c = '23498723984');
        IPIA_Record__c resultIpiaRecord = IPIAController.createIPIARecord(ipiaRecord);
        IPIAController.uploadIPIADocuments(resultIpiaRecord.Id, fileName, fileBase64, '');

        ContentDocumentLink contentDocumentLink = [SELECT Id, ContentDocumentId FROM ContentDocumentLink 
                                                   WHERE LinkedEntityId = :resultIpiaRecord.Id];
        ContentDocument contentDocumentToDelete = new ContentDocument(Id = contentDocumentLink.ContentDocumentId);

        Test.startTest();
        try {
            delete contentDocumentToDelete;
            System.assert(false, 'Expected DMLException was not thrown');
        } catch (DmlException e) {
            System.assert(e.getMessage().contains(Label.IPIA_Record_Delete_DocuSignDoc_Error), 'Expected error message not found');
        }
        Test.stopTest();
    }

    @IsTest
    public static void allowsDeletionOfIPIADocLinkedToIPIARecordWithoutDocuSignMetaData() {
        String fileName = 'Test File';
        String fileBase64 = 'VGhpcyBpcyBhIHRlc3QgZmlsZSBiYXNlNjQ=';

        IPIA_Record__c ipiaRecord = new IPIA_Record__c(MitId__c = '912345456', FormName__c = 'Test Form');
        IPIA_Record__c resultIpiaRecord = IPIAController.createIPIARecord(ipiaRecord);
        IPIAController.uploadIPIADocuments(resultIpiaRecord.Id, fileName, fileBase64, '');

        ContentDocumentLink contentDocumentLink = [SELECT Id, ContentDocumentId FROM ContentDocumentLink 
                                                   WHERE LinkedEntityId = :resultIpiaRecord.Id];
        ContentDocument contentDocumentToDelete = new ContentDocument(Id = contentDocumentLink.ContentDocumentId);

        Boolean exceptionThrown = false;
        Test.startTest();
        try {
            delete contentDocumentToDelete;
        } catch (DmlException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        System.assert(!exceptionThrown, 'Should NOT throw exception when no DocuSign meta data for linked IPIA Record');
        List<ContentDocument> deletedDocument = [SELECT Id FROM ContentDocument WHERE Id = :contentDocumentToDelete.Id];
        System.assertEquals(0, deletedDocument.size(), 'ContentDocument should be deleted');
    }
}