force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Entity_Recid__c.field-meta.xml
<CustomField>
    <fullName>Entity_Recid__c</fullName>
    <description>External Reference to Forrester Oracle RecIds for multiple tables. eg: Case table PK case_recid. Agreement table PK agreement_recid. The Record type with the classification need to be considered</description>
    <label>Entity Recid</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/IPIA.recordType-meta.xml
<RecordType>
    <fullName>IPIA</fullName>
    <active>true</active>
    <label>IPIA</label>
</RecordType>

force-app/main/default/classes/CreateDocumentLinkBatch.cls
// This will be a manual trigger as the Sys Admin Job Users
// Or the user that has ownership of the ContentVersion Files
global class CreateDocumentLinkBatch implements Database.Batchable<SObject>, Database.Stateful {
    public  Enum DocumentLinkType { IPIA }
    private DocumentLinkType documentType { get; set; }

    public CreateDocumentLinkBatch(DocumentLinkType documentType) {
        this.documentType = documentType;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('CreateDocumentLinkBatch Start');
        String likeValue = null;
        if (this.documentType == DocumentLinkType.IPIA ) {
            likeValue = '%IPIAs%';
        }

        if (!String.isBlank(likeValue)) {
            System.debug('CreateDocumentLinkBatch Linking IPIAs');
            return Database.getQueryLocator([SELECT Id, Title, Description, PathOnClient, TagCsv, Entity_Recid__c, Document_Classification__c,
                                             ContentSize, VersionNumber, IsLatest, ContentDocumentId
                                             FROM ContentVersion
                                             WHERE PathOnClient like :likeValue
                                         	    and Entity_Recid__c = '-1'
                                                and isLatest = true]);
        } else {
            System.debug('CreateDocumentLinkBatch Empty Document Link Type');
            // Empty result set
            return Database.getQueryLocator([SELECT Id FROM ContentVersion  where Id = null LIMIT 0]);
        }
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        System.debug(scope.size() + ' ContentVersions found');
        if (!scope.isEmpty()) {
            //System.enqueueJob(new CreateDocumentLinkJob(scope), 0);
            CreateDocumentLinkJob job = new CreateDocumentLinkJob(scope);
            QueueableContext ctx = null;
            job.execute(ctx);
        }
    }

    global void finish(Database.BatchableContext bc) {
    }


}