force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Entity_Recid__c.field-meta.xml
<CustomField>
    <fullName>Entity_Recid__c</fullName>
    <description>External Reference to Forrester Oracle RecIds for multiple tables. eg: Case table PK case_recid. Agreement table PK agreement_recid. The Record type with the classification need to be considered</description>
    <label>Entity Recid</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Disclosure</fullName>
    <active>true</active>
    <description>Disclosure Record Type</description>
    <label>Disclosure</label>
</RecordType>

force-app/main/default/classes/ContentVersionHandler.cls
// https://salesforce.stackexchange.com/questions/317757/how-to-automatically-change-the-name-of-a-file-upon-creation
// https://gist.github.com/erev1/ceb51a208c9d9343094ffc4e1786d06e
// https://salesforce.stackexchange.com/questions/363647/a-trigger-on-contentversion-object-with-additional-logic
// Document_Classification__c is a required field and we dont have a default type currently.
public class ContentVersionHandler {

    public static void onAfterInsert(List<ContentVersion> cvs) {
        List<ContentVersion> createDocumentLinks = new List<ContentVersion>();

        for (ContentVersion cv : cvs) {
            if (cv.Entity_RecId__c == '-1' || cv.TagCsv != null) { //TODO check on Entity_RecId__c != null, better way to flag the linking process
                createDocumentLinks.add(cv);
            }
        }

        if(!createDocumentLinks.isEmpty()) {
             Integer batchSize = 50;
             List<ContentVersion> batch = new List<ContentVersion>();
             for (ContentVersion cv : createDocumentLinks) {
                batch.add(cv);
                if (batch.size() >= batchSize) {
                    enqueueDocumentLinkJob(batch);
                    batch = new List<ContentVersion>();
                }
             }
             if (!batch.isEmpty()) {
                enqueueDocumentLinkJob(batch);
             }
        }
    }

    private static void enqueueDocumentLinkJob(List<ContentVersion> createDocumentLinks) {
        Integer delayInMinutes = 0;
        System.enqueueJob(new CreateDocumentLinkJob(createDocumentLinks), delayInMinutes);
        // Need to first Link the Documents to Container Object before calling the CRDRDocumentUploadJob to change the Status
    }

    public static void onBeforeInsert(List<ContentVersion> cvs) {
        Id cvDisclosureRecordTypeId = null; 
        List<PermissionSetAssignment> docuSignPermissionSetAssignment = null;

        for(ContentVersion cv : cvs){
            if (cv.Title != null && cv.Title.startsWith('DocuSign')) {
                if (docuSignPermissionSetAssignment == null) {
                    docuSignPermissionSetAssignment = getDocuSignPermissionSetAssignment();
                }
                Boolean isDocuSignUser = (!docuSignPermissionSetAssignment.isEmpty()) ? true : false;
                if(isDocuSignUser) {
                    if (cvDisclosureRecordTypeId == null) {
                        cvDisclosureRecordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName().get('Disclosure').getRecordTypeId();
                        System.debug('cvDisclosureRecordTypeId = ' + cvDisclosureRecordTypeId );
                    }

                    cv.RecordTypeId = cvDisclosureRecordTypeId;
                    cv.Document_Classification__c = 'Signed Disclosure';
                }
            }
        }        
    }

    // If no data found will return empty List
    private static List<PermissionSetAssignment> getDocuSignPermissionSetAssignment() {
        List<PermissionSetAssignment> docuSignPermissionSetAssignment = [SELECT Id
                       FROM PermissionSetAssignment where PermissionSetId IN (select Id from PermissionSet where Name='DocuSign_App_User_API')
                  AND AssigneeId = :UserInfo.getUserId()];
        System.debug('docuSignPermissionSetAssignment size() = ' + docuSignPermissionSetAssignment.size() );
        return docuSignPermissionSetAssignment;
    }
}