force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Entity_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Sub_Type__c</fullName>
    <label>Data Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N_A</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>KUALI</fullName>
                <label>Kuali</label>
            </value>
            <value>
                <fullName>AGENCY</fullName>
                <label>Agency</label>
            </value>
            <value>
                <fullName>ASSIGN</fullName>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>BY-AGT</fullName>
                <label>License by Agent</label>
            </value>
            <value>
                <fullName>GOVUSE</fullName>
                <label>Government Use License</label>
            </value>
            <value>
                <fullName>INST</fullName>
                <label>Institution</label>
            </value>
            <value>
                <fullName>JOI NO</fullName>
                <label>Joint - No Purple File</label>
            </value>
            <value>
                <fullName>JOINT</fullName>
                <label>Joint Ownership</label>
            </value>
            <value>
                <fullName>LIC</fullName>
                <label>License</label>
            </value>
            <value>
                <fullName>LIC NO</fullName>
                <label>License - No Purple File</label>
            </value>
            <value>
                <fullName>MASTER</fullName>
                <label>Master Agreement</label>
            </value>
            <value>
                <fullName>MOU</fullName>
                <label>Memo of Understanding</label>
            </value>
            <value>
                <fullName>MTA</fullName>
                <label>Outgoing Material Transfer Agreement</label>
            </value>
            <value>
                <fullName>OBYAGN</fullName>
                <label>Option by Agent</label>
            </value>
            <value>
                <fullName>OPT</fullName>
                <label>Option</label>
            </value>
            <value>
                <fullName>PUBL</fullName>
                <label>Publishing</label>
            </value>
            <value>
                <fullName>SUBLIC</fullName>
                <label>Sublicense</label>
            </value>
            <value>
                <fullName>SW-EU</fullName>
                <label>Software End Use</label>
            </value>
            <value>
                <fullName>SW-LIC</fullName>
                <label>Software End Use Licenses &gt; 1K</label>
            </value>
            <value>
                <fullName>TECHTR</fullName>
                <label>Tech Transfer</label>
            </value>
            <value>
                <fullName>TM</fullName>
                <label>Trademark</label>
            </value>
            <value>
                <fullName>TRACKG</fullName>
                <label>Tracking</label>
            </value>
            <value>
                <fullName>SRA</fullName>
                <label>Sponsor Research Agreement</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Sponsor Agreement</label>
            </value>
            <value>
                <fullName>CONSORTIUM</fullName>
                <label>Consortium</label>
            </value>
            <value>
                <fullName>SUB_AWARD</fullName>
                <label>Subaward Document</label>
            </value>
            <value>
                <fullName>ASSIGNMENT</fullName>
                <label>Assignment</label>
            </value>
            <value>
                <fullName>AGREEMENT</fullName>
                <label>Agreement</label>
            </value>
            <value>
                <fullName>NDA</fullName>
                <label>Non-Disclosure Agreement (NDA)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Note_level__c.field-meta.xml
<CustomField>
    <fullName>Note_level__c</fullName>
    <label>Note level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Level A</fullName>
            </value>
            <value>
                <fullName>Level B</fullName>
            </value>
            <value>
                <fullName>Level C</fullName>
            </value>
            <value>
                <fullName>Level D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <label>Note</label>
</RecordType>

force-app/main/default/classes/CreateNoteRecord.cls
public with sharing class CreateNoteRecord {
    @AuraEnabled
    public static void createRecord (ContentVersion nt, id PrentId){
        try{
            if(nt != null){
                /*
                * A ContentNote is the same as a ContentDocument where FileType=SNOTE.
                * Creating a ContentVersion where PathOnclient is suffixed with '.snote' is the same as inserting a Note
                * Createing a ContentVersion will automatically create a ContentDocument and set the LatestPublishedVersionId to the Id of the ContentVersion
                * Since the contentversion has required fields, We are inserting a ContentVersion then find the ContentDocument
                */
                Id noteRecordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName().get('Note').getRecordTypeId();

                // UNSAFE_HTML_CONTENT: Notes cant be saved because it contains HTML tags. We need to use the ContentNote to handle the save
                String base64VersionData = String.valueOf(nt.VersionData);
                if(Test.isRunningTest()) {
                   // JavaScript does not send a 'real' Blob Object, and the Unit test does. String.valueOf will return the value of 'Blob[32]'
                   // and toString System.UnexpectedException: Illegal arguments
                   base64VersionData = nt.VersionData.toString();
                }


                System.debug('nt.VersionData ' + base64VersionData);
                ContentVersion version = new ContentVersion(
                    Title = nt.Title,
                    Document_Classification__c = 'Original_Document',
                    Entity_Sub_Type__c = 'N_A',
                    VersionData = Blob.valueOf(base64VersionData),
                    PathOnClient = nt.Title + '.snote',
                    recordTypeId = noteRecordTypeId,
                    IsMajorVersion = false,
                    Note_level__c = nt.Note_level__c
                );
                insert version;

                ContentDocument cd = [SELECT id FROM ContentDocument WHERE LatestPublishedVersionId = :version.Id];

                ContentDocumentLink cdl = new ContentDocumentLink(
                    ContentDocumentId = cd.id,
                    LinkedEntityId = PrentId,
                    ShareType = 'V',
                    Visibility = 'AllUsers'
                );
                insert cdl;

                // The Version Data is base 64 encoded
                ContentNote note = [SELECT Id, LatestPublishedVersionId, LatestContentId, Title, Content FROM ContentNote where Id =:cd.id];
                note.Content = EncodingUtil.base64Decode(base64VersionData);
                update note;

            }
        } catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void updateContentNote(String contentNoteId, String title, String contentBase64, String notelevel) {
        try {
            List<ContentVersion> updateContentVersionList = new List<ContentVersion>();
            System.debug('contentBase64 ' + contentBase64);
            ContentNote[] cntList = [SELECT Id, LatestPublishedVersionId, LatestContentId, Title FROM ContentNote where Id =:contentNoteId];
            String contentVersionId = cntList[0].LatestPublishedVersionId;

            updateContentVersionList.add(new ContentVersion(Id = contentVersionId,Title= title, Note_level__c = notelevel));

            // Update the record
            if(!updateContentVersionList.isEmpty()) {
                update updateContentVersionList;

                ContentNote note = [SELECT Id, LatestPublishedVersionId, LatestContentId, Title, Content FROM ContentNote where Id =:contentNoteId];
                note.Content = EncodingUtil.base64Decode(contentBase64);
                update note;

            }

        } catch(Exception e) {
            // Handle specific exception INSUFFICIENT_ACCESS_OR_READONLY
            if (e.getMessage().contains('INSUFFICIENT_ACCESS_OR_READONLY')) {
                throw new AuraHandledException('Action Denied: You do not have the necessary permissions to edit this note. Please contact the note owner or your administrator to request changes');
            } else {
                // Handle any other exceptions
                throw new AuraHandledException('Error updating ContentNote: ' + e.getMessage());
            }
        }
    }

    @AuraEnabled
    public static void deleteContentNote(String contentNoteId) {
        List<ContentNote> noteToDelete = new List<ContentNote>();
        try {
            noteToDelete = [SELECT Id FROM ContentNote WHERE Id =: contentNoteId AND OwnerId =: UserInfo.getUserId() LIMIT 1];

            // Delete the record
            if (!noteToDelete.isEmpty()) {
                delete noteToDelete;
            }
        } catch(Exception e) {
            throw new AuraHandledException('Error deleting ContentNote: ' + e.getMessage());
        }

        if (noteToDelete.isEmpty()) {
            throw new AuraHandledException('Action Denied: This note does not exist or you do not have the necessary permissions to delete it.');
        }
    }

    @AuraEnabled(cacheable=true)
    public static String getNoteRecordTypeId (){

        return Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName().get('Note').getRecordTypeId();
    }
    
    @AuraEnabled
    public static list<NotesWrapper> getNoteRecords (id PrentId) {
        TimeZone tz = UserInfo.getTimeZone();
        Id currentUserId = UserInfo.getUserId();

        Set<Id> contentDocumentIds = new Set<Id>();
        for(ContentDocumentLink conDoc : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :PrentId]){
            contentDocumentIds.add(conDoc.ContentDocumentId);
        }
        list<ContentNote> cntNotes =  [SELECT Id, Title, Content, CreatedBy.Name,CreatedById, CreatedDate, OwnerId from ContentNote where Id In: contentDocumentIds order by CreatedDate desc];
        list<ContentVersion> cntVersions = [SELECT Id, ContentDocumentId, Note_level__c FROM ContentVersion where ContentDocumentId In: contentDocumentIds];
        Map<Id,ContentVersion> CDId_cntVersnMap = new Map<Id,ContentVersion>();
        if(cntVersions.size() >0){
            for(ContentVersion cv: cntVersions){
                CDId_cntVersnMap.put(cv.ContentDocumentId,cv);
            }
        }
        List<NotesWrapper> wrapList = new List<NotesWrapper>();
        for(ContentNote cn: cntNotes){
            String contentStr = (cn.Content).toString();
            String createdDateStr = (cn.CreatedDate.format('MM/dd/yyyy, hh:mm aa', tz.getID())).toString();
            String noteLevel = '';
            if(CDId_cntVersnMap.containsKey(cn.Id)){
                noteLevel = CDId_cntVersnMap.get(cn.Id).Note_level__c;
            }
            wrapList.add(new NotesWrapper((cn.Id).toString(), (cn.Title).toString(), contentStr, (cn.CreatedById).toString(), createdDateStr, (cn.CreatedBy.Name).toString(),noteLevel, currentUserId == cn.OwnerId));
        }
        
        return wrapList;
    }
    
    public class NotesWrapper{
        @AuraEnabled public String Id{get;set;}
        @AuraEnabled public String Title{get;set;}
        @AuraEnabled public String Content{get;set;}
        @AuraEnabled public String CreatedById{get;set;}
        @AuraEnabled public String CreatedDate{get;set;}
        @AuraEnabled public String CreatedByName{get;set;}
        @AuraEnabled public String noteLevel{get;set;}
        @AuraEnabled public Boolean isOwner{get;set;}
        public NotesWrapper(String Id, String Title, String Content, String CreatedById, String CreatedDate, String CreatedByName, String noteLevel, Boolean isOwner){
            this.Id = Id;
            this.Title = Title;
            this.Content = Content; 
            this.CreatedById = CreatedById;
            this.CreatedDate = CreatedDate;
            this.CreatedByName = CreatedByName;
            this.noteLevel = noteLevel;
            this.isOwner = isOwner;
        }
    }
    
}