force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Disclosure</fullName>
    <active>true</active>
    <description>Disclosure Record Type</description>
    <label>Disclosure</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/All_Inventors_Signed__c.field-meta.xml
<CustomField>
    <fullName>All_Inventors_Signed__c</fullName>
    <formula>Inventors_Count__c &gt; 0 &amp;&amp; Unsigned_Inventors_Count__c == 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Have all inventors signed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Inventors_Count__c.field-meta.xml
<CustomField>
    <fullName>Inventors_Count__c</fullName>
    <label>Number of inventors</label>
    <summaryForeignKey>DisclosureInventor__c.Disclosure__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Last_Modified_at_time_of_Signing_Request__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_at_time_of_Signing_Request__c</fullName>
    <description>This field holds the Disclosures Last Modified Date/Time at the time Signing Envelope was requested, so that we are able to tell if Disclosure has been modified since last request when Disclosure is in a Draft status. If Disclosure has been changed then we will need to update the doc on DocuSign&apos;s envelope if not we can leave as is.</description>
    <label>Last Modified at time of Signing Request</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Signing_Envelop_Id__c.field-meta.xml
<CustomField>
    <fullName>Signing_Envelop_Id__c</fullName>
    <description>This field contains the envelopId from DocuSign which is unique to this Disclosure.</description>
    <externalId>true</externalId>
    <label>Signing Envelop Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Signing_Init_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Signing_Init_Job_Id__c</fullName>
    <description>Id of Async Job (Queueable) used for DocuSign integration. Keeping job id such that it will enable to use monitor progress.</description>
    <label>Signing Init Job Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocuSignSummaryInfoJob.cls
// https://www.salesforceben.com/batch-apex/#:~:text=The%20difference%20between%20queueable%20and,can%20run%20up%20to%20100!

public with sharing class DocuSignSummaryInfoJob implements Finalizer, Queueable, Database.AllowsCallouts {
    public static Integer DEFAULT_INIT_SIGNING_JOB_MAX_RETRY = 1;
    private String disclosureIdStr;
    private Integer count;

    public DocuSignSummaryInfoJob(String disclosureIdStr, Integer count){
        this.disclosureIdStr = disclosureIdStr;
        this.count = count;
    }

    public void execute(QueueableContext ctx) {
        DocuSignService docuSignService = new DocuSignService();
        Finalizer f = this;
        System.attachFinalizer(f);

        String jobId = '' + ctx.getJobId();
        System.debug('Begin: executing DocuSignSummaryInfoJob queueable job: ' + jobId);

        

        try {

            Disclosure__c disclosure = [SELECT Id, Name, Signing_Envelop_Id__c, Inventors_Count__c, All_Inventors_Signed__c, Last_Modified_at_time_of_Signing_Request__c,
                                Signing_Init_Job_Id__c
                                FROM Disclosure__c
                                WHERE Id = :this.disclosureIdStr];
            String envelopeId = disclosure.Signing_Envelop_Id__c;
            System.debug('Query: executing DocuSignSummaryInfoJob envelopeId: ' + envelopeId);
            if (String.isEmpty(envelopeId) && this.count <= retryCount()) {
               // Disclosure has no EnvelopId
               DisclosureWrapper disclosureWrapper = DisclosureDao.getDisclosureWrapperById(this.disclosureIdStr, null);
               Boolean includeCoverPage = false;
               String base64Pdf = DocumentGenerationService.generate(disclosureWrapper.recordTypeDeveloperName, disclosureWrapper, includeCoverPage);
               Blob disclosureDocument = EncodingUtil.base64Decode(base64Pdf);
               Integer delayInMinutes = 0;
               this.count = this.count + 1;
               envelopeId = docuSignService.createEnvelopeForDisclosure(disclosureIdStr, disclosureDocument, disclosureWrapper);
               disclosure.Signing_Envelop_Id__c = envelopeId;
               disclosure.Last_Modified_at_time_of_Signing_Request__c = DateTime.now();
               String newJobId = '' + System.enqueueJob(new DocuSignSummaryInfoJob(this.disclosureIdStr, this.count), delayInMinutes); // This call fails after 5 times when it hits the chaining limit
               disclosure.Signing_Init_Job_Id__c = newJobId;
               update disclosure;

               return;
            }
            System.debug('Step: executing DocuSignSummaryInfoJob addSummaryInfoDocument: ' + this.disclosureIdStr);
            docuSignService.addSummaryInfoDocument(this.disclosureIdStr);

            System.debug('Step: executing DocuSignSummaryInfoJob fetchDisclosureDocument: ' + this.disclosureIdStr);
            fetchDisclosureDocument(docuSignService, this.disclosureIdStr, disclosure.Name);

        } catch (Exception ex) {
            System.debug('DocuSignSummaryInfoJob Error executing the job [' + jobId + ']: ' + ex.getMessage());

            throw ex;
        } finally {
            System.debug('DocuSignSummaryInfoJob Completed: execution of queueable job: ' + jobId);
        }
    }

    private void fetchDisclosureDocument(DocuSignService docuSignService, String disclosureId, String disclosureName) {
        Blob inventorDocBlob = docuSignService.getDisclosureDocument(disclosureId);
        
        System.debug('DocuSignSummaryInfoJob inventorDocBlob received create ContentVersion');
        String fileName = 'DocuSign_' + disclosureName + '.pdf';

        List<ContentDocumentLink> documentLinks = [SELECT  LinkedEntityId , ContentDocumentId FROM  ContentDocumentLink
                WHERE LinkedEntityId = :disclosureId
                AND ContentDocumentId IN (SELECT ContentDocumentId FROM ContentVersion WHERE PathOnClient = :fileName and Document_Classification__c = 'Signed Disclosure' )
            ];
        Boolean isUpdate = false;    
        ContentDocumentLink documentLink = null;
        if( documentLinks.size() == 1 ){
            isUpdate = true;
            documentLink = documentLinks.get(0);
        }


        Id cvDisclosureRecordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName().get('Disclosure').getRecordTypeId();
        ContentVersion cv = new ContentVersion();
        cv.Title = fileName; // Display name of the files
        cv.PathOnClient = fileName;
        cv.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
        cv.VersionData = inventorDocBlob;
        cv.Document_Classification__c = 'Signed Disclosure';
        if (isUpdate && documentLink != null) {
            cv.ContentDocumentId = documentLink.ContentDocumentId; // Use the same ContentDocumentId
        }
        cv.RecordTypeId = cvDisclosureRecordTypeId;

        //Insert ContentVersion, need the Id.
        insert cv;

        System.debug('ContentVersion inventorDocBlob Created');
        if (!isUpdate) {
            // First get the Content Document Id from ContentVersion Object
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
            //create ContentDocumentLink  record
            ContentDocumentLink conDocLink = new ContentDocumentLink();
            conDocLink.LinkedEntityId = disclosureId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
            conDocLink.ContentDocumentId = conDoc;  //ContentDocumentId Id from ContentVersion
            //V - Viewer permission. C - Collaborator permission. I - Inferred permission
            conDocLink.ShareType = 'I';
            conDocLink.Visibility = 'AllUsers';

            insert conDocLink;
        }


    }

    // Finalizer implementation (Retry) for initial Queueable Job
    public void execute(FinalizerContext ctx) {
        String parentJobId = '' + ctx.getAsyncApexJobId();
        System.debug('Begin: executing finalizer attached to DocuSignSummaryInfoJob queueable job: ' + parentJobId);
        
        if (ctx.getResult() == ParentJobResult.SUCCESS) {
            System.debug('DocuSignSummaryInfoJob queueable job [' + parentJobId + '] completed successfully.');
        } else {
            if (ctx.getException() != null) {
                System.debug('DocuSignSummaryInfoJob queueable job [' + parentJobId + '] failed due to unhandled exception: ' + ctx.getException().getMessage());
                HandleLogException.logException(ctx.getException());
            }

            System.debug('DocuSignSummaryInfoJob failed, this.count: ' + this.count);
            System.debug('retryCount(): ' + retryCount());


            // retries requests exponentially, increasing the waiting time between retries
            System.debug('Enqueueing another instance of the DocuSignSummaryInfoJob queueable...');
            // removing the delay
            Integer delayInMinutes = 0; // will this create a sort of exponential backoff retry (?? increasing the waiting time between retries) is it too much to be in minutes (SF only allows for min's)

            System.debug('this.count <= retryCount(): ' + (this.count <= retryCount()));
            if (this.count <= retryCount()) {
                this.count = this.count + 1;
                String newJobId = '' + System.enqueueJob(new DocuSignSummaryInfoJob(this.disclosureIdStr, this.count), delayInMinutes); // This call fails after 5 times when it hits the chaining limit
                System.debug('Enqueued new job: ' + newJobId);


            } else {
                System.debug('DocuSignSummaryInfoJob queueable job retry\'s have been exhausted');
            }            
        }

        System.debug('Completed: execution of finalizer attached to DocuSignSummaryInfoJob queueable job: ' + parentJobId);
    }

  public static void onDisclosureApprove(List<Disclosure__c> queryDisclosures,  Map<Id,Disclosure__c> oldDis) {
      for(Disclosure__c d:queryDisclosures) {
            Boolean onApproved = d.Status__c == 'Approved' && d.Status__c != oldDis.get(d.Id).Status__c;
            if(onApproved) {
                Integer currCount = 1;
                String envelopeId = d.Signing_Envelop_Id__c;
                Boolean createJob = true;
                // Dont create the Job if the envelopeId is Empty and we are busy with Unit testing
                if ((Test.isRunningTest() && String.isEmpty(envelopeId))) {
                    // If a disclosure is approved in a Unit test then a Queueable job is created. To avoid having to mock ALL the Call outs for each test
                    // not related to DocuSign we only run the test where the envelopeId was set.
                    createJob = false;
                }
                if (createJob) {
                    Id newJobId = System.enqueueJob(new DocuSignSummaryInfoJob(d.Id, currCount), 0);
                }
            }
        }
    }

    private static Integer retryCount() {
        try {
            String retryConf = ConfigurationBuilder.getConfigurationToString('initSigningJobMaxNumberOfRetry');
            return Integer.ValueOf(retryConf);
        } catch (ConfigurationBuilder.MissingConfigurationException ex) {
            return DocuSignEnvelopeForDisclosureJob.DEFAULT_INIT_SIGNING_JOB_MAX_RETRY;
        }
    }


}