force-app/main/default/objects/Contact_Action__c/Contact_Action__c.object-meta.xml
<CustomObject>
    <label>Contact Action</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Contact Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Last_Modified_at_time_of_Signing_Request__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_at_time_of_Signing_Request__c</fullName>
    <description>This field holds the Disclosures Last Modified Date/Time at the time Signing Envelope was requested, so that we are able to tell if Disclosure has been modified since last request when Disclosure is in a Draft status. If Disclosure has been changed then we will need to update the doc on DocuSign&apos;s envelope if not we can leave as is.</description>
    <label>Last Modified at time of Signing Request</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/Disclosure_Action__c.object-meta.xml
<CustomObject>
    <label>Disclosure Action</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Action__c/fields/Contact_Action__c.field-meta.xml
<CustomField>
    <fullName>Contact_Action__c</fullName>
    <label>Contact Action</label>
    <referenceTo>Contact_Action__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/recordTypes/Sign_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Sign_Disclosure</fullName>
    <active>true</active>
    <label>Sign Disclosure</label>
</RecordType>

force-app/main/default/classes/ExpiredSignDisclosureActions.cls
public class ExpiredSignDisclosureActions implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
     public class InvalidParameterException extends Exception {}

    // This need to be stateful batchable process
    Integer lastNDaysBefore = 120;
    Integer lastNDaysAfter = 999;

    public ExpiredSignDisclosureActions(){}

    public ExpiredSignDisclosureActions(Integer lastNDaysBeforeAugust, Integer lastNDaysAfterAugust ){
        this.lastNDaysBefore = lastNDaysBeforeAugust ;
        this.lastNDaysAfter = lastNDaysAfterAugust;
        if ( this.lastNDaysBefore <= 0 || this.lastNDaysAfter <= 0 ) {
            throw new InvalidParameterException('Expecting positive values');
        }
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
       Id recordTypeIdSignDisclosure = Schema.SObjectType.Disclosure_Action__c.getRecordTypeInfosByDeveloperName().get('Sign_Disclosure').getRecordTypeId();
       DateTime august = DateTime.newInstanceGmt(2024, 8, 1, 0, 0, 0);
       DateTime last120Days = Util.now().addDays(this.lastNDaysBefore * -1);
       DateTime last999Days = Util.now().addDays(this.lastNDaysAfter * -1);
       // The envelope create date is based on the first time someone attempts to sign the disclosure and NOT on the action create date
       // We dont store the envelope creation date only when it is modified
       return Database.getQueryLocator([ SELECT Id, Contact_Action__r.Id, Contact_Action__r.CreatedDate
                 FROM Disclosure_Action__c
                 WHERE
                     Contact_Action__r.Status__c = 'Pending'
                     AND Disclosure__r.Last_Modified_at_time_of_Signing_Request__c != null
                     AND (
                        (Disclosure__r.Last_Modified_at_time_of_Signing_Request__c < :august  AND Disclosure__r.Last_Modified_at_time_of_Signing_Request__c <= :last120Days)
                        OR (Disclosure__r.Last_Modified_at_time_of_Signing_Request__c >= :august  AND Disclosure__r.Last_Modified_at_time_of_Signing_Request__c <= :last999Days)
                     )
                     AND RecordTypeId = :recordTypeIdSignDisclosure
                   ]);
    }

    public void execute(Database.BatchableContext bc, List<Disclosure_Action__c> signActions) {
       List<Contact_Action__c> contactActions = new List<Contact_Action__c>();
       for (Disclosure_Action__c disclosureAction : signActions) {
           // Update all Contact Actions with new status
           Contact_Action__c contactAction = disclosureAction.Contact_Action__r;
           contactAction.Status__c = 'Canceled';
           contactActions.add(contactAction);
           System.debug('Contact Action to be updated: ' + contactAction.toString());    
       }
       System.debug('Contact Actions to be updated: ' + contactActions.toString());
       System.debug('Rows selected: ' + signActions.size());
       System.debug('Rows change: ' + contactActions.size());
       update contactActions;
       System.debug('Changes SUCCESSFUL');
    }

    public void finish(Database.BatchableContext bc) {
    }

}