force-app/main/default/objects/Contact_Action__c/Contact_Action__c.object-meta.xml
<CustomObject>
    <label>Contact Action</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Contact Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Actions</relationshipLabel>
    <relationshipName>Contact_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Last_Modified_at_time_of_Signing_Request__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_at_time_of_Signing_Request__c</fullName>
    <description>This field holds the Disclosures Last Modified Date/Time at the time Signing Envelope was requested, so that we are able to tell if Disclosure has been modified since last request when Disclosure is in a Draft status. If Disclosure has been changed then we will need to update the doc on DocuSign&apos;s envelope if not we can leave as is.</description>
    <label>Last Modified at time of Signing Request</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/Disclosure_Action__c/Disclosure_Action__c.object-meta.xml
<CustomObject>
    <label>Disclosure Action</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Action__c/fields/Contact_Action__c.field-meta.xml
<CustomField>
    <fullName>Contact_Action__c</fullName>
    <label>Contact Action</label>
    <referenceTo>Contact_Action__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/recordTypes/Sign_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Sign_Disclosure</fullName>
    <active>true</active>
    <label>Sign Disclosure</label>
</RecordType>

force-app/main/default/classes/ExpiredSignDisclosureActionsTest.cls
@isTest
public with sharing class ExpiredSignDisclosureActionsTest {
    
    @TestSetup
    static void makeData(){
        TestSetup.defaultConfiguration();
    }

    @isTest
    public static void testCancelSignDisclosureActions_Test1() {

        Id recordTypeIdSoftware = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        Account inventorContact = SampleDataFactory.createContact('Bob', true, '123456781');
        Account inventorTwoContact = SampleDataFactory.createContact('Jack', false, '123456780');
        Account nonMitInventorContact = SampleDataFactory.createContact('Donald', false, null);
        Account submittingContact = SampleDataFactory.createContact('Jeff', true, '11345678');

        Disclosure__c disclosure120Days = SampleDataFactory.createDisclosureSOB(recordTypeIdSoftware, 'Title Of', 'Draft', submittingContact);
        Disclosure__c disclosure119Days = SampleDataFactory.createDisclosureSOB(recordTypeIdSoftware, 'Title Of', 'Draft', submittingContact);
        Disclosure__c disclosure999Days = SampleDataFactory.createDisclosureSOB(recordTypeIdSoftware, 'Title Of', 'Draft', submittingContact);

        Util.now = DateTime.newInstanceGmt(2024, 8, 1, 0 ,0 , 0);
        disclosure120Days.Last_Modified_at_time_of_Signing_Request__c = Util.now().addDays(-120); // DocuSign marked the Envelopes as 120 days
        disclosure119Days.Last_Modified_at_time_of_Signing_Request__c = Util.now().addDays(-119); // This should still be valid
        disclosure999Days.Last_Modified_at_time_of_Signing_Request__c = Util.now().addDays(-999);
        update new List<Disclosure__c> {disclosure120Days, disclosure119Days, disclosure999Days};

        createContactAction(disclosure120Days, inventorContact);
        createContactAction(disclosure119Days, inventorTwoContact);
        createContactAction(disclosure999Days, nonMitInventorContact);

        List<Disclosure_Action__c> actions = getPendingSignedActions();

        System.Assert(actions.size() == 3, 'Three Sign Disclosure actions should have been created, one for each Inventor on the Disclosures');

        Test.startTest();
            Integer lastNDaysBefore = 120;
            Integer lastNDaysAfter = 999;
            ExpiredSignDisclosureActions sfu = new ExpiredSignDisclosureActions(lastNDaysBefore, lastNDaysAfter);
            Database.executeBatch(sfu, 200);
        Test.stopTest();
        List<Disclosure_Action__c> actionsAfter = getPendingSignedActions();
        System.Assert(actionsAfter.size() == 1, 'Two Expired Sign Disclosure Actions should have been Canceled');

    }

    @isTest
    public static void testExpiryScheduler() {
        Test.startTest();

        Integer olderThan120 = ExpiredSignDisclosureActionsSchedule.getConfigValue(ExpiredSignDisclosureActionsSchedule.CANCEL_SIGN_ACTIONS_OLDER_THAN_120_DAYS, 12);
        Integer olderThan999 = ExpiredSignDisclosureActionsSchedule.getConfigValue(ExpiredSignDisclosureActionsSchedule.CANCEL_SIGN_ACTIONS_OLDER_THAN_999_DAYS, 99);
        Integer defaultConfig = ExpiredSignDisclosureActionsSchedule.getConfigValue('missingConfig', 800);

        SchedulableContext sc = null;
        ExpiredSignDisclosureActionsSchedule job = new ExpiredSignDisclosureActionsSchedule();
        job.execute(sc);
        Test.stopTest();

        System.assert(olderThan120 == 120, 'Config value not read');
        System.assert(olderThan999 == 999, 'Config value not read');
        System.assert(defaultConfig == 800, 'Default value not set');


    }


    @isTest
    public static void testCancelSignDisclosureActions_Test2() {

        Id recordTypeIdSoftware = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        Account inventorContact = SampleDataFactory.createContact('Bob', true, '123456781');
        Account inventorTwoContact = SampleDataFactory.createContact('Jack', false, '123456780');
        Account nonMitInventorContact = SampleDataFactory.createContact('Donald', false, null);
        Account submittingContact = SampleDataFactory.createContact('Jeff', true, '11345678');

        Disclosure__c disclosure120Days = SampleDataFactory.createDisclosureSOB(recordTypeIdSoftware, 'Title Of', 'Draft', submittingContact);
        Disclosure__c disclosure119Days = SampleDataFactory.createDisclosureSOB(recordTypeIdSoftware, 'Title Of', 'Draft', submittingContact);
        Disclosure__c disclosure999Days = SampleDataFactory.createDisclosureSOB(recordTypeIdSoftware, 'Title Of', 'Draft', submittingContact);

        Util.now = DateTime.newInstanceGmt(2024, 11, 29, 0, 0, 0); // 120 days in the future from 1st Aug
        disclosure120Days.Last_Modified_at_time_of_Signing_Request__c = Util.now().addDays(-120);
        disclosure119Days.Last_Modified_at_time_of_Signing_Request__c = Util.now().addDays(-119); // The expiry should be 999 for these
        disclosure999Days.Last_Modified_at_time_of_Signing_Request__c = Util.now().addDays(-999); // Still created before 1st Aug
        update new List<Disclosure__c> {disclosure120Days, disclosure119Days, disclosure999Days};

        createContactAction(disclosure120Days, inventorContact);
        createContactAction(disclosure119Days, inventorTwoContact);
        createContactAction(disclosure999Days, nonMitInventorContact);

        List<Disclosure_Action__c> actions = getPendingSignedActions();

        System.Assert(actions.size() == 3, 'Three Sign Disclosure actions should have been created, one for each Inventor on the Disclosure');

        Test.startTest();
            ExpiredSignDisclosureActions sfu = new ExpiredSignDisclosureActions();
            Database.executeBatch(sfu, 200);
        Test.stopTest();
        List<Disclosure_Action__c> actionsAfter = getPendingSignedActions();
        System.Assert(actionsAfter.size() == 2, 'One Expired Sign Disclosure Actions should have been Canceled');

    }

    @isTest
    public static void testCancelSignDisclosureActions_Test3() {

        Id recordTypeIdSoftware = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        Account inventorContact = SampleDataFactory.createContact('Bob', true, '123456781');
        Account inventorTwoContact = SampleDataFactory.createContact('Jack', false, '123456780');
        Account nonMitInventorContact = SampleDataFactory.createContact('Donald', false, null);
        Account submittingContact = SampleDataFactory.createContact('Jeff', true, '11345678');

        Disclosure__c disclosure120Days = SampleDataFactory.createDisclosureSOB(recordTypeIdSoftware, 'Title Of', 'Draft', submittingContact);
        Disclosure__c disclosure119Days = SampleDataFactory.createDisclosureSOB(recordTypeIdSoftware, 'Title Of', 'Draft', submittingContact);
        Disclosure__c disclosure999Days = SampleDataFactory.createDisclosureSOB(recordTypeIdSoftware, 'Title Of', 'Draft', submittingContact);


        Util.now = DateTime.newInstanceGmt(2027, 4, 27, 0, 0, 0); // 999 days in the future from 1st Aug
        disclosure120Days.Last_Modified_at_time_of_Signing_Request__c = Util.now().addDays(-120);
        disclosure119Days.Last_Modified_at_time_of_Signing_Request__c = Util.now().addDays(-119); // The expiry should be 999 for these
        disclosure999Days.Last_Modified_at_time_of_Signing_Request__c = Util.now().addDays(-999);
        update new List<Disclosure__c> {disclosure120Days, disclosure119Days, disclosure999Days};

        createContactAction(disclosure120Days, inventorContact);
        createContactAction(disclosure119Days, inventorTwoContact);
        createContactAction(disclosure999Days, nonMitInventorContact);

        List<Disclosure_Action__c> actions = getPendingSignedActions();

        System.Assert(actions.size() == 3, 'Three Sign Disclosure actions should have been created, one for each Inventor on the Disclosure');

        Test.startTest();
            ExpiredSignDisclosureActions sfu = new ExpiredSignDisclosureActions();
            Database.executeBatch(sfu, 200);
        Test.stopTest();
        List<Disclosure_Action__c> actionsAfter = getPendingSignedActions();
        System.Assert(actionsAfter.size() == 2, 'One Expired Sign Disclosure Actions should have been Canceled');

    }

    private static void createContactAction(Disclosure__c disclosure, Account contact) {
        Id recordTypeIdSignDisclosure = Schema.SObjectType.Disclosure_Action__c.getRecordTypeInfosByDeveloperName().get('Sign_Disclosure').getRecordTypeId();

        Contact_Action__c contactAction = new Contact_Action__c();
        contactAction.Status__c = 'Pending';
        contactAction.Contact__c = contact.Id;
        insert contactAction;


        Disclosure_Action__c signAction = new Disclosure_Action__c();
        signAction.Disclosure__c = disclosure.Id;
        signAction.RecordTypeId = recordTypeIdSignDisclosure;
        signAction.Contact_Action__c = contactAction.Id;
        insert signAction;


    }

     /*
     * Helper class for getting SignDisclosure Actions
     */
    private static List<Disclosure_Action__c> getPendingSignedActions() {
        Id recordTypeIdSignDisclosure = Schema.SObjectType.Disclosure_Action__c.getRecordTypeInfosByDeveloperName()
            .get('Sign_Disclosure')
            .getRecordTypeId();
        List<Disclosure_Action__c> actions = [
            SELECT Id, Contact_Action__r.Id
            FROM Disclosure_Action__c
            WHERE
                Contact_Action__r.Status__c = 'Pending'
                AND RecordTypeId = :recordTypeIdSignDisclosure
        ];
        return actions;
    }

}