force-app/main/default/objects/Open_Source__c/Open_Source__c.object-meta.xml
<CustomObject>
    <label>Open Source</label>
    <nameField>
        <label>Open Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Source__c/fields/Software_Code_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Software_Code_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Software Code Disclosure</label>
    <referenceTo>Software_Code_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Software_Code_Disclosure__c/Software_Code_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Software Code Disclosure</label>
    <nameField>
        <label>Software Code Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Code Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Is_Open_Source_YN__c.field-meta.xml
<CustomField>
    <fullName>Is_Open_Source_YN__c</fullName>
    <label>Is Open Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SoftwareCodeDisclosureTriggerHandler.cls
public class SoftwareCodeDisclosureTriggerHandler {
    public static void onAfterUpdate(List<Software_Code_Disclosure__c> softwareCodeList, Map<Id, Software_Code_Disclosure__c> oldSoftwareCodeMap) {
        // If the Is_Open_Source_YN__c field is No, delete the related Open_Source__c object
        List<Open_Source__c> openSourceDeleteList = new List<Open_Source__c>();
        for(Software_Code_Disclosure__c softwareCode : softwareCodeList) {
            if(
                softwareCode.Is_Open_Source_YN__c == 'No' &&
                oldSoftwareCodeMap.get(softwareCode.Id).Is_Open_Source_YN__c == 'Yes'
            ) {
                openSourceDeleteList.addAll(DisclosureRecordFetch.getOpenSourceBySoftwareCodeId(softwareCode.Id));
            }
        }

        if(!openSourceDeleteList.isEmpty()) {
            delete openSourceDeleteList;
        }
    }
}