force-app/main/default/objects/BIP_PI__c/BIP_PI__c.object-meta.xml
<CustomObject>
    <label>BIP PI</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP PI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Pis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_PI__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Requested_Action__c.field-meta.xml
<CustomField>
    <fullName>Requested_Action__c</fullName>
    <label>Requested Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request background case review from proposal</fullName>
            </value>
            <value>
                <fullName>Report undisclosed background IP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Received</fullName>
                <default>true</default>
                <label>Request Received</label>
            </value>
            <value>
                <fullName>Assigned to TLO</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Assigned to PI</fullName>
            </value>
            <value>
                <fullName>PI Review Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateBipPi.cls
public with sharing class UpdateBipPi {

   //TODO move to the BIPController rather 
   @AuraEnabled
   public static string UpdateBipPiRecords(List<Map<String,String>> records){
    try {
        List<Bip_Pi__c> bipis = new List<BIP_Pi__c>();
         
       for(Map<String,String> record:records){
        Bip_Pi__c bip_pi= [Select Requested_Action__c, BIP_Request__r.Id, Comment__c from Bip_Pi__c where Id = :record.get('Id') limit 1];
        if(record.get('selectedActions')!=''){
            bip_pi.Requested_Action__c=record.get('selectedActions');
            system.debug('UpdateBipPi selectedActions updated');
            
        }
      

        if(record.get('comments')!=''){
            bip_pi.Comment__c=record.get('comments');
            system.debug('UpdateBipPi comments updated');
        }

        bip_pi.Status__c = 'Pending Feedback';
    
        bipis.add(bip_pi);
       }
       system.debug(JSON.serializePretty(records));
       update bipis;
       BIP_Request__c vRequest = new Bip_Request__c(id=bipis[0].BIP_Request__r.id, Status__c='Assigned to PI');
       update vRequest;  


        return 'success';


    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }
}