force-app/main/default/objects/BIP_PI__c/BIP_PI__c.object-meta.xml
<CustomObject>
    <label>BIP PI</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP PI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Pis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_PI__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/PI__c.field-meta.xml
<CustomField>
    <fullName>PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary PI</fullName>
            </value>
            <value>
                <fullName>Additional PI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateAdditionalBip.cls
public without sharing class CreateAdditionalBip {
   @AuraEnabled
   public static string createAdditionalBips(List<Map<String,String>> bipPis,Id bipReqId,Map<String,String> accountData){
    try {
        system.debug('createAdditionalBips');
        List<Bip_Pi__c> bipPiList = new List<Bip_Pi__c>();
        for(Map<String,String> bipMap:bipPis){
            Bip_Pi__c bipPi=new Bip_Pi__c();
            if(bipMap.containsKey('personRole')){
                bipPi.Role__c=bipMap.get('personRole');
            }
            else{
                bipPi.Role__c='Additional PI'; 
            }
    
           String accId= accountData.get(bipMap.get('mitId'));
           
           system.debug('accId--'+accId);
            bipPi.PI__c=accId;
            bipPi.BIP_Request__c=bipReqId;
            bipPiList.add(bipPi);
        }
       
      
        insert bipPiList;
        system.debug('recooInserted '+bipPiList);
        return 'Success';


        
    } catch (Exception e) {
 
        throw new AuraHandledException(e.getMessage());
    }
   }
}