force-app/main/default/objects/BIP_PI__c/BIP_PI__c.object-meta.xml
<CustomObject>
    <label>BIP PI</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP PI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Pis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_PI__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/PI__c.field-meta.xml
<CustomField>
    <fullName>PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary PI</fullName>
            </value>
            <value>
                <fullName>Additional PI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/TLO_Officer_Name__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Name__c</fullName>
    <label>TLO Officer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/email_CCs__c.field-meta.xml
<CustomField>
    <fullName>email_CCs__c</fullName>
    <label>CC Correspondence</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Primary_PI__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI__c</fullName>
    <label>Primary PI Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Primary_PI_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Requests (Primary PI Lookup)</relationshipLabel>
    <relationshipName>BIP_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Project_Title__c.field-meta.xml
<CustomField>
    <fullName>Project_Title__c</fullName>
    <label>Proposal/Research Project Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Proposal_Number__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Number__c</fullName>
    <label>Proposal Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Expedited</fullName>
            </value>
            <value>
                <fullName>Non-MIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Requestor_Department__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Department__c</fullName>
    <formula>Requestor_Name__r.PersonContact.Department</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requestor Department</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <formula>Requestor_Name__r.PersonContact.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requestor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requestor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please use Person Account only</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Requests</relationshipLabel>
    <relationshipName>BIP_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Received</fullName>
                <default>true</default>
                <label>Request Received</label>
            </value>
            <value>
                <fullName>Assigned to TLO</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Assigned to PI</fullName>
            </value>
            <value>
                <fullName>PI Review Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/TLO_Officer_Name__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Name__c</fullName>
    <label>Primary TLO</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BipRequestHelper.cls
public class BipRequestHelper {

    public static void afterBipRequestUpdate(List<BIP_Request__c> newBips , List<Bip_Request__c> oldBips){
        
        
        List<BIP_Request__c> toUpdate = new  List<BIP_Request__c>();
        List<BIP_Request__c> newbipRecs = [Select Id, Account_Number__c,Status__c, Owner.Email , email_CCs__c, Requestor_Name__c, Primary_PI__c, Proposal_Number__c, Request_Type__c, Due_Date__c, Comments__c, Requestor_Department__c, Requestor_Email__c, Primary_PI_Lookup__c, Primary_PI_Lookup__r.PersonEmail,  Primary_PI_Lookup__r.PersonContactId ,Project_Title__c , (SELECT Id, Status__c, Role__c, TLO_Officer_Name__c, CreatedBy.Name ,CreatedBy.Email ,PI__c, PI__r.Id , PI__r.Name FROM BIP_PIs__r)  From BIP_Request__c Where Id IN :newBips];
        List<BIP_Request__c> oldbipRecs = [Select Id, Status__c from Bip_request__c where Id in :oldBips]; 
        try{ 
      		 for(Integer i=0;i<newbipRecs.size();i++){
                        system.debug('status not changed');
               system.debug(newbipRecs[i].Id);
                    system.debug(oldBips[i].Id);
                 
            	if(newbipRecs[i].Status__c != oldBips[i].Status__c){
                    
                 system.debug('status changes');

                 List<BIP_PI__c> children = newbipRecs[i].BIP_PIs__r;
                 List<String> childEmails = new List<String>();
                 String childEmailString = '';
                
                 for(BIP_PI__c c:children ){
  
                	system.debug('bipRec.Owner.Email-'+newbipRecs[i].Owner.Email+' c.Owner.Email-:'+c.CreatedBy.Email );
                	if( c.CreatedBy.Email!=newbipRecs[i].Owner.Email){
              
                 		if(c.CreatedBy.Email!=null){
                       		childEmails.add(c.CreatedBy.Email);
                    		childEmailString=childEmailString+ c.CreatedBy.Email +',';
                  		}
                 		}
                     
                if(c.PI__c!=null && c.PI__r.PersonEmail!=null)
              	{ 	system.debug('c.Primary_PI_Lookup__c!=null');
               
                	childEmails.add(c.PI__r.PersonEmail);

               		childEmailString=childEmailString+c.PI__r.PersonEmail+',';
              }
                     
            }
                newbipRecs[i].email_CCs__c = childEmailString;
                toUpdate.add(newbipRecs[i]);
                    
                string toEmail = newbipRecs[i].Primary_PI_Lookup__r.PersonEmail;
                
              system.debug('now calling sendEmail');
              SendEmailController.sendEmail(newbipRecs[i].Id,'NA', toEmail, false, '', childEmails, 'NA', newbipRecs[i].Primary_PI_Lookup__c==null, true);
                 system.debug('after calling sendEmail');  
            }
        }
       
        update toUpdate;
        }
         catch (Exception ex) {
            throw new AuraHandledException('Error while sending email: ' + ex.getMessage());
        }
        
    }

    // public static void afterBIPPIInsert(List<BIP_PI__c> vBIPPIList){

    //     if (!Test.isRunningTest()) {
    //         System.enqueueJob(new QueryQueueable(vBIPPIList));
    //     }
    // }
    
}