force-app/main/default/objects/BIP_PI__c/BIP_PI__c.object-meta.xml
<CustomObject>
    <label>BIP PI</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP PI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Pis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_PI__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/PI__c.field-meta.xml
<CustomField>
    <fullName>PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary PI</fullName>
            </value>
            <value>
                <fullName>Additional PI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/TLO_Officer_Name__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Name__c</fullName>
    <label>TLO Officer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/email_CCs__c.field-meta.xml
<CustomField>
    <fullName>email_CCs__c</fullName>
    <label>CC Correspondence</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Primary_PI__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI__c</fullName>
    <label>Primary PI Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Primary_PI_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Requests (Primary PI Lookup)</relationshipLabel>
    <relationshipName>BIP_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Project_Title__c.field-meta.xml
<CustomField>
    <fullName>Project_Title__c</fullName>
    <label>Proposal/Research Project Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Proposal_Number__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Number__c</fullName>
    <label>Proposal Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Expedited</fullName>
            </value>
            <value>
                <fullName>Non-MIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Requestor_Department__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Department__c</fullName>
    <formula>Requestor_Name__r.PersonContact.Department</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requestor Department</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <formula>Requestor_Name__r.PersonContact.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requestor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requestor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please use Person Account only</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Requests</relationshipLabel>
    <relationshipName>BIP_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Received</fullName>
                <default>true</default>
                <label>Request Received</label>
            </value>
            <value>
                <fullName>Assigned to TLO</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Assigned to PI</fullName>
            </value>
            <value>
                <fullName>PI Review Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/TLO_Officer_Name__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Name__c</fullName>
    <label>Primary TLO</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getEmailData.cls
public with sharing class GetEmailData {
    public getEmailData() {}
    @AuraEnabled
    public static Map<String,Object> getEmailInfo(String recId){
        system.debug(recId);
        EmailTemplate template = new EmailTemplate();
			template = [SELECT Id, Name,Body from EmailTemplate WHERE DeveloperName ='Send_BIP_Request'  LIMIT 1];
      system.debug(template);
			BIP_Request__c bipRec = [Select Id, Account_Number__c, Owner.Email , email_CCs__c, Requestor_Name__c, Primary_PI__c, Proposal_Number__c, Request_Type__c, Due_Date__c, Comments__c, Requestor_Department__c, Requestor_Email__c, Primary_PI_Lookup__c, Primary_PI_Lookup__r.PersonEmail,  Primary_PI_Lookup__r.PersonContactId ,Project_Title__c , (SELECT Id, Status__c, Role__c, TLO_Officer_Name__c, CreatedBy.Name ,CreatedBy.Email ,PI__c, PI__r.Id , PI__r.Name, PI__r.PersonEmail FROM BIP_PIs__r)  From BIP_Request__c Where Id =:recId];
            List<BIP_PI__c> children = bipRec.BIP_PIs__r;
            system.debug('bippisize--'+children.size());
            List<String> childEmails = new List<String>();
           String PersonContactId = bipRec.Primary_PI_Lookup__r.PersonContactId;
             system.debug('-------'+PersonContactId);
             if(bipRec.email_CCs__c==null){
              String childEmailString = '';
            system.debug('children-----'+children);
              for(BIP_PI__c c:children ){
  
                system.debug('bipRec.Owner.Email-'+bipRec.Owner.Email+' c.Owner.Email-:'+c.CreatedBy.Email );
                 if( c.CreatedBy.Email!=bipRec.Owner.Email){
              
                  if(c.CreatedBy.Email!=null){
                    childEmails.add(c.CreatedBy.Email);
                    childEmailString=childEmailString+ c.CreatedBy.Email +',';
                  }
                 }
                if(c.PI__c!=null && c.PI__r.PersonEmail!=null)
              { 
               
                childEmails.add(c.PI__r.PersonEmail);

               childEmailString=childEmailString+c.PI__r.PersonEmail+',';
              }
            }
            bipRec.email_CCs__c = childEmailString;
            update bipRec;
             
             }
             else{
              childEmails= bipRec.email_CCs__c.split(',');
              system.debug('childEmails'+childEmails);
             }
             
             system.debug(bipRec.Primary_PI_Lookup__r.PersonEmail);
             String reqName =  bipRec.Requestor_Name__c==null ? '': bipRec.Requestor_Name__c;
             String reqEmail=  bipRec.Requestor_Email__c==null ? '': bipRec.Requestor_Email__c;
             String proposalNumber =  bipRec.Proposal_Number__c==null ? '': bipRec.Proposal_Number__c;
             String reqDep =  bipRec.Requestor_Department__c==null ? '': bipRec.Requestor_Department__c;
             String ppi =  bipRec.Primary_PI__c==null ? '': bipRec.Primary_PI__c;
             String dueDate =  bipRec.Due_Date__c==null ? '' : String.valueOf(bipRec.Due_Date__c);
             String projectTitle =  bipRec.Project_Title__c == null ? '': bipRec.Project_Title__c;
             String comments =  bipRec.Comments__c == null ? '': bipRec.Comments__c;
             String reqType =  bipRec.Request_Type__c == null ? '': bipRec.Request_Type__c;
   

           String previewEmailBody =  String.valueOf(template.Body).replace('{!BIP_Request__c.Requestor_Name__c}',reqName)
                                         .replace('{!BIP_Request__c.Requestor_Email__c}',reqEmail)
                                        .replace('{!BIP_Request__c.Proposal_Number__c}',proposalNumber)
                                        .replace('{!BIP_Request__c.Requestor_Department__c}',reqDep)
                                        .replace('{!BIP_Request__c.Primary_PI__c}',ppi)
                                        .replace('{!BIP_Request__c.Due_Date__c}',dueDate)
                                        .replace('{!BIP_Request__c.Project_Title__c}',projectTitle)
                                        .replace('{!BIP_Request__c.Comments__c}',comments)
                                        .replace('{!BIP_Request__c.Request_Type__c}',reqType);
                                        
               system.debug(previewEmailBody);
                                
            string toEmail = bipRec.Primary_PI_Lookup__r.PersonEmail;
            system.debug('Email='+bipRec.Primary_PI_Lookup__r.PersonEmail);
            system.debug('Temp='+template);
            Map<String,Object> result = new Map<String,Object>{
                'to' =>toEmail,
                'cc' => childEmails,
                'templateBody'=>previewEmailBody,
                'templateId'=>template.Id,
                'PersonContactId'=>PersonContactId,
               'isPrimaryPiLookupNull'=> bipRec.Primary_PI_Lookup__c == null
            };
            return result;


    }
}