force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Copyright_Disclosure__c/Copyright_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Copyright Disclosure</label>
    <nameField>
        <label>Copyright Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copyright Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Copyright Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Copyright_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Copyright Disclosures</relationshipLabel>
    <relationshipName>Copyright_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Delegated_To__c.field-meta.xml
<CustomField>
    <fullName>Delegated_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegated To</label>
    <referenceTo>Department_Head__c</referenceTo>
    <relationshipLabel>Delegated By</relationshipLabel>
    <relationshipName>Delegated_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>TLO Case Number</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Rejected_By__c.field-meta.xml
<CustomField>
    <fullName>Rejected_By__c</fullName>
    <label>Rejected By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>TLO Admin</fullName>
            </value>
            <value>
                <fullName>Department Head</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/TLO_License_Officer__c.field-meta.xml
<CustomField>
    <fullName>TLO_License_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TLO Officer</label>
    <referenceTo>TLO_Officer__c</referenceTo>
    <relationshipName>TLO_Officer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Invention_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Invention_Disclosure</fullName>
    <active>true</active>
    <label>Invention</label>
</RecordType>

force-app/main/default/objects/Invention_Disclosure__c/Invention_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Invention Disclosure</label>
    <nameField>
        <label>Invention Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Invention Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Invention_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Invention Disclosures</relationshipLabel>
    <relationshipName>Invention_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Software_Code_Disclosure__c/Software_Code_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Software Code Disclosure</label>
    <nameField>
        <label>Software Code Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Code Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Software Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Software_Code_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Software Code Disclosures</relationshipLabel>
    <relationshipName>Software_Code_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Third_Party_Code__c/Third_Party_Code__c.object-meta.xml
<CustomObject>
    <label>Third Party Code</label>
    <nameField>
        <label>Third Party Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Code__c/fields/Software_Code_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Software_Code_Disclosure__c</fullName>
    <label>Software Code Disclosure</label>
    <referenceTo>Software_Code_Disclosure__c</referenceTo>
    <relationshipLabel>Third Party Code</relationshipLabel>
    <relationshipName>Third_Party_Code</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Third_Party_Content__c/Third_Party_Content__c.object-meta.xml
<CustomObject>
    <label>Third Party Content</label>
    <nameField>
        <label>Third Party Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Content__c/fields/Copyright_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Copyright_Disclosure__c</fullName>
    <label>Copyright Disclosure</label>
    <referenceTo>Copyright_Disclosure__c</referenceTo>
    <relationshipLabel>Third Party Contents</relationshipLabel>
    <relationshipName>Third_Party_Contents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TLO_Officer__c/TLO_Officer__c.object-meta.xml
<CustomObject>
    <label>TLO Officer</label>
    <nameField>
        <label>TLO Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TLO Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TLO_Officer__c/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <externalId>true</externalId>
    <label>MIT ID</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DisclosureSampleDataFactory.cls
//@isTest
public with sharing class DisclosureSampleDataFactory {
    public static void submitForDeptHeadEndorsement(Disclosure__c disclosure) {
        disclosure.Status__c = 'Pending Department Approval';
        update disclosure;
    }

    public static void archiveDisclosure(Disclosure__c disclosure) {
        disclosure.Status__c = 'Archived';
        update disclosure;
    }

    public static void sysAdminMoveBackToDraftDisclosure(
        Disclosure__c disclosure
    ) {
        disclosure.Status__c = 'Draft';
        update disclosure;
    }

    public static void deptHeadEndorsesDisclosure(
        Disclosure__c disclosure,
        String comment
    ) {
        System.debug('**** Dept Head Endorse ****');
        disclosure.Status__c = 'Inventor Submitted';
        if (comment != null && comment != '') {
            Department_Head__c deptHead = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
                disclosure.Id
            )[0];
            System.debug(deptHead);
            deptHead.Comment__c = comment;
            System.debug(deptHead);
            update deptHead;
        }
        update disclosure;
    }

    public static void deptHeadRejectsDisclosure(
        Disclosure__c disclosure,
        String rejectionReason
    ) {
        disclosure.Status__c = 'Rejected';
        disclosure.Rejection_Reason__c = rejectionReason;
        disclosure.Rejected_By__c = 'Department Head';
        update disclosure;
    }

    public static void tloRejectsDisclosure(
        Disclosure__c disclosure,
        String rejectionReason
    ) {
        disclosure.Status__c = 'Rejected';
        disclosure.Rejection_Reason__c = rejectionReason;
        disclosure.Rejected_By__c = 'TLO Admin';
        update disclosure;
    }

    public static void tloApprovesDisclosure(Disclosure__c disclosure) {
        if (disclosure.Status__c == 'Draft') {
            disclosure.Status__c = 'Pending Department Approval';
            update disclosure;

            disclosure.Status__c = 'Inventor Submitted';
            update disclosure;
        }

        disclosure.Status__c = 'Approved';
        update disclosure;
    }

    // TODO
    public static void submittingInventorToSignDisclosure(
        Disclosure__c disclosure
    ) {
        // disclosure.Status__c = 'Pending Department Approval';
        // update disclosure;
    }

    public static void deptHeadDelegateDisclosure(
        Disclosure__c disclosure,
        Department_Head__c secondDeptHead,
        String comment
    ) {
        List<Department_Head__c> deptHeads = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
            disclosure.Id
        );
        Department_Head__c currDeptHead = deptHeads[0];

        currDeptHead.Delegated_To__c = secondDeptHead.Id;
        currDeptHead.Comment__c = (comment == null ? '' : comment);
        update currDeptHead;
    }

    public static Disclosure__c createCopyrightDisclosureWithDeptHeadAsInventor(
        String title,
        Boolean includeFiles
    ) {
        Account submittedBy = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '12345678'
        ];
        Account piContact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777700'
        ];
        Account departmentHead = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777778'
        ];
        Account inventor1 = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '900047497'
        ];
        //Account sampleContact2 = [ SELECT Id FROM Account WHERE MitId__pc = '777777777' ];

        System.debug('Copyright: Sample');
        // main disclosure for copyright type
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            RecordTypeIdUtility.DISCLOSURE_COPYRIGHT,
            title,
            'Draft',
            submittedBy
        );
        Copyright_Disclosure__c copyrightDisclosure = SampleDataFactory.createCopyright(
            title,
            disclosure,
            piContact
        );

        // dept head
        SampleDataFactory.createOpenSource(
            'Open Source for Inventor Submitted Copyright',
            copyrightDisclosure,
            null
        );
        Department_Head__c firstDeptHead = SampleDataFactory.createDepartmentHead(
            disclosure,
            departmentHead
        );

        // other data for copyright
        SampleDataFactory.createDisclosureExternalFunding(
            disclosure,
            'OPP1201537',
            '6945744',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosure,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(disclosure);
        Third_Party_Content__c thirdPartyContent = SampleDataFactory.createThirdPartyContent(
            'Third Party Content',
            copyrightDisclosure
        );

        // inventors
        SampleDataFactory.createInventor(disclosure, true, submittedBy); // submitting for yourself (as inventor) Submitted Person MUST be one of the inventors
        SampleDataFactory.createInventor(disclosure, true, inventor1);

        if (includeFiles) {
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Copyright.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.createThirdPartyContentDocument(
                ContentVersionClassification.THIRD_PARTY_AGREEMENTS,
                'ThirdPartyContent1.pdf',
                'pdf',
                thirdPartyContent
            );
        }

        return disclosure;
    }

    public static Disclosure__c createDraftSoftwareDisclosureNoDeptHead(
        String title,
        Boolean includeFiles
    ) {
        Account submittingContact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '12345678'
        ];
        Account piContact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777700'
        ];
        Account nonMitInventor = [
            SELECT Id
            FROM Account
            WHERE PersonEmail = 'cr11@guest.test'
        ];
        Account mitInventor = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '900047497'
        ];

        System.debug('Software: Sample');
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            RecordTypeIdUtility.DISCLOSURE_SOFTWARE,
            title,
            'Draft',
            submittingContact
        );
        Software_Code_Disclosure__c softwareCodeDisclosure = SampleDataFactory.createSoftwareCode(
            'Sample Inventor Submitted Software Code',
            disclosure
        );

        SampleDataFactory.createDisclosureExternalFunding(
            disclosure,
            'OPP1201537',
            '6945744',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosure,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(disclosure);
        Third_Party_Code__c thirdPartyCode = SampleDataFactory.createThirdPartyCode(
            'Third Party Code',
            softwareCodeDisclosure
        );

        SampleDataFactory.createInventor(disclosure, true, submittingContact);
        SampleDataFactory.createInventor(disclosure, true, mitInventor);
        SampleDataFactory.createInventor(disclosure, false, nonMitInventor);

        if (includeFiles) {
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Software.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.updateTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Software.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.SOFTWARE_CODE,
                'Open_Source_Software.pdf',
                'pdf',
                disclosure
            );
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.SOFTWARE_CODE,
                'Open_Source_Software2.txt',
                'txt',
                disclosure
            );
            SampleDataFactory.createThirdPartyCodeDocument(
                ContentVersionClassification.THIRD_PARTY_CODE,
                'ThirdPartyCode1.pdf',
                'pdf',
                thirdPartyCode
            );
        }

        update disclosure;

        return disclosure;
    }

    public static Disclosure__c createApprovedSOBInventionDisclosure(
        String title
    ) {
        Id recordTypeIdInvention = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Invention_Disclosure')
            .getRecordTypeId();

        Account submittingContact1 = [
            SELECT Id, Name
            FROM Account
            WHERE MitId__pc = '700000001'
        ];
        Account inventorContact2 = [
            SELECT Id, Name
            FROM Account
            WHERE MitId__pc = '900047497'
        ];
        Account piContact = [
            SELECT Id, Name
            FROM Account
            WHERE MitId__pc = '777777700'
        ];
        TLO_Officer__c tloOfficer = [
            SELECT Id, Name
            FROM TLO_Officer__c
            WHERE MitId__c = '777773000'
        ];

        Disclosure__c disclosureSOB = SampleDataFactory.createDisclosureSOB(
            recordTypeIdInvention,
            title,
            'Draft',
            submittingContact1
        );
        SampleDataFactory.createDisclosureExternalFunding(
            disclosureSOB,
            '12345',
            '6789',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosureSOB,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(disclosureSOB);
        Invention_Disclosure__c inventionApprovedSample = SampleDataFactory.createInvention(
            'Invention Disclosure Draft Sample',
            disclosureSOB
        );
        SampleDataFactory.createThesis(
            'Thesis Sample for Invention Inventor Submitted',
            inventionApprovedSample
        );
        SampleDataFactory.createThirdPartyMaterial(
            'create third party material comments',
            inventionApprovedSample
        );
        SampleDataFactory.createInventor(disclosureSOB, true, inventorContact2);
        disclosureSOB.Status__c = 'Inventor Submitted';
        update disclosureSOB;
        disclosureSOB.Status__c = 'Approved';
        disclosureSOB.Case_Number__c = '12345J';
        disclosureSOB.TLO_License_Officer__c = tloOfficer.Id;
        update disclosureSOB;
        return disclosureSOB;
    }

    public static Disclosure__c createDraftSoftwareDisclosureFullyPopulated(
        String title,
        Boolean includeFiles
    ) {
        Account submittingContact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '12345678'
        ];
        Account piContact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777700'
        ];
        Account departmentHead = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777778'
        ];
        Account nonMitInventor = [
            SELECT Id
            FROM Account
            WHERE PersonEmail = 'cr11@guest.test'
        ];
        Account mitInventor = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '900047497'
        ];

        System.debug('Software: Sample');
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            RecordTypeIdUtility.DISCLOSURE_SOFTWARE,
            title,
            'Draft',
            submittingContact
        );
        Software_Code_Disclosure__c softwareCodeDisclosure = SampleDataFactory.createSoftwareCode(
            'Sample Inventor Submitted Software Code',
            disclosure
        );

        SampleDataFactory.createDepartmentHead(disclosure, departmentHead);
        SampleDataFactory.createDisclosureExternalFunding(
            disclosure,
            'OPP1201537',
            '6945744',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosure,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(disclosure);
        SampleDataFactory.createOpenSource(
            'Open Source for Inventor Submitted Software Code',
            null,
            softwareCodeDisclosure
        );
        Third_Party_Code__c thirdPartyCode = SampleDataFactory.createThirdPartyCode(
            'Third Party Code',
            softwareCodeDisclosure
        );

        SampleDataFactory.createInventor(disclosure, true, submittingContact);
        SampleDataFactory.createInventor(disclosure, true, mitInventor);
        SampleDataFactory.createInventor(disclosure, false, nonMitInventor);

        if (includeFiles) {
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Software.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.updateTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Software.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.SOFTWARE_CODE,
                'Open_Source_Software.pdf',
                'pdf',
                disclosure
            );
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.SOFTWARE_CODE,
                'Open_Source_Software2.txt',
                'txt',
                disclosure
            );
            SampleDataFactory.createThirdPartyCodeDocument(
                ContentVersionClassification.THIRD_PARTY_CODE,
                'ThirdPartyCode1.pdf',
                'pdf',
                thirdPartyCode
            );
        }

        update disclosure;

        return disclosure;
    }

    public static Disclosure__c createDraftSoftwareDisclosurePrimaryInventorOnly(
        String title,
        Boolean includeFiles
    ) {
        Account submittingContact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '12345678'
        ];
        Account piContact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777700'
        ];
        Account departmentHead = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777778'
        ];

        System.debug('Software: Sample');
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            RecordTypeIdUtility.DISCLOSURE_SOFTWARE,
            title,
            'Draft',
            submittingContact
        );
        Software_Code_Disclosure__c softwareCodeDisclosure = SampleDataFactory.createSoftwareCode(
            'Sample Inventor Submitted Software Code',
            disclosure
        );

        SampleDataFactory.createDepartmentHead(disclosure, departmentHead);
        SampleDataFactory.createDisclosureExternalFunding(
            disclosure,
            'OPP1201537',
            '6945744',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosure,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(disclosure);
        SampleDataFactory.createOpenSource(
            'Open Source for Inventor Submitted Software Code',
            null,
            softwareCodeDisclosure
        );
        Third_Party_Code__c thirdPartyCode = SampleDataFactory.createThirdPartyCode(
            'Third Party Code',
            softwareCodeDisclosure
        );

        SampleDataFactory.createInventor(disclosure, true, submittingContact);

        if (includeFiles) {
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Software.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.updateTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Software.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.SOFTWARE_CODE,
                'Open_Source_Software.pdf',
                'pdf',
                disclosure
            );
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.SOFTWARE_CODE,
                'Open_Source_Software2.txt',
                'txt',
                disclosure
            );
            SampleDataFactory.createThirdPartyCodeDocument(
                ContentVersionClassification.THIRD_PARTY_CODE,
                'ThirdPartyCode1.pdf',
                'pdf',
                thirdPartyCode
            );
        }

        update disclosure;

        return disclosure;
    }
}