force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Contact_Action__c/Contact_Action__c.object-meta.xml
<CustomObject>
    <label>Contact Action</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Contact Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Actions</relationshipLabel>
    <relationshipName>Contact_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Copyright_Disclosure__c/Copyright_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Copyright Disclosure</label>
    <nameField>
        <label>Copyright Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copyright Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Copyright Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Copyright_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Copyright Disclosures</relationshipLabel>
    <relationshipName>Copyright_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>TLO Case Number</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/SubmittedOnBehalf__c.field-meta.xml
<CustomField>
    <fullName>SubmittedOnBehalf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted on behalf of someone else</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright</label>
</RecordType>

force-app/main/default/objects/Disclosure_Action__c/Disclosure_Action__c.object-meta.xml
<CustomObject>
    <label>Disclosure Action</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Action__c/fields/Contact_Action__c.field-meta.xml
<CustomField>
    <fullName>Contact_Action__c</fullName>
    <label>Contact Action</label>
    <referenceTo>Contact_Action__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_1__c.field-meta.xml
<CustomField>
    <fullName>Reminder_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_2__c.field-meta.xml
<CustomField>
    <fullName>Reminder_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_3__c.field-meta.xml
<CustomField>
    <fullName>Reminder_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/recordTypes/Endorse_or_Delegate_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Endorse_or_Delegate_Disclosure</fullName>
    <active>true</active>
    <label>Endorse or Delegate Disclosure</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Disclosure__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Variables__c.field-meta.xml
<CustomField>
    <fullName>Variables__c</fullName>
    <label>Variables</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/Open_Source__c.object-meta.xml
<CustomObject>
    <label>Open Source</label>
    <nameField>
        <label>Open Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Source__c/fields/Copyright_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Copyright_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copyright Disclosure</label>
    <referenceTo>Copyright_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright_Disclosure</label>
</RecordType>

force-app/main/default/classes/DisclosureDeptHeadEndorseReminderTest.cls
@isTest
public with sharing class DisclosureDeptHeadEndorseReminderTest {
    @TestSetup
    static void makeData() {
        TestSetup.defaultConfiguration();
    }

    @isTest
    public static void testReminderNotification() {
        // Constants
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Copyright_Disclosure')
            .getRecordTypeId();
        DateTime theDate = DateTime.now().addDays(-30);
        Util.now = DateTime.now().addDays(-30 + 7);

        String disclosureTitle = 'Test DisclosureDeptHeadEndorseReminder';

        // Contacts
        Account inventorContact = SampleDataFactory.createContact(
            'Inventor',
            true,
            '123456781'
        );
        Account piContact = SampleDataFactory.createContact(
            'PI',
            true,
            '123456784'
        );
        Account firstDeptHeadContact = SampleDataFactory.createContact(
            'DeptHead1',
            true,
            '123456782'
        );

        Account submittingContact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '11345678'
        );

        // Disclosure
        Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
            recordTypeIdSoftwareCode,
            disclosureTitle,
            'Draft',
            submittingContact
        );
        Test.setCreatedDate(disclosure.Id, theDate);

        Copyright_Disclosure__c copyrightDisclosure = SampleDataFactory.createCopyright(
            disclosureTitle,
            disclosure,
            piContact
        );

        Open_Source__c openSource = SampleDataFactory.createOpenSource(
            disclosureTitle,
            copyrightDisclosure,
            null
        );

        Department_Head__c firstDeptHead = SampleDataFactory.createDepartmentHead(
            disclosure,
            firstDeptHeadContact
        );
        DisclosureInventor__c inventor = SampleDataFactory.createInventor(
            disclosure,
            true,
            inventorContact
        );

        disclosure.Status__c = 'Pending Department Approval';
        update disclosure;

        Id recordTypeId = Schema.SObjectType.Disclosure_Action__c.getRecordTypeInfosByDeveloperName()
            .get('Endorse_or_Delegate_Disclosure')
            .getRecordTypeId();
        Disclosure_Action__c disclosureAction = [
            SELECT
                Id,
                CreatedDate,
                Contact_Action__r.Name,
                Contact_Action__r.Status__c,
                Contact_Action__c,
                RecordType.DeveloperName,
                RecordType.name,
                Disclosure__c,
                Disclosure__r.Name,
                Disclosure__r.Name__c,
                Disclosure__r.RecordType.Name,
                Contact_Action__r.Contact__r.PersonEmail,
                Contact_Action__r.Contact__r.Name,
                Disclosure__r.Submitting_Contact__c,
                Disclosure__r.Submitting_Contact__r.Id,
                Disclosure__r.Submitting_Contact__r.Name,
                Disclosure__r.Submitting_Contact__r.PersonEmail,
                Disclosure__r.Submitting_Contact__r.AltEmail__pc,
                Reminder_1__c,
                Reminder_2__c,
                Reminder_3__c
            FROM Disclosure_Action__c
            WHERE
                Disclosure__c = :disclosure.Id
                AND RecordTypeId = :recordTypeId
            LIMIT 1
        ];
        Test.setCreatedDate(disclosureAction.Id, theDate);

        Test.startTest();
        Database.executeBatch(new DisclosureDeptHeadEndorseReminder(), 1);
        Test.stopTest();

        List<Notification__c> notification = [
            SELECT Id, Template__c, Variables__c
            FROM Notification__c
            WHERE
                Template__c = :NotificationBuilder.TEMPLATE_DEPT_HEAD_ENDORSEMENT_REMINDER
        ];
        Map<String, Object> jsonVal = (Map<String, Object>) JSON.deserializeUntyped(
            notification[0].Variables__c
        );
        System.debug('\n\nnotification:- \n\n' + notification + '\n\n');
        System.debug(
            '\n\nnotification[0].Variables__c):- \n\n' +
            notification[0].Variables__c +
            '\n\n'
        );

        System.assertEquals(
            '7',
            String.valueOf(jsonVal.get('outstanding')),
            'First reminder is 7 days outstanding'
        );
        System.assertEquals(
            disclosureAction.Disclosure__r.Name,
            String.valueOf(jsonVal.get('disclosure_name')),
            'disclosure_name'
        );
        System.assertEquals(
            ContactNameUtil.toFullName(
                firstDeptHeadContact.FirstName,
                firstDeptHeadContact.MiddleName,
                firstDeptHeadContact.LastName,
                true
            ),
            String.valueOf(jsonVal.get('dlc_name')),
            'dlc_name is not correct'
        );
        System.assertEquals(
            1,
            notification.size(),
            'We should have at least one notification'
        );

        System.assertEquals(
            disclosureAction.Disclosure__r.RecordType.Name,
            String.valueOf(jsonVal.get('disclosure_type')),
            'disclosure_type not set correctly'
        );
        System.assertEquals(
            disclosureAction.Disclosure__r.Submitting_Contact__r.Name,
            String.valueOf(jsonVal.get('submitter_name')),
            'submitter_name not set correctly'
        );
        System.assertEquals(
            disclosureAction.Disclosure__r.Name,
            String.valueOf(jsonVal.get('disclosure_name')),
            'disclosure_name not set correctly'
        );
        System.assertEquals(
            disclosureAction.Disclosure__r.Name__c,
            String.valueOf(jsonVal.get('disclosure_title')),
            'disclosure_title not set correctly'
        );

        Disclosure__c disclosureToTest = getDisclosureToTest(disclosureTitle);
        List<Disclosure_Action__c> disclosureActions = [
            SELECT
                Id,
                CreatedDate,
                Contact_Action__r.Name,
                Contact_Action__r.Status__c,
                Contact_Action__c,
                RecordType.DeveloperName,
                RecordType.name,
                Disclosure__c,
                Disclosure__r.Name,
                Disclosure__r.Name__c,
                Disclosure__r.RecordType.Name,
                Contact_Action__r.Contact__r.PersonEmail,
                Contact_Action__r.Contact__r.Name,
                Reminder_1__c,
                Reminder_2__c,
                Reminder_3__c
            FROM Disclosure_Action__c
            WHERE
                Disclosure__c = :disclosureToTest.Id
                AND RecordTypeId = :recordTypeId
        ];
        System.debug(
            '\n\n disclosureActions:- \n\n' +
            disclosureActions +
            '\n\n'
        );
    }

    private static Disclosure__c getDisclosureToTest(String title) {
        Disclosure__c disclosureToTest = [
            SELECT
                Id,
                Status__c,
                Name__c,
                Case_Number__c,
                SubmittedOnBehalf__c,
                Submitting_Contact__c,
                Submitting_Contact__r.Id,
                Submitting_Contact__r.Name,
                Submitting_Contact__r.PersonEmail,
                Submitting_Contact__r.AltEmail__pc
            FROM Disclosure__c
            WHERE Name__c = :title
            LIMIT 1
        ];
        return disclosureToTest;
    }
}