force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Copyright_Disclosure__c/Copyright_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Copyright Disclosure</label>
    <nameField>
        <label>Copyright Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copyright Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Copyright Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Copyright_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Copyright Disclosures</relationshipLabel>
    <relationshipName>Copyright_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Delegated_To__c.field-meta.xml
<CustomField>
    <fullName>Delegated_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegated To</label>
    <referenceTo>Department_Head__c</referenceTo>
    <relationshipLabel>Delegated By</relationshipLabel>
    <relationshipName>Delegated_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright</label>
</RecordType>

force-app/main/default/objects/Third_Party_Content__c/Third_Party_Content__c.object-meta.xml
<CustomObject>
    <label>Third Party Content</label>
    <nameField>
        <label>Third Party Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Content__c/fields/Copyright_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Copyright_Disclosure__c</fullName>
    <label>Copyright Disclosure</label>
    <referenceTo>Copyright_Disclosure__c</referenceTo>
    <relationshipLabel>Third Party Contents</relationshipLabel>
    <relationshipName>Third_Party_Contents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CopyrightDisclosuresSampleFactory.cls
public class CopyrightDisclosuresSampleFactory {
    public static Disclosure__c createDisclosure(
        String title,
        Boolean includeFiles
    ) {
        // Record type id's
        Id recordTypeIdCopyright = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Copyright_Disclosure')
            .getRecordTypeId();

        /**
         * Contact creation to be used throughout
         */
        Account existingContact1 = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '900047497'
        ];

        Account sampleContact1 = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '12345678'
        ];

        Account sampleContact2 = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777777'
        ];

        Account departmentHeadContact2 = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777778'
        ];

        Account piContact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777700'
        ];
        /**
         * Sample Data
         */

        /**
         * Copyright sample data
         */
        System.debug('Copyright: Sample');
        Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
            recordTypeIdCopyright,
            title,
            'Draft',
            sampleContact1
        );

        Department_Head__c firstDeptHead = SampleDataFactory.createDepartmentHead(
            disclosure,
            departmentHeadContact2
        );
        Department_Head__c secondDeptHead = SampleDataFactory.createDepartmentHead(
            disclosure,
            sampleContact1
        );
        firstDeptHead.Delegated_To__c = secondDeptHead.Id;
        update firstDeptHead;

        SampleDataFactory.createDisclosureExternalFunding(
            disclosure,
            'OPP1201537',
            '6945744',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosure,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(disclosure);
        Copyright_Disclosure__c copyrightDisclosure = SampleDataFactory.createCopyright(
            'Sample Inventor Submitted Copyright',
            disclosure,
            piContact
        );
        SampleDataFactory.createOpenSource(
            'Open Source for Inventor Submitted Copyright',
            copyrightDisclosure,
            null
        );
        Third_Party_Content__c thirdPartyContent = SampleDataFactory.createThirdPartyContent(
            'Third Party Content',
            copyrightDisclosure
        );
        Third_Party_Content__c thirdPartyContent2 = SampleDataFactory.createThirdPartyContent(
            'Third Party Content2',
            copyrightDisclosure
        );
        Third_Party_Content__c thirdPartyContent3 = SampleDataFactory.createThirdPartyContent(
            'Third Party Content3',
            copyrightDisclosure
        );
        SampleDataFactory.createInventor(disclosure, true, existingContact1);
        if (includeFiles) {
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Copyright.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.createThirdPartyContentDocument(
                ContentVersionClassification.THIRD_PARTY_AGREEMENTS,
                'ThirdPartyContent1.pdf',
                'pdf',
                thirdPartyContent
            );
            SampleDataFactory.createThirdPartyContentDocument(
                ContentVersionClassification.THIRD_PARTY_AGREEMENTS,
                'ThirdPartyContent2.pdf',
                'pdf',
                thirdPartyContent2
            );
            SampleDataFactory.createThirdPartyContentDocument(
                ContentVersionClassification.THIRD_PARTY_AGREEMENTS,
                'ThirdPartyContent3.pdf',
                'pdf',
                thirdPartyContent3
            );
        }
        // Department head approval, Can not directly go to Inventor Submitted
        disclosure.Status__c = 'Pending Department Approval';
        update disclosure;

        return disclosure;
    }
}