force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Has_Processed__c.field-meta.xml
<CustomField>
    <fullName>Has_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>TLO Case Number</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/SubmittedOnBehalf__c.field-meta.xml
<CustomField>
    <fullName>SubmittedOnBehalf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted on behalf of someone else</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/AdditionalComments__c.field-meta.xml
<CustomField>
    <fullName>AdditionalComments__c</fullName>
    <label>11. Additional Comments</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/AdditionalSponsorsOrFunding__c.field-meta.xml
<CustomField>
    <fullName>AdditionalSponsorsOrFunding__c</fullName>
    <label>8. Addtl.  SRAs or funding sources?</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/AffiliatedWithOrgsDlcs__c.field-meta.xml
<CustomField>
    <fullName>AffiliatedWithOrgsDlcs__c</fullName>
    <label>7. Affiliations?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wyss</fullName>
                <label>Wyss Institute</label>
            </value>
            <value>
                <fullName>Whitehead</fullName>
            </value>
            <value>
                <fullName>Broad</fullName>
                <label>Broad Institute</label>
            </value>
            <value>
                <fullName>SMART</fullName>
                <label>Singapore MIT Alliance for Research and Technology</label>
            </value>
            <value>
                <fullName>IMES</fullName>
                <label>Institute for Medical Engineering and Sciences</label>
            </value>
            <value>
                <fullName>Ragon</fullName>
                <label>Ragon Institute</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Disclosure__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Collaboration__c.field-meta.xml
<CustomField>
    <fullName>Collaboration__c</fullName>
    <label>4. Research part of a collaboration?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/CollaborationDetails__c.field-meta.xml
<CustomField>
    <fullName>CollaborationDetails__c</fullName>
    <label>4a. Collab. details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/ConsultantOrContract__c.field-meta.xml
<CustomField>
    <fullName>ConsultantOrContract__c</fullName>
    <label>5. Research done by consultant/CRO?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/ConsultantOrContractDetails__c.field-meta.xml
<CustomField>
    <fullName>ConsultantOrContractDetails__c</fullName>
    <label>5a. Consultant/CRO details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/FundingThroughDlc__c.field-meta.xml
<CustomField>
    <fullName>FundingThroughDlc__c</fullName>
    <label>6. Funding through CBA, ML, LL?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BitsAndAtoms</fullName>
                <label>Center for Bits and Atoms (CBA)</label>
            </value>
            <value>
                <fullName>MediaLab</fullName>
                <label>Media Lab</label>
            </value>
            <value>
                <fullName>LincolnLab</fullName>
                <label>Lincoln Lab</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/MitAtTimeOfInvention__c.field-meta.xml
<CustomField>
    <fullName>MitAtTimeOfInvention__c</fullName>
    <defaultValue>false</defaultValue>
    <label>At MIT at time of Invention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PartOfClass__c.field-meta.xml
<CustomField>
    <fullName>PartOfClass__c</fullName>
    <label>9. Conceived in MIT class?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PartOfClassDetails__c.field-meta.xml
<CustomField>
    <fullName>PartOfClassDetails__c</fullName>
    <label>9a. MIT Class details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PrimaryInventor__c.field-meta.xml
<CustomField>
    <fullName>PrimaryInventor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/SalaryWages__c.field-meta.xml
<CustomField>
    <fullName>SalaryWages__c</fullName>
    <label>1. Who pays your salary/wages?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>Non-MIT</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/SalaryWagesDetails__c.field-meta.xml
<CustomField>
    <fullName>SalaryWagesDetails__c</fullName>
    <label>1a. Salary/Wages details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Comment__c.field-meta.xml
<CustomField>
    <fullName>Signed_Comment__c</fullName>
    <description>Signed Comment -&gt; only used when Inventor Opt&apos;s out of Disclosure</description>
    <label>Signed Comment</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Disclosure_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Disclosure_Date__c</fullName>
    <label>Signed Disclosure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/ThirdPartyMaterials__c.field-meta.xml
<CustomField>
    <fullName>ThirdPartyMaterials__c</fullName>
    <label>10. Other  materials or datasets?</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/WorkDoneAtMIT__c.field-meta.xml
<CustomField>
    <fullName>WorkDoneAtMIT__c</fullName>
    <label>2. Relevant work done @ MIT?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/WorkDoneOutsideMIT__c.field-meta.xml
<CustomField>
    <fullName>WorkDoneOutsideMIT__c</fullName>
    <label>3. Relevant work @ other organization?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/WorkDoneOutsideMITDetails__c.field-meta.xml
<CustomField>
    <fullName>WorkDoneOutsideMITDetails__c</fullName>
    <label>3a. Other Org. details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DisclosureInventorSignedToForrester.cls
public class DisclosureInventorSignedToForrester implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    public class ForresterCalloutException extends Exception {}
    public Database.QueryLocator start(Database.BatchableContext bc){
        Integer retryCount = Integer.ValueOf(retryCount());
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    Has_Processed__c,
                    Retry_Count__c,
                    Record_Id__c,
                    sObject_Name__c,
                    Job_Name__c
                FROM Async_Request__c
                WHERE
                    Has_Processed__c = FALSE
                    AND Retry_Count__c < :retryCount
                    AND sObject_Name__c = 'DisclosureInventor__c'
                    AND (Job_Name__c = 'InventorSignedDisclosureToForresterJob'
                    OR Job_Name__c = 'InventorAddedToApprovedDisclosureToForresterJob')
                ORDER BY Job_Name__c
            ]
        );
        // Order by Job Name to add new inventors first.
    }
    public static DisclosureInventor__c getDisclosureInventorById(
        String RecordId
    ) {
        DisclosureInventor__c disinv = [
            SELECT
                Id,
                PrimaryInventor__c,
                Signed_Status__c,
                Signed_Disclosure_Date__c,
                Signed_Comment__c,
                MitAtTimeOfInvention__c,
                Contact__c,
                Disclosure__r.SubmittedOnBehalf__c,
                Disclosure__r.Case_Number__c,
                //Extra Questions
                SalaryWages__c,
                SalaryWagesDetails__c,
                AdditionalComments__c,
                AdditionalSponsorsOrFunding__c,
                CollaborationDetails__c,
                ConsultantOrContractDetails__c,
                PartOfClassDetails__c,
                WorkDoneOutsideMIT__c,
                WorkDoneOutsideMITDetails__c,
                toLabel(FundingThroughDlc__c),
                Contact__r.FirstName,
                Contact__r.MiddleName,
                Contact__r.LastName,
                toLabel(AffiliatedWithOrgsDlcs__c),
                ConsultantOrContract__c,
                WorkDoneAtMIT__c,
                Collaboration__c,
                PartOfClass__c,
                Contact__r.Name,
                ThirdPartyMaterials__c
            FROM DisclosureInventor__c
            WHERE Id = :RecordId
        ];
        return disinv;
    }
    public void execute(
        Database.BatchableContext bc,
        List<Async_Request__c> scope
    ) {
        try {
            Async_Request__c async = scope[0];
            if (scope != null && async != null && async.Record_Id__c != null) {
                Map<String, String> headers = new Map<String, String>();

                DisclosureInventor__c disinv = getDisclosureInventorById(
                    async.Record_Id__c
                );
                Account tloContact = DisclosureRecordFetch.getContactById(
                    disinv.Contact__c
                );

                headers.put('Content-Type', 'application/json');
                String apiName = 'forresterApi';
                String endpoints =
                    '/disclosures/' +
                    disinv.Disclosure__r.Case_Number__c +
                    '';
                String response = null;
                Boolean includeExtraQuestions = true;
                if (
                    async.Job_Name__c ==
                    'InventorAddedToApprovedDisclosureToForresterJob'
                ) {
                    includeExtraQuestions = false; // Inventor need to answer it first
                    response = AwsApiCall.restPost(
                        apiName,
                        endpoints,
                        headers,
                        prepareJSONRequestBody(
                            disinv,
                            tloContact,
                            includeExtraQuestions
                        )
                    );
                } else {
                    response = AwsApiCall.restPatch(
                        apiName,
                        endpoints,
                        headers,
                        prepareJSONRequestBody(
                            disinv,
                            tloContact,
                            includeExtraQuestions
                        )
                    );
                }
                System.debug('Signed Disclosure Batch response ' + response);
                Map<String, Object> respObj = (Map<String, Object>) JSON.deserializeUntyped(
                    response
                );
                if (String.valueOf(respObj.get('status')) == 'SUCCESS') {
                    async.Has_Processed__c = true;
                } else {
                    Integer count = Integer.valueOf(async.Retry_Count__c);
                    async.Retry_Count__c = count + 1;
                    async.Has_Processed__c = false;
                }
                update async;

                if(async.Has_Processed__c == false) {
                    // log exception only after the retry count is updated
                    String message = respObj.get('message') != null ? String.valueOf(respObj.get('message')) : '';
                    throw new ForresterCalloutException('Unable to update Forrester: retry count ['+ async.Retry_Count__c +'] ' + message);
                }

            }
        } catch (exception ex) {
            HandleLogException.logException(ex);
        }
    }

    public void finish(Database.BatchableContext bc) {
    }

    public static String prepareJSONRequestBody(
        DisclosureInventor__c disinv,
        Account tloContact,
        Boolean includeExtraQuestions
    ) {
        ForresterDto.InventorDto inventor = new ForresterDto.InventorDto();
        inventor.mitId = tloContact.MitId__pc;
        inventor.inventorName = ContactNameUtil.toFullName(
            tloContact.FirstName,
            tloContact.MiddleName,
            tloContact.LastName,
            true
        );
        inventor.legalGivenName = tloContact.FirstName;
        inventor.legalMiddleName = tloContact.MiddleName;
        inventor.legalLastName = tloContact.Lastname;
        inventor.email = tloContact.PersonEmail;
        inventor.oldEmail = null; //old email only used to change email, It should only be used once
        inventor.hhmi = tloContact.HHMI_Current__pc;
        inventor.signedDisclosureComment = disinv.Signed_Comment__c;
        inventor.signedDisclosureFlag = Helpers.signedStatusBoolean(
            disinv.Signed_Status__c
        );
        inventor.govEmployeeStatusFlag = tloContact.GovernmentEmployeeStatus__pc;
        inventor.atMitAtTheTimeOfInvention = disinv.MitAtTimeOfInvention__c;
        inventor.alternatePhone = tloContact.PersonMobilePhone;
        inventor.alternateEmail = tloContact.AltEmail__pc;
        inventor.alternateAddress = tloContact.PersonMailingStreet;
        inventor.alternateAddressCity = tloContact.PersonMailingCity;
        inventor.alternateAddressState = tloContact.PersonMailingState;
        inventor.alternateAddressZipcode = tloContact.PersonMailingPostalCode;
        inventor.alternateAddressCountry = tloContact.PersonMailingCountry;
        inventor.countryCitizenship = tloContact.CountryOfCitizenship__pc;
        inventor.submitOnBehalfOf = false; // False by default SOB does not automatically get added as inventor and cannot add themselves as an inventor either
        inventor.primaryContact = disinv.PrimaryInventor__c;
        inventor.institution = tloContact.Institution__pc;
        inventor.institutionCode = tloContact.InstitutionCode__pc;
        inventor.birthday = Helpers.birthDayFromValue(
            tloContact.PersonBirthdate
        );
        inventor.position = tloContact.PersonTitle;
        inventor.department = tloContact.PersonDepartment;
        if (includeExtraQuestions) {
            ForresterDto.AdditionalInformationDto extraInfo = mapAdditionalInformation(
                disinv
            );
            if (JSON.serialize(extraInfo, true) != '{}') {
                inventor.additionalInformation = extraInfo;
            }
        }

        List<ForresterDto.InventorDto> inventors = new List<ForresterDto.InventorDto>();
        inventors.add(inventor);
        PatchDisclosureDto jsonBody = new PatchDisclosureDto();
        jsonBody.user = Label.MIT_ForresterUser;
        jsonBody.inventors = inventors;

        Boolean suppressApexObjectNulls = true;
        return JSON.serialize(jsonBody, suppressApexObjectNulls);
    }

    private static ForresterDto.AdditionalInformationDto mapAdditionalInformation(
        DisclosureInventor__c disinv
    ) {
        ForresterDto.AdditionalInformationDto additionalInformation = new ForresterDto.AdditionalInformationDto();
        additionalInformation.salaryOrWages = disinv.SalaryWages__c;
        additionalInformation.salaryOrWagesDetail = disinv.SalaryWagesDetails__c;
        additionalInformation.workAtMit = disinv.WorkDoneAtMIT__c;
        additionalInformation.workAtOtherInstitution = disinv.WorkDoneOutsideMIT__c;
        additionalInformation.workAtOtherInstitutionMoreDetail = disinv.WorkDoneOutsideMITDetails__c;
        additionalInformation.wasResearchAsPartOfCollaboration = disinv.Collaboration__c;
        additionalInformation.wasResearchAsPartOfCollaborationMoreDetail = disinv.CollaborationDetails__c;
        additionalInformation.wasResearchAsPerformedByConsultant = disinv.ConsultantOrContract__c;
        additionalInformation.wasResearchAsPerformedByConsultantMoreDetail = disinv.ConsultantOrContractDetails__c;
        if (disinv.FundingThroughDlc__c != null) {
            additionalInformation.fundingDlc = new List<String>{
                disinv.FundingThroughDlc__c
            };
        }
        if (disinv.AffiliatedWithOrgsDlcs__c != null) {
            additionalInformation.affiliationOptions = new List<String>{
                disinv.AffiliatedWithOrgsDlcs__c
            };
        }
        additionalInformation.additionalSponsoredResearchOrFundingSources = disinv.AdditionalSponsorsOrFunding__c;
        additionalInformation.conceivedDuringCourseWork = disinv.PartOfClass__c;
        additionalInformation.conceivedDuringCourseWorkMoreDetail = disinv.PartOfClassDetails__c;
        additionalInformation.thirdPartyMaterialsOrDatasets = disinv.ThirdPartyMaterials__c;
        additionalInformation.additionalComments = disinv.AdditionalComments__c;
        return additionalInformation;
    }

    private static String retryCount() {
        return ConfigurationBuilder.getConfigurationToString(
            'batchJobMaxNumberOfRetry'
        );
    }
}