force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Contact_Action__c/Contact_Action__c.object-meta.xml
<CustomObject>
    <label>Contact Action</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Contact Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Actions</relationshipLabel>
    <relationshipName>Contact_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Delegated_To__c.field-meta.xml
<CustomField>
    <fullName>Delegated_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegated To</label>
    <referenceTo>Department_Head__c</referenceTo>
    <relationshipLabel>Delegated By</relationshipLabel>
    <relationshipName>Delegated_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/Disclosure_Action__c.object-meta.xml
<CustomObject>
    <label>Disclosure Action</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Action__c/fields/Contact_Action__c.field-meta.xml
<CustomField>
    <fullName>Contact_Action__c</fullName>
    <label>Contact Action</label>
    <referenceTo>Contact_Action__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/recordTypes/Endorse_or_Delegate_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Endorse_or_Delegate_Disclosure</fullName>
    <active>true</active>
    <label>Endorse or Delegate Disclosure</label>
</RecordType>

force-app/main/default/objects/Disclosure_Action__c/recordTypes/Sign_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Sign_Disclosure</fullName>
    <active>true</active>
    <label>Sign Disclosure</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactActionHandler.cls
/**
 * Handler class for Contact Action operations
 */
public with sharing class ContactActionHandler {
    // Record Type Ids
    public static Id recordTypeIdDelegate = Schema.SObjectType.Disclosure_Action__c.getRecordTypeInfosByDeveloperName()
        .get('Endorse_or_Delegate_Disclosure')
        .getRecordTypeId();
    public static Id recordTypeIdSignDisclosure = Schema.SObjectType.Disclosure_Action__c.getRecordTypeInfosByDeveloperName()
        .get('Sign_Disclosure')
        .getRecordTypeId();

    // Status types
    public enum Status {
        Pending,
        Completed,
        Canceled
    }

    public static void initDisclosureContactAction(
        List<DisclosureInventor__c> inventors,
        Id disclosureActionRecordTypeId
    ) {
        initDisclosureContactAction(
            DisclosureRecordFetch.getContactDisclosureMapByInventors(inventors),
            disclosureActionRecordTypeId
        );
    }

    /**
     * Initialize Disclosure_Action__c objects using a list of Account objects and a Record Type
     * @param disclosureContactMap A list of Disclosure__c Ids and associated Account objects
     * @param disclosureActionRecordTypeId The Id of the Disclosure_Action__c Record Type to be used
     */
    public static void initDisclosureContactAction(
        Map<Account, Id> contactDisclosureMap,
        Id disclosureActionRecordTypeId
    ) {
        System.debug(contactDisclosureMap.toString());
        List<Contact_Action__c> contactActions = new List<Contact_Action__c>();
        List<Disclosure_Action__c> disclosureActions = new List<Disclosure_Action__c>();
        Map<Account, Contact_Action__c> contactActionMap = new Map<Account, Contact_Action__c>();

        // Create the Contact Actions
        System.debug('Creating Contact Actions');

        for (Account key : contactDisclosureMap.keySet()) {
            Contact_Action__c contactAction = new Contact_Action__c(
                Contact__c = key.Id,
                Status__c = 'Pending'
            );
            contactActions.add(contactAction);
            contactActionMap.put(key, contactAction);
        }

        if (!contactActions.isEmpty()) {
            insert contactActions;

            // Create the corresponding Disclosure Actions
            System.debug('Creating Disclosure Actions');

            for (Account contact : contactActionMap.keySet()) {
                Contact_Action__c contactAction = contactActionMap.get(contact);
                Id disclosure = contactDisclosureMap.get(contact);

                System.debug('Contact Action');
                System.debug(contactAction);

                Disclosure_Action__c disclosureAction = new Disclosure_Action__c(
                    Contact_Action__c = contactAction.Id,
                    RecordTypeId = disclosureActionRecordTypeId,
                    Disclosure__c = disclosure
                );
                disclosureActions.add(disclosureAction);

                System.debug('Disclosure Action');
                System.debug(disclosureAction);
            }

            if (!disclosureActions.isEmpty()) {
                insert disclosureActions;
            }
        }
    }

    /**
     * Mark pending Contact Actions as complete if the Department Head has delegated
     * @param deptHeads List of Department_Head__c objects that need to be cleansed
     */
    public static void completeDelegatedPendingContactActions(
        List<Department_Head__c> deptHeads
    ) {
        List<Contact_Action__c> contactActions = new List<Contact_Action__c>();

        for (Department_Head__c deptHead : deptHeads) {
            // Check if the Department Head has delegated to someone else, but still has a pending Actions
            if (deptHead.Delegated_To__c != null) {
                List<Disclosure_Action__c> deptHeadActions = [
                    SELECT Id, Contact_Action__r.Id
                    FROM Disclosure_Action__c
                    WHERE
                        Contact_Action__r.Contact__c = :deptHead.Contact__c
                        AND Contact_Action__r.Status__c = 'Pending'
                        AND Disclosure__c = :deptHead.Disclosure__c
                        AND RecordTypeId = :recordTypeIdDelegate
                ];

                contactActions.addAll(
                    getUpdatedDisclosureActionStatus(
                        deptHeadActions,
                        Status.Completed
                    )
                );
            }
        }

        if (!contactActions.isEmpty()) {
            update contactActions;
        }
    }

    /**
     * Mark pending Contact Actions as cancelled if the Department Head has been deleted
     * @param deptHeads List of Department_Head__c objects that need to be cleansed
     */
    public static void cancelDeletedDeptHeadPendingContactActions(
        List<Department_Head__c> deptHeads
    ) {
        List<Contact_Action__c> contactActions = new List<Contact_Action__c>();

        for (Department_Head__c deptHead : deptHeads) {
            // Check if the Department Head has pending Actions
            List<Disclosure_Action__c> deptHeadActions = [
                SELECT Id, Contact_Action__r.Id
                FROM Disclosure_Action__c
                WHERE
                    Contact_Action__r.Contact__c = :deptHead.Contact__c
                    AND Contact_Action__r.Status__c = 'Pending'
                    AND Disclosure__c = :deptHead.Disclosure__c
                    AND RecordTypeId = :recordTypeIdDelegate
            ];

            contactActions.addAll(
                getUpdatedDisclosureActionStatus(
                    deptHeadActions,
                    Status.Canceled
                )
            );
        }

        if (!contactActions.isEmpty()) {
            update contactActions;
        }
    }

    /**
     * Mark pending Contact Actions as complete if the Inventor has Signed
     * @param inventors List of DisclosureInventor__c objects that need to be checked
     */
    public static void completeSignDisclosureActions(
        List<DisclosureInventor__c> inventors
    ) {
        List<Contact_Action__c> contactActions = new List<Contact_Action__c>();

        // TODO this is not a bulkified query for the Disclosure_Action__c :-(
        for (DisclosureInventor__c inv : inventors) {
            Boolean inventorMadeSigningDecision = (inv.Signed_Status__c ==
            'Yes' ||
            inv.Signed_Status__c == 'Opted Out');

            // Check if the Inventor has signed the disclosure, but still has pending Actions
            if (inventorMadeSigningDecision) {
                List<Disclosure_Action__c> signActions = [
                    SELECT Id, Contact_Action__r.Id
                    FROM Disclosure_Action__c
                    WHERE
                        Contact_Action__r.Contact__c = :inv.Contact__c
                        AND Contact_Action__r.Status__c = 'Pending'
                        AND Disclosure__c = :inv.Disclosure__c
                        AND RecordTypeId = :recordTypeIdSignDisclosure
                ];

                // Opted Out: is a legitimate decisions for this action and is thus Completed (not Cancelled)
                contactActions.addAll(
                    getUpdatedDisclosureActionStatus(
                        signActions,
                        Status.Completed
                    )
                );
            }
        }

        if (!contactActions.isEmpty()) {
            update contactActions;
        }
    }

    /**
     * Mark all "Pending" Contact Actions related to the given Disclosures as "Completed"
     * @param disclosures List of Disclousres to be processed
     */
    public static void markDisclosureActionsAsCompleted(
        List<Disclosure__c> disclosures
    ) {
        List<Contact_Action__c> contactActions = getUpdatedDisclosureActionStatus(
            getPendingDisclosureActionsFromDisclosures(disclosures),
            Status.Completed
        );
        if (!contactActions.isEmpty()) {
            update contactActions;
        }
    }

    /**
     * Mark all "Pending" Contact Actions related to the given Disclosures as "Cancelled"
     * @param disclosures The list of Disclousres to be processed
     */
    public static void markDisclosureActionsAsCancelled(
        List<Disclosure__c> disclosures
    ) {
        List<Contact_Action__c> contactActions = getUpdatedDisclosureActionStatus(
            getPendingDisclosureActionsFromDisclosures(disclosures),
            Status.Canceled
        );
        if (!contactActions.isEmpty()) {
            update contactActions;
        }
    }

    /**
     * Mark all "Pending" Contact Actions related to the given Disclosure as "Cancelled"
     * @param disclosure The Disclousre to be processed
     */
    public static void markDisclosureActionsAsCancelled(
        Disclosure__c disclosure
    ) {
        List<Contact_Action__c> contactActions = getUpdatedDisclosureActionStatus(
            getPendingDisclosureActionsFromDisclosure(disclosure),
            Status.Canceled
        );
        if (!contactActions.isEmpty()) {
            update contactActions;
        }
    }

    /**
     * Return the list of associated Contact Actions with a new status
     * @param disclosureActions List of Disclosure Actions that need their associated Contact Actions updated
     * @param status The new status to be used for the Contact Actions
     */
    public static List<Contact_Action__c> getUpdatedDisclosureActionStatus(
        List<Disclosure_Action__c> disclosureActions,
        Status status
    ) {
        List<Contact_Action__c> contactActions = new List<Contact_Action__c>();

        for (Disclosure_Action__c disclosureAction : disclosureActions) {
            // Update all Contact Actions with new status
            Contact_Action__c contactAction = disclosureAction.Contact_Action__r;
            contactAction.Status__c = status.name();
            contactActions.add(contactAction);
            System.debug(
                'Contact Actions to be updated: ' + contactActions.toString()
            );
        }

        return contactActions;
    }

    /**
     * Get all "Pending" Disclosure Actions for a given list of Disclosures
     * @param disclosures The list of Disclosures to be processed
     */
    public static List<Disclosure_Action__c> getPendingDisclosureActionsFromDisclosures(
        List<Disclosure__c> disclosures
    ) {
        List<Id> disclosureIds = new List<Id>();

        for (Disclosure__c disclosure : disclosures) {
            disclosureIds.add(disclosure.Id);
        }

        List<Disclosure_Action__c> disclosureActions = [
            SELECT Id, Contact_Action__r.Id
            FROM Disclosure_Action__c
            WHERE
                Contact_Action__r.Status__c = 'Pending'
                AND Disclosure__c IN :disclosureIds
                AND RecordTypeId != :recordTypeIdSignDisclosure // TODO: This needs to be updated when we get new disclosure status!!!!
        ];

        return disclosureActions;
    }

    /**
     * Get all "Pending" Disclosure Actions for a given list of Disclosures
     * @param disclosure The list of Disclosures to be processed
     */
    public static List<Disclosure_Action__c> getPendingDisclosureActionsFromDisclosure(
        Disclosure__c disclosure
    ) {
        List<Disclosure__c> disclosures = new List<Disclosure__c>();
        disclosures.add(disclosure);
        List<Disclosure_Action__c> disclosureActions = getPendingDisclosureActionsFromDisclosures(
            disclosures
        );
        return disclosureActions;
    }
}