force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Contact_Action__c/Contact_Action__c.object-meta.xml
<CustomObject>
    <label>Contact Action</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Contact Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Actions</relationshipLabel>
    <relationshipName>Contact_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>TLO Case Number</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/SubmittedOnBehalf__c.field-meta.xml
<CustomField>
    <fullName>SubmittedOnBehalf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted on behalf of someone else</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/BioTang_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>BioTang_Disclosure</fullName>
    <active>true</active>
    <label>Biological and Tangible Property</label>
</RecordType>

force-app/main/default/objects/Disclosure_Action__c/Disclosure_Action__c.object-meta.xml
<CustomObject>
    <label>Disclosure Action</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Action__c/fields/Contact_Action__c.field-meta.xml
<CustomField>
    <fullName>Contact_Action__c</fullName>
    <label>Contact Action</label>
    <referenceTo>Contact_Action__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_1__c.field-meta.xml
<CustomField>
    <fullName>Reminder_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_2__c.field-meta.xml
<CustomField>
    <fullName>Reminder_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_3__c.field-meta.xml
<CustomField>
    <fullName>Reminder_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/recordTypes/Sign_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Sign_Disclosure</fullName>
    <active>true</active>
    <label>Sign Disclosure</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Disclosure__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Variables__c.field-meta.xml
<CustomField>
    <fullName>Variables__c</fullName>
    <label>Variables</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DisclosureInventorSignReminderTest.cls
@isTest
public with sharing class DisclosureInventorSignReminderTest {
    // @TestSetup
    // static void makeData() {
    //     TestSetup.defaultConfiguration();
    // }

    // @IsTest
    // public static void inventorSignReminderTest() {
    //     String disclosureTitle = 'Test Delegate Action';

    //     // Constants
    //     Id disclosureRecordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
    //         .get('BioTang_Disclosure')
    //         .getRecordTypeId();
    //     DateTime theDate = DateTime.now().addDays(-30);
    //     Util.now = DateTime.now().addDays(-30 + 7);

    //     // Contacts
    //     Account inventorContact = SampleDataFactory.createContact(
    //         'Inventor',
    //         true,
    //         '123456781'
    //     );
    //     Account submittingContact = SampleDataFactory.createContact(
    //         'Jeff',
    //         true,
    //         '11345678'
    //     );
    //     Account inactiveContact = SampleDataFactory.createContact(
    //         'InactiveInventor',
    //         false,
    //         '123456782'
    //     );
    //     inactiveContact.InvitationCode__pc = 'INVCODE01';
    //     update inactiveContact;

    //     // Disclosure
    //     Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
    //         disclosureRecordTypeId,
    //         disclosureTitle,
    //         'Draft',
    //         submittingContact
    //     );
    //     Test.setCreatedDate(disclosure.Id, theDate);
    //     DisclosureInventor__c inventor = SampleDataFactory.createInventor(
    //         disclosure,
    //         true,
    //         inventorContact
    //     );
    //     DisclosureInventor__c inactiveInventor = SampleDataFactory.createInventor(
    //         disclosure,
    //         false,
    //         inactiveContact
    //     );

    //     disclosure.Status__c = 'Pending Department Approval';
    //     update disclosure;
    //     disclosure.Status__c = 'Approved';
    //     update disclosure;

    //     Id recordTypeId = Schema.SObjectType.Disclosure_Action__c.getRecordTypeInfosByDeveloperName()
    //         .get('Sign_Disclosure')
    //         .getRecordTypeId();
    //     List<Disclosure_Action__c> signDisclosureActions = [
    //         SELECT
    //             Id,
    //             CreatedDate,
    //             Reminder_1__c,
    //             Reminder_2__c,
    //             Reminder_3__c,
    //             Contact_Action__c,
    //             Contact_Action__r.Name,
    //             Contact_Action__r.Status__c,
    //             Contact_Action__r.Contact__r.Name,
    //             Contact_Action__r.Contact__r.PersonEmail,
    //             Disclosure__c,
    //             Disclosure__r.Name__c,
    //             Disclosure__r.RecordType.Name,
    //             RecordType.Name,
    //             RecordType.DeveloperName
    //         FROM Disclosure_Action__c
    //         WHERE
    //             Disclosure__c = :disclosure.Id
    //             AND RecordTypeId = :recordTypeId
    //         LIMIT 2
    //     ];
    //     Test.setCreatedDate(signDisclosureActions[0].Id, theDate);
    //     Test.setCreatedDate(signDisclosureActions[1].Id, theDate);

    //     Test.startTest();
    //     Database.executeBatch(new DisclosureInventorSignReminder(), 2);
    //     Test.stopTest();

    //     Disclosure_Action__c disclosureAction;
    //     for (Disclosure_Action__c action : signDisclosureActions) {
    //         if (
    //             action.Contact_Action__r.Contact__r.Id == inventorContact.Id
    //         ) {
    //             disclosureAction = action;
    //         }
    //     }
    //     System.assertNotEquals(
    //         disclosureAction,
    //         null,
    //         'Action not found for Contact'
    //     );

    //     List<Notification__c> notification = [
    //         SELECT Id, Template__c, Variables__c
    //         FROM Notification__c
    //         WHERE
    //             Template__c = :NotificationBuilder.TEMPLATE_DISCLOSURE_SIGNATURE_REMINDER
    //     ];
    //     System.debug('Notification:' + notification);
    //     Map<String, Object> jsonVal = (Map<String, Object>) JSON.deserializeUntyped(
    //         notification[0].Variables__c
    //     );

    //     Disclosure__c disclosureToTest = getDisclosureToTest(disclosureTitle);
    //     System.assertEquals(
    //         '7',
    //         String.valueOf(jsonVal.get('outstanding')),
    //         'should be 7'
    //     );
    //     System.assertEquals(
    //         disclosureToTest.Name,
    //         String.valueOf(jsonVal.get('disclosure_name')),
    //         'disclosure_name'
    //     );
    //     System.assertEquals(
    //         disclosureToTest.Name__c,
    //         String.valueOf(jsonVal.get('disclosure_title')),
    //         'disclosure_title'
    //     );

    //     // disclosureToTest.RecordType.Name for BioTang need to be replace with 'Tangible Property Disclosure'
    //     System.assertEquals(
    //         Label.Disclosure_Type_Notify_BioTang,
    //         String.valueOf(jsonVal.get('disclosure_type')),
    //         'disclosure_type'
    //     );
    //     System.assertEquals(
    //         disclosureAction.Contact_Action__r.Contact__r.Name,
    //         String.valueOf(jsonVal.get('inventor_name')),
    //         'inventor_name'
    //     );
    //     System.assertEquals(
    //         2,
    //         notification.size(),
    //         'only 2 at this point in time'
    //     );

    //     // NonMit Inventor Reminder
    //     List<Notification__c> nonMitNotification = [
    //         SELECT Id, Template__c, Variables__c
    //         FROM Notification__c
    //         WHERE
    //             Template__c = :NotificationBuilder.TEMPLATE_DISCLOSURE_SIGNATURE_REMINDER
    //     ];
    //     System.assertEquals(
    //         2,
    //         nonMitNotification.size(),
    //         '2 notification for Inactive Kerb Contact and Active Kerb. Only have one template for both Mit and Non-Mit'
    //     );
    //     Map<String, Object> jsonValInactiveKerb = (Map<String, Object>) JSON.deserializeUntyped(
    //         nonMitNotification[1].Variables__c
    //     );
    //     System.assertEquals(
    //         disclosureToTest.Name,
    //         String.valueOf(jsonValInactiveKerb.get('disclosure_name')),
    //         'disclosure_name'
    //     );
    //     System.assertEquals(
    //         disclosureToTest.Name__c,
    //         String.valueOf(jsonValInactiveKerb.get('disclosure_title')),
    //         'disclosure_title'
    //     );
    //     System.assertEquals(
    //         inactiveContact.InvitationCode__pc,
    //         String.valueOf(jsonValInactiveKerb.get('invitation_code')),
    //         'invitation_code'
    //     );
    //     System.assertEquals(
    //         false,
    //         jsonValInactiveKerb.get('isActiveKerb'),
    //         'isActiveKerb'
    //     );
    //     List<Disclosure_Action__c> disclosureActions = [
    //         SELECT
    //             Id,
    //             CreatedDate,
    //             Contact_Action__r.Name,
    //             Contact_Action__r.Status__c,
    //             Contact_Action__c,
    //             RecordType.DeveloperName,
    //             RecordType.name,
    //             Disclosure__c,
    //             Disclosure__r.Name__c,
    //             Disclosure__r.RecordType.Name,
    //             Contact_Action__r.Contact__r.PersonEmail,
    //             Contact_Action__r.Contact__r.Name,
    //             Reminder_1__c,
    //             Reminder_2__c,
    //             Reminder_3__c
    //         FROM Disclosure_Action__c
    //         WHERE
    //             Disclosure__c = :disclosure.Id
    //             AND RecordTypeId = :recordTypeId
    //     ];
    //     System.debug(
    //         '\n\n disclosureActions:- \n\n' + disclosureActions + '\n\n'
    //     );
    // }

    // @IsTest
    // public static void InviteCodeForExistingInventorSignReminderTest() {
    //     String disclosureTitle = 'Test Delegate Action';

    //     // Constants
    //     Id disclosureRecordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
    //         .get('BioTang_Disclosure')
    //         .getRecordTypeId();
    //     DateTime theDate = DateTime.now().addDays(-30);
    //     Util.now = DateTime.now().addDays(-30 + 7);

    //     // Contacts
    //     Account inventorContact = SampleDataFactory.createContact(
    //         'Inventor',
    //         true,
    //         '123456781'
    //     );
    //     Account submittingContact = SampleDataFactory.createContact(
    //         'Jeff',
    //         true,
    //         '11345678'
    //     );
    //     Account jitContact = SampleDataFactory.createContact(
    //         'Bob',
    //         false,
    //         '02345678'
    //     ); // jitUser
    //     jitContact.InvitationCode__pc = 'INVCODE02';
    //     update jitContact;

    //     // Disclosure
    //     Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
    //         disclosureRecordTypeId,
    //         disclosureTitle,
    //         'Draft',
    //         submittingContact
    //     );
    //     Test.setCreatedDate(disclosure.Id, theDate);
    //     DisclosureInventor__c inventor = SampleDataFactory.createInventor(
    //         disclosure,
    //         true,
    //         inventorContact
    //     );
    //     DisclosureInventor__c inactiveInventor = SampleDataFactory.createInventor(
    //         disclosure,
    //         false,
    //         jitContact
    //     );

    //     disclosure.Status__c = 'Pending Department Approval';
    //     update disclosure;
    //     disclosure.Status__c = 'Approved';
    //     update disclosure;

    //     // The Inventor logged in, used the Invitation Code, but did not sign the disclosure
    //     SampleDataTest.getJitUser(jitContact);

    //     Id recordTypeId = Schema.SObjectType.Disclosure_Action__c.getRecordTypeInfosByDeveloperName()
    //         .get('Sign_Disclosure')
    //         .getRecordTypeId();
    //     List<Disclosure_Action__c> signDisclosureActions = [
    //         SELECT Id, CreatedDate
    //         FROM Disclosure_Action__c
    //         WHERE
    //             Disclosure__c = :disclosure.Id
    //             AND RecordTypeId = :recordTypeId
    //         LIMIT 2
    //     ];
    //     Test.setCreatedDate(signDisclosureActions[0].Id, theDate);
    //     Test.setCreatedDate(signDisclosureActions[1].Id, theDate);

    //     Test.startTest();
    //     Database.executeBatch(new DisclosureInventorSignReminder(), 2);
    //     Test.stopTest();

    //     // NonMit Inventor Reminder should not contain invitation code since user already signed In
    //     List<Notification__c> nonMitNotification = [
    //         SELECT Id, Template__c, Variables__c
    //         FROM Notification__c
    //         WHERE
    //             Template__c = :NotificationBuilder.TEMPLATE_DISCLOSURE_SIGNATURE_REMINDER
    //     ];
    //     System.assertEquals(
    //         2,
    //         nonMitNotification.size(),
    //         '2 notification, Inactive Kerb Contact and Active Kerb have only one Template'
    //     );
    //     Map<String, Object> jsonValInactiveKerb = (Map<String, Object>) JSON.deserializeUntyped(
    //         nonMitNotification[0].Variables__c
    //     );
    //     System.assertEquals(
    //         null,
    //         jsonValInactiveKerb.get('invitation_code'),
    //         'invitation_code should not be set'
    //     );
    //     System.assertEquals(
    //         Label.Disclosure_Notify_Inventor_Desc_Copy_BioTang,
    //         jsonValInactiveKerb.get('inventor_description_copy'),
    //         'inventor_description_copy should be set'
    //     );
    // }

    // private static Disclosure__c getDisclosureToTest(String title) {
    //     Disclosure__c disclosureToTest = [
    //         SELECT
    //             Id,
    //             Status__c,
    //             Name,
    //             Name__c,
    //             Case_Number__c,
    //             RecordType.name,
    //             SubmittedOnBehalf__c,
    //             Submitting_Contact__c,
    //             Submitting_Contact__r.Id,
    //             Submitting_Contact__r.Name,
    //             Submitting_Contact__r.PersonEmail,
    //             Submitting_Contact__r.AltEmail__pc
    //         FROM Disclosure__c
    //         WHERE Name__c = :title
    //         LIMIT 1
    //     ];
    //     return disclosureToTest;
    // }
}