force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Rejected_By__c.field-meta.xml
<CustomField>
    <fullName>Rejected_By__c</fullName>
    <label>Rejected By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>TLO Admin</fullName>
            </value>
            <value>
                <fullName>Department Head</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/TLO_License_Officer__c.field-meta.xml
<CustomField>
    <fullName>TLO_License_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TLO Officer</label>
    <referenceTo>TLO_Officer__c</referenceTo>
    <relationshipName>TLO_Officer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/MitAtTimeOfInvention__c.field-meta.xml
<CustomField>
    <fullName>MitAtTimeOfInvention__c</fullName>
    <defaultValue>false</defaultValue>
    <label>At MIT at time of Invention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PrimaryInventor__c.field-meta.xml
<CustomField>
    <fullName>PrimaryInventor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Source__c/Open_Source__c.object-meta.xml
<CustomObject>
    <label>Open Source</label>
    <nameField>
        <label>Open Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Source__c/fields/Software_Code_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Software_Code_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Software Code Disclosure</label>
    <referenceTo>Software_Code_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software_Code_Disclosure</label>
</RecordType>

force-app/main/default/objects/Software_Code_Disclosure__c/Software_Code_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Software Code Disclosure</label>
    <nameField>
        <label>Software Code Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Code Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Software Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Software_Code_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Software Code Disclosures</relationshipLabel>
    <relationshipName>Software_Code_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TLO_Officer__c/TLO_Officer__c.object-meta.xml
<CustomObject>
    <label>TLO Officer</label>
    <nameField>
        <label>TLO Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TLO Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DisclosureStatusChangeValidationTest.cls
@isTest
public class DisclosureStatusChangeValidationTest {
    @TestSetup
    static void setup() {
        TestSetup.defaultConfiguration();
    }

    public static Disclosure__c initDisclosure(String type, String status) {
        Account sampleContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '777777777'
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Traverso',
            true,
            '12345679'
        );

        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get(type)
            .getRecordTypeId();
        Disclosure__c testDisclosure = new Disclosure__c(
            Name__c = 'Test Disclosure',
            Status__c = 'Draft',
            RecordTypeId = recordTypeId,
            Submitting_Contact__c = sampleContact.Id
        );
        insert testDisclosure;

        DisclosureInventor__c sampleInventor1 = new DisclosureInventor__c(
            MitAtTimeOfInvention__c = true,
            PrimaryInventor__c = true,
            Signed_Status__c = 'Pending',
            Contact__c = sampleContact.Id,
            Disclosure__c = testDisclosure.Id
        );

        insert sampleInventor1;
        Department_Head__c depHead = new Department_Head__c(
            Disclosure__c = testDisclosure.Id,
            Signed_Date__c = Date.newInstance(2020, 7, 7),
            Contact__c = deptHeadContact.Id
        );
        insert depHead;

        update new Disclosure__c(Id = testDisclosure.Id, Status__c = status);
        return testDisclosure;
    }

    @isTest
    public static void NullToDraftTest() {
        Test.startTest();
        Account sampleContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '777777777'
        );
        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Disclosure__c testDisclosure = new Disclosure__c(
            Name__c = 'Test Disclosure',
            RecordTypeId = recordTypeId,
            Submitting_Contact__c = sampleContact.Id
        );
        insert testDisclosure;

        Disclosure__c updated = [
            SELECT Id, Status__c
            FROM Disclosure__c
            WHERE Id = :testDisclosure.Id
        ];
        System.assert(
            updated.Status__c == 'Draft',
            'Disclosure__c Status should be Draft'
        );
        Test.stopTest();
    }

    @isTest
    public static void draftToInventorSubmittedTest() {
        Test.startTest();
        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        Disclosure__c testDisclosure = initDisclosure('Software_Code_Disclosure', 'Draft');
        Software_Code_Disclosure__c softwareCode = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            testDisclosure
        );
        Open_Source__c openSource = SampleDataFactory.createOpenSource(
            'Sample Open Source',
            null,
            softwareCode
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Marcus',
            true,
            '12345579'
        );

        Disclosure__c updatedDisclosure = [
            SELECT Id, Submitted_Date__c, Status__c
            FROM Disclosure__c
            WHERE Id = :testDisclosure.Id
        ];

        System.assert(
            updatedDisclosure.Submitted_Date__c == null,
            'Disclosure__c Submitted_Date__c should be null'
        );

        updatedDisclosure.Status__c = 'Inventor Submitted';

        update updatedDisclosure;

        Disclosure__c disclosureControl = [
            SELECT Id, Submitted_Date__c
            FROM Disclosure__c
            WHERE Id = :testDisclosure.Id
        ];

        System.assert(
            disclosureControl.Submitted_Date__c == Date.today(),
            'Disclosure__c Submitted_Date__c should be set to Todays date'
        );

        Test.stopTest();
    }

    @isTest
    public static void InventorSubmittedToApprovedTest() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new PdfGeneratorApiMock());

        SampleDataFactory.createSoftwareCodeDocumentTemplate();

        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        Disclosure__c testDisclosure = initDisclosure('Software_Code_Disclosure', 'Draft');

        Disclosure__c updatedDisclosure = [
            SELECT Id, Submitted_Date__c, Status__c
            FROM Disclosure__c
            WHERE Id = :testDisclosure.Id
        ];

        Software_Code_Disclosure__c softwareCode = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            testDisclosure
        );
        Account contact = SampleDataFactory.createContact(
            'Marcus',
            true,
            '12345579'
        );
        
        updatedDisclosure.Status__c = 'Inventor Submitted';
        update updatedDisclosure;

        updatedDisclosure.Status__c = 'Approved';

        update updatedDisclosure;

        // Should be able to update TLO Office once disclosure is approved
        TLO_Officer__c tloOfficer = SampleDataFactory.createTLOOfficer(
            'MA',
            'Mary',
            '12345559'
        );
        updatedDisclosure.TLO_License_Officer__c = tloOfficer.Id;
        update updatedDisclosure;

        Disclosure__c disclosureControl = [
            SELECT Id, Submitted_Date__c
            FROM Disclosure__c
            WHERE Id = :testDisclosure.Id
        ];

        System.assert(
            disclosureControl.Submitted_Date__c == Date.today(),
            'Disclosure__c Submitted_Date__c should be set to Todays date'
        );

        Test.stopTest();
    }

   @isTest
    public static void approvedToInventorSubmittedTest() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new PdfGeneratorApiMock());

        SampleDataFactory.createSoftwareCodeDocumentTemplate();

        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        Disclosure__c testDisclosure = initDisclosure('Software_Code_Disclosure', 'Draft');

        Disclosure__c updatedDisclosure = [
            SELECT Id, Submitted_Date__c, Status__c
            FROM Disclosure__c
            WHERE Id = :testDisclosure.Id
        ];

        Software_Code_Disclosure__c softwareCode = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            testDisclosure
        );
        Account contact = SampleDataFactory.createContact(
            'Marcus',
            true,
            '12345579'
        );

        updatedDisclosure.Status__c = 'Inventor Submitted';
        update updatedDisclosure;

        updatedDisclosure.Status__c = 'Approved';

        update updatedDisclosure;

        try {
            // Change Approve Disclosure back to Inventor Submitted
            updatedDisclosure.Status__c = 'Inventor Submitted';
            update updatedDisclosure;
            System.assert(false, 'Expecting exception for invalid flow transition');
        } catch (Exception error) {
           System.assert(true, error.getMessage());
        }



        Test.stopTest();
    }

    @isTest
    public static void InventorSubmittedToRejectedTest() {
        Test.startTest();
        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        Disclosure__c testDisclosure = initDisclosure('Software_Code_Disclosure', 'Draft');

        Software_Code_Disclosure__c softwareCode = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            testDisclosure
        );
        Account contact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '12345579'
        );
                testDisclosure.Status__c = 'Inventor Submitted';
        update testDisclosure;

        Disclosure__c updatedDisclosure = [
            SELECT Id, Submitted_Date__c, Status__c
            FROM Disclosure__c
            WHERE Id = :testDisclosure.Id
        ];

        updatedDisclosure.Status__c = 'Rejected';
        updatedDisclosure.Rejection_Reason__c = 'Sample Rejection Reason';
        updatedDisclosure.Rejected_By__c = 'TLO Admin';

        update updatedDisclosure;

        Disclosure__c disclosureControl = [
            SELECT Id, Submitted_Date__c
            FROM Disclosure__c
            WHERE Id = :testDisclosure.Id
        ];

        Test.stopTest();
    }

    @isTest
    public static void draftToAnyPrimaryInventorStaffMemberTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account nonMitContact = SampleDataFactory.createContact(
            'Parker',
            false,
            null
        );
        Account mitContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Traverso',
            true,
            '12345679'
        );
        Account piContact = SampleDataFactory.createContact(
            'Paul',
            true,
            '77777700'
        );

        Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosureSOB(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            mitContact
        );
        SampleDataFactory.createDepartmentHead(
            newDraftSoftwareCodeDisclosureSample,
            deptHeadContact
        );
        SampleDataFactory.createDisclosureExternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            '12345',
            '6789',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(
            newDraftSoftwareCodeDisclosureSample
        );
        Software_Code_Disclosure__c newDraftSoftwareCodeSample = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            newDraftSoftwareCodeDisclosureSample
        );
        Open_Source__c openSource = SampleDataFactory.createOpenSource(
            'Sample Open Source',
            null,
            newDraftSoftwareCodeSample
        );
        SampleDataFactory.createInventor(
            newDraftSoftwareCodeDisclosureSample,
            true,
            nonMitContact
        );

        Account contact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '12345579'
        );
        
        newDraftSoftwareCodeDisclosureSample.Status__c = 'Rejected';

        try {
            update newDraftSoftwareCodeDisclosureSample;
            System.assert(
                false,
                'Primary Inventor must be MIT Staff Member, error not thrown.'
            );
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    public static void draftToAnyDepartmentHeadInventorStaffMemberTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account nonMitContact = SampleDataFactory.createContact(
            'Parker',
            false,
            null
        );
        Account mitContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Traverso',
            false,
            '12345679'
        );
        Account piContact = SampleDataFactory.createContact(
            'Paul',
            true,
            '77777700'
        );

        Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            mitContact
        );
        SampleDataFactory.createDepartmentHead(
            newDraftSoftwareCodeDisclosureSample,
            nonMitContact
        );
        SampleDataFactory.createDisclosureExternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            '12345',
            '6789',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(
            newDraftSoftwareCodeDisclosureSample
        );
        Software_Code_Disclosure__c newDraftSoftwareCodeSample = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            newDraftSoftwareCodeDisclosureSample
        );
        Open_Source__c openSource = SampleDataFactory.createOpenSource(
            'Sample Open Source',
            null,
            newDraftSoftwareCodeSample
        );
        SampleDataFactory.createInventor(
            newDraftSoftwareCodeDisclosureSample,
            true,
            mitContact
        );

        Account contact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '12345579'
        );
        
        newDraftSoftwareCodeDisclosureSample.Status__c = 'Rejected';

        try {
            update newDraftSoftwareCodeDisclosureSample;
            System.assert(
                false,
                'Department Head must be MIT Staff Member, error not thrown.'
            );
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    public static void draftToAnyDepartmentHeadSameAsInventorTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account mitContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account piContact = SampleDataFactory.createContact(
            'Paul',
            true,
            '77777700'
        );

        Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            mitContact
        );
        SampleDataFactory.createDisclosureExternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            '12345',
            '6789',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(
            newDraftSoftwareCodeDisclosureSample
        );
        Software_Code_Disclosure__c newDraftSoftwareCodeSample = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            newDraftSoftwareCodeDisclosureSample
        );
        SampleDataFactory.createInventor(
            newDraftSoftwareCodeDisclosureSample,
            true,
            mitContact
        );

        Account contact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '12345579'
        );
        
        newDraftSoftwareCodeDisclosureSample.Status__c = 'Rejected';

        try {
            SampleDataFactory.createDepartmentHead(
                newDraftSoftwareCodeDisclosureSample,
                mitContact
            );
            update newDraftSoftwareCodeDisclosureSample;
            System.assert(
                false,
                'Dept. Head cannot be one of the Inventors already listed on disclosure, error not thrown.'
            );
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    public static void draftToAnyInventorSameAsDepartmentHeadTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account nonMitContact = SampleDataFactory.createContact(
            'Parker',
            false,
            null
        );
        Account mitContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Traverso',
            true,
            '12345679'
        );
        Account sampleContact1 = SampleDataFactory.createContact(
            'Peter',
            true,
            '777777777'
        );
        Account piContact = SampleDataFactory.createContact(
            'Paul',
            true,
            '77777700'
        );

        Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosureSOB(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            sampleContact1
        );
        SampleDataFactory.createDepartmentHead(
            newDraftSoftwareCodeDisclosureSample,
            mitContact
        );
        SampleDataFactory.createDisclosureExternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            '12345',
            '6789',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(
            newDraftSoftwareCodeDisclosureSample
        );
        Software_Code_Disclosure__c newDraftSoftwareCodeSample = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            newDraftSoftwareCodeDisclosureSample
        );
        Open_Source__c openSource = SampleDataFactory.createOpenSource(
            'Sample Open Source',
            null,
            newDraftSoftwareCodeSample
        );

        Account contact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '12345579'
        );
        
        newDraftSoftwareCodeDisclosureSample.Status__c = 'Rejected';

        try {
            SampleDataFactory.createInventor(
                newDraftSoftwareCodeDisclosureSample,
                true,
                mitContact
            );
            update newDraftSoftwareCodeDisclosureSample;
            System.assert(
                false,
                'Inventor cannot be one of the Dept. Heads already listed on disclosure, error not thrown.'
            );
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    public static void draftToAnyOneDepartmentHeadTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account nonMitContact = SampleDataFactory.createContact(
            'Parker',
            false,
            null
        );
        Account mitContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account mitContact2 = SampleDataFactory.createContact(
            'Peter',
            true,
            '12345677'
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Traverso',
            true,
            '12345679'
        );
        Account piContact = SampleDataFactory.createContact(
            'Paul',
            true,
            '77777700'
        );

        Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            mitContact
        );
        SampleDataFactory.createDepartmentHead(
            newDraftSoftwareCodeDisclosureSample,
            mitContact2
        );
        SampleDataFactory.createDepartmentHead(
            newDraftSoftwareCodeDisclosureSample,
            deptHeadContact
        );
        SampleDataFactory.createDisclosureExternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            '12345',
            '6789',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(
            newDraftSoftwareCodeDisclosureSample
        );
        Software_Code_Disclosure__c newDraftSoftwareCodeSample = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            newDraftSoftwareCodeDisclosureSample
        );
        Open_Source__c openSource = SampleDataFactory.createOpenSource(
            'Sample Open Source',
            null,
            newDraftSoftwareCodeSample
        );
        SampleDataFactory.createInventor(
            newDraftSoftwareCodeDisclosureSample,
            true,
            mitContact
        );

        Account contact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '12345579'
        );
        
        newDraftSoftwareCodeDisclosureSample.Status__c = 'Rejected';

        try {
            update newDraftSoftwareCodeDisclosureSample;
            System.assert(
                false,
                'Only 1 Department Head is allowed, error not thrown.'
            );
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    public static void draftToAnyPrimaryInventorCountTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account nonMitContact = SampleDataFactory.createContact(
            'Parker',
            false,
            null
        );
        Account mitContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Traverso',
            true,
            '12345679'
        );
        Account piContact = SampleDataFactory.createContact(
            'Paul',
            true,
            '77777700'
        );

        Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosureSOB(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            mitContact
        );
        SampleDataFactory.createDepartmentHead(
            newDraftSoftwareCodeDisclosureSample,
            mitContact
        );
        SampleDataFactory.createDisclosureExternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            '12345',
            '6789',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(
            newDraftSoftwareCodeDisclosureSample
        );
        Software_Code_Disclosure__c newDraftSoftwareCodeSample = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            newDraftSoftwareCodeDisclosureSample
        );
        Open_Source__c openSource = SampleDataFactory.createOpenSource(
            'Sample Open Source',
            null,
            newDraftSoftwareCodeSample
        );
        SampleDataFactory.createInventor(
            newDraftSoftwareCodeDisclosureSample,
            false,
            nonMitContact
        );

        Account contact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '12345579'
        );
        
        newDraftSoftwareCodeDisclosureSample.Status__c = 'Rejected';

        try {
            update newDraftSoftwareCodeDisclosureSample;
            System.assert(
                false,
                'At least 1 Primary Inventor, error not thrown.'
            );
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    public static void draftToAnySuccessTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account nonMitContact = SampleDataFactory.createContact(
            'Parker',
            false,
            null
        );
        Account submittingContact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '11345678'
        );
        Account mitContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Traverso',
            true,
            '12345679'
        );
        Account piContact = SampleDataFactory.createContact(
            'Paul',
            true,
            '77777700'
        );

        Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosureSOB(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            submittingContact
        );
        SampleDataFactory.createDepartmentHead(
            newDraftSoftwareCodeDisclosureSample,
            deptHeadContact
        );
        SampleDataFactory.createDisclosureExternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            '12345',
            '6789',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(
            newDraftSoftwareCodeDisclosureSample
        );
        Software_Code_Disclosure__c newDraftSoftwareCodeSample = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            newDraftSoftwareCodeDisclosureSample
        );
        Open_Source__c openSource = SampleDataFactory.createOpenSource(
            'Sample Open Source',
            null,
            newDraftSoftwareCodeSample
        );
        SampleDataFactory.createInventor(
            newDraftSoftwareCodeDisclosureSample,
            true,
            mitContact
        );
        SampleDataFactory.createInventor(
            newDraftSoftwareCodeDisclosureSample,
            false,
            nonMitContact
        );

        Account contact = SampleDataFactory.createContact(
            'John',
            true,
            '12345579'
        );

        newDraftSoftwareCodeDisclosureSample.Status__c = 'Pending Department Approval';
        update newDraftSoftwareCodeDisclosureSample;

        newDraftSoftwareCodeDisclosureSample.Status__c = 'Rejected';
        newDraftSoftwareCodeDisclosureSample.Rejection_Reason__c = 'Sample Rejection Reason';
        newDraftSoftwareCodeDisclosureSample.Rejected_By__c = 'TLO Admin';

        try {
            update newDraftSoftwareCodeDisclosureSample;
            System.assert(true, 'Success');
        } catch (Exception error) {
            System.assert(false, error.getMessage());
        }
        Test.stopTest();
    }
    @isTest
    public static void draftToAnySuccessPIContactTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account nonMitContact = SampleDataFactory.createContact(
            'Parker',
            false,
            null
        );
        Account submittingContact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '11345678'
        );
        Account mitContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Traverso',
            true,
            '12345679'
        );
        Account piContact = SampleDataFactory.createContact(
            'Paul',
            true,
            '77777700'
        );

        Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosureSOB(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            submittingContact
        );
        SampleDataFactory.createDepartmentHead(
            newDraftSoftwareCodeDisclosureSample,
            deptHeadContact
        );
        SampleDataFactory.createDisclosureExternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            '12345',
            '6789',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            newDraftSoftwareCodeDisclosureSample,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(
            newDraftSoftwareCodeDisclosureSample
        );
        Software_Code_Disclosure__c newDraftSoftwareCodeSample = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            newDraftSoftwareCodeDisclosureSample
        );
        Open_Source__c openSource = SampleDataFactory.createOpenSource(
            'Sample Open Source',
            null,
            newDraftSoftwareCodeSample
        );
        SampleDataFactory.createInventor(
            newDraftSoftwareCodeDisclosureSample,
            true,
            mitContact
        );
        SampleDataFactory.createInventor(
            newDraftSoftwareCodeDisclosureSample,
            false,
            nonMitContact
        );
        // Can not change status from Draft to Rejected
        newDraftSoftwareCodeDisclosureSample.Status__c = 'Pending Department Approval';
        update newDraftSoftwareCodeDisclosureSample;
        //Dept. Head can be listed as PI on disclosure - Unlikely but is still possible.
        newDraftSoftwareCodeDisclosureSample.Status__c = 'Rejected';
        newDraftSoftwareCodeDisclosureSample.Rejection_Reason__c = 'Sample Rejection Reason';
        newDraftSoftwareCodeDisclosureSample.Rejected_By__c = 'TLO Admin';

        try {
            update newDraftSoftwareCodeDisclosureSample;
            System.assert(true, 'Success');
        } catch (Exception error) {
            System.assert(false, error.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    public static void approvedFromInsertTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        try {
            Account mitContact = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosure(
                recordTypeIdSoftwareCode,
                'Sample Draft Disclosure for Software Code',
                'Approved',
                mitContact
            );
            System.assert(
                false,
                'Initial Disclosure with Approved Status, error not thrown '
            );
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    public static void draftToRejectedToDraftTest() {
        Test.startTest();
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        try {
            Account nonMitContact = SampleDataFactory.createContact(
                'Parker',
                false,
                null
            );
            Account mitContact = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account deptHeadContact = SampleDataFactory.createContact(
                'Traverso',
                true,
                '12345679'
            );
            Account piContact = SampleDataFactory.createContact(
                'Paul',
                true,
                '77777700'
            );
            Disclosure__c newDraftSoftwareCodeDisclosureSample = SampleDataFactory.createDisclosure(
                recordTypeIdSoftwareCode,
                'Sample Draft Disclosure for Software Code',
                null,
                mitContact
            );

            SampleDataFactory.createDepartmentHead(
                newDraftSoftwareCodeDisclosureSample,
                deptHeadContact
            );
            SampleDataFactory.createDisclosureExternalFunding(
                newDraftSoftwareCodeDisclosureSample,
                '12345',
                '6789',
                piContact,
                'External Sponsor 1'
            );
            SampleDataFactory.createDisclosureInternalFunding(
                newDraftSoftwareCodeDisclosureSample,
                'Yes',
                '12345678',
                'Internal Funding 1'
            );
            SampleDataFactory.createCommercialInterest(
                newDraftSoftwareCodeDisclosureSample
            );
            Software_Code_Disclosure__c newDraftSoftwareCodeSample = SampleDataFactory.createSoftwareCode(
                'Sample Draft Software Code',
                newDraftSoftwareCodeDisclosureSample
            );
            Open_Source__c openSource = SampleDataFactory.createOpenSource(
                'Sample Open Source',
                null,
                newDraftSoftwareCodeSample
            );
            SampleDataFactory.createInventor(
                newDraftSoftwareCodeDisclosureSample,
                true,
                mitContact
            );
            SampleDataFactory.createInventor(
                newDraftSoftwareCodeDisclosureSample,
                false,
                nonMitContact
            );
            
            newDraftSoftwareCodeDisclosureSample.Status__c = 'Rejected';
            update newDraftSoftwareCodeDisclosureSample;
            newDraftSoftwareCodeDisclosureSample.Status__c = 'Draft';
            update newDraftSoftwareCodeDisclosureSample;
            System.assert(
                false,
                'Disclosure with Rejected Status can not be updated, error not thrown '
            );
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
        Test.stopTest();
    }
}