force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/Software_Code_Disclosure__c/Software_Code_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Software Code Disclosure</label>
    <nameField>
        <label>Software Code Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Code Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Software Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Software_Code_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Software Code Disclosures</relationshipLabel>
    <relationshipName>Software_Code_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Third_Party_Code__c/Third_Party_Code__c.object-meta.xml
<CustomObject>
    <label>Third Party Code</label>
    <nameField>
        <label>Third Party Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Code__c/fields/Software_Code_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Software_Code_Disclosure__c</fullName>
    <label>Software Code Disclosure</label>
    <referenceTo>Software_Code_Disclosure__c</referenceTo>
    <relationshipLabel>Third Party Code</relationshipLabel>
    <relationshipName>Third_Party_Code</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SoftwareDisclosuresSampleFactory.cls
public class SoftwareDisclosuresSampleFactory {
    public static Disclosure__c createDisclosure(
        String title,
        Boolean includeFiles
    ) {
        // Record type id's
        Id recordTypeIdSoftware = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        /**
         * Contact creation to be used throughout
         */

        Account existingContact1 = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '900047497'
        ];
        Account sampleContact1 = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '12345678'
        ];

        Account sampleNonMitContact = [
            SELECT Id
            FROM Account
            WHERE PersonEmail = 'cr11@guest.test'
        ];

        Account departmentHeadContact2 = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777778'
        ];

        Account piContact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '777777700'
        ];
        /**
         * Sample Data
         */

        /**
         * Software Code sample data
         */

        System.debug('Software: Sample');
        Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
            recordTypeIdSoftware,
            title,
            'Draft',
            sampleContact1
        );
        SampleDataFactory.createDepartmentHead(
            disclosure,
            departmentHeadContact2
        );
        SampleDataFactory.createDisclosureExternalFunding(
            disclosure,
            'OPP1201537',
            '6945744',
            piContact,
            'External Sponsor 1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosure,
            'Yes',
            '12345678',
            'Internal Funding 1'
        );
        SampleDataFactory.createCommercialInterest(disclosure);
        Software_Code_Disclosure__c softwareCodeDisclosure = SampleDataFactory.createSoftwareCode(
            'Sample Inventor Submitted Software Code',
            disclosure
        );
        SampleDataFactory.createOpenSource(
            'Open Source for Inventor Submitted Software Code',
            null,
            softwareCodeDisclosure
        );
        Third_Party_Code__c thirdPartyCode = SampleDataFactory.createThirdPartyCode(
            'Third Party Code',
            softwareCodeDisclosure
        );
        Third_Party_Code__c thirdPartyCode2 = SampleDataFactory.createThirdPartyCode(
            'Third Party Code2',
            softwareCodeDisclosure
        );
        Third_Party_Code__c thirdPartyCode3 = SampleDataFactory.createThirdPartyCode(
            'Third Party Code3',
            softwareCodeDisclosure
        );
        SampleDataFactory.createInventor(disclosure, true, existingContact1);
        SampleDataFactory.createInventor(
            disclosure,
            false,
            sampleNonMitContact
        );

        if (includeFiles) {
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Software.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.updateTechnicalDocument(
                ContentVersionClassification.TECHNICAL_DESCRIPTION,
                'Technical_Description_Software.docx',
                'docx',
                disclosure
            );
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.SOFTWARE_CODE,
                'Open_Source_Software.pdf',
                'pdf',
                disclosure
            );
            SampleDataFactory.createTechnicalDocument(
                ContentVersionClassification.SOFTWARE_CODE,
                'Open_Source_Software2.txt',
                'txt',
                disclosure
            );
            SampleDataFactory.createThirdPartyCodeDocument(
                ContentVersionClassification.THIRD_PARTY_CODE,
                'ThirdPartyCode1.pdf',
                'pdf',
                thirdPartyCode
            );
        }
        // Department head approval, Can not directly go to Inventor Submitted
        disclosure.Status__c = 'Pending Department Approval';
        update disclosure;

        return disclosure;
    }
}