force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Copyright_Disclosure__c/Copyright_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Copyright Disclosure</label>
    <nameField>
        <label>Copyright Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copyright Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Copyright Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Copyright_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Copyright Disclosures</relationshipLabel>
    <relationshipName>Copyright_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/recordTypes/Invention_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Invention_Disclosure</fullName>
    <active>true</active>
    <label>Invention</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/MitAtTimeOfInvention__c.field-meta.xml
<CustomField>
    <fullName>MitAtTimeOfInvention__c</fullName>
    <defaultValue>false</defaultValue>
    <label>At MIT at time of Invention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PrimaryInventor__c.field-meta.xml
<CustomField>
    <fullName>PrimaryInventor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Source__c/Open_Source__c.object-meta.xml
<CustomObject>
    <label>Open Source</label>
    <nameField>
        <label>Open Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Source__c/fields/Copyright_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Copyright_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copyright Disclosure</label>
    <referenceTo>Copyright_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/fields/Open_Source_Licensing__c.field-meta.xml
<CustomField>
    <fullName>Open_Source_Licensing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open Source Licensing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/fields/Software_Code_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Software_Code_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Software Code Disclosure</label>
    <referenceTo>Software_Code_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright_Disclosure</label>
</RecordType>

force-app/main/default/objects/Open_Source__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software_Code_Disclosure</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Software_Code_Disclosure__c/Software_Code_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Software Code Disclosure</label>
    <nameField>
        <label>Software Code Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Code Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Software Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Software_Code_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Software Code Disclosures</relationshipLabel>
    <relationshipName>Software_Code_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Third_Party_Content__c/Third_Party_Content__c.object-meta.xml
<CustomObject>
    <label>Third Party Content</label>
    <nameField>
        <label>Third Party Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Content__c/fields/Copyright_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Copyright_Disclosure__c</fullName>
    <label>Copyright Disclosure</label>
    <referenceTo>Copyright_Disclosure__c</referenceTo>
    <relationshipLabel>Third Party Contents</relationshipLabel>
    <relationshipName>Third_Party_Contents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DisclosureValidationTest.cls
@IsTest
public with sharing class DisclosureValidationTest {
    @TestSetup
    static void setup() {
        TestSetup.defaultConfiguration();
    }

    private static Disclosure__c initDisclosure(String type) {
        Account sampleContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '777777777'
        );
        Account deptHeadContact = SampleDataFactory.createContact(
            'Traverso',
            true,
            '12345679'
        );

        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get(type)
            .getRecordTypeId();
        Disclosure__c testDisclosure = new Disclosure__c(
            Name__c = 'Test Disclosure',
            Status__c = 'Draft',
            RecordTypeId = recordTypeId,
            Submitting_Contact__c = sampleContact.Id
        );
        insert testDisclosure;

        DisclosureInventor__c sampleInventor1 = new DisclosureInventor__c(
            MitAtTimeOfInvention__c = true,
            PrimaryInventor__c = true,
            Signed_Status__c = 'Yes',
            Contact__c = sampleContact.Id,
            Disclosure__c = testDisclosure.Id
        );

        insert sampleInventor1;
        Department_Head__c depHead = new Department_Head__c(
            Disclosure__c = testDisclosure.Id,
            Signed_Date__c = Date.newInstance(2020, 7, 7),
            Contact__c = deptHeadContact.Id
        );
        insert depHead;

        update new Disclosure__c(Id = testDisclosure.Id, Status__c = 'Draft');
        return testDisclosure;
    }

    @IsTest
    static void testDisclosureOnDelete() {
        Test.startTest();
        User user = getUser();
        System.runAs(user) {
            System.debug('testDisclosureOnDelete');
            Disclosure__c testDisclosure = new Disclosure__c(
                Name__c = 'Test Disclosure',
                Status__c = null
            );
            DisclosureValidation.onBeforeDelete(
                new List<Disclosure__c>{ testDisclosure }
            );
            System.assertEquals(
                testDisclosure.Name__c,
                'Test Disclosure',
                'Expecting Name to be `Test Disclosure` '
            );
        }
        Test.stopTest();
    }

    static User getUser() {
        Id systemAdminProfileId = [
            SELECT Id
            FROM Profile
            WHERE Name = 'System Administrator'
            LIMIT 1
        ]
        .Id;

        User userExample = new User();
        userExample.Username =
            'emailtest' +
            '_' +
            DateTime.now().format('MM-dd-yyyy-HH-mm-ss') +
            '@mit.edu.' +
            UserInfo.getOrganizationId().toLowerCase();
        userExample.FirstName = 'First';
        userExample.LastName = 'Last';
        userExample.Alias = 'Alias';
        userExample.Email = 'emailtest1@mit.edu';
        userExample.TimeZoneSidKey = 'America/New_York';
        userExample.LocaleSidKey = 'en_US';
        userExample.EmailEncodingKey = 'ISO-8859-1';
        userExample.ProfileId = systemAdminProfileId;
        userExample.LanguageLocaleKey = 'en_US';

        insert userExample;
        return userExample;
    }

    static Disclosure__c setupSoftwareCodeDisclosure(String status) {
        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        // Test setup
        Disclosure__c testDisclosure = initDisclosure(
            'Software_Code_Disclosure'
        );
        Software_Code_Disclosure__c testSoftwareCodeDisclosure = new Software_Code_Disclosure__c(
            Name = 'Test Sotware Code Disclosure',
            Disclosure__c = testDisclosure.Id
        );
        insert testSoftwareCodeDisclosure;
        Account contact = SampleDataFactory.createContact(
            'Marcus',
            true,
            '12345589'
        );
        // Default status is Draft
        if (status != 'Draft') {
            testDisclosure.Status__c = status;
            update testDisclosure;
        }

        return testDisclosure;
    }

    @IsTest
    static void testDisclosureSuccessTriggerViaDML() {
        Test.startTest();
        User user = getUser();
        System.runAs(user) {
            Disclosure__c testDisclosure = setupSoftwareCodeDisclosure('Draft');
            Database.DeleteResult result = Database.delete(testDisclosure);
            System.assert(
                result.isSuccess(),
                'Owner able to Remove disclosure'
            );

            List<Software_Code_Disclosure__c> softwareCodeDisclosures = [
                SELECT Id
                FROM Software_Code_Disclosure__c
                WHERE Disclosure__r.Id = :testDisclosure.Id
                LIMIT 10
            ];
            System.assert(
                softwareCodeDisclosures.size() == 0,
                'Software_Code_Disclosure__c should also be deleted'
            );
        }
        Test.stopTest();
    }

    @IsTest
    static void testDisclosureFailureTriggerViaDML() {
        Test.startTest();
        User user = getUser();
        Disclosure__c testDisclosure = setupSoftwareCodeDisclosure('Draft');
        System.runAs(user) {
            try {
                Database.DeleteResult result = Database.delete(testDisclosure);
                //! TODO: Replace this ASAP
                // System.assert(false,'Exception not thrown');
            } catch (Exception error) {
                System.assert(
                    error.getMessage()
                        .contains(DisclosureValidation.INITIATOR_ERROR_MSG),
                    'Expecting ' + DisclosureValidation.INITIATOR_ERROR_MSG
                );
            }
        }
        Test.stopTest();
    }

    @IsTest
    static void testDisclosureStatusFailureTriggerViaDML() {
        Test.startTest();
        User user = getUser();
        Disclosure__c testDisclosure = setupSoftwareCodeDisclosure(
            'Inventor Submitted'
        );
        System.runAs(user) {
            try {
                Database.DeleteResult result = Database.delete(testDisclosure);
                System.assert(false, 'Exception not thrown');
            } catch (Exception error) {
                System.assert(
                    error.getMessage()
                        .contains(DisclosureValidation.DRAFT_ERROR_MSG),
                    'Expecting ' + DisclosureValidation.DRAFT_ERROR_MSG
                );
            }
        }
        Test.stopTest();
    }

    @isTest
    static void testContactValidation() {
        Account contact = new Account(
            AltEmail__pc = 'tlo@advance.io',
            PersonOtherPhone = '0612345678',
            CountryOfCitizenship__pc = 'USA',
            FirstName = 'John',
            Government_Agency_Name__pc = 'U.S. Air Force',
            GovernmentEmployeeStatus__pc = true,
            GuestAccountNeeded__pc = 'No',
            HHMI_Current__pc = true,
            HHMI_Current_Date_From__pc = Date.newInstance(2023, 2, 14),
            Institution__pc = 'Massachusetts Institute of Technology',
            InstitutionCode__pc = '12345',
            InvitationCode__pc = '',
            KerbName__pc = 'kerb',
            LastName = 'Johnson',
            MiddleName = 'Jay',
            MitId__pc = '12345678',
            MoiraStatus__pc = '1',
            OldEmail__pc = 'old@yahoo.com',
            PersonBirthdate = Date.newInstance(2000, 2, 14),
            PersonDepartment = 'Computer Science',
            PersonEmail = 'sample@mit.edu',
            PersonMailingStreet = '244 Wood Street',
            PersonMailingCity = 'Lexington',
            PersonMailingCountry = 'United States of America',
            PersonMailingPostalCode = '02421-6426',
            PersonMailingState = 'MA',
            PersonTitle = 'Lecturer',
            Phone = '0613245672',
            PreferredName__pc = 'JJ',
            VaAppointment__pc = 'No'
        );

        try {
            insert contact;
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
    }

    // FIXME: This test is failing due to the new email field not being the same as the old field
    //  its not unique, Person Accounts email field cannot be unique
    // @isTest
    // static void testContactDuplicateEmailValidation() {
    //     Test.startTest();

    //     Id personAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
    //         .get('PersonAccount')
    //         .getRecordTypeId();
    //     Account contact = new Account(
    //         PersonEmail = 'sample@mit.edu',
    //         FirstName = 'sample',
    //         LastName = 'contact',
    //         RecordTypeId = personAccountRecordTypeId
    //     );
    //     Account contact2 = new Account(
    //         PersonEmail = 'sample@mit.edu',
    //         FirstName = 'sample2',
    //         LastName = 'contact',
    //         RecordTypeId = personAccountRecordTypeId
    //     );

    //     insert contact;

    //     try {
    //         insert contact2;
    //         System.assert(
    //             false,
    //             'Duplicate Account Email Address, error not thrown.'
    //         );
    //     } catch (Exception error) {
    //         System.assert(true, error.getMessage());
    //     }
    //     Test.stopTest();
    // }

    static testMethod void validateAfterUpdateArchiveNoPrimaryInventor() {
        try {
            Test.startTest();
            Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Invention_Disclosure')
                .getRecordTypeId();
            Account contact = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account contactHead = SampleDataFactory.createContact(
                'Donald1',
                true,
                '123456781'
            );
            Disclosure__c disclosure = SampleDataFactory.createDisclosure(
                recordTypeId,
                'Sample Draft Disclosure for Invention',
                'Draft',
                contact
            );
            DisclosureInventor__c disclosureInventor = SampleDataFactory.createInventor(
                disclosure,
                false,
                contact
            );

            Department_Head__c departmentHead = SampleDataFactory.createDepartmentHead(
                disclosure,
                contactHead
            );
            disclosure.Status__c = 'Archived';
            update disclosure;
            Test.stopTest();
        } catch (Exception ex) {
            String errorMessage = ex.getMessage();
            System.assert(false, errorMessage);
            //Should be able to Archive without validation.
        }
    }

    static testMethod void validateAfterUpdateOnBehalfOf() {
        Test.startTest();
        try {
            Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Invention_Disclosure')
                .getRecordTypeId();
            Account contact = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account contactHead = SampleDataFactory.createContact(
                'Donald1',
                true,
                '123456781'
            );
            Disclosure__c disclosure = SampleDataFactory.createDisclosure(
                recordTypeId,
                'Sample Draft Disclosure for Invention',
                'Draft',
                contact
            );
            DisclosureInventor__c disclosureInventor = SampleDataFactory.createInventor(
                disclosure,
                true,
                contact
            );

            Department_Head__c departmentHead = SampleDataFactory.createDepartmentHead(
                disclosure,
                contactHead
            );

            List<Disclosure__c> disclosures = new List<Disclosure__c>();
            disclosures.add(disclosure);
            DisclosureValidation.DisclosureContext disclosureContext = DisclosureValidation.getDisclosureContext(
                disclosures
            );

            DisclosureValidation.onBehalfOfInventorValidation(
                disclosureContext.disclosureInventorMap
            );
            disclosure.Status__c = 'Rejected';
            update disclosure;
        } catch (Exception ex) {
            String errorMessage = ex.getMessage();
            System.assertEquals(
                errorMessage.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                true
            );
            //Please review the Rejection Reason before rejecting the disclosure
        }
        Test.stopTest();
    }

    static testMethod void validateCopyrightDepartmentHead() {
        Test.startTest();
        try {
            Id recordTypeIdCopyright = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Copyright_Disclosure')
                .getRecordTypeId();

            Account sampleContact1 = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account sampleContact2 = SampleDataFactory.createContact(
                'Jeff',
                true,
                '12345679'
            );
            Account departmentHeadContact = SampleDataFactory.createContact(
                'Donald1',
                true,
                '123456781'
            );

            Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
                recordTypeIdCopyright,
                'Copyright Success',
                'Draft',
                sampleContact1
            );

            Department_Head__c firstDeptHead = SampleDataFactory.createDepartmentHead(
                disclosure,
                departmentHeadContact
            );

            SampleDataFactory.createDisclosureInternalFunding(
                disclosure,
                'Yes',
                '12345678',
                'Internal Funding 1'
            );
            SampleDataFactory.createCommercialInterest(disclosure);
            Copyright_Disclosure__c copyrightDisclosure = SampleDataFactory.createCopyright(
                'Sample Inventor Submitted Copyright',
                disclosure,
                departmentHeadContact
            );
            Open_Source__c openSource = SampleDataFactory.createOpenSource(
                'Open Source for Inventor Submitted Copyright',
                copyrightDisclosure,
                null
            );
            System.assertEquals(
                openSource.Open_Source_Licensing__c,
                true,
                'Expecting OpenSource Licensing to be true'
            );
            Third_Party_Content__c thirdPartyContent = SampleDataFactory.createThirdPartyContent(
                'Third Party Content',
                copyrightDisclosure
            );
            SampleDataFactory.createInventor(disclosure, true, sampleContact2);
            // Department head approval, Can not directly go to Inventor Submitted
            disclosure.Status__c = 'Pending Department Approval';
            update disclosure;
        } catch (Exception ex) {
            System.assert(false, ex.getMessage());
        }
        Test.stopTest();
    }

    static testMethod void validateCopyrightDepartmentHeadNoOpenSource() {
        Test.startTest();
        try {
            Id recordTypeIdCopyright = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Copyright_Disclosure')
                .getRecordTypeId();

            Account sampleContact1 = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account sampleContact2 = SampleDataFactory.createContact(
                'Jeff',
                true,
                '12345679'
            );
            Account departmentHeadContact = SampleDataFactory.createContact(
                'Donald1',
                true,
                '123456781'
            );

            Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
                recordTypeIdCopyright,
                'Copyright Success',
                'Draft',
                sampleContact1
            );

            Department_Head__c noDeptHead = null; // Enforce Test intention

            SampleDataFactory.createDisclosureInternalFunding(
                disclosure,
                'Yes',
                '12345678',
                'Internal Funding 1'
            );
            SampleDataFactory.createCommercialInterest(disclosure);
            Copyright_Disclosure__c copyrightDisclosure = SampleDataFactory.createCopyright(
                'Sample Inventor Submitted Copyright',
                disclosure,
                departmentHeadContact
            );
            Open_Source__c openSource = SampleDataFactory.createOpenSource(
                'Open Source for Inventor Submitted Copyright',
                copyrightDisclosure,
                null
            );
            openSource.Open_Source_Licensing__c = false;
            update openSource;
            System.assertEquals(
                openSource.Open_Source_Licensing__c,
                false,
                'Expecting OpenSource Licensing to be false'
            );

            Third_Party_Content__c thirdPartyContent = SampleDataFactory.createThirdPartyContent(
                'Third Party Content',
                copyrightDisclosure
            );
            SampleDataFactory.createInventor(disclosure, true, sampleContact2);
            // Department head approval, Can not directly go to Inventor Submitted
            disclosure.Status__c = 'Pending Department Approval';
            update disclosure;
        } catch (Exception ex) {
            System.assert(false, ex.getMessage());
        }
        Test.stopTest();
    }

    static testMethod void validateCopyrightDepartmentHeadFailure() {
        Test.startTest();
        try {
            Id recordTypeIdCopyright = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Copyright_Disclosure')
                .getRecordTypeId();

            Account sampleContact1 = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account sampleContact2 = SampleDataFactory.createContact(
                'Jeff',
                true,
                '12345679'
            );
            Account departmentHeadContact = SampleDataFactory.createContact(
                'Donald1',
                true,
                '123456781'
            );

            Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
                recordTypeIdCopyright,
                'Copyright Success',
                'Draft',
                sampleContact1
            );

            Department_Head__c noDeptHead = null; // Enforce Test intention

            SampleDataFactory.createDisclosureInternalFunding(
                disclosure,
                'Yes',
                '12345678',
                'Internal Funding 1'
            );
            SampleDataFactory.createCommercialInterest(disclosure);
            Copyright_Disclosure__c copyrightDisclosure = SampleDataFactory.createCopyright(
                'Sample Inventor Submitted Copyright',
                disclosure,
                departmentHeadContact
            );
            Open_Source__c openSource = SampleDataFactory.createOpenSource(
                'Open Source for Inventor Submitted Copyright',
                copyrightDisclosure,
                null
            );
            System.assertEquals(
                openSource.Open_Source_Licensing__c,
                true,
                'Expecting OpenSource Licensing to be true'
            );
            Third_Party_Content__c thirdPartyContent = SampleDataFactory.createThirdPartyContent(
                'Third Party Content',
                copyrightDisclosure
            );
            SampleDataFactory.createInventor(disclosure, true, sampleContact2);
            // Department head approval, Can not directly go to Inventor Submitted
            disclosure.Status__c = 'Pending Department Approval';
            update disclosure;

            System.assert(false, 'Exception not thrown');
        } catch (Exception ex) {
            System.assertEquals(
                ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                true,
                ex.getMessage()
            );
        }
        Test.stopTest();
    }

    static testMethod void validateSoftwareDepartmentHead() {
        Test.startTest();
        try {
            Id recordTypeIdSoftware = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Software_Code_Disclosure')
                .getRecordTypeId();

            Account sampleContact1 = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account existingContact1 = SampleDataFactory.createContact(
                'Jeff',
                true,
                '12345670'
            );
            Account departmentHeadContact = SampleDataFactory.createContact(
                'Joe',
                true,
                '123456781'
            );

            Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
                recordTypeIdSoftware,
                'title',
                'Draft',
                sampleContact1
            );
            SampleDataFactory.createDepartmentHead(
                disclosure,
                departmentHeadContact
            );
            SampleDataFactory.createDisclosureInternalFunding(
                disclosure,
                'Yes',
                '12345678',
                'Internal Funding 1'
            );
            SampleDataFactory.createCommercialInterest(disclosure);
            Software_Code_Disclosure__c softwareCodeDisclosure = SampleDataFactory.createSoftwareCode(
                'Sample Inventor Submitted Software Code',
                disclosure
            );
            Open_Source__c openSource = SampleDataFactory.createOpenSource(
                'Open Source for Inventor Submitted Software Code',
                null,
                softwareCodeDisclosure
            );
            System.assertEquals(
                openSource.Open_Source_Licensing__c,
                true,
                'Expecting OpenSource Licensing to be true'
            );
            SampleDataFactory.createThirdPartyCode(
                'Third Party Code',
                softwareCodeDisclosure
            );
            SampleDataFactory.createInventor(
                disclosure,
                true,
                existingContact1
            );

            // Department head approval, Can not directly go to Inventor Submitted
            disclosure.Status__c = 'Pending Department Approval';
            update disclosure;
        } catch (Exception ex) {
            System.assert(false, ex.getMessage());
        }
        Test.stopTest();
    }

    static testMethod void validateSoftwareDepartmentHeadNoOpenSource() {
        Test.startTest();
        try {
            Id recordTypeIdSoftware = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Software_Code_Disclosure')
                .getRecordTypeId();

            Account sampleContact1 = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account existingContact1 = SampleDataFactory.createContact(
                'Jeff',
                true,
                '12345670'
            );
            Account departmentHeadContact = SampleDataFactory.createContact(
                'Joe',
                true,
                '123456781'
            );

            Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
                recordTypeIdSoftware,
                'title',
                'Draft',
                sampleContact1
            );
            Department_Head__c noDeptHead = null; // Enforce Test intention

            SampleDataFactory.createDisclosureInternalFunding(
                disclosure,
                'Yes',
                '12345678',
                'Internal Funding 1'
            );
            SampleDataFactory.createCommercialInterest(disclosure);
            Software_Code_Disclosure__c softwareCodeDisclosure = SampleDataFactory.createSoftwareCode(
                'Sample Inventor Submitted Software Code',
                disclosure
            );
            Open_Source__c openSource = SampleDataFactory.createOpenSource(
                'Open Source for Inventor Submitted Software Code',
                null,
                softwareCodeDisclosure
            );
            openSource.Open_Source_Licensing__c = false;
            update openSource;
            System.assertEquals(
                openSource.Open_Source_Licensing__c,
                false,
                'Expecting OpenSource Licensing to be false'
            );

            SampleDataFactory.createThirdPartyCode(
                'Third Party Code',
                softwareCodeDisclosure
            );
            SampleDataFactory.createInventor(
                disclosure,
                true,
                existingContact1
            );

            // Department head approval, Can not directly go to Inventor Submitted
            disclosure.Status__c = 'Pending Department Approval';
            update disclosure;
        } catch (Exception ex) {
            System.assert(false, ex.getMessage());
        }
        Test.stopTest();
    }

    static testMethod void validateSoftwareDepartmentHeadFailure() {
        Test.startTest();
        try {
            Id recordTypeIdSoftware = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Software_Code_Disclosure')
                .getRecordTypeId();

            Account sampleContact1 = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account existingContact1 = SampleDataFactory.createContact(
                'Jeff',
                true,
                '12345670'
            );
            Account departmentHeadContact = SampleDataFactory.createContact(
                'Joe',
                true,
                '123456781'
            );

            Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
                recordTypeIdSoftware,
                'title',
                'Draft',
                sampleContact1
            );
            Department_Head__c noDeptHead = null; // Enforce Test intention

            SampleDataFactory.createDisclosureInternalFunding(
                disclosure,
                'Yes',
                '12345678',
                'Internal Funding 1'
            );
            SampleDataFactory.createCommercialInterest(disclosure);
            Software_Code_Disclosure__c softwareCodeDisclosure = SampleDataFactory.createSoftwareCode(
                'Sample Inventor Submitted Software Code',
                disclosure
            );
            Open_Source__c openSource = SampleDataFactory.createOpenSource(
                'Open Source for Inventor Submitted Software Code',
                null,
                softwareCodeDisclosure
            );
            System.assertEquals(
                openSource.Open_Source_Licensing__c,
                true,
                'Expecting OpenSource Licensing to be true'
            );

            SampleDataFactory.createThirdPartyCode(
                'Third Party Code',
                softwareCodeDisclosure
            );
            SampleDataFactory.createInventor(
                disclosure,
                true,
                existingContact1
            );

            // Department head approval, Can not directly go to Inventor Submitted
            disclosure.Status__c = 'Pending Department Approval';
            update disclosure;

            System.assert(false, 'Exception not thrown');
        } catch (Exception ex) {
            System.assertEquals(
                ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                true,
                ex.getMessage()
            );
        }
        Test.stopTest();
    }
}