force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/Disclosure_Action__c.object-meta.xml
<CustomObject>
    <label>Disclosure Action</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Action__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/recordTypes/Endorse_or_Delegate_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Endorse_or_Delegate_Disclosure</fullName>
    <active>true</active>
    <label>Endorse or Delegate Disclosure</label>
</RecordType>

force-app/main/default/classes/DepartmentHeadAfterHandler.cls
/**
 * Handler for Department_Head__c after triggers
 */

public with sharing class DepartmentHeadAfterHandler {
    private static Id recordTypeIdDelegate = Schema.SObjectType.Disclosure_Action__c.getRecordTypeInfosByDeveloperName()
        .get('Endorse_or_Delegate_Disclosure')
        .getRecordTypeId();

    /**
     * Handler method for Department_Head__c after insert operations
     * @param deptHeads List of Department_Head__c objects that were inserted
     */
    public static void insertDepartmentHead(
        List<Department_Head__c> deptHeads
    ) {
        // Create Contact Actions
        if (deptHeads != null) {
            initContactActions(deptHeads);
        }
    }

    /**
     * Handler method for Department_Head__c after update operations
     * @param deptHeads List of Department_Head__c objects that were updated
     */
    public static void updateDepartmentHead(
        List<Department_Head__c> deptHeads
    ) {
        if (deptHeads != null) {
            ContactActionHandler.completeDelegatedPendingContactActions(
                deptHeads
            );
        }
    }

    /**
     * Handler method for Department_Head__c after delete operations
     * @param deptHeads List of Department_Head__c objects that were deleted
     */
    public static void deleteDepartmentHead(
        List<Department_Head__c> deptHeads
    ) {
        if (deptHeads != null) {
            ContactActionHandler.cancelDeletedDeptHeadPendingContactActions(
                deptHeads
            );
        }
    }

    /**
     * Initialize Contact_Actions__c for Department Heads if the Dislcosure
     * Status is 'Pending Department Approval', normally when delegated
     * @param deptHeads List of Department_Head__c objects that need Contact_Actions__c created
     */
    private static void initContactActions(List<Department_Head__c> deptHeads) {
        Map<Account, Id> contactDisclosureMap = new Map<Account, Id>();

        for (Department_Head__c deptHead : deptHeads) {
            Disclosure__c disc = DisclosureRecordFetch.getDisclosureById(
                deptHead.Disclosure__c
            );
            if (disc.Status__c == 'Pending Department Approval') {
                contactDisclosureMap.put(
                    DisclosureRecordFetch.getContactById(deptHead.Contact__c),
                    deptHead.Disclosure__c
                );
            }
        }
        ContactActionHandler.initDisclosureContactAction(
            contactDisclosureMap,
            recordTypeIdDelegate
        );
    }
}