force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

force-app/main/default/objects/BioTang_Disclosure__c/BioTang_Disclosure__c.object-meta.xml
<CustomObject>
    <label>BioTang Disclosure</label>
    <nameField>
        <label>BioTang Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BioTang Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BioTang_Disclosure__c/fields/disclosure__c.field-meta.xml
<CustomField>
    <fullName>disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match BioTang Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BioTang_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>BioTang Disclosure</relationshipLabel>
    <relationshipName>BioTang_Disclosure</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BioTang_Disclosure__c/recordTypes/cellLine.recordType-meta.xml
<RecordType>
    <fullName>cellLine</fullName>
    <active>true</active>
    <label>Cell Line</label>
</RecordType>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>TLO Case Number</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/BioTang_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>BioTang_Disclosure</fullName>
    <active>true</active>
    <label>Biological and Tangible Property</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Disclosure__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DisclosureDaoTest.cls
@IsTest
public class DisclosureDaoTest {
    @TestSetup
    static void makeData() {
        System.debug('======makeData======');
        TestSetup.defaultConfiguration();
        ContactSampleDataFactory.createSampleContacts();

    }

    @isTest
    public static void DocumentSummaryTest() {
        String disclosureTitle = 'validateSummaryDocInfo';
        Disclosure__c disclosure = DisclosureSampleDataFactory.createDraftSoftwareDisclosureFullyPopulated(
            disclosureTitle,
            false
        );
        disclosure.Status__c = 'Pending Department Approval';
        update disclosure;

        disclosure.Status__c = 'Inventor Submitted';
        update disclosure;

        disclosure.Status__c = 'Approved';
        disclosure.Case_Number__c = '1234';
        update disclosure;

        Test.startTest();

        DisclosureSummaryWrapper disclosureWrapper = DisclosureDao.getDisclosureSummaryWrapperById(
            disclosure.Id
        );
        System.assertEquals(
            '1234',
            disclosureWrapper.disclosure.Case_Number__c,
            'Case Number not set'
        );

        Account submittingContact = [
            SELECT Id, FirstName, MiddleName, LastName
            FROM Account
            WHERE MitId__pc = '12345678'
        ];

        String fullName = ContactNameUtil.toFullName(
            submittingContact.FirstName,
            submittingContact.MiddleName,
            submittingContact.LastName,
            true
        );

        System.assertEquals(
            fullName,
            disclosureWrapper.submittingContactFullName,
            'Submitting Contact Fullname not set'
        );
        System.assert(
            !String.isEmpty(disclosureWrapper.submittedDate),
            'Submitted Date not set'
        );

        Test.stopTest();
    }

    @IsTest
    static void getInventorByIdTest() {
        System.debug('======getInventorByIdTest======');
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Id recordTypeIdSub = Schema.SObjectType.BioTang_Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('cellLine')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'CellLine-Joe',
            true,
            '900000001'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'Sample Draft Disclosure for CellLine',
            'Draft',
            cont
        );

        DisclosureInventor__c inventor1 = generateDocumentCommonTest(
            disclosure,
            recordTypeIdSub
        );

        Test.startTest();

        DisclosureInventorWrapper inventorWrapper = DisclosureDao.getInventorById(
            disclosure.Id,
            inventor1.Id
        );

        Test.stopTest();

        System.assertEquals(inventor1.Id, inventorWrapper.inventor.Id);
    }

    static DisclosureInventor__c generateDocumentCommonTest(
        Disclosure__c disclosure,
        Id recordTypeIdSub
    ) {
        System.debug('======generateDocumentCommonTest======');
        Account inventorContact1 = SampleDataFactory.createContact(
            'Inventor1',
            true,
            '900000002'
        );

        Account inventorContact2 = SampleDataFactory.createContact(
            'Inventor2',
            true,
            '900000003'
        );
        DisclosureInventor__c inventor1 = SampleDataFactory.createInventor(
            disclosure,
            true,
            inventorContact1
        );
        DisclosureInventor__c inventor2 = SampleDataFactory.createInventor(
            disclosure,
            false,
            inventorContact2
        );
        SampleDataFactory.addInventorExtraQuestion(inventor1);
        SampleDataFactory.addInventorExtraQuestion(inventor2);
        Account piContact = SampleDataFactory.createContact(
            'PI1',
            true,
            '900000006'
        );
        SampleDataFactory.createDisclosureExternalFunding(
            disclosure,
            'grantNum1',
            'AwardId1',
            piContact,
            'sponsor1'
        );
        SampleDataFactory.createDisclosureInternalFunding(
            disclosure,
            'Yes',
            'costObjectNumber1',
            'fundingDetails1'
        );
        Account dHeadContact = SampleDataFactory.createContact(
            'DepHead1',
            true,
            '900000007'
        );
        Department_Head__c departmentHead = SampleDataFactory.createDepartmentHead(
            disclosure,
            dHeadContact
        );

        Account shipper = SampleDataFactory.createContact(
            'Shipper',
            true,
            '900000004'
        );
        Account pointOfContact = SampleDataFactory.createContact(
            'PointOfContact',
            true,
            '900000005'
        );

        BioTang_Disclosure__c bioTangDisclosure = SampleDataFactory.createBioTang(
            'Test BioTang',
            disclosure,
            recordTypeIdSub,
            pointOfContact,
            shipper
        );

        SampleDataFactory.createLabMaterials(
            'Lab Material 1',
            bioTangDisclosure
        );

        SampleDataFactory.createLabMaterials(
            'Lab Material 2',
            bioTangDisclosure
        );

        String subTypeName = Schema.SObjectType.BioTang_Disclosure__c.getRecordTypeInfosById()
            .get(bioTangDisclosure.RecordTypeId)
            .getName();

        SampleDataFactory.createTechnicalDocument(
            ContentVersionClassification.PUBLICATION_MANUSCRIPTS,
            subTypeName + '1.docx',
            'docx',
            disclosure
        );

        SampleDataFactory.createTechnicalDocument(
            ContentVersionClassification.PUBLICATION_MANUSCRIPTS,
            subTypeName + '2.docx',
            'docx',
            disclosure
        );
        SampleDataFactory.createTechnicalDocument(
            ContentVersionClassification.TECHNICAL_DESCRIPTION,
            'Technical_Description_' + subTypeName + '1.docx',
            'docx',
            disclosure
        );
        SampleDataFactory.createTechnicalDocument(
            ContentVersionClassification.TECHNICAL_DESCRIPTION,
            'Technical_Description_' + subTypeName + '2.docx',
            'docx',
            disclosure
        );
        SampleDataFactory.createCommercialInterest(disclosure);

        return inventor1;
    }
}