force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Commercialization_Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Commercialization_Plan_Id__c</fullName>
    <label>Commercialization Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Seeking additional funding to further develop this invention</label>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>Marketing and/or furthering development of this invention to attract commercial
                    partners</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Developing and/or using this invention for internal purposes only</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Developing and/or preparing this invention with intent to commercialize ourselves</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Making available for distribution and/or licensing for research purposes only</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>No current commercialization plan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Election_Status__c.field-meta.xml
<CustomField>
    <fullName>Election_Status__c</fullName>
    <label>Election Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elect to Retain Title</fullName>
            </value>
            <value>
                <fullName>Does Not Retain Title</fullName>
            </value>
            <value>
                <fullName>Designated as Unpatented Biological Material or Research Tool</fullName>
            </value>
            <value>
                <fullName>Under Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/First_Commercial_Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>First_Commercial_Year_of_Sale__c</fullName>
    <label>First Commercial Year of Sale</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Docket_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Docket_Number__c</fullName>
    <description>Invention Docket Number</description>
    <label>Invention Docket Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Report_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Report_Number__c</fullName>
    <label>Invention Report Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_1__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_1__c</fullName>
    <label>Is US Manufacturing Required 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_2__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_2__c</fullName>
    <label>Is US Manufacturing Required 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_3__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_3__c</fullName>
    <label>Is US Manufacturing Required 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Latest_Stage_of_Development__c</fullName>
    <label>Latest Stage of Development</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Commercialized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Companies__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Companies__c</fullName>
    <label>New US Companies</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Jobs__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Jobs__c</fullName>
    <label>New US Jobs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Primary_Agency__c.field-meta.xml
<CustomField>
    <fullName>Primary_Agency__c</fullName>
    <label>Primary Agency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <label>Reporting Year</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Status__c</fullName>
    <description>Status</description>
    <label>Utilization Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Include for Utilization</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UtilizationReportDao.cls
public with sharing class UtilizationReportDao {

    public static UtilizationReportWrapper getUtilizationReportWrapperById(String utilReportIdStr) {
        UtilizationReportWrapper utilWrapper = new UtilizationReportWrapper();
        IEdisonService iEdisonService = new IEdisonService();
        Utilization_Report__c utilReport = [SELECT
            Id,
            Name,
            Invention_Report_Number__c,
            Invention_Docket_Number__c,
            Reporting_Year__c,
            Latest_Stage_of_Development__c,
            Utilization_Report_Status__c,
            First_Commercial_Year_of_Sale__c,
            Total_Income__c,
            New_Us_Jobs__c,
            New_Us_Companies__c,
            Notes__c,
            Commercialization_Plan_Id__c,
            toLabel(Commercialization_Plan_Id__c) Commercialization_Plan,
            Is_US_Manufacturing_Required_1__c,
            Is_US_Manufacturing_Required_2__c,
            Is_US_Manufacturing_Required_3__c,
            Election_Status__c,
            Primary_Agency__c,
            Error_Messages__c
        FROM Utilization_Report__c
        WHERE Id = :utilReportIdStr LIMIT 1];
        IEdisonUtilizationSearchResponse existingReport = iEdisonService.searchUtilization(1, 0, utilReport.Invention_Report_Number__c, '', new List<String>(), Integer.valueOf(utilReport.Reporting_Year__c), '');
        utilWrapper.utilizationReport = utilReport;
        if (existingReport.utilizations != null && !existingReport.utilizations.isEmpty()) {
            utilWrapper.utilization = existingReport.utilizations[0];
            utilWrapper.helperIsUSManufacturingRequired1 = utilWrapper.utilization.isUSManufacturingRequired1 == 'Y' ? true: null ;
        }

        String strJSON = JSON.serialize(utilWrapper);
        System.debug(strJSON);
        return utilWrapper;
    }

}