force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_Exclusive_Optionee_Name__c.field-meta.xml
<CustomField>
    <fullName>Forrester_Exclusive_Optionee_Name__c</fullName>
    <label>Forrester Exclusive Licenses Options</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_First_Commercial_Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>Forrester_First_Commercial_Year_of_Sale__c</fullName>
    <label>Forrester First Commercial Year of Sale</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Forrester_Latest_Stage_of_Development__c</fullName>
    <label>Forrester Latest Stage of Development</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_Non_Exclusive_Optionee_Name__c.field-meta.xml
<CustomField>
    <fullName>Forrester_Non_Exclusive_Optionee_Name__c</fullName>
    <label>Forrester Non-Exclusive Licenses Options</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_Small_Business_Optionee_Name__c.field-meta.xml
<CustomField>
    <fullName>Forrester_Small_Business_Optionee_Name__c</fullName>
    <label>Forrester Small Business Licenses</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Forrester_Summarized_Agreement_Income__c.field-meta.xml
<CustomField>
    <fullName>Forrester_Summarized_Agreement_Income__c</fullName>
    <label>Summarized Agreement Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Status__c</fullName>
    <description>Status</description>
    <label>Utilization Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Include for Utilization</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UtilizationForresterDataTriggerHandler.cls
public with sharing class UtilizationForresterDataTriggerHandler {
    public static void onBeforeUpdate(
            List<Utilization_Report__c> utilizationReports,
            Map<Id, Utilization_Report__c> oldUtilizationReports
    ) {
        for (Utilization_Report__c currentReport : utilizationReports ) {
            Utilization_Report__c oldReport = (oldUtilizationReports != null &&
                oldUtilizationReports.get(currentReport.Id) != null)
                    ? oldUtilizationReports.get(currentReport.Id)
                    : null;
            checkAndUpdateStatus(currentReport, oldReport); //, updateList);
        }
    }

    private static void checkAndUpdateStatus(Utilization_Report__c current, Utilization_Report__c old) { // , List<Utilization_Report__c> updateList) {
        // System.debug('Begin: checkAndUpdateStatus');
        // System.debug(JSON.serializePretty(old));
        // System.debug(JSON.serializePretty(current));
        Boolean dataChanged = false;

        if ((current.Forrester_Latest_Stage_of_Development__c ?? '') != (old.Forrester_Latest_Stage_of_Development__c ?? '')) {
            dataChanged = true;
        }

        if ((current.Forrester_First_Commercial_Year_of_Sale__c ?? '') != (old.Forrester_First_Commercial_Year_of_Sale__c ?? '')) {
            dataChanged = true;
        }

        if ( current.Forrester_Summarized_Agreement_Income__c <> old.Forrester_Summarized_Agreement_Income__c) {
            dataChanged = true;
        }
        
        if (!String.isBlank(old.Forrester_Exclusive_Optionee_Name__c)) {
            if ((current.Forrester_Exclusive_Optionee_Name__c ?? '') != (old.Forrester_Exclusive_Optionee_Name__c ?? '')) {
                dataChanged = true;
            }
        }
        if (!String.isBlank(old.Forrester_Non_Exclusive_Optionee_Name__c)) {
            if ((current.Forrester_Non_Exclusive_Optionee_Name__c ?? '') != (old.Forrester_Non_Exclusive_Optionee_Name__c ?? '')) {
                dataChanged = true;
            }
        }
        if (!String.isBlank(old.Forrester_Small_Business_Optionee_Name__c)) {
            if ((current.Forrester_Small_Business_Optionee_Name__c ?? '') != (old.Forrester_Small_Business_Optionee_Name__c ?? '')) {
                dataChanged = true;
            }
        }
        
        if (dataChanged) {
            if (
            current.Utilization_Report_Status__c == 'Completed' ||
            current.Utilization_Report_Status__c == 'Error') {
                current.Utilization_Report_Status__c = 'New';
                System.debug('Updating utilization report status to New:' + String.valueOf(current.Id));
            }
        }
        //System.debug('End: checkAndUpdateStatus');
    }
}