force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Case_RecId__c.field-meta.xml
<CustomField>
    <fullName>Case_RecId__c</fullName>
    <label>Case</label>
    <length>24</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>Utilization Reports</relationshipLabel>
    <relationshipName>Utilization_Reports_Case</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Report_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Report_Number__c</fullName>
    <label>Invention Report Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Status__c</fullName>
    <description>Status</description>
    <label>Utilization Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Include for Utilization</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report_Config__c/Utilization_Report_Config__c.object-meta.xml
<CustomObject>
    <label>Utilization Reports FY Config</label>
    <nameField>
        <displayFormat>URC-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports FY Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EdisonInventionSearchJobTest.cls
@isTest
public with sharing class EdisonInventionSearchJobTest {
    
    @TestSetup
    static void setupTestData() {
        TestSetup.defaultConfiguration();
    }
    
    @isTest
    public static void EdisonInventionSearch() {
        IEdisonApiMock iEdisonApiMock = new IEdisonApiMock();
        Test.setMock(HttpCalloutMock.class, iEdisonApiMock);

        Utilization_Report_Config__c config1 = SampleDataFactory.createUtilizationReportConfig('2023', '2022-07-01', '2023-06-28', 'LIC;OPT;BY-AGT');
        Utilization_Report_Config__c config2 = SampleDataFactory.createUtilizationReportConfig('2024', '2023-07-01', '2024-06-28', 'LIC;OPT;BY-AGT');
        Utilization_Report__c utilizationReport1 = SampleDataFactory.createUtilizationReport('1', '1574340', 2024, 'New');
        Utilization_Report__c utilizationReport2 = SampleDataFactory.createUtilizationReport('2', '1574341', 2024, 'Include for Utilization');
        Utilization_Report__c utilizationReport3 = SampleDataFactory.createUtilizationReportWithError('3', '1574342', 2024);


        Test.startTest();
            System.enqueueJob(new EdisonInventionSearchJob(false), 0);
        Test.stopTest();

        // ASSERT
        Utilization_Report__c utilizationReport4 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '1' LIMIT 1];
        Utilization_Report__c utilizationReport5 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '2' LIMIT 1];
        Utilization_Report__c utilizationReport6 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '3' LIMIT 1];
        Utilization_Report__c utilizationReport7 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '0820102-15-0070' LIMIT 1];
        System.assert(utilizationReport4.Invention_Report_Number__c == '1');
        System.assert(utilizationReport5.Invention_Report_Number__c == '2');
        System.assert(utilizationReport6.Invention_Report_Number__c == '3');
        System.assert(utilizationReport7.Invention_Report_Number__c == '0820102-15-0070');
    }
    @isTest
    public static void EdisonInventionSearchErrorItems() {
        IEdisonApiMock iEdisonApiMock = new IEdisonApiMock();
        Test.setMock(HttpCalloutMock.class, iEdisonApiMock);

        Utilization_Report_Config__c config1 = SampleDataFactory.createUtilizationReportConfig('2023', '2022-07-01', '2023-06-28', 'LIC;OPT;BY-AGT');
        Utilization_Report_Config__c config2 = SampleDataFactory.createUtilizationReportConfig('2024', '2023-07-01', '2024-06-28', 'LIC;OPT;BY-AGT');
        Utilization_Report__c utilizationReport1 = SampleDataFactory.createUtilizationReport('1', '1574340', 2024, 'New');
        Utilization_Report__c utilizationReport2 = SampleDataFactory.createUtilizationReportWithError('2', '1574342', 2024);
        Utilization_Report__c utilizationReport3 = SampleDataFactory.createUtilizationReportWithError('0820102-15-0070', '11353', 2024);


        Test.startTest();
            System.enqueueJob(new EdisonInventionSearchJob(true), 0);
        Test.stopTest();

        // ASSERT
        Utilization_Report__c utilizationReport4 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c, Case_RecId__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '1' LIMIT 1];
        Utilization_Report__c utilizationReport5 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c, Case_RecId__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '2' LIMIT 1];
        Utilization_Report__c utilizationReport6 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c, Case_RecId__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '0820102-15-0070' LIMIT 1];
        System.assert(utilizationReport4.Invention_Report_Number__c == '1');
        System.assert(utilizationReport5.Invention_Report_Number__c == '2');
        System.assert(utilizationReport6.Invention_Report_Number__c == '0820102-15-0070');
        System.assert(utilizationReport6.Case_RecId__c == '10856');
    }

}