force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Commercialization_Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Commercialization_Plan_Id__c</fullName>
    <label>Commercialization Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Seeking additional funding to further develop this invention</label>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>Marketing and/or furthering development of this invention to attract commercial
                    partners</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Developing and/or using this invention for internal purposes only</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Developing and/or preparing this invention with intent to commercialize ourselves</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Making available for distribution and/or licensing for research purposes only</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>No current commercialization plan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/First_Commercial_Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>First_Commercial_Year_of_Sale__c</fullName>
    <label>First Commercial Year of Sale</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Report_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Report_Number__c</fullName>
    <label>Invention Report Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_1__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_1__c</fullName>
    <label>Is US Manufacturing Required 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_2__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_2__c</fullName>
    <label>Is US Manufacturing Required 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_3__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_3__c</fullName>
    <label>Is US Manufacturing Required 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Latest_Stage_of_Development__c</fullName>
    <label>Latest Stage of Development</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Commercialized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Companies__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Companies__c</fullName>
    <label>New US Companies</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Jobs__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Jobs__c</fullName>
    <label>New US Jobs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <label>Reporting Year</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Status__c</fullName>
    <description>Status</description>
    <label>Utilization Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Include for Utilization</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubmitUtilizationReportJobTest.cls
@isTest
public class SubmitUtilizationReportJobTest {
    @TestSetup
    static void setup() {
        TestSetup.defaultConfiguration();
        TestSetup.defaultDocTemplatesConfiguration();
    }


    @isTest
    public static void submitUtilizationReports() {
        IEdisonApiMock iEdisonApiMock = new IEdisonApiMock();
        Test.setMock(HttpCalloutMock.class, iEdisonApiMock);

        Utilization_Report__c utilizationReport1 = SampleDataFactory.createUtilizationReport('1', '1574340', 2024, 'New');
        Utilization_Report__c utilizationReport2 = SampleDataFactory.createUtilizationReport('2', '1574341', 2024, 'In Progress');
        Utilization_Report__c utilizationReport3 = SampleDataFactory.createUtilizationReport('3', '1574343', 2024, 'Include for Utilization');
        Utilization_Report__c utilizationReport4 = SampleDataFactory.createUtilizationReport('4', '1574344', 2024, 'In Progress');
      
        List<Utilization_Report__c> testList = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c FROM Utilization_Report__c];
        System.debug('testList0:' + JSON.serialize(testList[0], true));
        System.debug('testList1:' + JSON.serialize(testList[1], true));
        System.debug('testList3:' + JSON.serialize(testList[2], true));
        System.debug('testList4:' + JSON.serialize(testList[3], true));


        Utilization_Report__c testItem = [SELECT 
            Id, 
            Name, 
            Invention_Report_Number__c,
            Reporting_Year__c,
            Latest_Stage_of_Development__c,
            Utilization_Report_Status__c,
            First_Commercial_Year_of_Sale__c,
            Total_Income__c,
            New_Us_Jobs__c,
            New_Us_Companies__c,
            Notes__c,
            Commercialization_Plan_Id__c,
            Is_US_Manufacturing_Required_1__c,
            Is_US_Manufacturing_Required_2__c,
            Is_US_Manufacturing_Required_3__c
        FROM Utilization_Report__c 
        WHERE Invention_Report_Number__c = '2' LIMIT 1];

        System.debug('testItem:' + JSON.serialize(testItem, true));

        Test.startTest();
        Id batchprocessid = Database.executeBatch(
            new SubmitUtilizationReportJob(),
            2
        );

        AsyncApexJob aaj = [
            SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors
            FROM AsyncApexJob
            WHERE ID = :batchprocessid
        ];
        System.debug('aaj:' + JSON.serialize(aaj, true));
        System.assert(aaj != null);
        Test.stopTest();
        Utilization_Report__c resultReport1 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '1' LIMIT 1];
        Utilization_Report__c resultReport2 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '2' LIMIT 1];
        Utilization_Report__c resultReport3 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '3' LIMIT 1];
        Utilization_Report__c resultReport4 = [SELECT ID, Name, Invention_Report_Number__c, Utilization_Report_Status__c FROM Utilization_Report__c WHERE Invention_Report_Number__c = '4' LIMIT 1];
        System.assert(resultReport1.Utilization_Report_Status__c == 'New');
        System.assert(resultReport2.Utilization_Report_Status__c == 'Completed');
        System.assert(resultReport3.Utilization_Report_Status__c == 'Include for Utilization');
        System.assert(resultReport4.Utilization_Report_Status__c == 'Completed');
    }
}