force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Status__c</fullName>
    <description>Status</description>
    <label>Utilization Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Include for Utilization</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Submitted_Date__c</fullName>
    <label>Utilization Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateUtilizationReportJob.cls
public class CreateUtilizationReportJob implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query =
            'SELECT Id, Utilization_Report_Status__c, Error_Messages__c From Utilization_Report__c where Utilization_Report_Status__c = \'Include for Utilization\' or Utilization_Report_Status__c = \'In Progress\'';
        return Database.getQueryLocator(query);
    }

    public void execute(
        Database.BatchableContext bc,
        List<Utilization_Report__c> scope
    ) {
        System.debug('--+--' + scope.size());

        IEdisonService iEdisonService = new IEdisonService();
        List<Utilization_Report__c> updateList = new List<Utilization_Report__c>();
        for (Utilization_Report__c utilReport : scope) {
            Utilization_Report__c current = [SELECT 
                Id, 
                Utilization_Report_Status__c,
                Error_Messages__c
            FROM Utilization_Report__c
            WHERE Id = :utilReport.Id LIMIT 1];
            // Verify that the status is still 'Include for Utilization'
            // Retry submission of reports that is still 'in Progress' 
            if (current.Utilization_Report_Status__c == 'Include for Utilization' || current.Utilization_Report_Status__c == 'In Progress') {
                updateList.add(current);
                current.Utilization_Submitted_Date__c = Date.today();
                current.Utilization_Report_Status__c = 'In Progress';
                current.Error_Messages__c = '';
            }

            System.debug('---+Batch+---');
        }

        if (!updateList.isEmpty()) {
            update updateList;
        }
    }

    public void finish(Database.BatchableContext bc) {
        SubmitUtilizationReportJob submitReportJob = new SubmitUtilizationReportJob();
        Database.executeBatch(submitReportJob, 20); 
    }
 }