force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Commercialization_Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Commercialization_Plan_Id__c</fullName>
    <label>Commercialization Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Seeking additional funding to further develop this invention</label>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>Marketing and/or furthering development of this invention to attract commercial
                    partners</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Developing and/or using this invention for internal purposes only</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Developing and/or preparing this invention with intent to commercialize ourselves</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Making available for distribution and/or licensing for research purposes only</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>No current commercialization plan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/First_Commercial_Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>First_Commercial_Year_of_Sale__c</fullName>
    <label>First Commercial Year of Sale</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Docket_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Docket_Number__c</fullName>
    <description>Invention Docket Number</description>
    <label>Invention Docket Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Report_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Report_Number__c</fullName>
    <label>Invention Report Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_1__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_1__c</fullName>
    <label>Is US Manufacturing Required 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_2__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_2__c</fullName>
    <label>Is US Manufacturing Required 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_3__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_3__c</fullName>
    <label>Is US Manufacturing Required 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Latest_Stage_of_Development__c</fullName>
    <label>Latest Stage of Development</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Commercialized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Companies__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Companies__c</fullName>
    <label>New US Companies</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Jobs__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Jobs__c</fullName>
    <label>New US Jobs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <label>Reporting Year</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Status__c</fullName>
    <description>Status</description>
    <label>Utilization Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Include for Utilization</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Title__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Title__c</fullName>
    <formula>Name &amp; &quot; - &quot; &amp; Invention_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Utilization Report Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SubmitUtilizationReportJob.cls
public class SubmitUtilizationReportJob implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query =
            'SELECT Id, Invention_Report_Number__c From Utilization_Report__c where Utilization_Report_Status__c = \'In Progress\'';
        return Database.getQueryLocator(query);
    }

    public void execute(
        Database.BatchableContext bc,
        List<Utilization_Report__c> scope
    ) {
        System.debug('--+--' + scope.size());

        IEdisonService edisonService = new IEdisonService();
        List<Utilization_Report__c> updateList = new List<Utilization_Report__c>();
        List<ContentVersion> insertContentVersions = new List<ContentVersion>();
        List<Exception> exceptions =  new List<Exception>();
        try {
            for (Utilization_Report__c utilReport : scope) {
                Utilization_Report__c current = [SELECT 
                    Id, 
                    Name,
                    Invention_Docket_Number__c,
                    Invention_Report_Number__c,
                    Reporting_Year__c,
                    Latest_Stage_of_Development__c,
                    Utilization_Report_Status__c,
                    Utilization_Report_Title__c,
                    First_Commercial_Year_of_Sale__c,
                    Total_Income__c,
                    New_Us_Jobs__c,
                    New_Us_Companies__c,
                    Notes__c,
                    Commercialization_Plan_Id__c,
                    Is_US_Manufacturing_Required_1__c,
                    Is_US_Manufacturing_Required_2__c,
                    Is_US_Manufacturing_Required_3__c,
                    Error_Messages__c
                FROM Utilization_Report__c
                WHERE Id = :utilReport.Id LIMIT 1];
                if (current.Utilization_Report_Status__c == 'In Progress') {
                    updateList.add(current);
                    try {
                        IEdisonUtilizationSearchResponse existingReport = edisonService.searchUtilization(1, 0, current.Invention_Report_Number__c, '', new List<String>(), integer.valueof(current.Reporting_Year__c), '');
                        Map<Integer, Object> response;
                        if (existingReport.totalRecords > 0) {
                            response = edisonService.updateUtilization(current.Id);
                        } else {
                            response = edisonService.createUtilization(current.Id);
                        }

                        if (response.get(400) != null) {
                            current.Utilization_Report_Status__c = 'Error';
                            current.Error_Messages__c = JSON.serialize(response.get(400), true);
                        } else {
                            current.Utilization_Report_Status__c = 'Completed';
                            edisonService.mapUtilizationToReport(current, (IEdisonUtilizationResponse)response.get(201));
                            // Submission is Successful, generate the document
                            ContentVersion utilizationDocument = IEdisonService.generateUtilizationDocument(current);
                            insertContentVersions.add(utilizationDocument);
                        }
                    } catch (exception ex) {
                        String message = ex.getMessage();
                        if ((ex.getTypeName() == 'System.CalloutException') &&  (message.contains('401') || message.contains('403') || message.contains('500') || message.contains('502'))) {
                            // Keep report 'In Progress' and retry submission on next scheduled run 
                            System.debug('inner:-' + ex.getMessage());
                            exceptions.add(ex);
                        } else {
                            current.Utilization_Report_Status__c = 'Error';    
                        }
                        IEdisonErrorResponse errorResponse = IEdisonService.FormulateError(ex);
                        current.Error_Messages__c = JSON.serialize(errorResponse, true);
                    }
                }

                System.debug('---+Batch+---');
            }

            for (Exception e : exceptions) {
                HandleLogException.logException(e);
            }

            if (!updateList.isEmpty()) {
                update updateList;
            }
            if (!insertContentVersions.isEmpty()) {
                insert insertContentVersions;
            }
        } catch (Exception e) {
            System.debug(e.getMessage());
            HandleLogException.logException(e);
        }
    }

    public void finish(Database.BatchableContext bc) {
    }

 }