force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <description>Container object for external table</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement__c/fields/ExternalAgreement__c.field-meta.xml
<CustomField>
    <fullName>ExternalAgreement__c</fullName>
    <label>ExternalAgreement</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_CRDR__c/Case_CRDR__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE_CRDR)</description>
    <label>CRDR</label>
    <nameField>
        <label>Case CRDR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRDRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR__c/fields/Case_Recid__c.field-meta.xml
<CustomField>
    <fullName>Case_Recid__c</fullName>
    <label>Case Recid</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <description>Shirley Document types</description>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/CRDR.recordType-meta.xml
<RecordType>
    <fullName>CRDR</fullName>
    <active>true</active>
    <description>CRDR Worksheets, Correspondence and CRDR Finacial Documents</description>
    <label>CRDR</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Disclosure</fullName>
    <active>true</active>
    <description>Disclosure Record Type</description>
    <label>Disclosure</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/DisclosureInventor.recordType-meta.xml
<RecordType>
    <fullName>DisclosureInventor</fullName>
    <active>true</active>
    <label>DisclosureInventor</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <label>Note</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Other_Agreement.recordType-meta.xml
<RecordType>
    <fullName>Other_Agreement</fullName>
    <active>true</active>
    <description>Agreements ossociated with a Case</description>
    <label>Other Agreement</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Sponsor_Agreement.recordType-meta.xml
<RecordType>
    <fullName>Sponsor_Agreement</fullName>
    <active>true</active>
    <description>External Sponsor Agreements</description>
    <label>Sponsor Agreement</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/TLO_Agreement.recordType-meta.xml
<RecordType>
    <fullName>TLO_Agreement</fullName>
    <active>true</active>
    <description>TLO Agreement Document Type</description>
    <label>TLO Agreement</label>
</RecordType>

force-app/main/default/objects/Forrester_Case__x/Forrester_Case__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_VIEW</externalName>
    <label>Case</label>
    <pluralLabel>Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case RecId</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/DISCLOSURE_TITLE__c.field-meta.xml
<CustomField>
    <fullName>DISCLOSURE_TITLE__c</fullName>
    <description>DISCLOSURE_TITLE</description>
    <externalDeveloperName>DISCLOSURE_TITLE</externalDeveloperName>
    <label>Disclosure Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_AGREEMENT_VIEW__x/Forrester_SHIR_AGREEMENT_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_AGREEMENT_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_AGREEMENT_VIEW</externalName>
    <label>Agreement</label>
    <pluralLabel>Agreements</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_AGREEMENT_VIEW__x/fields/AGREEMENT_RECID__c.field-meta.xml
<CustomField>
    <fullName>AGREEMENT_RECID__c</fullName>
    <description>AGREEMENT_RECID</description>
    <externalDeveloperName>AGREEMENT_RECID</externalDeveloperName>
    <label>Agreement Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_AGREEMENT_VIEW__x/fields/AGREEMENT_STATUS__c.field-meta.xml
<CustomField>
    <fullName>AGREEMENT_STATUS__c</fullName>
    <description>AGREEMENT_STATUS</description>
    <externalDeveloperName>AGREEMENT_STATUS</externalDeveloperName>
    <label>Status Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x/Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CASE_CRDR_AGREEMENT_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_CRDR_AGREEMENT_VIEW</externalName>
    <label>CRDR Case Agreement</label>
    <pluralLabel>CRDR Case Agreements</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x/fields/AGREEMENT_RECID__c.field-meta.xml
<CustomField>
    <fullName>AGREEMENT_RECID__c</fullName>
    <description>AGREEMENT_RECID</description>
    <externalDeveloperName>AGREEMENT_RECID</externalDeveloperName>
    <label>Agreement</label>
    <length>24</length>
    <referenceTo>Forrester_SHIR_AGREEMENT_VIEW__x</referenceTo>
    <relationshipLabel>CRDR Case Agreements</relationshipLabel>
    <relationshipName>CRDR_Case_Agreements</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x/fields/AGREEMENT_STATUS__c.field-meta.xml
<CustomField>
    <fullName>AGREEMENT_STATUS__c</fullName>
    <description>AGREEMENT_STATUS</description>
    <externalDeveloperName>AGREEMENT_STATUS</externalDeveloperName>
    <label>Agreement Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x/fields/AGREEMENT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>AGREEMENT_TYPE__c</fullName>
    <description>AGREEMENT_TYPE</description>
    <externalDeveloperName>AGREEMENT_TYPE</externalDeveloperName>
    <label>Type Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CASE_CRDR_RECID</label>
    <length>24</length>
    <referenceTo>Forrester_SHIR_CRDR_VIEW__x</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>CRDR_Case_Agreements</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>CASE_RECID</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x/fields/COMPANY_NAME__c.field-meta.xml
<CustomField>
    <fullName>COMPANY_NAME__c</fullName>
    <description>COMPANY_NAME</description>
    <externalDeveloperName>COMPANY_NAME</externalDeveloperName>
    <label>Licensee</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CRDR_RELATED_CRDRS_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CRDR_RELATED_CRDRS_VIEW</externalName>
    <label>Related CRDR</label>
    <pluralLabel>Related CRDRs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/AGREEMENT_RECID__c.field-meta.xml
<CustomField>
    <fullName>AGREEMENT_RECID__c</fullName>
    <description>AGREEMENT_RECID</description>
    <externalDeveloperName>AGREEMENT_RECID</externalDeveloperName>
    <label>Agreement</label>
    <length>12</length>
    <referenceTo>Forrester_SHIR_AGREEMENT_VIEW__x</referenceTo>
    <relationshipLabel>Related CRDRs</relationshipLabel>
    <relationshipName>Related_CRDRs</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CRDR</label>
    <length>12</length>
    <referenceTo>Forrester_SHIR_CRDR_VIEW__x</referenceTo>
    <relationshipLabel>Related CRDRs</relationshipLabel>
    <relationshipName>Related_CRDRs</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case</label>
    <length>12</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>Related CRDRs</relationshipLabel>
    <relationshipName>Related_CRDRs</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Contract Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/RELATED_CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>RELATED_CASE_CRDR_RECID__c</fullName>
    <description>RELATED_CASE_CRDR_RECID</description>
    <externalDeveloperName>RELATED_CASE_CRDR_RECID</externalDeveloperName>
    <label>Related CRDR</label>
    <length>12</length>
    <referenceTo>Forrester_SHIR_CRDR_VIEW__x</referenceTo>
    <relationshipLabel>DO_NOT_USE</relationshipLabel>
    <relationshipName>Related_CRDRs_Child</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/Forrester_SHIR_CRDR_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CRDR_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CRDR_VIEW</externalName>
    <label>CRDR</label>
    <pluralLabel>CRDRs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CRDR RecId</label>
    <length>24</length>
    <referenceTargetField>Case_CRDR__c.ExternalCaseCRDRId__c</referenceTargetField>
    <referenceTo>Case_CRDR__c</referenceTo>
    <relationshipLabel>CRDRs</relationshipLabel>
    <relationshipName>CRDRs</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case</label>
    <length>24</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>CRDRs</relationshipLabel>
    <relationshipName>CRDRs</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/DISCLOSURE_TITLE__c.field-meta.xml
<CustomField>
    <fullName>DISCLOSURE_TITLE__c</fullName>
    <description>DISCLOSURE_TITLE</description>
    <externalDeveloperName>DISCLOSURE_TITLE</externalDeveloperName>
    <label>Case Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TLO_Case__c/TLO_Case__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE)</description>
    <label>TLO Case</label>
    <nameField>
        <label>TLO Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TLO Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TLO_Case__c/fields/ExternalCaseId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseId__c</fullName>
    <description>RecId from external object</description>
    <label>ExternalCaseId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GlobalRecordSearchController.cls
/**
* @description: Apex class to search CRDR records and create files against these CRDR records
**/
public class GlobalRecordSearchController {
    
    @AuraEnabled(cacheable=true)
    public static List<ObjectWrapper> getContentDocumentLinks(String contentDocumentId, String recordTypeId,String currentRecordId,String entitySubType) {
        List<ObjectWrapper> result = new List<ObjectWrapper>();
        List<Object> objectList = new List<Object>();
        try {
            String objectName = 'ContentVersion';
            String typeName = Schema.getGlobalDescribe().get(objectName).getDescribe().getRecordTypeInfosById().get(recordTypeId)?.getDeveloperName();
            
            // Query ContentDocumentLinks based on ContentDocumentId
            List<ContentDocumentLink> contentDocLinks = [
                SELECT ContentDocumentId, LinkedEntityId
                FROM ContentDocumentLink
                WHERE ContentDocumentId = :contentDocumentId
            ];
            
            // Create a map to store ContentDocumentId to its list of ContentDocumentLinks
            Map<String, List<ContentDocumentLink>> contentDocumentIdToLinkedEntityId = new Map<String, List<ContentDocumentLink>>();
            
            // Set to store LinkedEntityIds
            Set<Id> linkedEntityIds = new Set<Id>();
            
            // Iterate through ContentDocumentLinks and populate the map and set
            for (ContentDocumentLink link : contentDocLinks) {
                String sObjName = link.LinkedEntityId.getSObjectType().getDescribe().getName();
                
                if(sObjName == 'Agreement__c' || sObjName == 'TLO_Case__c'){
                    
                    if (!contentDocumentIdToLinkedEntityId.containsKey(link.ContentDocumentId)) {
                        contentDocumentIdToLinkedEntityId.put(link.ContentDocumentId, new List<ContentDocumentLink>());
                    }
                    contentDocumentIdToLinkedEntityId.get(link.ContentDocumentId).add(link);
                    
                    // Add LinkedEntityId to the set
                    linkedEntityIds.add(link.LinkedEntityId);

                }
            }
            
            // Query Agreements based on LinkedEntityIds
            List<Agreement__c> agreementsList = [
                SELECT Id, Name, ExternalAgreement__c
                FROM Agreement__c
                WHERE Id IN :linkedEntityIds
            ];
            
            // Map ExternalAgreement__c to Agreement__c record
            Map<String, Agreement__c> externalAgreementToAgreementMap = new Map<String, Agreement__c>();
            for (Agreement__c agreement : agreementsList) {
                externalAgreementToAgreementMap.put(agreement.ExternalAgreement__c, agreement);
            }
            
            // Query TLO_Case__c based on LinkedEntityIds
            List<TLO_Case__c> caseList = [
                SELECT Id, ExternalCaseId__c
                FROM TLO_Case__c
                WHERE Id IN :linkedEntityIds
            ];
            
            // Map ExternalCaseId__c to TLO_Case__c record
            Map<String, TLO_Case__c> externalCaseIdToCaseMap = new Map<String, TLO_Case__c>();
            for (TLO_Case__c caseRecord : caseList) {
                externalCaseIdToCaseMap.put(caseRecord.ExternalCaseId__c, caseRecord);
            }
            
            // Retrieve objectList using fetchRelatedToRecords method
            if(typeName == 'CRDR' || typeName == 'Case' || typeName == 'Sponsor_Agreement' || typeName == 'Other_Agreement'){
                system.debug('externalCaseIdToCaseMap.keySet() case==> '+externalCaseIdToCaseMap.keySet());
                objectList = fetchForresterCaseRecords(externalCaseIdToCaseMap.keySet());
 
            }else{
                objectList = fetchRelatedToRecords(recordTypeId, currentRecordId, entitySubType);  
            }
            
            // Iterate over objectList to find matching agreements or cases and retrieve ContentDocumentLink count
            for (Object obj : objectList) {
                if (obj instanceof ObjectWrapper) {
                    ObjectWrapper objWrapper = (ObjectWrapper) obj;

                    if (objWrapper.value != null) {
                        String externalId = objWrapper.value;
                        Integer linkCount = 0;
                        String description = objWrapper.description;
                        String recordId = objWrapper.recordId;
                        String label = objWrapper.label;

                        if (externalAgreementToAgreementMap.containsKey(externalId)) {
                            Agreement__c agreement = externalAgreementToAgreementMap.get(externalId);
                            // Retrieve ContentDocumentLink count for the specific Agreement__c
                            if (contentDocumentIdToLinkedEntityId.containsKey(contentDocumentId)) {
                                linkCount = contentDocumentIdToLinkedEntityId.get(contentDocumentId).size();
                            }
                            result.add(createObjectWrapper(recordId, label, description, externalId, linkCount));
                        } else if (externalCaseIdToCaseMap.containsKey(externalId)) {
                            
                            // Retrieve ContentDocumentLink count for the specific TLO_Case__c
                            if (contentDocumentIdToLinkedEntityId.containsKey(contentDocumentId)) {
                                linkCount = contentDocumentIdToLinkedEntityId.get(contentDocumentId).size();
                            }
                            result.add(createObjectWrapper(recordId, label, description, externalId, linkCount));
                        }
                    }
                }
            }
            
        } catch (Exception ex) {
            throw new AuraHandledException('Error: ' + ex.getMessage());
        }

        return result;
    }
    
    /**
* @description: Fetches Forrester_Case__x records based on given Ids and returns a list of ObjectWrapper instances.
* @param caseIds Set<String> containing the Ids of Forrester_Case__x records.
* @return List<ObjectWrapper> containing ObjectWrapper instances.
**/
    private static List<ObjectWrapper> fetchForresterCaseRecords(Set<String> caseIds) {
        List<ObjectWrapper> objWrapperList = new List<ObjectWrapper>();
        for (Forrester_Case__x caseRecord : [SELECT Id, CASE_RECID__c, CONTRACT_CASE_NUM__c, DISCLOSURE_TITLE__c FROM Forrester_Case__x WHERE CASE_RECID__c IN :caseIds]) {
            ObjectWrapper wrapper = new ObjectWrapper();
            wrapper.recordId = caseRecord.Id;
            wrapper.label = caseRecord.CONTRACT_CASE_NUM__c;
            wrapper.value = caseRecord.CASE_RECID__c;
            wrapper.description = caseRecord.DISCLOSURE_TITLE__c;
            wrapper.icon = ''; 
            wrapper.variant = ''; 
            objWrapperList.add(wrapper);
        }

        return objWrapperList;
    }
    // Helper method to create ObjectWrapper instance
    private static ObjectWrapper createObjectWrapper(String recordId, String label, String description, String value, Integer linkCount) {
        ObjectWrapper wrapper = new ObjectWrapper();
        wrapper.recordId = recordId;
        wrapper.label = label;
        wrapper.description = description;
        wrapper.value = value;
        wrapper.icon = ''; 
        wrapper.variant = ''; 
        wrapper.linkCount = linkCount;
        return wrapper;
    }
    
    
    /**
* @description: Searches for CRDR records based on the provided search term and selected record type.
* @param selectedSubEntityType The data subtype searched for.
* @param crdrRecordId The recordId of TLO Objects to search for.
* @param selectedRecordType The selected record type.
* @return List of ObjectWrapper containing search results.
**/
    @AuraEnabled(cacheable = true)
    public static List<ObjectWrapper> fetchRelatedToRecords(String selectedRecordType, String crdrRecordId, String selectedSubEntityType) {
        List<ObjectWrapper> wrapperList = new List<ObjectWrapper>();
        
        try {
            String objectName = 'ContentVersion';
            String typeName = Schema.getGlobalDescribe().get(objectName).getDescribe().getRecordTypeInfosById().get(selectedRecordType)?.getDeveloperName();
            if (typeName != null) {
                List<SObject> records = new List<SObject>();
                // Construct SOSL query for each record type
                switch on typeName {
                    when 'CRDR' {
                        // SOQL query for CRDR records
                        records = searchCRDRRecords(crdrRecordId);
                        
                        // records = searchCaseRecords(searchTerm, crdrRecordId);
                    }
                    when 'Case' {
                        // SOQL query for Case records
                        records = searchCaseRecords(crdrRecordId);
                    }
                    when 'Sponsor_Agreement' {
                        // SOQL query for Case records
                        records = searchCaseRecords(crdrRecordId);
                    }
                    when 'Other_Agreement' {
                        // SOQL query for Case records
                        records = searchCaseRecords(crdrRecordId);
                    }
                    when 'TLO_Agreement' {
                        // SOQL query for TLO_Agreement records
                        records = searchTLOAgreementRecords(crdrRecordId, selectedSubEntityType);
                    }
                }
                
                // Process search results
                for (SObject record : records) {
                    
                    String icon = 'standard:approval';
                    String label = '';
                    String value = '';
                    String description = '';
                    String variant = 'success';
                    if (typeName == 'CRDR') {
                        icon = 'custom:custom5';
                        label = (String) record.get('CONTRACT_CASE_NUM__c');
                        value = (String) record.get('CASE_RECID__c');
                        description = (String) record.get('DISCLOSURE_TITLE__c');
                    }
                    if (typeName == 'CASE') {
                        icon = 'custom:custom5';
                        label = (String) record.get('CONTRACT_CASE_NUM__c');
                        value = (String) record.get('CASE_RECID__c');
                        description = (String) record.get('DISCLOSURE_TITLE__c');
                    }
                    
                    if (typeName == 'TLO_Agreement') {
                        String agreementStatus = (String) record.get('AGREEMENT_STATUS__c');
                        icon ='standard:approval';
                        variant ='success';
                        label = (String) record.get('AGREEMENT_RECID__c');
                        value = (String) record.get('AGREEMENT_RECID__c');
                        description = (String) record.get('COMPANY_NAME__c');
                    }
                    
                    if (typeName == 'Sponsor_Agreement') {
                        icon = 'standard:record';
                        label = (String) record.get('CONTRACT_CASE_NUM__c');
                        value = (String) record.get('CASE_RECID__c');
                        description = (String) record.get('DISCLOSURE_TITLE__c');
                    }
                    
                    if (typeName == 'Other_Agreement') {
                        icon = 'standard:network_contract';
                        label = (String) record.get('CONTRACT_CASE_NUM__c');
                        value = (String) record.get('CASE_RECID__c');
                        description = (String) record.get('DISCLOSURE_TITLE__c');
                    }
                    
                    ObjectWrapper objWrapper = new ObjectWrapper();
                    objWrapper.recordId = (String) record.get('Id');
                    objWrapper.label = label;
                    objWrapper.value = value;
                    objWrapper.description = description;
                    objWrapper.icon = icon;
                    objWrapper.variant = variant;
                    
                    wrapperList.add(objWrapper);
                }
            }
        } catch (Exception ex) {
            throw new AuraHandledException('Error : ' + ex.getMessage());
        }
        return wrapperList;
    }

    /**
* @description: This is used to get the default CRDR .
* @return default crdr record which will not be removed
**/
    @AuraEnabled(cacheable = true)
    public static List<ObjectWrapper> getDefaultCrdr(String selectedRecordDeveloperName, String crdrRecordId) {
        List<ObjectWrapper> wrapperList = new List<ObjectWrapper>();

        try {
            if (crdrRecordId != null){
                String caseRecId = null;
                if (selectedRecordDeveloperName == 'CRDR' || selectedRecordDeveloperName == 'Case' || selectedRecordDeveloperName == 'Other_Agreement' || selectedRecordDeveloperName == 'Sponsor_Agreement' ) {
                    List<Forrester_SHIR_CRDR_VIEW__x> records =[SELECT Id, CASE_CRDR_RECID__c, CONTRACT_CASE_NUM__c, CASE_RECID__c, DISCLOSURE_TITLE__c FROM Forrester_SHIR_CRDR_VIEW__x WHERE Id =: crdrRecordId LIMIT 1];
                    if (!records.isEmpty()){
                        caseRecId = records[0].CASE_RECID__c ;
                    }
                } else {
                    return wrapperList;
                }

                if( caseRecId != null){
                    List<Forrester_Case__x> caseRecords =[SELECT Id, CASE_RECID__c, CONTRACT_CASE_NUM__c, DISCLOSURE_TITLE__c FROM Forrester_Case__x WHERE CASE_RECID__c =: caseRecId LIMIT 1];

                    ObjectWrapper objWrapper = new ObjectWrapper();
                    objWrapper.recordId = caseRecords[0].Id;
                    objWrapper.label = caseRecords[0].CONTRACT_CASE_NUM__c;
                    objWrapper.value = caseRecords[0].CASE_RECID__c;
                    objWrapper.description = caseRecords[0].DISCLOSURE_TITLE__c;
                    objWrapper.icon ='custom:custom5';
                    objWrapper.variant ='success';
                    wrapperList.add(objWrapper);
                }
            }
        }catch (Exception ex) {
            throw new AuraHandledException('Error : ' + ex.getMessage());
        }
        return wrapperList;
    }

    // Helper method to search CRDR records
    private static List<SObject> searchCRDRRecords(String crdrRecordId) {
        List<SObject> records = new List<SObject>();
        Set<String> crdrIds = new Set<String>();

        // Fetch related CRDR records based on crdrRecordId
        for (Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x fcrdr : [SELECT Id, RELATED_CASE_CRDR_RECID__r.Id FROM Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x WHERE CASE_CRDR_RECID__r.Id = :crdrRecordId]) {
            crdrIds.add(fcrdr.RELATED_CASE_CRDR_RECID__r.Id);
        }

        // Build SOQL query for CRDR records based on search term and numeric check
        Integer batchSize = 50;
        String soqlQuery = 'SELECT Id, CASE_RECID__c, CASE_CRDR_RECID__c, CONTRACT_CASE_NUM__c, DISCLOSURE_TITLE__c FROM Forrester_SHIR_CRDR_VIEW__x WHERE Id IN :batchFilter ';
        // Execute SOQL query
        return ExternalObjectRepository.fetchExternalQueryByExternalRecIds(new List<String>(crdrIds), soqlQuery, batchSize);

    }

    // Helper method to search Case records
    public static List<SObject> searchCaseRecords(String crdrRecordId) {
        List<SObject> records = new List<SObject>();
        Set<String> caseIds = new Set<String>();

        // Fetch related Case records based on crdrRecordId
        for (Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x fcrdr : [SELECT Id, CASE_RECID__r.Id, CASE_RECID__c FROM Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x WHERE CASE_CRDR_RECID__r.Id = :crdrRecordId]) {
            caseIds.add(fcrdr.CASE_RECID__r.Id);
        }

        // Build SOQL query for Case records based on search term and numeric check
        String soqlQuery = 'SELECT Id, CASE_RECID__c, CONTRACT_CASE_NUM__c, DISCLOSURE_TITLE__c FROM Forrester_Case__x WHERE Id IN :caseIds';
        // Execute SOQL query
        records = Database.query(soqlQuery);
        return records;
    }

    // Helper method to search TLO_Agreement records
    private static List<SObject> searchTLOAgreementRecords(String crdrRecordId, String selectedSubEntityType) {
        List<SObject> records = new List<SObject>();
        Set<String> agreementIds = new Set<String>();

        // Fetch related Agreement records based on crdrRecordId and selectedSubEntityType
        for (Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x fcrdr : [SELECT Id, CASE_CRDR_RECID__r.Id, AGREEMENT_RECID__r.Id FROM Forrester_SHIR_CASE_CRDR_AGREEMENT_VI__x WHERE CASE_CRDR_RECID__r.Id = :crdrRecordId]) {
            agreementIds.add(fcrdr.AGREEMENT_RECID__r.Id);
        }

        // Build SOQL query for TLO_Agreement records based on search term, numeric check, and selectedSubEntityType.
        Integer batchSize = 50;
        String soqlQuery = 'SELECT Id, AGREEMENT_RECID__c, AGREEMENT_TYPE__c, COMPANY_NAME__c, AGREEMENT_STATUS__c FROM Forrester_SHIR_AGREEMENT_VIEW__x WHERE Id IN :batchFilter AND AGREEMENT_TYPE__c = \'' + selectedSubEntityType + '\'';
        // Execute SOQL query
        return ExternalObjectRepository.fetchExternalQueryByExternalRecIds(new List<String>(agreementIds), soqlQuery, batchSize);

    }

    /**
* @description: Uploads files against selected CRDR records.
* @param selectedItems List of selected items.
* @param filedata Serialized file data.
* @param selectedEntitySubType Selected EntitySubType.
* @param selectedRecordType Selected record type.
* @param selectedDocumentTypeOptions Selected document type options.
* @return Upload status.
**/
    @AuraEnabled
    public static String uploadFiles(List<ObjectWrapper> selectedItems, String filedata, String selectedEntitySubType, String selectedRecordType, String selectedDocumentTypeOptions) {
        try {
            if (String.isBlank(filedata)) {
                return 'File data is blank.';
            }

            List<FileDataWP> files = (List<FileDataWP>) JSON.deserialize(filedata, List<FileDataWP>.class);
            if (files.isEmpty()) {
                return 'No files found to upload.';
            }

            Set<String> externalIds = new Set<String>();
            for (ObjectWrapper selectedItem : selectedItems) {
                if (selectedItem.value != null) {
                    String value = selectedItem.value;
                    externalIds.add(value);
                }
            }

            List<ContentVersion> cvList = new List<ContentVersion>();
            for (FileDataWP file : files) {
                ContentVersion conVer = new ContentVersion();
                conVer.Document_Classification__c = selectedDocumentTypeOptions;
                conVer.ContentLocation = 'S';
                conVer.VersionData = EncodingUtil.base64Decode(file.fileContent);
                conVer.Title = file.fileName;
                conVer.RecordTypeId = selectedRecordType;
                conVer.Entity_Sub_Type__c = selectedEntitySubType;
                conVer.PathOnClient = file.fileName ;
                cvList.add(conVer);
            }

            List<SObject> existingContainers = new List<SObject>();
            String objectName = 'ContentVersion';

            if (selectedRecordType != null) {
                String typeName = Schema.getGlobalDescribe().get(objectName).getDescribe().getRecordTypeInfosById().get(selectedRecordType)?.getDeveloperName();
                if (typeName == 'CRDR') {
                    // CRDRs will only upload to Cases and never to CRDRs
                    existingContainers = [SELECT Id, ExternalCaseId__c FROM TLO_Case__c WHERE ExternalCaseId__c IN :externalIds];
                } else if (typeName == 'TLO_Agreement') {
                    existingContainers = [Select Id, ExternalAgreement__c from Agreement__c where ExternalAgreement__c IN :externalIds];
                }else if(typeName == 'Case'){
                    existingContainers = [SELECT Id, ExternalCaseId__c FROM TLO_Case__c WHERE ExternalCaseId__c IN :externalIds];
                }else if(typeName == 'Other_Agreement'){
                    existingContainers = [SELECT Id, ExternalCaseId__c FROM TLO_Case__c WHERE ExternalCaseId__c IN :externalIds];
                }else if(typeName == 'Sponsor_Agreement'){
                    existingContainers = [SELECT Id, ExternalCaseId__c FROM TLO_Case__c WHERE ExternalCaseId__c IN :externalIds];
                }
            }

            if (existingContainers != null && !existingContainers.isEmpty()) {
                insert cvList;
                List<ContentDocumentLink> cdList = new List<ContentDocumentLink>();
                for (ContentVersion cv : [SELECT ContentDocumentId FROM ContentVersion WHERE Id IN :cvList]) {
                    for (SObject container : existingContainers) {
                        ContentDocumentLink conDocLink = new ContentDocumentLink();
                        conDocLink.LinkedEntityId = container.Id;
                        conDocLink.ContentDocumentId = cv.ContentDocumentId;
                        conDocLink.Visibility = 'AllUsers';
                        conDocLink.shareType = 'I';
                        cdList.add(conDocLink);
                    }
                }
                insert cdList;
            } else {
                return 'Found no existing Record to link the file(s) with.';
            }
            return 'success';
        } catch (Exception ex) {
            return ex.getMessage();
        }
    }

    @AuraEnabled
    public static String uploadRelatedDocuments(String filedata, String recordId, String contentVersionRecordTypeId, String agreementDataSubTypeValue, String agreementRecId, String selectedDocumentTypeOptions) {
        try {
            if (String.isBlank(filedata)) {
                return 'File data is blank.';
            }

            List<FileDataWP> files = (List<FileDataWP>) JSON.deserialize(filedata, List<FileDataWP>.class);
            if (files.isEmpty()) {
                return 'No files found to upload.';
            }

            List<ContentVersion> cvList = new List<ContentVersion>();
            for (FileDataWP file : files) {
                ContentVersion conVer = new ContentVersion();
                conVer.Document_Classification__c = selectedDocumentTypeOptions;
                conVer.ContentLocation = 'S';
                conVer.VersionData = EncodingUtil.base64Decode(file.fileContent);
                conVer.Title = file.fileName;
                conVer.RecordTypeId = contentVersionRecordTypeId;
                conVer.Entity_Sub_Type__c = agreementDataSubTypeValue;
                conVer.PathOnClient = file.fileName ;
                cvList.add(conVer);
            }

            List<SObject> existingContainers = new List<SObject>();
            String objectName = 'ContentVersion';

            if (agreementRecId != null) {
                String typeName = Schema.getGlobalDescribe().get(objectName).getDescribe().getRecordTypeInfosById().get(contentVersionRecordTypeId)?.getDeveloperName();
                if (typeName == 'TLO_Agreement') {
                    existingContainers = [Select Id, ExternalAgreement__c from Agreement__c where ExternalAgreement__c =:agreementRecId];
                }
            }

            if (existingContainers != null && !existingContainers.isEmpty()) {
                insert cvList; // We dont want Orphan documents
                List<ContentDocumentLink> cdList = new List<ContentDocumentLink>();
                for (ContentVersion cv : [SELECT ContentDocumentId FROM ContentVersion WHERE Id IN :cvList]) {
                    for (SObject container : existingContainers) {
                        ContentDocumentLink conDocLink = new ContentDocumentLink();
                        conDocLink.LinkedEntityId = container.Id;
                        conDocLink.ContentDocumentId = cv.ContentDocumentId;
                        conDocLink.Visibility = 'AllUsers';
                        conDocLink.shareType = 'I';
                        cdList.add(conDocLink);
                    }
                }
                insert cdList;
            } else {
                return 'Found no existing Record to link the file(s) with.';
            }
            return 'success';
        } catch (Exception ex) {
            return ex.getMessage();
        }
    }

    /**
* @description: This is used to get all recordtypes on case object except the master .
* @return all recordtypes on Content version as picklist except the master recordtype.
**/
    @AuraEnabled(cacheable=true)
    public static List<RecordTypeInfoWrapper> getContentVersionRecordTypes() {
        List<RecordTypeInfoWrapper> recordTypes = new List<RecordTypeInfoWrapper>();

        // Get all record types of ContentVersion
        Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
        Schema.SObjectType contentType = globalDescribe.get('ContentVersion');
        Schema.DescribeSObjectResult describeResult = contentType.getDescribe();

        List<Schema.RecordTypeInfo> recordTypeInfos = describeResult.getRecordTypeInfos();

        for(Schema.RecordTypeInfo recordTypeInfo : recordTypeInfos) {
            // Exclude the master record type
            if (!recordTypeInfo.isMaster() && recordTypeInfo.getDeveloperName() != 'Disclosure' && recordTypeInfo.getDeveloperName() != 'DisclosureInventor' && recordTypeInfo.getDeveloperName() != 'Note') {
                recordTypes.add(new RecordTypeInfoWrapper(recordTypeInfo));
            }
        }

        return recordTypes;
    }

    // Wrapper class for RecordTypeInfo
    public class RecordTypeInfoWrapper {
        @AuraEnabled
        public String recordTypeId { get; set; }
        @AuraEnabled
        public String name { get; set; }
        @AuraEnabled
        public String developerName { get; set; }

        public RecordTypeInfoWrapper(Schema.RecordTypeInfo recordTypeInfo) {
            this.recordTypeId = recordTypeInfo.getRecordTypeId();
            this.name = recordTypeInfo.getName();
            this.developerName = recordTypeInfo.getDeveloperName();
        }
    }
    public class ObjectWrapper {
        @AuraEnabled public String recordId { get; set; }
        @AuraEnabled public String label { get; set; }
        @AuraEnabled public String value { get; set; }
        @AuraEnabled public String description { get; set; }
        @AuraEnabled public String icon { get; set; }
        @AuraEnabled public String variant { get; set; }
        @AuraEnabled public Integer linkCount { get; set; }

    }

    public class FileDataWP {
        public String fileName;
        public String fileContent;
    }
}