force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <description>Container object for external table</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement__c/fields/ExternalAgreement__c.field-meta.xml
<CustomField>
    <fullName>ExternalAgreement__c</fullName>
    <label>ExternalAgreement</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Entity_Recid__c.field-meta.xml
<CustomField>
    <fullName>Entity_Recid__c</fullName>
    <description>External Reference to Forrester Oracle RecIds for multiple tables. eg: Case table PK case_recid. Agreement table PK agreement_recid. The Record type with the classification need to be considered</description>
    <label>Entity Recid</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_AGREEMENT_VIEW__x/Forrester_SHIR_AGREEMENT_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_AGREEMENT_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_AGREEMENT_VIEW</externalName>
    <label>Agreement</label>
    <pluralLabel>Agreements</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Document_Link__c/Log_Document_Link__c.object-meta.xml
<CustomObject>
    <label>Log Document Link Message</label>
    <nameField>
        <displayFormat>LCV-{000000}</displayFormat>
        <label>Log Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Document Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AgreementDocumentLinkProcessor.cls
public with sharing class AgreementDocumentLinkProcessor extends DocumentLinkProcessor {


    protected override void createDocumentLink(List<ContentVersion> contentVersions) {
        if(contentVersions.isEmpty()) {
            return;
        }
        List<ContentVersion> contentVersionUpdateList = new List<ContentVersion>();
        List<ContentDocumentLink> contentDocumentLinkInsertList = new List<ContentDocumentLink>();
        List<Log_Document_Link__c> logs = new List<Log_Document_Link__c>();

        Map<Id, ContentVersion> cvMap = new Map<Id, ContentVersion>(contentVersions);
        Map<Id, FileNameDefinition> fileDefMap = new Map<Id, FileNameDefinition>();
        Map<Id, List<Forrester_SHIR_AGREEMENT_VIEW__x> > externalViewMap = new Map<Id, List<Forrester_SHIR_AGREEMENT_VIEW__x> >();

        // Parse all PathOnClient values
        for(ContentVersion contentVersion : contentVersions) {
            FileNameDefinition parsed = parsePathOnClient(contentVersion.PathOnClient, contentVersion.Entity_RecId__c);
            if(parsed == null) {
                contentVersion.Entity_RecId__c = '-1' ; // will allow retry
                contentVersionUpdateList.add(contentVersion);
                logs.add(getLogDocumentLinkInstance(contentVersion.Id, contentVersion.PathOnClient,'Parsing-PathOnClient', 'Unable to parse'));
                continue;
            }
            fileDefMap.put(contentVersion.Id, parsed);
        }

        //Build the SObject query filter sets
        Set<String> agreementNumbers = new Set<String>();
        for(ContentVersion contentVersion : contentVersions) {
            FileNameDefinition parsed = fileDefMap.get(contentVersion.Id);
            if(parsed == null) {
                continue;
            }
            agreementNumbers.add(parsed.agreementNumber);
        }

        // Bulk query SObject
        List<Agreement__c> agreementBulkList = [Select Id, ExternalAgreement__c from Agreement__c where ExternalAgreement__c =:agreementNumbers ];
        Map<String, Agreement__c> agreementLookup = new Map<String, Agreement__c>();
        for(Agreement__c agreement : agreementBulkList) {
            agreementLookup.put(agreement.ExternalAgreement__c, agreement);
        }

        for(ContentVersion contentVersion : contentVersions) {
            FileNameDefinition parsed = fileDefMap.get(contentVersion.Id);
            if(parsed == null) {
                continue;
            }

            Agreement__c agreement = agreementLookup.get(parsed.agreementNumber);
            if (agreement == null) {
                contentVersion.Entity_RecId__c = '-1' ; // will allow retry
                contentVersionUpdateList.add(contentVersion);

                logs.add(getLogDocumentLinkInstance(contentVersion.Id, contentVersion.PathOnClient, 'Container-Object-Query', 'No rows found for ExternalAgreement__c ' + parsed.agreementNumber ));
                continue;
            }


            ContentDocumentLink conDocLink = new ContentDocumentLink();
            conDocLink.LinkedEntityId = agreement.Id;
            conDocLink.ContentDocumentId = contentVersion.ContentDocumentId;
            conDocLink.ShareType = 'I';
            conDocLink.Visibility = 'AllUsers';
            contentDocumentLinkInsertList.add(conDocLink);
            String entityRecId = String.valueOf(agreement.ExternalAgreement__c);

            contentVersion.Entity_RecId__c = entityRecId;
            Boolean updateClassification = !isImageSiloDocument(contentVersion);
            if(parsed.classification != null && updateClassification) {
                contentVersion.Document_Classification__c =  parsed.classification;
            }
            contentVersionUpdateList.add(contentVersion);
        }
        if(!contentDocumentLinkInsertList.isEmpty()) {
            insert contentDocumentLinkInsertList;
        }
        if(!contentVersionUpdateList.isEmpty()) {
            update contentVersionUpdateList;
        }
        if(!logs.isEmpty()) {
            insert logs;
        }
    }

    Boolean isImageSiloDocument(ContentVersion cv) {
        // Do not update the Classification if the data was uploaded from ImageSilo Source
        if (cv.TagCsv != null && cv.TagCsv != null && cv.TagCsv.contains('ImageSilo')) { // Will revisit this when importing NewSilo Documents
            return true;
        }
        return false;
    }


    @TestVisible
    protected override FileNameDefinition parsePathOnClient(String pathOnClient, String entityRecId) {
        // We have a Entity RecId, use the value.
        if (entityRecId != '-1') {
            FileNameDefinition parsed = new FileNameDefinition();
            parsed.agreementNumber = StringUtils.removeNonNumericCharacters(entityRecId); // example '4912302.b'
            parsed.classification = getClassification(pathOnClient) ;
            return parsed;
        }

        List<Pattern> patterns = new List<Pattern>();
        patterns.add(Pattern.compile('(?i).*[\\/\\\\]([0-9]+)-[\\[].*pdf'));
        patterns.add(Pattern.compile('(?i).*[\\/\\\\]([0-9]+).pdf'));
        patterns.add(Pattern.compile('(?i).*[\\/\\\\]([0-9]+)[ ]*[-]+[^\\[].*pdf'));

        for(Pattern myPattern : patterns) {
            Matcher myMatcher = myPattern.matcher(pathOnClient);

            if (myMatcher.matches()) {
                FileNameDefinition parsed = new FileNameDefinition();
                parsed.agreementNumber = myMatcher.group(1) ;
                parsed.classification = null;
                return parsed;
            }
        }
        return null;
    }
   @TestVisible
   private String getClassification(String pathOnClient) {
        Map<Pattern, String> patterns = new Map<Pattern, String>();
        patterns.put(Pattern.compile('(?i).*[\\/](License).*'), ContentVersionClassification.ORIGINAL_DOCUMENT);

        for(Pattern myPattern : patterns.keySet()) {
            Matcher myMatcher = myPattern.matcher(pathOnClient);
            if (myMatcher.matches()) {
                return patterns.get(myPattern);
            }
        }
        return null;
   }


}