force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Invention_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Invention_Disclosure</fullName>
    <active>true</active>
    <label>Invention</label>
</RecordType>

force-app/main/default/objects/Invention_Disclosure__c/Invention_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Invention Disclosure</label>
    <nameField>
        <label>Invention Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invention_Disclosure__c/fields/Anticipated_Publication_Comment__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Publication_Comment__c</fullName>
    <label>Anticipated Publication Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Invention Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Invention_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Invention Disclosures</relationshipLabel>
    <relationshipName>Invention_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Anticipated_Publication__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Anticipated_Publication__c</fullName>
    <label>Anticipated Publication Disclosure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Oral_Presentation__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Oral_Presentation__c</fullName>
    <label>Oral Presentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Published_Or_Disclosed__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Published_Or_Disclosed__c</fullName>
    <label>Published Or Disclosed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Oral_Disclosure_Date__c.field-meta.xml
<CustomField>
    <fullName>Oral_Disclosure_Date__c</fullName>
    <label>Oral Disclosure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InventionDisclosureTriggerHandlerTest.cls
@isTest
public class InventionDisclosureTriggerHandlerTest {

    @isTest
    public static void createInventionDisclosure() {
        Id recordTypeIdInventionDisclosure = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName().get('Invention_Disclosure').getRecordTypeId();	        
        Account cont = SampleDataFactory.createContact('Donald',true, '12345678');	        
        Disclosure__c d = SampleDataFactory.createDisclosure(recordTypeIdInventionDisclosure, 'Draft for Invention Disclosure', 'Draft', cont);
        system.debug('from test class:'+d.Id);
        try {
            Invention_Disclosure__c idis = new Invention_Disclosure__c();
            idis.Disclosure__c = d.Id;
            idis.Name = 'Test';
            idis.Disclosure_Published_Or_Disclosed__c = 'Yes';
            idis.Disclosure_Anticipated_Publication__c = 'Yes';
            idis.Disclosure_Oral_Presentation__c = 'Yes';
            idis.Disclosure_Anticipated_Publication__c = 'Yes';
            insert idis;
            
            Invention_Disclosure__c idis1 = new Invention_Disclosure__c();
            idis1.Disclosure__c = d.Id;
            idis1.Name = 'Test2';
            idis1.Disclosure_Published_Or_Disclosed__c = 'No';
            insert idis1;
            
            update idis;
            
        }catch(Exception ex) {
            String msg = ex.getMessage();
            system.debug('from test class 2:'+msg);
            system.assert(msg.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }
    }

    @isTest
    public static void updateInventionDisclosure() {
        Id recordTypeIdInventionDisclosure = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName().get('Invention_Disclosure').getRecordTypeId();	        
        Account cont = SampleDataFactory.createContact('Donald',true, '12345678');	        
        Disclosure__c d = SampleDataFactory.createDisclosure(recordTypeIdInventionDisclosure, 'Draft for Invention Disclosure', 'Draft', cont);
        system.debug('from test class:'+d.Id);
        try {
            Invention_Disclosure__c idis = new Invention_Disclosure__c();
            idis.Disclosure__c = d.Id;
            idis.Name = 'Test';
            idis.Disclosure_Published_Or_Disclosed__c = 'Yes';
            idis.Disclosure_Anticipated_Publication__c = 'No';
            idis.Disclosure_Oral_Presentation__c = 'No';
            idis.Disclosure_Anticipated_Publication__c = 'No';
            insert idis;
            
            Invention_Disclosure__c idis1 = new Invention_Disclosure__c();
            idis1.Disclosure__c = d.Id;
            idis1.Name = 'Test2';
            idis1.Disclosure_Published_Or_Disclosed__c = 'No';
            idis1.Disclosure_Anticipated_Publication__c = 'No';
            idis1.Disclosure_Oral_Presentation__c = 'No';
            idis1.Disclosure_Anticipated_Publication__c = 'No';
            idis1.Anticipated_Publication_Comment__c = '1';
            idis1.Oral_Disclosure_Date__c = date.today();
            insert idis1;
            d.Status__c = 'Approved';
            update d;
            update idis1;
            List<Invention_Disclosure__c> inList = new List<Invention_Disclosure__c>();
            inList.add(idis1);
            inList.add(idis);
        }catch(Exception ex) {
            String msg = ex.getMessage();
            system.debug('from test class 2:'+msg);
            system.assert(msg.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }
    }
}