force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/Disclosure_Audit_Event__c/Disclosure_Audit_Event__c.object-meta.xml
<CustomObject>
    <label>Disclosure Audit Event</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Activity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Audit Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Audit_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Longer descriptive text, possibly including HTML tags, e.g. “John Doe signed the disclosure”</description>
    <inlineHelpText>Longer descriptive text, possibly including HTML tags, e.g. “John Doe signed the disclosure”</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Disclosure_Audit_Event__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Audit Events</relationshipLabel>
    <relationshipName>Disclosure_Audit_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Audit_Event__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>Date-time field stating when exactly the event was recorded in Shirley</description>
    <inlineHelpText>Date-time field stating when exactly the event was recorded in Shirley</inlineHelpText>
    <label>Event Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Disclosure_Audit_Event__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Brief title of the event, e.g. “Signed”</description>
    <inlineHelpText>Brief title of the event, e.g. “Signed”</inlineHelpText>
    <label>Subject</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure_Audit_Event__c/recordTypes/PendingDepartmentApproval.recordType-meta.xml
<RecordType>
    <fullName>PendingDepartmentApproval</fullName>
    <active>true</active>
    <description>The Disclosure is pending for approval from a Department Head</description>
    <label>PendingDepartmentApproval</label>
</RecordType>

force-app/main/default/objects/Disclosure_Audit_Event__c/recordTypes/Signing.recordType-meta.xml
<RecordType>
    <fullName>Signing</fullName>
    <active>true</active>
    <description>A user has signed the disclosure</description>
    <label>Signing</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/DocuSign_Recipient_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Recipient_StatusCode__c</fullName>
    <description>This field will hold the value of DocuSign&apos;s Status Code for this Inventor. (That will be used to map back to Signed flag) 
DocuSign events are send for all inventors on a Disclosure at the same time. Needing to ensure status code is mapped correctly for each.</description>
    <label>DocuSign Recipient StatusCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Disclosure_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Disclosure_Date__c</fullName>
    <label>Signed Disclosure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Variables__c.field-meta.xml
<CustomField>
    <fullName>Variables__c</fullName>
    <label>Variables</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DisclosureInventorSignedTest.cls
@isTest
public with sharing class DisclosureInventorSignedTest {
    @isTest
    static void testAuditTrailCreatedForInventorSigned() {
        TestSetup.defaultConfiguration();
        // String title = 'givenCopyrightAsInventor_whenSubmitteForDeptHeadEndorsement_thenAuditForEndorseRequestExists';
        // Disclosure__c disclosure = DisclosureSampleDataFactory.createCopyrightDisclosureWithDeptHeadAsInventor(title , false);

        // Constants
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        // Contacts
        Account contact1 = SampleDataFactory.createContact(
            'Bob',
            true,
            '123456781'
        );
        Account contact2 = SampleDataFactory.createContact(
            'Donald',
            true,
            '123654'
        );

        // Disclosure
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Test Inventor Actions on Signing',
            'Draft',
            contact1
        );

        // Inventors On Disclosure
        DisclosureInventor__c inventor1 = SampleDataFactory.createInventor(
            disclosure,
            true,
            contact1
        );
        DisclosureInventor__c inventor2 = SampleDataFactory.createInventor(
            disclosure,
            true,
            contact2
        );

        //testing
        inventor1.DocuSign_Recipient_StatusCode__c = 'Completed';
        inventor1.Signed_Disclosure_Date__c = Date.newInstance(2023, 3, 13);
        update inventor1;

        DisclosureInventor__c disInv = [
            SELECT
                Id,
                DocuSign_Recipient_StatusCode__c,
                Signed_Status__c,
                Signed_Disclosure_Date__c,
                Contact__r.Name,
                Disclosure__r.Name,
                Contact__r.PersonEmail,
                Disclosure__r.Name__c,
                Disclosure__c
            FROM DisclosureInventor__c
            WHERE Id = :inventor1.Id
        ];

        System.assert(disInv != null, 'Unable to find Disclosure Inventor');
        System.assert(
            disInv.DocuSign_Recipient_StatusCode__c == 'Completed',
            'disInv.DocuSign_Recipient_StatusCode__c should have been \'Completed\''
        );
        System.assert(
            disInv.Signed_Status__c == 'Yes',
            'disInv.Signed_Status__c should have been \'Yes\''
        );
        System.assert(
            disInv.Signed_Disclosure_Date__c != null,
            'disInv.Signed_Disclosure_Date__c should have been set'
        );

        Disclosure__c disclosureToTest = [
            SELECT Id
            FROM Disclosure__c
            WHERE Name__c = 'Test Inventor Actions on Signing'
            LIMIT 1
        ];
        List<Disclosure_Audit_Event__c> inventorAuditTrail = [
            SELECT
                Id,
                Description__c,
                Disclosure__c,
                Event_Date__c,
                Subject__c,
                RecordTypeId
            FROM Disclosure_Audit_Event__c
            WHERE Disclosure__c = :disclosureToTest.Id
        ];

        System.assertEquals(
            2,
            inventorAuditTrail.size(),
            'inventorAuditTrail.size() should be 2 at this point'
        );

        Disclosure_Audit_Event__c auditEntry = inventorAuditTrail[1];
        String expected =
            '<a href="/lightning/r/Account/' +
            disInv.Contact__r.Id +
            '/view" target="_self">' +
            disInv.Contact__r.Name +
            '</a> ' +
            label.Disclosure_DAE_Description_Signed;
        Id recordTypeSignedId = Schema.SObjectType.Disclosure_Audit_Event__c.getRecordTypeInfosByDeveloperName()
            .get('Signing')
            .getRecordTypeId();
        System.assertEquals(
            expected,
            auditEntry.Description__c,
            'Description__c not what was expected'
        );
        System.assertEquals(
            disclosureToTest.Id,
            auditEntry.Disclosure__c,
            'Disclosure__c should be equal to the Disclosure we currently testing'
        );
        System.assertEquals(
            Label.Disclosure_DAE_Subject_Signed,
            auditEntry.Subject__c,
            'Subject__c should be value from label Disclosure_DAE_Subject_Signed'
        );
        System.assertEquals(
            recordTypeSignedId,
            auditEntry.RecordTypeId,
            'RecordTypeId needs to be for PendingDepartmentApproval'
        );
    }

    @isTest
    static void testEachInventorSigned() {
        TestSetup.defaultConfiguration();
        // Constants
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        // Contacts
        Account submittingContact = SampleDataFactory.createContact(
            'Bob',
            true,
            '123456781'
        );
        Account coInventorContact = SampleDataFactory.createContact(
            'Donald',
            true,
            '1236541'
        );
        // Disclosure
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Test Inventor Actions on Signing',
            'Draft',
            submittingContact
        );
        // Inventors On Disclosure
        DisclosureInventor__c submittingInventor = SampleDataFactory.createInventor(
            disclosure,
            true,
            submittingContact
        );
        DisclosureInventor__c coInventor = SampleDataFactory.createInventor(
            disclosure,
            true,
            coInventorContact
        );

        Test.startTest();
        submittingInventor.Signed_Status__c = 'Yes';
        submittingInventor.DocuSign_Recipient_StatusCode__c = 'Completed';
        submittingInventor.Signed_Disclosure_Date__c = Date.newInstance(
            2023,
            3,
            13
        );
        update submittingInventor;

        List<Notification__c> notification = [
            SELECT Id, Template__c, Variables__c
            FROM Notification__c
            WHERE
                Template__c = :NotificationBuilder.TEMPLATE_DISCLOSUREINVENTOR_EACH_SIGNED_MIT
        ];
        System.Assert(
            notification.size() == 0,
            'The Ops team does not need to get a “Signature Received” email  when the inventor signs upon Submission. \n' +
            'They already get an email telling them a case has been submitted'
        );

        coInventor.Signed_Status__c = 'Yes';
        coInventor.DocuSign_Recipient_StatusCode__c = 'Completed';
        coInventor.Signed_Disclosure_Date__c = Date.newInstance(2023, 3, 13);
        update coInventor;

        List<Notification__c> coInventorNotifcations = [
            SELECT Id, Template__c, Variables__c
            FROM Notification__c
            WHERE
                Template__c = :NotificationBuilder.TEMPLATE_DISCLOSUREINVENTOR_EACH_SIGNED_MIT
        ];
        System.Assert(
            coInventorNotifcations.size() == 1,
            'coInventor “Signature Received” email  should have been created'
        );

        Map<String, Object> jsonVal = (Map<String, Object>) JSON.deserializeUntyped(
            coInventorNotifcations[0].Variables__c
        );
        System.assertEquals(
            'Test Inventor Actions on Signing',
            String.valueOf(jsonVal.get('disclosure_title')),
            'Should match the name for disclosure created above'
        );
        System.assertEquals(
            ContactNameUtil.toFullName(
                submittingContact.FirstName,
                submittingContact.MiddleName,
                submittingContact.LastName,
                true
            ),
            String.valueOf(jsonVal.get('submitter_name')),
            'Should be the name for submittingContact above'
        );
        System.assertEquals(
            ContactNameUtil.toFullName(
                coInventorContact.FirstName,
                coInventorContact.MiddleName,
                coInventorContact.LastName,
                true
            ),
            String.valueOf(jsonVal.get('inventor_name')),
            'Should be the name for coInventorContact above'
        );
        Test.stopTest();
    }
}