force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ArchiveDraftDisclosures.cls
public class ArchiveDraftDisclosures implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String days = olderThanNDays();
        String query =
            'Select Id,CreatedDate,Status__c,Submitting_Contact__c, Submitting_Contact__r.PersonEmail,Draft_Date__c From Disclosure__c where Status__c = \'Draft\' AND Draft_Date__c < LAST_N_Days:' +
            Integer.valueOf(days);
        return Database.getQueryLocator(query);
    }

    public void execute(
        Database.BatchableContext bc,
        List<Disclosure__c> scope
    ) {
        System.debug('--+--' + scope.size());
        List<Disclosure__c> updatedis = new List<Disclosure__c>();
        for (Disclosure__c dis : scope) {
            dis.Status__c = 'Archived';
            updatedis.add(dis);
        }
        if (updatedis != null && !updatedis.isEmpty()) {
            update updatedis;
            // Send Email using Trigger Handler

            System.debug('---+Batch+---');
        }
    }

    public void finish(Database.BatchableContext bc) {
    }

    private static String olderThanNDays() {
        return ConfigurationBuilder.getConfigurationToString(
            'archiveDraftOlderThan'
        );
    }
}