force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PrimaryInventor__c.field-meta.xml
<CustomField>
    <fullName>PrimaryInventor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Review_Draft_Watcher__c.field-meta.xml
<CustomField>
    <fullName>Review_Draft_Watcher__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Review Draft Disclosure</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisclosureEnableWatchers.cls
@RestResource(urlMapping='/api/disclosure-enable-watchers/v1/*')
global with sharing class DisclosureEnableWatchers {
    global class DisclosureWatcher {
        public String disclosureId;
        public String status;
        public Set<Id> disclosureInventors;
    }

    @HttpPost
    global static String enableWatchersRest() {
        RestResponse response = RestContext.response;

        String disclosureIdStr = RestContext.request.params.get('disclosureId');

        DisclosureWatcher disclosureWatcher = enableDraftWatchers(
            disclosureIdStr
        );
        if (disclosureWatcher != null) {
            String json = JSON.serialize(disclosureWatcher, true);
            response.statusCode = 200;
            return json;
        } else {
            response.statusCode = 304; // Not Modified
            return null;
        }
    }

    public static DisclosureWatcher enableDraftWatchers(
        String disclosureIdStr
    ) {
        List<DisclosureInventor__c> updateList = new List<DisclosureInventor__c>();

        List<DisclosureInventor__c> inventors = DisclosureRecordFetch.getDisclosureInventorsWithContactByDisclosureId(
            disclosureIdStr
        );
        for (DisclosureInventor__c inventor : inventors) {
            Boolean inventorForSubmittingContact =
                inventor.Contact__c ==
                inventor.Disclosure__r.Submitting_Contact__c; // Dont ask submitting contact to review Draft

            if (
                inventor.Disclosure__r.Status__c == 'Draft' &&
                inventor.PrimaryInventor__c == true &&
                inventorForSubmittingContact == false
            ) {
                inventor.Review_Draft_Watcher__c = true;
                updateList.add(inventor);
            }
        }

        if (!updateList.isEmpty()) {
            update updateList;

            Map<Id, DisclosureInventor__c> inventorMap = new Map<Id, DisclosureInventor__c>(
                updateList
            );

            sendDraftForReviewEvent(inventorMap);

            DisclosureWatcher disclosureWatcher = new DisclosureWatcher();
            disclosureWatcher.disclosureId = disclosureIdStr;
            disclosureWatcher.status = 'successful';
            disclosureWatcher.disclosureInventors = inventorMap.keySet();
            return disclosureWatcher;
        } else {
            return null;
        }
    }

    private static void sendDraftForReviewEvent(
        Map<Id, DisclosureInventor__c> inventorMap
    ) {
        List<Notification__c> notificationList = new List<Notification__c>();
        for (Id key : inventorMap.keySet()) {
            DisclosureInventor__c inventor = inventorMap.get(key);

            Map<String, String> variables = new Map<String, String>();
            variables.put('inventor_name', inventor.Contact__r.Name);
            variables.put('disclosure_title', inventor.Disclosure__r.Name__c);
            variables.put('disclosure_name', inventor.Disclosure__r.Name);
            variables.put(
                'disclosure_type',
                inventor.Disclosure__r.RecordType.Name
            );
            variables.put(
                'submitter_name',
                inventor.Disclosure__r.Submitting_Contact__r.Name
            );
            variables.put(
                'submitter_email',
                inventor.Disclosure__r.Submitting_Contact__r.PersonEmail
            );

            Notification__c newNotification = NotificationBuilder.buildNotificationEmail(
                inventor.Contact__r.PersonEmail,
                NotificationBuilder.TEMPLATE_DISCLOSURE_PRIMARY_INVENTOR_DRAFT_REVIEW,
                variables
            );
            notificationList.add(newNotification);
        }

        if (notificationList != null && !notificationList.isEmpty()) {
            insert notificationList;
        }
    }
}