force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/recordTypes/BioTang_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>BioTang_Disclosure</fullName>
    <active>true</active>
    <label>Biological and Tangible Property</label>
</RecordType>

force-app/main/default/objects/TLO_Contact_Update_Request__c/TLO_Contact_Update_Request__c.object-meta.xml
<CustomObject>
    <description>Holds requested / recommended updates for a TLO Contact</description>
    <label>TLO Contact Update Request</label>
    <nameField>
        <displayFormat>CRU-{000000}</displayFormat>
        <label>TLO Contact Update Requests ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TLO_Contact Update Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>TLO_Contact_Update_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipName>Contact_Requested_Updates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Primary Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/TLOContactUpdateReqTriggerHandlerTest.cls
@isTest
public class TLOContactUpdateReqTriggerHandlerTest {
    @isTest
    public static void testOnBeforeUpdate() {
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Disclosure__c d = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'BioTang',
            'Draft',
            cont
        );

        Account contact = SampleDataFactory.createContact(
            'Donald1',
            false,
            '12345671'
        );
        contact.PersonEmail = null;
        update contact;

        TLO_Contact_Update_Request__c cur = new TLO_Contact_Update_Request__c(
            Disclosure__c = d.Id,
            Contact__c = contact.Id,
            Email__c = 'test@gmail.com'
        );
        insert (cur);

        try {
            DisclosureRecordFetch.markCompleteTLOContactUpdateRequestById(
                cur.Id
            );
            System.assert(false, 'Validation error not thrown');
        } catch (Exception ex) {
            String msg = ex.getMessage();
            system.assert(
                msg.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                'Field Validation not thrown ' + msg
            );
        }
    }

    @isTest
    public static void testNoInstitutionOnContactWhenCompleted() {
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'Donald',
            false,
            '12345678'
        );
        Disclosure__c d = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'BioTang',
            'Draft',
            cont
        );

        cont.Institution__pc = null;
        cont.InstitutionCode__pc = '';
        update cont;

        TLO_Contact_Update_Request__c cur = new TLO_Contact_Update_Request__c(
            Disclosure__c = d.Id,
            Contact__c = cont.Id,
            Email__c = 'test@gmail.com'
        );
        insert (cur);

        try {
            DisclosureRecordFetch.markCompleteTLOContactUpdateRequestById(
                cur.Id
            );
            System.assert(false, 'Validation error not thrown');
        } catch (Exception ex) {
            String msg = ex.getMessage();
            System.debug('\n\n ex:- ' + ex);
            System.debug('\n\n msg:- ' + msg);

            System.assert(
                msg.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                'Field Validation not thrown ' + msg
            );
            System.assert(
                msg.contains('Institution can not be empty'),
                'Field Validation not thrown ' + msg
            );
        }
    }

    @isTest
    public static void testNoInstitutionOnContactWhenRejected() {
        Test.startTest();
        Id recordTypeIdBioTang = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('BioTang_Disclosure')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'Donald',
            false,
            '12345678'
        );
        Disclosure__c d = SampleDataFactory.createDisclosure(
            recordTypeIdBioTang,
            'BioTang',
            'Draft',
            cont
        );

        cont.Institution__pc = null;
        cont.InstitutionCode__pc = '';
        update cont;

        TLO_Contact_Update_Request__c cur = new TLO_Contact_Update_Request__c(
            Disclosure__c = d.Id,
            Contact__c = cont.Id,
            Email__c = 'test@gmail.com'
        );
        insert (cur);

        try {
            DisclosureRecordFetch.rejectTLOContactUpdateRequestById(cur.Id);
            System.assert(false, 'Validation error not thrown');
        } catch (Exception ex) {
            String msg = ex.getMessage();
            System.debug('\n\n ex:- ' + ex);
            System.debug('\n\n msg:- ' + msg);

            System.assert(
                msg.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                'Field Validation not thrown ' + msg
            );
            System.assert(
                msg.contains('Institution can not be empty'),
                'Field Validation not thrown ' + msg
            );
        }
    }

    //TODO part of this also run under the community profile too
    //public static void testInactiveKerbMitEmailOnContact() {
}