force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Invention_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Invention_Disclosure</fullName>
    <active>true</active>
    <label>Invention</label>
</RecordType>

force-app/main/default/objects/Invention_Disclosure__c/Invention_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Invention Disclosure</label>
    <nameField>
        <label>Invention Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invention_Disclosure__c/fields/Anticipated_Publication_Disclosure_Date__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Publication_Disclosure_Date__c</fullName>
    <label>Anticipated Publication Disclosure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Invention Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Invention_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Invention Disclosures</relationshipLabel>
    <relationshipName>Invention_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Anticipated_Publication__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Anticipated_Publication__c</fullName>
    <label>Anticipated Publication Disclosure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Oral_Presentation__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Oral_Presentation__c</fullName>
    <label>Oral Presentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Published_Or_Disclosed__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Published_Or_Disclosed__c</fullName>
    <label>Published Or Disclosed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Reduced_To_Practice__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Reduced_To_Practice__c</fullName>
    <label>Reduced To Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Oral_Disclosure_Date__c.field-meta.xml
<CustomField>
    <fullName>Oral_Disclosure_Date__c</fullName>
    <label>Oral Disclosure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Publication_Date__c.field-meta.xml
<CustomField>
    <fullName>Publication_Date__c</fullName>
    <label>Publication Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Reduced_To_Practice_Date__c.field-meta.xml
<CustomField>
    <fullName>Reduced_To_Practice_Date__c</fullName>
    <label>Reduced To Practice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InventionDisclosureValidationTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-13-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public with sharing class InventionDisclosureValidationTest {
    @TestSetup
    static void setup(){
        TestSetup.defaultConfiguration();
    }

    @isTest
    public static void InventionDisclosureValidationTestTrue() {
        try {
            Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName().get('Invention_Disclosure').getRecordTypeId();
            Disclosure__c testDisclosure = new Disclosure__c(Name__c = 'Test Disclosure', Status__c = 'Inventor Submitted', RecordTypeId = recordTypeId);
            insert testDisclosure;
            Invention_Disclosure__c testInvention = new Invention_Disclosure__c(Name = 'Test Invention', Disclosure__c = testDisclosure.Id, Disclosure_Published_Or_Disclosed__c = 'Yes', Disclosure_Anticipated_Publication__c = 'Yes', Disclosure_Oral_Presentation__c = 'Yes', Disclosure_Reduced_To_Practice__c = 'Yes');
            insert testInvention;
            InventionDisclosureFieldValidation.validateInventionDisclosureFields(testInvention);
        } catch(Exception e) {
            System.assert(true);
        }
    }

    @isTest
    public static void InventionDisclosureValidationDisclosureUpdateTestTrue() {
        try {
            Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName().get('Invention_Disclosure').getRecordTypeId();
            Disclosure__c testDisclosure = new Disclosure__c(Name__c = 'Test Disclosure', RecordTypeId = recordTypeId);
            insert testDisclosure;
            Invention_Disclosure__c testInvention = new Invention_Disclosure__c(Name = 'Test Invention', Disclosure__c = testDisclosure.Id, Disclosure_Published_Or_Disclosed__c = 'Yes', Disclosure_Anticipated_Publication__c = 'Yes', Disclosure_Oral_Presentation__c = 'Yes', Disclosure_Reduced_To_Practice__c = 'Yes');
            insert testInvention;
            InventionDisclosureFieldValidation.validateReducedToPracticeDisclosureUpdate(testInvention);
            InventionDisclosureFieldValidation.validateOralPresentationDisclosureUpdate(testInvention);
            InventionDisclosureFieldValidation.validatePublishedOrDisclosedDisclosureUpdate(testInvention);

            testDisclosure.Status__c = 'Inventor Submitted';
            Database.update(testDisclosure);
            Boolean result = InventionDisclosureFieldValidation.validateInventionDisclosureFieldsDisclosureUpdate(testInvention);
        } catch(Exception e) {
            System.assert(true);
        }
    }

    @isTest
    public static void InventionDisclosureValidationTestFalse() {
        try {
            Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName().get('Invention_Disclosure').getRecordTypeId();
            Disclosure__c testDisclosure = new Disclosure__c(Name__c = 'Test Disclosure', Status__c = 'Inventor Submitted', RecordTypeId = recordTypeId);
            insert testDisclosure;
            Invention_Disclosure__c testInvention = new Invention_Disclosure__c(Name = 'Test Invention',Disclosure__c = testDisclosure.Id, Publication_Date__c = Date.newInstance(2022, 06, 09), Anticipated_Publication_Disclosure_Date__c = Date.newInstance(2022, 06, 09), Oral_Disclosure_Date__c = Date.newInstance(2022, 06, 09), Reduced_To_Practice_Date__c = Date.newInstance(2022, 06, 09));
            insert testInvention;
            InventionDisclosureFieldValidation.validateInventionDisclosureFields(testInvention);
        } catch(Exception e) {
            System.assert(true);
        }
    }

    @isTest
    public static void InventionDisclosureValidationDisclosureUpdateTestFalse() {
        try {
            Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName().get('Invention_Disclosure').getRecordTypeId();
            Disclosure__c testDisclosure = new Disclosure__c(Name__c = 'Test Disclosure', RecordTypeId = recordTypeId);
            insert testDisclosure;
            Invention_Disclosure__c testInvention = new Invention_Disclosure__c(Name = 'Test Invention', Disclosure__c = testDisclosure.Id, Publication_Date__c = Date.newInstance(2022, 06, 09), Anticipated_Publication_Disclosure_Date__c = Date.newInstance(2022, 06, 09), Oral_Disclosure_Date__c = Date.newInstance(2022, 06, 09), Reduced_To_Practice_Date__c = Date.newInstance(2022, 06, 09));
            insert testInvention;

            testDisclosure.Status__c = 'Inventor Submitted';
            Database.update(testDisclosure);
            Boolean result = InventionDisclosureFieldValidation.validateInventionDisclosureFieldsDisclosureUpdate(testInvention);
        } catch(Exception e) {
            System.assert(true);
        }
    }
}