force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor_Event__e/DisclosureInventor_Event__e.object-meta.xml
<CustomObject>
    <label>DisclosureInventor_Event</label>
    <pluralLabel>DisclosureInventor_Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor_Event__e/fields/LinkedEntityId__c.field-meta.xml
<CustomField>
    <fullName>LinkedEntityId__c</fullName>
    <label>LinkedEntityId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DisclosureInventorEventProducer.cls
public with sharing class DisclosureInventorEventProducer {
    public DisclosureInventorEventProducer() {

    }

    public static void onApprovedInventorAdded(List<DisclosureInventor__c> disclosureInventorRelatedList) {
        if(disclosureInventorRelatedList != null && !disclosureInventorRelatedList.isEmpty()) {

            List<DisclosureInventor_Event__e> events = new List<DisclosureInventor_Event__e>();
            for(DisclosureInventor__c disinv: disclosureInventorRelatedList) {
                Disclosure__c disclosure = disinv.Disclosure__r;

                // Adding Inventors to Approved state
                if (disclosure.Status__c == 'Approved') {
                    DisclosureInventor_Event__e event = new DisclosureInventor_Event__e(Event_Name__c = 'onApprovedInventorAdded', LinkedEntityId__c = disinv.Id );
                    events.add(event);
                }
            }
            if(events != null && !events.isEmpty()) {
                List<Database.SaveResult> results = EventBus.publish(events);
                validateEventBusPublish(results);
            }
        }

    }

    public static void validateEventBusPublish(List<Database.SaveResult> results) {
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                EventBusException ex;
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' + err.getStatusCode() +  ' - ' +  err.getMessage());
                    if (ex == null) {
                     ex = new EventBusException(err.getMessage());
                    }
                }
                throw ex;
            }
        }
    }
    public class EventBusException extends Exception {}
}