force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/Invention_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Invention Disclosure</label>
    <nameField>
        <label>Invention Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Invention Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Invention_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Invention Disclosures</relationshipLabel>
    <relationshipName>Invention_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InventionDisclosureTriggerHandler.cls
public class InventionDisclosureTriggerHandler {

    public static void onBeforeInsert(List<Invention_Disclosure__c> inventionDisclosureListList) {
        Map<Id, Disclosure__c> parents = new Map<Id, Disclosure__c>();
        for(Invention_Disclosure__c inventionDisclosure: inventionDisclosureListList) {
            parents.put(inventionDisclosure.disclosure__c, null);
        }
        if(parents != null && parents.size() > 0) {
            parents.putAll([SELECT Status__c FROM Disclosure__c WHERE Id = :parents.keySet()]);
            for(Invention_Disclosure__c inventionDisclosure:inventionDisclosureListList) {
                Disclosure__c disclosure = parents.get(inventionDisclosure.disclosure__c);
                if(disclosure.Status__c != 'Draft') {
                    InventionDisclosureFieldValidation.validateInventionDisclosureFields(inventionDisclosure);
                }
            }
        }
    }
    
    public static void onBeforeUpdate(List<Invention_Disclosure__c> inventionDisclosureList, Map<Id, Invention_Disclosure__c> oldinv) {
        for(Invention_Disclosure__c inventionDisclosure:inventionDisclosureList) {
            InventionDisclosureFieldValidation.validateInventionDisclosureFieldsDisclosureUpdate(inventionDisclosure);
        }
    }
    
    public static void onAfterInsert(List<Invention_Disclosure__c> invDis) {
        
    }
    
    public static void onAfterUpdate(List<Invention_Disclosure__c> invDis, Map<Id, Invention_Disclosure__c> oldinv) { 
    
    }
}