force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Last_Modified_at_time_of_Signing_Request__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_at_time_of_Signing_Request__c</fullName>
    <description>This field holds the Disclosures Last Modified Date/Time at the time Signing Envelope was requested, so that we are able to tell if Disclosure has been modified since last request when Disclosure is in a Draft status. If Disclosure has been changed then we will need to update the doc on DocuSign&apos;s envelope if not we can leave as is.</description>
    <label>Last Modified at time of Signing Request</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Signing_Envelop_Id__c.field-meta.xml
<CustomField>
    <fullName>Signing_Envelop_Id__c</fullName>
    <description>This field contains the envelopId from DocuSign which is unique to this Disclosure.</description>
    <externalId>true</externalId>
    <label>Signing Envelop Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DocumentGenerateEmbeddedSigningAPI.cls
@RestResource(urlMapping =  '/api/generate-signing-url/v1/*')
global with sharing class DocumentGenerateEmbeddedSigningAPI {

    @HttpGet
    global static String generateEmbeddedSigningUrl() {        
        String disclosureIdStr = RestContext.request.params.get('disclosureId');
        String returnUrl = RestContext.request.params.get('returnUrl');
        String inventorId = RestContext.request.params.get('inventorId');

        System.debug('#disclosureIdStr: ' + disclosureIdStr);
        System.debug('#returnUrl: ' + returnUrl);
        System.debug('#inventorId: ' + inventorId);

        //Native App not needing to pass the returnUrl in.. therefore always use localhost
        returnUrl = returnUrl != null ? returnUrl : 'http://localhost';

        Disclosure__c disclosure = [SELECT Id, Name, Signing_Envelop_Id__c,
                                            Last_Modified_at_time_of_Signing_Request__c, LastModifiedDate
                                        FROM Disclosure__c 
                                        WHERE Id = :disclosureIdStr];

        Boolean disclosureHasEnvelopeId = disclosure.Signing_Envelop_Id__c != null;
        System.debug('#disclosureHasEnvelopeId: ' + disclosureHasEnvelopeId);

        RestResponse response = RestContext.response;
        if (!disclosureHasEnvelopeId) {            
            // no envelopId therefore respond with error
            response.statusCode = 400; // calling this on a disclosure which has not had initiate signing process run yet
            return 'Ensure `/api/initiate-signing-process/v2/*` has been called first, Disclosure DocuSign Envenlope Creation could Still Processing';
        } else {
            response.statusCode = 200; // 200 - complete

            DocuSignService docuSignService = new DocuSignService();
            return docuSignService.generateEmbeddedSigningUrl(disclosureIdStr, returnUrl, inventorId);
        }
    }
}