force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Contact_Recid__c.field-meta.xml
<CustomField>
    <fullName>Contact_Recid__c</fullName>
    <externalId>true</externalId>
    <label>Forrester Contact RecID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <externalId>true</externalId>
    <label>MIT ID</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/Forrester_CONTACT__x.object-meta.xml
<CustomObject>
    <description>Forrester_CONTACT</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_CONTACT</externalName>
    <label>Forrester_CONTACT</label>
    <pluralLabel>Forrester_CONTACT</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_CONTACT__x/fields/MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>MIT_ID__c</fullName>
    <description>MIT_ID</description>
    <externalDeveloperName>MIT_ID</externalDeveloperName>
    <label>MIT_ID</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Record__c/fields/Contact_Recid__c.field-meta.xml
<CustomField>
    <fullName>Contact_Recid__c</fullName>
    <label>Forrester Contact RecID</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/FormName__c.field-meta.xml
<CustomField>
    <fullName>FormName__c</fullName>
    <label>Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <label>MIT ID</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/SignDatetime__c.field-meta.xml
<CustomField>
    <fullName>SignDatetime__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ForresterIPIAAsyncSaveHandlerTest.cls
@isTest
private class ForresterIPIAAsyncSaveHandlerTest {
    @TestSetup
    static void setup() {
        TestSetup.defaultConfiguration();
    }

    @isTest
    static void processSaveTest() {
        // Insert Account without rec id
        IPIA_Record__c ipiaRecord = new IPIA_Record__c(MitId__c = '912345101' , FormName__c = 'Test_IPIA_FormName_1', SignDatetime__c = Date.Today().addDays(-30));
        insert ipiaRecord;

        Async_Request__c asyncReq = AsyncRequestHelper.prepareAsyncRequest(
            ipiaRecord.Id,
            'IPIA_Record__c',
            'IPIASignedToForresterJob'
        );
        insert asyncReq;

        Boolean isSuccess = true;
        Database.SaveResult saveResult = (Database.SaveResult) JSON.deserialize(
            JSON.serialize(
                new Map<String, Object>{
                    'id' => ipiaRecord.Id,
                    'success' => isSuccess,
                    'errors' => new List<String>()
                }
            ),
            Database.SaveResult.class
        );

        // Create mock database instance for external data
        ExternalQueryMock mock = ExternalQueryMock.getInstance();

        // Mock Forrester Contact data
        List<Forrester_CONTACT__x> mockForresterContacts = new List<Forrester_CONTACT__x>();
        Forrester_CONTACT__x mockForresterContact = new Forrester_CONTACT__x(
            MIT_ID__c = '912345101' ,
            CONTACT_RECID__c = '12345'
        );
        mockForresterContacts.add(mockForresterContact);

        mock.setDataStore('Forrester_CONTACT__x:Ids', mockForresterContacts);

        Test.startTest();
        // Create an instance of the callback handler
        ForresterIPIAAsyncSaveHandler forresterIPIACallbackHandler = new ForresterIPIAAsyncSaveHandler(
            asyncReq.Id
        );
        forresterIPIACallbackHandler.processSave(saveResult);
        Test.stopTest();

    }


}