force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Has_Processed__c.field-meta.xml
<CustomField>
    <fullName>Has_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Record__c/fields/DocusignEnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>DocusignEnvelopeId__c</fullName>
    <label>Docusign Envelope Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/FormName__c.field-meta.xml
<CustomField>
    <fullName>FormName__c</fullName>
    <label>Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/IPIA_Type__c.field-meta.xml
<CustomField>
    <fullName>IPIA_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IPIA Type</label>
    <referenceTo>IPIA_Type__c</referenceTo>
    <relationshipLabel>IPIAs</relationshipLabel>
    <relationshipName>IPIA_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <label>MIT ID</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/SignDatetime__c.field-meta.xml
<CustomField>
    <fullName>SignDatetime__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IPIA_Type__c/IPIA_Type__c.object-meta.xml
<CustomObject>
    <label>IPIA Type</label>
    <nameField>
        <label>IPIA Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPIA Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Type__c/fields/Exemption__c.field-meta.xml
<CustomField>
    <fullName>Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exemption</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IPIA_Type__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>IPIA Type Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Needs TLO Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IPIADocuSignDownloadBatchScheduleTest.cls
@IsTest
public with sharing class IPIADocuSignDownloadBatchScheduleTest {
    @TestSetup
    static void setup() {
        TestSetup.defaultConfiguration();
    }

    @isTest
    public static void testScheduleAbort() {
        Test.startTest();
        IPIADocuSignDownloadBatchSchedule.scheduleMe();
        IPIADocuSignDownloadBatchSchedule.abortSchedule();
        Test.stopTest();
    }


    @IsTest
    public static void testRetryIPIADownload() {
       HttpMockBlobFactory mock = new HttpMockBlobFactory(201, 'OK', '', new Map<String,String>());

       IPIA_Type__c ipiaType1 = new IPIA_Type__c(Name = 'Other', Exemption__c = true, Status__c = 'Active');
       insert ipiaType1;

       String envelopeId = 'e00cd216-2997-469e-996e-a19177aa4d47';
       IPIA_Record__c ipiaRecord1 = new IPIA_Record__c(FormName__c = ipiaType1.Name, MitId__c = '912345671', SignDatetime__c = Date.today().addDays(-2), IPIA_Type__c = ipiaType1.Id, DocusignEnvelopeId__c = envelopeId);
       List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>{ipiaRecord1};

       insert ipiaRecords;
       try {
            Test.startTest();
            IPIADocuSignDownloadBatch batchJob = new IPIADocuSignDownloadBatch();
            Database.executeBatch(batchJob, 1); // Can only process one at a time.
            Test.stopTest();
            System.assert(false,'Exception not thrown');
       } catch(Exception e) {
       }
       List<Async_Request__c> asyncReqs = [
                                 SELECT
                                     Id,
                                     Has_Processed__c,
                                     Retry_Count__c,
                                     Record_Id__c,
                                     sObject_Name__c
                                 FROM Async_Request__c
                                 WHERE
                                     sObject_Name__c = 'IPIA_Record__c'
                                     AND Job_Name__c = 'IPIADownloadSignedJob'
                                     AND Has_Processed__c = false

                             ];
       System.assert(asyncReqs.size() == 1, 'Expecting one Async Request');

    }

}