force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Has_Processed__c.field-meta.xml
<CustomField>
    <fullName>Has_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ForresterIPIAAsyncSaveHandler.cls
public class ForresterIPIAAsyncSaveHandler extends DataSource.AsyncSaveCallback {
    public final Id asyncRequestId;

    public ForresterIPIAAsyncSaveHandler(Id asyncRequestId) {
        this.asyncRequestId = asyncRequestId;
    }
    // Implement the handleResult method
    override public void processSave(Database.SaveResult saveResult) {
         Async_Request__c asyncRequest = [SELECT
                                    Id,
                                    Has_Processed__c,
                                    Retry_Count__c,
                                    Record_Id__c,
                                    sObject_Name__c,
                                    Job_Name__c
                                FROM Async_Request__c
                                WHERE
                                   Id = :asyncRequestId
                            ];

        if (saveResult.isSuccess()) {
            System.debug('🐞 ~ ForresterIPIAAsyncSaveHandler ~ processSave ~ saveResult:' + JSON.serializePretty(saveResult));
            asyncRequest.Has_Processed__c = true;
        } else {
            System.debug('Error saving record: ' + saveResult.getErrors()[0].getMessage());
            asyncRequest.Has_Processed__c = false;
            asyncRequest.Retry_Count__c =  Integer.valueOf(asyncRequest.Retry_Count__c) + 1;
        }
        update asyncRequest;
    }
}