force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Has_Processed__c.field-meta.xml
<CustomField>
    <fullName>Has_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IPIASignedToForresterJob.cls
public class IPIASignedToForresterJob implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext bc){
        Integer retryCount = Integer.ValueOf(retryCount());
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    Has_Processed__c,
                    Retry_Count__c,
                    Record_Id__c,
                    sObject_Name__c,
                    Job_Name__c
                FROM Async_Request__c
                WHERE
                   Has_Processed__c = FALSE
                   AND Retry_Count__c < :retryCount
                   AND sObject_Name__c = 'IPIA_Record__c'
                   AND Job_Name__c = 'IPIASignedToForresterJob'
                ORDER BY Job_Name__c
            ]
        );

    }

    public void execute(Database.BatchableContext bc, List<Async_Request__c> scope) {
       if (scope != null && !scope.isEmpty()) {
         Map<Id, Async_Request__c> asyncMap = new Map<Id, Async_Request__c>(scope);
         Integer delayInMinutes = 0;
         IPIARecordUpsertJob upsertIpiaJob = new IPIARecordUpsertJob(asyncMap.keySet());
         // From a batch you can only add one Queueable Job
         System.enqueueJob(upsertIpiaJob, delayInMinutes);
       }
    }

    public void finish(Database.BatchableContext bc) {
    }


    private static String retryCount() {
        return ConfigurationBuilder.getConfigurationToString(
            'batchJobMaxNumberOfRetry'
        );
    }
}