force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Has_Processed__c.field-meta.xml
<CustomField>
    <fullName>Has_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Entity_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Sub_Type__c</fullName>
    <label>Data Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N_A</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>KUALI</fullName>
                <label>Kuali</label>
            </value>
            <value>
                <fullName>AGENCY</fullName>
                <label>Agency</label>
            </value>
            <value>
                <fullName>ASSIGN</fullName>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>BY-AGT</fullName>
                <label>License by Agent</label>
            </value>
            <value>
                <fullName>GOVUSE</fullName>
                <label>Government Use License</label>
            </value>
            <value>
                <fullName>INST</fullName>
                <label>Institution</label>
            </value>
            <value>
                <fullName>JOI NO</fullName>
                <label>Joint - No Purple File</label>
            </value>
            <value>
                <fullName>JOINT</fullName>
                <label>Joint Ownership</label>
            </value>
            <value>
                <fullName>LIC</fullName>
                <label>License</label>
            </value>
            <value>
                <fullName>LIC NO</fullName>
                <label>License - No Purple File</label>
            </value>
            <value>
                <fullName>MASTER</fullName>
                <label>Master Agreement</label>
            </value>
            <value>
                <fullName>MOU</fullName>
                <label>Memo of Understanding</label>
            </value>
            <value>
                <fullName>MTA</fullName>
                <label>Outgoing Material Transfer Agreement</label>
            </value>
            <value>
                <fullName>OBYAGN</fullName>
                <label>Option by Agent</label>
            </value>
            <value>
                <fullName>OPT</fullName>
                <label>Option</label>
            </value>
            <value>
                <fullName>PUBL</fullName>
                <label>Publishing</label>
            </value>
            <value>
                <fullName>SUBLIC</fullName>
                <label>Sublicense</label>
            </value>
            <value>
                <fullName>SW-EU</fullName>
                <label>Software End Use</label>
            </value>
            <value>
                <fullName>SW-LIC</fullName>
                <label>Software End Use Licenses &gt; 1K</label>
            </value>
            <value>
                <fullName>TECHTR</fullName>
                <label>Tech Transfer</label>
            </value>
            <value>
                <fullName>TM</fullName>
                <label>Trademark</label>
            </value>
            <value>
                <fullName>TRACKG</fullName>
                <label>Tracking</label>
            </value>
            <value>
                <fullName>SRA</fullName>
                <label>Sponsor Research Agreement</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Sponsor Agreement</label>
            </value>
            <value>
                <fullName>CONSORTIUM</fullName>
                <label>Consortium</label>
            </value>
            <value>
                <fullName>SUB_AWARD</fullName>
                <label>Subaward Document</label>
            </value>
            <value>
                <fullName>ASSIGNMENT</fullName>
                <label>Assignment</label>
            </value>
            <value>
                <fullName>AGREEMENT</fullName>
                <label>Agreement</label>
            </value>
            <value>
                <fullName>NDA</fullName>
                <label>Non-Disclosure Agreement (NDA)</label>
            </value>
            <value>
                <fullName>IPIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/IPIA.recordType-meta.xml
<RecordType>
    <fullName>IPIA</fullName>
    <active>true</active>
    <label>IPIA</label>
</RecordType>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Record__c/fields/DocusignEnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>DocusignEnvelopeId__c</fullName>
    <label>Docusign Envelope Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/FormName__c.field-meta.xml
<CustomField>
    <fullName>FormName__c</fullName>
    <label>Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/IPIA_Type__c.field-meta.xml
<CustomField>
    <fullName>IPIA_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IPIA Type</label>
    <referenceTo>IPIA_Type__c</referenceTo>
    <relationshipLabel>IPIAs</relationshipLabel>
    <relationshipName>IPIA_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <label>MIT ID</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Type__c/IPIA_Type__c.object-meta.xml
<CustomObject>
    <label>IPIA Type</label>
    <nameField>
        <label>IPIA Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPIA Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IPIADocuSignDownloadJob.cls
// https://www.salesforceben.com/batch-apex/#:~:text=The%20difference%20between%20queueable%20and,can%20run%20up%20to%20100!

public with sharing class IPIADocuSignDownloadJob implements Finalizer, Queueable, Database.AllowsCallouts {
    public static Integer DEFAULT_IPIA_DOWNLOAD_JOB_MAX_RETRY = 3;
    private String asyncRequestIdStr;

    public IPIADocuSignDownloadJob(String asyncRequestIdStr){
        this.asyncRequestIdStr = asyncRequestIdStr;
    }

    private Async_Request__c getAsyncRequest() {
        Async_Request__c asyncRequest = [SELECT Id, Record_Id__c, Has_Processed__c, Retry_Count__c
                                            FROM Async_Request__c
                                            WHERE Id = :asyncRequestIdStr];
        return asyncRequest;
    }

    public void execute(QueueableContext ctx) {
        IPIARecordService ipiaService = new IPIARecordService();
        Finalizer f = this;
        System.attachFinalizer(f);

        String jobId = '' + ctx.getJobId();
        System.debug('Begin: executing IPIADocuSignDownloadJob queueable job: ' + jobId);

        Async_Request__c asyncRequest = getAsyncRequest();
        try {

            String ipiaRecordIdStr = asyncRequest.Record_Id__c;

            IPIA_Record__c ipiaRecord = [ SELECT Id, DocusignEnvelopeId__c,
                                                 IPIA_Type__c,
                                                 IPIA_Type__r.Name,
                                                 FormName__c,
                                                 MitId__c
                                                 FROM IPIA_Record__c
                                                 WHERE Id = :ipiaRecordIdStr];

            String envelopeId = ipiaRecord.DocusignEnvelopeId__c;
            System.debug('Query: executing IPIADocuSignDownloadJob envelopeId: ' + envelopeId);

            if (!String.isEmpty(envelopeId) && asyncRequest.Has_Processed__c == false) {
               String formName = (ipiaRecord.IPIA_Type__c != null) ? ipiaRecord.IPIA_Type__r.Name : ipiaRecord.FormName__c;
               String documentTitle = ipiaRecord.MitId__c + '-' + formName ;
               fetchIPIADocument(ipiaService, ipiaRecordIdStr, documentTitle);
            }
            asyncRequest.Has_Processed__c = true;
            update asyncRequest;

        } catch (Exception ex) {
             System.debug('IPIADocuSignDownloadJob Error executing the job [' + jobId + ']: ' + ex.getMessage());
             asyncRequest.Retry_Count__c = Integer.valueOf(asyncRequest.Retry_Count__c) + 1;
             asyncRequest.Has_Processed__c = false;
             update asyncRequest;

            throw ex;
        } finally {
            System.debug('IPIADocuSignDownloadJob Completed: execution of queueable job: ' + jobId);
        }
    }

    private void fetchIPIADocument(IPIARecordService ipiaService, String ipiaRecordId, String disclosureName) {
        Blob docBlob = ipiaService.getIpiaRecordDocument(ipiaRecordId);
        
        System.debug('IPIADocuSignDownloadJob docBlob received create ContentVersion');
        String fileName = 'IPIA_' + disclosureName + '.pdf';

        List<ContentDocumentLink> documentLinks = [SELECT  LinkedEntityId , ContentDocumentId FROM  ContentDocumentLink
                WHERE LinkedEntityId = :ipiaRecordId
                AND ContentDocumentId IN (SELECT ContentDocumentId FROM ContentVersion WHERE PathOnClient = :fileName and Entity_Sub_Type__c = 'IPIA' and Document_Classification__c = 'Original_Document' )
            ];
        Boolean isUpdate = false;    
        ContentDocumentLink documentLink = null;
        if( documentLinks.size() == 1 ){
            isUpdate = true;
            documentLink = documentLinks.get(0);
        }


        Id cvDisclosureRecordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName().get('IPIA').getRecordTypeId();
        ContentVersion cv = new ContentVersion();
        cv.Title = fileName; // Display name of the files
        cv.PathOnClient = fileName;
        cv.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
        cv.VersionData = docBlob;
        cv.Document_Classification__c = 'Original_Document';
        cv.Entity_Sub_Type__c = 'IPIA';
        if (isUpdate && documentLink != null) {
            cv.ContentDocumentId = documentLink.ContentDocumentId; // Use the same ContentDocumentId
        }
        cv.RecordTypeId = cvDisclosureRecordTypeId;

        //Insert ContentVersion, need the Id.
        insert cv;

        System.debug('ContentVersion docBlob Created');
        if (!isUpdate) {
            // First get the Content Document Id from ContentVersion Object
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
            //create ContentDocumentLink  record
            ContentDocumentLink conDocLink = new ContentDocumentLink();
            conDocLink.LinkedEntityId = ipiaRecordId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
            conDocLink.ContentDocumentId = conDoc;  //ContentDocumentId Id from ContentVersion
            //V - Viewer permission. C - Collaborator permission. I - Inferred permission
            conDocLink.ShareType = 'I';
            conDocLink.Visibility = 'AllUsers';

            insert conDocLink;
        }


    }

    // Finalizer implementation (Retry) for initial Queueable Job
    public void execute(FinalizerContext ctx) {
        String parentJobId = '' + ctx.getAsyncApexJobId();
        System.debug('Begin: executing finalizer attached to IPIADocuSignDownloadJob queueable job: ' + parentJobId);
        
        if (ctx.getResult() == ParentJobResult.SUCCESS) {
            System.debug('IPIADocuSignDownloadJob queueable job [' + parentJobId + '] completed successfully.');
        } else {
            if (ctx.getException() != null) {
                System.debug('IPIADocuSignDownloadJob queueable job [' + parentJobId + '] failed due to unhandled exception: ' + ctx.getException().getMessage());
                HandleLogException.logException(ctx.getException());
            }
        }
    }

  public static void startDocuSignIpiaDownload(List<IPIA_Record__c> queryIpiaRecords,  Map<Id,IPIA_Record__c> oldIpias) {

      List<Async_Request__c> asyncJobs = new List<Async_Request__c>();
      for(IPIA_Record__c d: queryIpiaRecords) {
            if (String.isBlank(d.DocusignEnvelopeId__c)) {
                continue;
            }
            IPIA_Record__c oldIpia = (oldIpias != null && oldIpias.get(d.Id) != null) ? oldIpias.get(d.Id) : new IPIA_Record__c();
            Boolean onRecordChanged = d.DocusignEnvelopeId__c != oldIpia.DocusignEnvelopeId__c ;
            System.debug('IPIADocuSignDownloadJob.onRecordChanged: ' + onRecordChanged );
            if(onRecordChanged) {

                String envelopeId = d.DocusignEnvelopeId__c;
                Async_Request__c asyncJob =
                                        AsyncRequestHelper.prepareAsyncRequest(
                                            d.Id,
                                            'IPIA_Record__c',
                                            'IPIADownloadSignedJob'
                                        );
                 asyncJobs.add(asyncJob);
            }
        }
        if (!asyncJobs.isEmpty()) {
            insert asyncJobs;
            for (Async_Request__c asyncJob : asyncJobs) {
              if (!Test.isRunningTest()) {
                Id newJobId = System.enqueueJob(new IPIADocuSignDownloadJob(asyncJob.Id), 0);
              }
            }
        }
    }

    private static Integer retryCount() {
        try {
            String retryConf = ConfigurationBuilder.getConfigurationToString('batchJobMaxNumberOfRetry');
            return Integer.ValueOf(retryConf);
        } catch (ConfigurationBuilder.MissingConfigurationException ex) {
            return DEFAULT_IPIA_DOWNLOAD_JOB_MAX_RETRY;
        }
    }


}