force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Has_Processed__c.field-meta.xml
<CustomField>
    <fullName>Has_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/DocuSign_Recipient_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Recipient_StatusCode__c</fullName>
    <description>This field will hold the value of DocuSign&apos;s Status Code for this Inventor. (That will be used to map back to Signed flag) 
DocuSign events are send for all inventors on a Disclosure at the same time. Needing to ensure status code is mapped correctly for each.</description>
    <label>DocuSign Recipient StatusCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisclosureInventorSignedHandlerTest.cls
@isTest
public with sharing class DisclosureInventorSignedHandlerTest {
    // @TestSetup
    // static void setup() {
    //     TestSetup.defaultConfiguration();
    // }

    // @isTest
    // public static void testSignDisclosureCreatesAsyncJobForDocRetrieval() {
    //     // Setup variables
    //     ContactSampleDataFactory.createSampleContacts();

    //     String title = 'testSignDisclosureCreatesAsyncJobForDocRetrieval';
    //     Disclosure__c disclosure = DisclosureSampleDataFactory.createDraftSoftwareDisclosureNoDeptHead(
    //         title,
    //         true
    //     );

    //     List<DisclosureInventor__c> inventors = DisclosureRecordFetch.getDisclosureInventorsWithContactByDisclosureId(
    //         disclosure.Id
    //     );
    //     DisclosureInventor__c inventor = inventors[0];

    //     inventor.DocuSign_Recipient_StatusCode__c = 'Completed';
    //     update inventor;

    //     List<DisclosureInventor__c> inventorsToTest = DisclosureRecordFetch.getDisclosureInventorsWithContactByDisclosureIdInventorId(
    //         disclosure.Id,
    //         inventor.Id
    //     );
    //     DisclosureInventor__c inventorToTest = inventorsToTest[0];
    //     System.assertEquals(
    //         'Yes',
    //         inventorToTest.Signed_Status__c,
    //         'Should be true?'
    //     );

    //     List<Async_Request__c> asyncRequests = [
    //         SELECT
    //             Id,
    //             Has_Processed__c,
    //             Retry_Count__c,
    //             Record_Id__c,
    //             sObject_Name__c
    //         FROM Async_Request__c
    //         WHERE
    //             Has_Processed__c = FALSE
    //             AND Retry_Count__c = 0
    //             AND sObject_Name__c = 'DisclosureInventor__c'
    //             AND Job_Name__c = 'FetchInventorSignedDocJob'
    //             AND Record_Id__c = :inventorToTest.Id
    //     ];

    //     System.assertEquals(
    //         1,
    //         asyncRequests.size(),
    //         'asyncRequest for this Inventor Should Exist'
    //     );
    // }
}