force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Has_Processed__c.field-meta.xml
<CustomField>
    <fullName>Has_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Disclosure</fullName>
    <active>true</active>
    <description>Disclosure Record Type</description>
    <label>Disclosure</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/DisclosureInventor.recordType-meta.xml
<RecordType>
    <fullName>DisclosureInventor</fullName>
    <active>true</active>
    <label>DisclosureInventor</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Log_Exception__c/Log_Exception__c.object-meta.xml
<CustomObject>
    <label>Log Exception</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Log Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FetchInventorSignedDocJob.cls
public with sharing class FetchInventorSignedDocJob implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Integer retryCount = Integer.ValueOf(
            ConfigurationBuilder.getConfigurationToString(
                'batchJobMaxNumberOfRetry'
            )
        );
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    Has_Processed__c,
                    Retry_Count__c,
                    Record_Id__c,
                    sObject_Name__c
                FROM Async_Request__c
                WHERE
                    Has_Processed__c = FALSE
                    AND Retry_Count__c < :retryCount
                    AND sObject_Name__c = 'DisclosureInventor__c'
                    AND Job_Name__c = 'FetchInventorSignedDocJob'
            ]
        );
    }

    public void execute(
        Database.BatchableContext bc,
        List<Async_Request__c> scopes
    ) {
        // We can not do a callout if there is transactions that have not committed.

        List<ContentDocumentLink> conDocLinkInsert = new List<ContentDocumentLink>();
        List<Async_Request__c> asyncRequestUpdate = new List<Async_Request__c>();
        List<Log_Exception__c> logExceptions = new List<Log_Exception__c>();

        Set<String> inventorIds = new Set<String>();
        for (Async_Request__c async : scopes) {
            inventorIds.add(async.Record_Id__c);
        }
        List<DisclosureInventor__c> inventors = [
            SELECT Id, Disclosure__r.Id
            FROM DisclosureInventor__c
            WHERE Id = :inventorIds
        ];

        Map<Id, DisclosureInventor__c> inventorMap = new Map<Id, DisclosureInventor__c>(
            inventors
        );
        Map<Id, Blob> docusignMap = new Map<Id, Blob>();

        // Get all the blobs and add to inventor map.
        for (Async_Request__c async : scopes) {
            try {
                DisclosureInventor__c inventor = inventorMap.get(
                    async.Record_Id__c
                );

                Id disclosureId = inventor.Disclosure__r.Id;
                Id inventorId = inventor.Id;
                System.debug(
                    'FetchInventorSignedDocJob disclosureId:- ' +
                    disclosureId +
                    ', inventorId:- ' +
                    inventorId +
                    ' Blob START'
                );

                DocuSignService docuSignService = new DocuSignService();
                Blob inventorDocBlob = docuSignService.getDocumentForInventor(
                    disclosureId,
                    inventorId
                );
                docusignMap.put(inventorId, inventorDocBlob);
                System.debug(
                    'FetchInventorSignedDocJob disclosureId:- ' +
                    disclosureId +
                    ', inventorId:- ' +
                    inventorId +
                    ' Blob END'
                );
            } catch (exception ex) {
                logExceptions.add(HandleLogException.logExceptionInstance(ex));
            }
        }

        for (Async_Request__c async : scopes) {
            try {
                DisclosureInventor__c inventor = inventorMap.get(
                    async.Record_Id__c
                );

                Id disclosureId = inventor.Disclosure__r.Id;
                Id inventorId = inventor.Id;
                System.debug(
                    'FetchInventorSignedDocJob disclosureId:- ' +
                    disclosureId +
                    ', inventorId:- ' +
                    inventorId +
                    ' CV START'
                );

                Blob inventorDocBlob = docusignMap.get(inventorId);

                System.debug(
                    'FetchInventorSignedDocJob inventorDocBlob received create ContentVersion'
                );

                Id cvDisclosureInventorRecordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByDeveloperName()
                    .get('DisclosureInventor')
                    .getRecordTypeId();
                ContentVersion cv = new ContentVersion();
                cv.Title = 'DocuSign_' + inventorId + '.pdf'; // Display name of the files
                cv.PathOnClient = 'DocuSign_' + inventorId + '.pdf';
                cv.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
                cv.VersionData = inventorDocBlob;
                cv.Document_Classification__c = 'Signed Disclosure';
                cv.RecordTypeId = cvDisclosureInventorRecordTypeId;

                //Insert ContentVersion, need the Id.
                insert cv;

                System.debug('ContentVersion inventorDocBlob Created');

                // First get the Content Document Id from ContentVersion Object
                Id conDoc = [
                    SELECT ContentDocumentId
                    FROM ContentVersion
                    WHERE Id = :cv.Id
                ]
                .ContentDocumentId;
                //create ContentDocumentLink  record
                ContentDocumentLink conDocLink = new ContentDocumentLink();
                conDocLink.LinkedEntityId = inventorId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                conDocLink.ContentDocumentId = conDoc; //ContentDocumentId Id from ContentVersion
                //V - Viewer permission. C - Collaborator permission. I - Inferred permission
                conDocLink.ShareType = 'I';
                conDocLink.Visibility = 'AllUsers';

                // We can do all the inserts later
                conDocLinkInsert.add(conDocLink);
                System.debug(
                    'FetchInventorSignedDocJob disclosureId:- ' +
                    disclosureId +
                    ', inventorId:- ' +
                    inventorId +
                    ' CV END'
                );

                async.Has_Processed__c = true;
                asyncRequestUpdate.add(async);
            } catch (exception ex) {
                logExceptions.add(HandleLogException.logExceptionInstance(ex));

                async.Retry_Count__c =
                    Integer.valueOf(async.Retry_Count__c) + 1;
                async.Has_Processed__c = false;
                asyncRequestUpdate.add(async);
            }
        }
        if (!logExceptions.isEmpty()) {
            insert logExceptions;
        }

        if (!conDocLinkInsert.isEmpty()) {
            insert conDocLinkInsert;
        }
        if (!asyncRequestUpdate.isEmpty()) {
            update asyncRequestUpdate;
        }
    }

    public void finish(Database.BatchableContext bc) {
        System.debug(
            'FetchInventorSignedDocJob Finished JobId:- ' + bc.getJobId()
        );
    }
}