force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Has_Processed__c.field-meta.xml
<CustomField>
    <fullName>Has_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AsyncRequestHelper.cls
public with sharing class AsyncRequestHelper {

    // https://www.apexhours.com/generic-approach-to-salesforce-queueable/
    public static Async_Request__c prepareAsyncRequest(String recordId, String objectName, String jobName) {
        Async_Request__c asyn = new Async_Request__c();
        asyn.Has_Processed__c = false;
        asyn.Retry_Count__c = 0;
        asyn.Record_Id__c = recordId;
        asyn.sObject_Name__c = objectName;
        asyn.Job_Name__c = jobName;
        return asyn;
    }
}