force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Has_Processed__c.field-meta.xml
<CustomField>
    <fullName>Has_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Recid__c.field-meta.xml
<CustomField>
    <fullName>Contact_Recid__c</fullName>
    <externalId>true</externalId>
    <label>Forrester Contact RecID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <externalId>true</externalId>
    <label>MIT ID</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/Forrester_CONTACT__x.object-meta.xml
<CustomObject>
    <description>Forrester_CONTACT</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_CONTACT</externalName>
    <label>Forrester_CONTACT</label>
    <pluralLabel>Forrester_CONTACT</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_CONTACT__x/fields/ALTERNATE_IPIA_AGMT_DATE__c.field-meta.xml
<CustomField>
    <fullName>ALTERNATE_IPIA_AGMT_DATE__c</fullName>
    <description>ALTERNATE_IPIA_AGMT_DATE</description>
    <externalDeveloperName>ALTERNATE_IPIA_AGMT_DATE</externalDeveloperName>
    <label>ALTERNATE_IPIA_AGMT_DATE</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/fields/ALTERNATE_IPIA_AGMT_FLAG__c.field-meta.xml
<CustomField>
    <fullName>ALTERNATE_IPIA_AGMT_FLAG__c</fullName>
    <description>ALTERNATE_IPIA_AGMT_FLAG</description>
    <externalDeveloperName>ALTERNATE_IPIA_AGMT_FLAG</externalDeveloperName>
    <label>ALTERNATE_IPIA_AGMT_FLAG</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/fields/ALTERNATE_IPIA_TYPE__c.field-meta.xml
<CustomField>
    <fullName>ALTERNATE_IPIA_TYPE__c</fullName>
    <description>ALTERNATE_IPIA_TYPE</description>
    <externalDeveloperName>ALTERNATE_IPIA_TYPE</externalDeveloperName>
    <label>ALTERNATE_IPIA_TYPE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/fields/IPIA_COMMENT__c.field-meta.xml
<CustomField>
    <fullName>IPIA_COMMENT__c</fullName>
    <description>IPIA_COMMENT</description>
    <externalDeveloperName>IPIA_COMMENT</externalDeveloperName>
    <label>IPIA_COMMENT</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/fields/IPIA_SIGNED_DATE__c.field-meta.xml
<CustomField>
    <fullName>IPIA_SIGNED_DATE__c</fullName>
    <description>IPIA_SIGNED_DATE</description>
    <externalDeveloperName>IPIA_SIGNED_DATE</externalDeveloperName>
    <label>IPIA_SIGNED_DATE</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/fields/IPIA_SIGNED_FLAG__c.field-meta.xml
<CustomField>
    <fullName>IPIA_SIGNED_FLAG__c</fullName>
    <description>IPIA_SIGNED_FLAG</description>
    <externalDeveloperName>IPIA_SIGNED_FLAG</externalDeveloperName>
    <label>IPIA_SIGNED_FLAG</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/fields/MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>MIT_ID__c</fullName>
    <description>MIT_ID</description>
    <externalDeveloperName>MIT_ID</externalDeveloperName>
    <label>MIT_ID</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_IPIA_TYPES__x/Forrester_IPIA_TYPES__x.object-meta.xml
<CustomObject>
    <description>Forrester_IPIA_TYPES</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_IPIA_TYPES</externalName>
    <label>Forrester_IPIA_TYPE</label>
    <pluralLabel>Forrester_IPIA_TYPE</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_IPIA_TYPES__x/fields/IPIA_TYPE__c.field-meta.xml
<CustomField>
    <fullName>IPIA_TYPE__c</fullName>
    <description>IPIA_TYPE</description>
    <externalDeveloperName>IPIA_TYPE</externalDeveloperName>
    <label>IPIA Type</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Record__c/fields/Contact_Recid__c.field-meta.xml
<CustomField>
    <fullName>Contact_Recid__c</fullName>
    <label>Forrester Contact RecID</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/FormName__c.field-meta.xml
<CustomField>
    <fullName>FormName__c</fullName>
    <label>Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/IPIA_Type__c.field-meta.xml
<CustomField>
    <fullName>IPIA_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IPIA Type</label>
    <referenceTo>IPIA_Type__c</referenceTo>
    <relationshipLabel>IPIAs</relationshipLabel>
    <relationshipName>IPIA_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <label>MIT ID</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/SignDatetime__c.field-meta.xml
<CustomField>
    <fullName>SignDatetime__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IPIA_Type__c/IPIA_Type__c.object-meta.xml
<CustomObject>
    <label>IPIA Type</label>
    <nameField>
        <label>IPIA Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPIA Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Type__c/fields/Exemption__c.field-meta.xml
<CustomField>
    <fullName>Exemption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exemption</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IPIARecordUpsertJob.cls
public with sharing class IPIARecordUpsertJob implements Queueable, Database.AllowsCallouts {
    public final Set<Id> asyncRequestIdsList;
    public class IPIARecordSyncException extends Exception {
    }

    public IPIARecordUpsertJob(Set<Id> asyncRequestIdsList) {
        this.asyncRequestIdsList = asyncRequestIdsList;
    }

    public List<Async_Request__c> start(QueueableContext ctx) {
        System.debug('🐞 ~ IPIARecordUpsertJob:start ' + ctx.getJobId());
         Integer retryCount = Integer.ValueOf(
                ConfigurationBuilder.getConfigurationToString(
                    'batchJobMaxNumberOfRetry'
                )
            );
         List<Async_Request__c> asyncRequests = [SELECT
                            Id,
                            Has_Processed__c,
                            Retry_Count__c,
                            Record_Id__c,
                            sObject_Name__c,
                            Job_Name__c
                        FROM Async_Request__c
                        WHERE
                            Has_Processed__c = FALSE
                            AND Retry_Count__c < :retryCount
                            AND sObject_Name__c = 'IPIA_Record__c'
                            AND Job_Name__c = 'IPIASignedToForresterJob'
                            AND Id = :asyncRequestIdsList
                        ORDER BY Job_Name__c
                    ];

         return asyncRequests;
    }

    private List<Forrester_IPIA_TYPES__x> invalidExternalIpiaTypes(List<IPIA_Record__c> ipiaRecords ) {
        List<Forrester_IPIA_TYPES__x> ipiaTypes = new List<Forrester_IPIA_TYPES__x>();

        List<String> ipiaTypeNames = new List<String>();
        for (IPIA_Record__c ipiaRecord : ipiaRecords) {
          if (ipiaRecord.IPIA_Type__r.Exemption__c == true && ipiaRecord.IPIA_Type__r.Name != null) {
            ipiaTypeNames.add(ipiaRecord.IPIA_Type__r.Name);
          }
        }
        if (ipiaTypeNames.isEmpty()) {
            return ipiaTypes;
        }
        List<Forrester_IPIA_TYPES__x> externalIpiaTypes = ExternalObjectRepository.getExternalIpiaTypesByName(ipiaTypeNames);
        for(String ipiaTypeName : ipiaTypeNames) {
            Boolean exist = false;
            for (Forrester_IPIA_TYPES__x  externalIpiaType : externalIpiaTypes) {
                if (externalIpiaType.IPIA_TYPE__c == ipiaTypeName) {
                    exist = true;
                    break;
                }
            }
            if(!exist) {
                Forrester_IPIA_TYPES__x forresterIPIAType = new Forrester_IPIA_TYPES__x();
                forresterIPIAType.IPIA_TYPE__c = ipiaTypeName;
                ipiaTypes.add(forresterIPIAType);
            }
        }

        return ipiaTypes;
    }

    public void execute(QueueableContext ctx) {
        System.debug('🐞 ~ IPIARecordUpsertJob.execute');
        List<Async_Request__c> scope = start(ctx);

        Map<String, Async_Request__c> asyncRequestMap = new Map<String, Async_Request__c>();
        for(Async_Request__c asyncRequest : scope) {
            asyncRequestMap.put(asyncRequest.Record_Id__c, asyncRequest);
        }
        List<IPIA_Record__c> ipiaRecords = [
             SELECT Id, MitId__c, SignDatetime__c, IPIA_Type__r.Exemption__c ,IPIA_Type__r.Name, FormName__c, Contact_Recid__c
             FROM IPIA_Record__c
             WHERE Id IN :asyncRequestMap.keySet()
         ];

        if (!ipiaRecords.isEmpty()) {
            List<Forrester_IPIA_TYPES__x> insertIpiaTypes = invalidExternalIpiaTypes (ipiaRecords);
            // Lookup Map
            List<String> contactMitIds = new List<String>();
            for (IPIA_Record__c ipiaRecord : ipiaRecords) {
              contactMitIds.add(ipiaRecord.MitId__c);
            }
            Map<String, List<Forrester_CONTACT__x>> mitIdMap = new Map<String, List<Forrester_CONTACT__x>>();

            List<Forrester_CONTACT__x> externalContacts = ExternalObjectRepository.getExternalContactByMitIds(contactMitIds);
            for(Forrester_CONTACT__x forresterContact : externalContacts ) {
                if (!mitIdMap.containsKey(forresterContact.MIT_ID__c)) {
                    mitIdMap.put(forresterContact.MIT_ID__c, new List<Forrester_CONTACT__x>());
                }
                List<Forrester_CONTACT__x> mitIdContact = mitIdMap.get(forresterContact.MIT_ID__c);
                mitIdContact.add(forresterContact);
            }
            if (!insertIpiaTypes.isEmpty()) {
                // Cannot be async need to wait for types to exist. On retry will cover concurrent issues
                // A callout was unsuccessful because of pending uncommitted work
                // Setting up the unit test has uncommitted transactions.
                // There is no pending commit before this call
                if (!Test.isRunningTest()) {
                    Database.insertImmediate(insertIpiaTypes);
                }else {
                    Database.insertAsync(insertIpiaTypes);
                 }
            }
            List<IPIA_Record__c> updateIpiaRecords = new List<IPIA_Record__c>();
            List<Async_Request__c> asyncUpdateList = new List<Async_Request__c>();
            for (IPIA_Record__c ipiaRecord : ipiaRecords) {
                try {

                    // Lookup forrester contact
                    List<Forrester_CONTACT__x> forresterContacts = mitIdMap.get(ipiaRecord.MitId__c);

                    if (forresterContacts != null && forresterContacts.size() == 1) {
                        Forrester_CONTACT__x forresterContact = forresterContacts[0];
                        Integer maxLength = 4000;
                        String formName = (!String.isBlank(ipiaRecord.FormName__c)) ? ipiaRecord.FormName__c : '(no matching IPIA Type found)';
                        String formNameType = (!String.isBlank(ipiaRecord.IPIA_Type__r.Name)) ? ipiaRecord.IPIA_Type__r.Name : formName ;
                        forresterContact.IPIA_COMMENT__c = getIPIATypeComment(maxLength, forresterContact.IPIA_COMMENT__c, formNameType, ipiaRecord.SignDatetime__c);
                        if (ipiaRecord.IPIA_Type__r.Exemption__c == true) {
                            forresterContact.ALTERNATE_IPIA_AGMT_FLAG__c = 'Y';
                            forresterContact.ALTERNATE_IPIA_AGMT_DATE__c = Helpers.dateToEdmDateTimeOffset(ipiaRecord.SignDatetime__c);
                            forresterContact.ALTERNATE_IPIA_TYPE__c = ipiaRecord.IPIA_Type__r.Name;
                            // Blank Normal IPIA
                            forresterContact.IPIA_SIGNED_FLAG__c = 'N';
                            forresterContact.IPIA_SIGNED_DATE__c = null;

                        } else {
                            forresterContact.IPIA_SIGNED_FLAG__c = 'Y';
                            forresterContact.IPIA_SIGNED_DATE__c = Helpers.dateToEdmDateTimeOffset(ipiaRecord.SignDatetime__c);
                            // Blank Alternate IPIA
                            forresterContact.ALTERNATE_IPIA_AGMT_FLAG__c = 'N';
                            forresterContact.ALTERNATE_IPIA_AGMT_DATE__c = null;
                            forresterContact.ALTERNATE_IPIA_TYPE__c = null;
                        }
                        if (ipiaRecord.Contact_Recid__c != forresterContact.CONTACT_RECID__c) {
                            // WARNING: Dont add any new fields, this could cause infinite loop if triggered parent fields are also updated
                            ipiaRecord.Contact_Recid__c = forresterContact.CONTACT_RECID__c;
                            updateIpiaRecords.add(ipiaRecord);
                        }
                        System.debug('🐞 ~ IPIARecordUpsertJob.execute: updating forresterContact' + JSON.serializePretty(forresterContact));
                        Async_Request__c asyncRequest = asyncRequestMap.get(ipiaRecord.Id);
                        ForresterIPIAAsyncSaveHandler forresterIPIACallbackHandler = new ForresterIPIAAsyncSaveHandler(asyncRequest.Id);

                        ExternalObjectDatabase.updateAsync(forresterContact, forresterIPIACallbackHandler, AccessLevel.SYSTEM_MODE);
                    } else if (forresterContacts != null && forresterContacts.size() > 1) {
                        // TODO: What to do when more than one primary contact point email address exists for the same record?
                        IPIARecordSyncException multipleContactFound = new IPIARecordSyncException('Multiple forrester contact found for account with MIT ID ' + ipiaRecord.MitId__c);
                        throw multipleContactFound;
                    } else if (forresterContacts == null || forresterContacts.isEmpty()) {
                        // TODO create new Contact
                        System.debug('🐞 ~ IPIARecordUpsertJob.execute: No forrester contact found for account with MIT ID ' + ipiaRecord.MitId__c);
                        IPIARecordSyncException noContactFound = new IPIARecordSyncException('No forrester contact found for account with MIT ID ' + ipiaRecord.MitId__c);
                        throw noContactFound;
                    }
                } catch (Exception ex) {
                    System.debug('🐞 ~ IPIARecordUpsertJob.execute: Exception ex: ' + ex);
                    Async_Request__c asyncRequest = asyncRequestMap.get(ipiaRecord.Id);
                    asyncRequest.Retry_Count__c =  Integer.valueOf(asyncRequest.Retry_Count__c) + 1;
                    asyncUpdateList.add(asyncRequest);
                    HandleLogException.logException(ex);
                }
            }
            if (!updateIpiaRecords.isEmpty()) {
                update updateIpiaRecords;
            }
            if(!asyncUpdateList.isEmpty()) {
                update asyncUpdateList;
            }
        }
    }

    /*
        Create a comment and truncate the value if needed. When truncated an ellipsis is used to indicate it.
        Forrester can only store a value upto 4000 varchar2
    */
    @TestVisible
    private String getIPIATypeComment(Integer maxLength, String originalString, String ipiaTypeName, Date signedDate ) {

        String firstChar = '\n';
        if (originalString == null || originalString == '' ) {
            originalString = '';
            // If original String is empty we dont need a new line
            firstChar = '';
        }

        List<String> appendTexts = new List<String>{
            firstChar + 'Signed: ' + ipiaTypeName
        };

        String signedDateFormatted = Helpers.formatDateGMT(signedDate, 'MM/dd/yyyy');
        if (signedDateFormatted != null) {
            appendTexts.add(' Date: ' + signedDateFormatted);
        }

       // Calculate total length of all append texts
       Integer totalAppendLength = 0;
       for (String appendText : appendTexts) {
           totalAppendLength += appendText.length();
       }

       // Determine available length for the original string
       Integer availableLength = maxLength - totalAppendLength;
       String ellipsis = '';

       // Check if truncation is needed
       if (originalString.length() > availableLength) {
           ellipsis = '...';
           availableLength -= ellipsis.length();
           if (availableLength > 0) {
               originalString = originalString.substring(originalString.length() - availableLength);
           } else {
               originalString = '';
           }
       }

       // Build the final string
       String finalString = ellipsis + originalString;
       for (String appendText : appendTexts) {
           finalString += appendText;
       }

       System.debug('Final String (' + finalString.length() + ' chars): ' + finalString);
       return finalString;
    }

}