force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ASYN-{00000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/SubmittedOnBehalf__c.field-meta.xml
<CustomField>
    <fullName>SubmittedOnBehalf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted on behalf of someone else</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisclosureInventorSignedHandler.cls
public with sharing class DisclosureInventorSignedHandler {
    public static void handleInventorSigned(
        List<DisclosureInventor__c> inventorList
    ) {
        System.debug('DisclosureInventorSignedHandler START');
        if (inventorList != null && !inventorList.isEmpty()) {
            List<Async_Request__c> asyncJobsForInventorSigning = new List<Async_Request__c>();

            for (DisclosureInventor__c inventor : inventorList) {
                Boolean inventorMadeSigningDecision = (inventor.Signed_Status__c !=
                null &&
                inventor.Signed_Status__c != 'Pending');
                Boolean isSubmittingInventor =
                    inventor.Disclosure__r.Submitting_Contact__c ==
                    inventor.Contact__c;
                // Need to send Opt Out comment, and Signed Status to Forrester
                if (inventorMadeSigningDecision && !isSubmittingInventor) {
                    // The additional questions of the inventor who submitted the disclosure should not be sent to Forrester twice.
                    // they are already sent for the submitting inventor (inventor.Disclosure__r.Submitting_Contact__c)
                    // when Disclosure is approved -> if Disclosure.SubmittedOnBehalf__c == false.
                    asyncJobsForInventorSigning.add(
                        AsyncRequestHelper.prepareAsyncRequest(
                            inventor.Id,
                            'DisclosureInventor__c',
                            'InventorSignedDisclosureToForresterJob'
                        )
                    );
                }

                if (inventor.Signed_Status__c == 'Yes') {
                    //nothing to do against DocuSign of Forrester if inventor opted out
                    asyncJobsForInventorSigning.add(
                        AsyncRequestHelper.prepareAsyncRequest(
                            inventor.Id,
                            'DisclosureInventor__c',
                            'FetchInventorSignedDocJob'
                        )
                    );
                }
            }
            System.debug(
                'DisclosureInventorSignedHandler asyncJobsForInventorSigning:- ' +
                asyncJobsForInventorSigning
            );
            if (
                asyncJobsForInventorSigning != null &&
                !asyncJobsForInventorSigning.isEmpty()
            ) {
                System.debug(
                    'DisclosureInventorSignedHandler asyncJobsForInventorSigning.size():- ' +
                    asyncJobsForInventorSigning.size()
                );
                insert asyncJobsForInventorSigning;
            }
        }
        System.debug('DisclosureInventorSignedHandler FINISH');
    }
}