force-app/main/default/objects/Forrester_Case__x/Forrester_Case__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_VIEW</externalName>
    <label>Case</label>
    <pluralLabel>Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_NO_SUFFIX__c.field-meta.xml
<CustomField>
    <fullName>CASE_NO_SUFFIX__c</fullName>
    <description>CASE_NO_SUFFIX</description>
    <externalDeveloperName>CASE_NO_SUFFIX</externalDeveloperName>
    <label>Case No Suffix</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case RecId</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_STATUS__c.field-meta.xml
<CustomField>
    <fullName>CASE_STATUS__c</fullName>
    <description>CASE STATUS</description>
    <externalDeveloperName>CASE_STATUS</externalDeveloperName>
    <label>Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_SUFFIX__c.field-meta.xml
<CustomField>
    <fullName>CASE_SUFFIX__c</fullName>
    <description>CASE_SUFFIX</description>
    <externalDeveloperName>CASE_SUFFIX</externalDeveloperName>
    <label>Case Suffix</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CASE_TYPE__c</fullName>
    <description>CASE_TYPE</description>
    <externalDeveloperName>CASE_TYPE</externalDeveloperName>
    <label>Case Type</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CONCEPTION_DATE__c.field-meta.xml
<CustomField>
    <fullName>CONCEPTION_DATE__c</fullName>
    <description>CONCEPTION_DATE</description>
    <externalDeveloperName>CONCEPTION_DATE</externalDeveloperName>
    <label>Conception Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/DISCLOSURE_TITLE__c.field-meta.xml
<CustomField>
    <fullName>DISCLOSURE_TITLE__c</fullName>
    <description>DISCLOSURE_TITLE</description>
    <externalDeveloperName>DISCLOSURE_TITLE</externalDeveloperName>
    <label>Disclosure Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/OPEN_DATE__c.field-meta.xml
<CustomField>
    <fullName>OPEN_DATE__c</fullName>
    <description>OPEN_DATE</description>
    <externalDeveloperName>OPEN_DATE</externalDeveloperName>
    <label>Opened</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/SORT_ORDER__c.field-meta.xml
<CustomField>
    <fullName>SORT_ORDER__c</fullName>
    <description>SORT_ORDER</description>
    <externalDeveloperName>SORT_ORDER</externalDeveloperName>
    <label>Sort Order</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/STATUS__c.field-meta.xml
<CustomField>
    <fullName>STATUS__c</fullName>
    <description>STATUS</description>
    <externalDeveloperName>STATUS</externalDeveloperName>
    <label>Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CASE_INVENTOR_SHARE_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_INVENTOR_SHARE_VIEW</externalName>
    <label>Case Inventor Share</label>
    <pluralLabel>Case Inventor Shares</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case Recid</label>
    <length>12</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>Inventors</relationshipLabel>
    <relationshipName>Case_Inventor_Share</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/INVENTOR_NAME__c.field-meta.xml
<CustomField>
    <fullName>INVENTOR_NAME__c</fullName>
    <description>INVENTOR_NAME</description>
    <externalDeveloperName>INVENTOR_NAME</externalDeveloperName>
    <label>Name</label>
    <length>84</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/IS_PRIMARY_PI__c.field-meta.xml
<CustomField>
    <fullName>IS_PRIMARY_PI__c</fullName>
    <defaultValue>false</defaultValue>
    <description>IS_PRIMARY_PI</description>
    <externalDeveloperName>IS_PRIMARY_PI</externalDeveloperName>
    <label>Primary Inventor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/PREFERRED_EMAIL__c.field-meta.xml
<CustomField>
    <fullName>PREFERRED_EMAIL__c</fullName>
    <description>PREFERRED_EMAIL</description>
    <externalDeveloperName>PREFERRED_EMAIL</externalDeveloperName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_IP_VIEW__x/Forrester_SHIR_CASE_IP_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CASE_IP_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_IP_VIEW</externalName>
    <label>Case Patent</label>
    <pluralLabel>Case Patents</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CASE_IP_VIEW__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case</label>
    <length>24</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>Patents</relationshipLabel>
    <relationshipName>Case_Patents</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_IP_VIEW__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Case Contract Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_IP_VIEW__x/fields/COUNTRY_CODE__c.field-meta.xml
<CustomField>
    <fullName>COUNTRY_CODE__c</fullName>
    <description>COUNTRY_CODE</description>
    <externalDeveloperName>COUNTRY_CODE</externalDeveloperName>
    <label>Country Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_IP_VIEW__x/fields/FILE_DATE__c.field-meta.xml
<CustomField>
    <fullName>FILE_DATE__c</fullName>
    <description>FILE_DATE</description>
    <externalDeveloperName>FILE_DATE</externalDeveloperName>
    <label>File Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_IP_VIEW__x/fields/IP_TYPE_DESCRIPTION__c.field-meta.xml
<CustomField>
    <fullName>IP_TYPE_DESCRIPTION__c</fullName>
    <description>IP_TYPE_DESCRIPTION</description>
    <externalDeveloperName>IP_TYPE_DESCRIPTION</externalDeveloperName>
    <label>IP Type</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_IP_VIEW__x/fields/PATENT_ISSUED_DATE__c.field-meta.xml
<CustomField>
    <fullName>PATENT_ISSUED_DATE__c</fullName>
    <description>PATENT_ISSUED_DATE</description>
    <externalDeveloperName>PATENT_ISSUED_DATE</externalDeveloperName>
    <label>Patent Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_IP_VIEW__x/fields/PATENT_NUM__c.field-meta.xml
<CustomField>
    <fullName>PATENT_NUM__c</fullName>
    <description>PATENT_NUM</description>
    <externalDeveloperName>PATENT_NUM</externalDeveloperName>
    <label>Patent Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_IP_VIEW__x/fields/SERIAL_NUM__c.field-meta.xml
<CustomField>
    <fullName>SERIAL_NUM__c</fullName>
    <description>SERIAL_NUM</description>
    <externalDeveloperName>SERIAL_NUM</externalDeveloperName>
    <label>Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseVisibilityApiTest.cls
@IsTest
public class CaseVisibilityApiTest {
    @TestSetup
    static void setup() {
        TestSetup.defaultConfiguration();
    }

    static List<Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x > getExternalInventorMock() {
        List<Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x > mockRecords = new List<Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x >();
        Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x mockRecord = new Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x();
        mockRecord.CASE_RECID__c = '16235' ;
        mockRecord.MIT_ID__c = '910006320';
        mockRecord.CONTRACT_CASE_NUM__c = '9209L';
        mockRecord.IS_PRIMARY_PI__c = true;
        mockRecord.INVENTOR_NAME__c = 'Mr Inventor';
        mockRecord.PREFERRED_EMAIL__c = 'mrinventor@test.com';
        mockRecords.add(mockRecord);
        return mockRecords;
    }
    static List<Forrester_Case__x> getExternalCaseMock() {

        List<Forrester_Case__x> mockCaseRecords = new List<Forrester_Case__x>();
        Forrester_Case__x mockCaseRecord = new Forrester_Case__x();
        mockCaseRecord.CASE_RECID__c = '16235';
        mockCaseRecord.CONTRACT_CASE_NUM__c = '10368J';
        mockCaseRecord.CASE_NO_SUFFIX__c = '10368';
        mockCaseRecord.SORT_ORDER__c = '1';
        mockCaseRecord.CASE_SUFFIX__c = 'J';
        mockCaseRecord.CASE_TYPE__c = 'Invention';
        mockCaseRecord.DISCLOSURE_TITLE__c = 'DISCLOSURE_TITLE';
        mockCaseRecord.STATUS__c = 'Pre Closed';
        mockCaseRecord.CASE_STATUS__c = 'Active';
        mockCaseRecord.OPEN_DATE__c = Date.newInstance(2025, 7, 7);
        mockCaseRecord.CONCEPTION_DATE__c = DateTime.now();
        mockCaseRecords.add(mockCaseRecord);
        return mockCaseRecords;

    }
    static List<Forrester_SHIR_CASE_IP_VIEW__x> getExternalPatentMock() {
        List<Forrester_SHIR_CASE_IP_VIEW__x> mockPatentRecords = new List<Forrester_SHIR_CASE_IP_VIEW__x>();
        Forrester_SHIR_CASE_IP_VIEW__x mockPatentRecord = new Forrester_SHIR_CASE_IP_VIEW__x();
        mockPatentRecord.SERIAL_NUM__c = '08/486806';
        mockPatentRecord.FILE_DATE__c = DateTime.now().date();
        mockPatentRecord.IP_STATUS_DESCRIPTION__c = 'Granted';
        mockPatentRecord.IP_TYPE_DESCRIPTION__c = 'Patent Cooperation Treaty';
        mockPatentRecord.PATENT_NUM__c = '11/662551';
        mockPatentRecord.PATENT_ISSUED_DATE__c =  DateTime.now().date();
        mockPatentRecord.PUB_NUMBER__c = 'WO89/007136';
        mockPatentRecord.COUNTRY_CODE__c = 'US,NL';
        mockPatentRecord.COUNTRY_NAME__c = 'United States of America,Netherlands';
        mockPatentRecord.DESIGNATED_COUNTRIES__c = 'US;NL';
        mockPatentRecords.add(mockPatentRecord);
        return mockPatentRecords;

    }

    static void mockExternalCases() {
        List<Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x > mockRecords = getExternalInventorMock();
        List<Forrester_Case__x> mockCaseRecords = getExternalCaseMock();
        StackExternalMock externalMock = new StackExternalMock();
        externalMock.push(mockCaseRecords);
        externalMock.push(mockRecords);

        ExternalObjectQuery.setMock(externalMock);
    }

    static void mockExternalCaseDetail() {
        List<Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x > mockRecords = getExternalInventorMock();
        List<Forrester_Case__x> mockCaseRecords = getExternalCaseMock();
        StackExternalMock externalMock = new StackExternalMock();
        externalMock.push(mockRecords);
        externalMock.push(mockCaseRecords);

        ExternalObjectQuery.setMock(externalMock);
    }

    @IsTest
    static void caseVisibilityCasesByMitIdTest() {
        mockExternalCases();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = '/api/cases/v1/';
        req.httpMethod = 'GET';
        req.params.put('page', '1');
        req.params.put('pageSize', '10');
        req.params.put('mitId', '900053951');
        req.params.put('nameSearch', 'TITLE');
        req.params.put('filters', 'caseStatus:Active,caseType:Invention,openDate>2003-06-20');

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        CaseVisibilityCasesApi.getCases();
        System.assert(res.statusCode == 200, 'HTTP Status Code should be 200');
        String body = String.valueOf(RestContext.response.responseBody);
        System.debug(body);
        Test.stopTest();
    }

    @IsTest
    static void caseVisibilityCasesByCurrentUserTest() {
        mockExternalCases();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = '/api/cases/v1/';
        req.httpMethod = 'GET';
        req.params.put('page', '1');
        req.params.put('pageSize', '10');

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        System.runAs(SampleDataTest.getJitUser()) {
            String mitId = CaseVisibilityCasesApi.getContextMitId();
            System.assert(mitId == '02345678', 'Current Account MitId should be used');
            CaseVisibilityCasesApi.getCases();
            String body = String.valueOf(RestContext.response.responseBody);
            System.debug(body);
            System.assert(RestContext.response.statusCode == 200, 'HTTP Status Code should be 200 found ' + res.statusCode);
        }

        Test.stopTest();
    }


    @IsTest
    static void caseVisibilityCaseDetailByMitIdTest() {
        mockExternalCaseDetail();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = '/api/cases/detail/v1/';
        req.httpMethod = 'GET';
        req.params.put('caseNumber', '10368');
        req.params.put('mitId', '900053951');

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        CaseVisibilityCaseDetailApi.getCaseByCaseNumber();
        System.assert(RestContext.response.statusCode == 200, 'HTTP Status Code should be 200');
        String body = String.valueOf(RestContext.response.responseBody);
        System.debug(body);
        Test.stopTest();
    }

    @IsTest
    static void caseVisibilityPatentByCaseNumberTest() {
        List<Forrester_SHIR_CASE_IP_VIEW__x > mockRecords = getExternalPatentMock();
        StackExternalMock externalMock = new StackExternalMock();
        externalMock.push(mockRecords);
        ExternalObjectQuery.setMock(externalMock);

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = '/api/cases/detail/patents/v1/';
        req.httpMethod = 'GET';
        req.params.put('caseNumber', '10368');
        req.params.put('mitId', '900053951');

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        CaseVisibilityPatentsApi.getCasePatentsByCaseNumber();
        System.assert(RestContext.response.statusCode == 200, 'HTTP Status Code should be 200');
        String body = String.valueOf(RestContext.response.responseBody);
        System.debug(body);
        Test.stopTest();
    }

    @IsTest
    static void caseVisibilityInventorByCaseNumberTest() {
        List<Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x > mockRecords = getExternalInventorMock();
        StackExternalMock externalMock = new StackExternalMock();
        externalMock.push(mockRecords);
        ExternalObjectQuery.setMock(externalMock);

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = '/api/cases/detail/inventors/v1/';
        req.httpMethod = 'GET';
        req.params.put('caseNumber', '9209L');

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        CaseVisibilityInventorsApi.getCaseInventorsByCaseNumber();
        System.assert(RestContext.response.statusCode == 200, 'HTTP Status Code should be 200');
        String body = String.valueOf(RestContext.response.responseBody);
        System.debug(body);
        Test.stopTest();
    }
}