force-app/main/default/objects/Forrester_Case__x/Forrester_Case__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_VIEW</externalName>
    <label>Case</label>
    <pluralLabel>Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case__x/fields/STATUS__c.field-meta.xml
<CustomField>
    <fullName>STATUS__c</fullName>
    <description>STATUS</description>
    <externalDeveloperName>STATUS</externalDeveloperName>
    <label>Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/Utilization_Commercial_Prods__c.object-meta.xml
<CustomObject>
    <description>The FDA Approved Commercial products for the utilization with fiscal year prior 2023.</description>
    <label>Utilization Commercial Prod</label>
    <nameField>
        <label>Utilization Commercial Prods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Commercial Prods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Commercial_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Name__c</fullName>
    <label>Commercial Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Fda_Approval_Number__c.field-meta.xml
<CustomField>
    <fullName>Fda_Approval_Number__c</fullName>
    <label>Fda Approval Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Fda_Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Fda_Approval_Type__c</fullName>
    <label>Fda Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biologic</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>Drug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Govt_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Govt_Review_Status__c</fullName>
    <label>Govt Review Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Public_Ind__c.field-meta.xml
<CustomField>
    <fullName>Public_Ind__c</fullName>
    <label>Public Ind</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Commercial_Prods__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipLabel>Utilization Commercial Prods</relationshipLabel>
    <relationshipName>Utilization_Commercial_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/Utilization_Licensee__c.object-meta.xml
<CustomObject>
    <description>Licensee with license counts</description>
    <label>Utilization Licensee</label>
    <nameField>
        <label>Licensee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee__c/fields/Exclusive_Count__c.field-meta.xml
<CustomField>
    <fullName>Exclusive_Count__c</fullName>
    <label>Exclusive Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/fields/Licensee_Name__c.field-meta.xml
<CustomField>
    <fullName>Licensee_Name__c</fullName>
    <label>Licensee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/fields/Non_Exclusive_Count__c.field-meta.xml
<CustomField>
    <fullName>Non_Exclusive_Count__c</fullName>
    <label>Non Exclusive Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipName>Utilization_Licensee_Counts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/Utilization_Licensee_Man_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>Junction box object to link (many to many) licensees with m Manufaturing Comm Prods</description>
    <label>Utilization Licensee Man Comm Prod</label>
    <nameField>
        <label>Utilization Licensee Man Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensee Man Comm Prod</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/fields/Utilization_Licensee__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Licensee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Licensee</label>
    <referenceTo>Utilization_Licensee__c</referenceTo>
    <relationshipName>Utilization_Licensees1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/fields/Utilization_Manufacturing_Comm_Prod__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Manufacturing_Comm_Prod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Manufacturing Comm Prod</label>
    <referenceTo>Utilization_Manufacturing_Comm_Prod__c</referenceTo>
    <relationshipName>Utilization_Manufacturing_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/Utilization_Manufacturing_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>The manufacturing commercial products</description>
    <label>Utilization Manufacturing Comm Prod</label>
    <nameField>
        <label>Utilization Manufacturing Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturing Comm Prods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipLabel>Utilization Manufacturing Comm Prods</relationshipLabel>
    <relationshipName>Utilization_Manufacturing_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Commercialization_Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Commercialization_Plan_Id__c</fullName>
    <label>Commercialization Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Seeking additional funding to further develop this invention</label>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>Marketing and/or furthering development of this invention to attract commercial
                    partners</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Developing and/or using this invention for internal purposes only</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Developing and/or preparing this invention with intent to commercialize ourselves</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Making available for distribution and/or licensing for research purposes only</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>No current commercialization plan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Funding_Agency__c.field-meta.xml
<CustomField>
    <fullName>Funding_Agency__c</fullName>
    <label>Agency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_1__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_1__c</fullName>
    <label>Is US Manufacturing Required 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_2__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_2__c</fullName>
    <label>Is US Manufacturing Required 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Is_US_Manufacturing_Required_3__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Manufacturing_Required_3__c</fullName>
    <label>Is US Manufacturing Required 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Latest_Stage_of_Development__c</fullName>
    <label>Latest Stage of Development</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Commercialized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Companies__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Companies__c</fullName>
    <label>New US Companies</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/New_Us_Jobs__c.field-meta.xml
<CustomField>
    <fullName>New_Us_Jobs__c</fullName>
    <label>New US Jobs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Status__c</fullName>
    <description>Status</description>
    <label>Utilization Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Include for Utilization</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report_Config__c/Utilization_Report_Config__c.object-meta.xml
<CustomObject>
    <label>Utilization Reports FY Config</label>
    <nameField>
        <displayFormat>URC-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports FY Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report_Config__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ComplianceUtilizationReportController.cls
/**
 * Created by Andreas du Preez on 2024/10/28.
 */

public with sharing class ComplianceUtilizationReportController {

    @AuraEnabled
    public static ComplianceUtilizationReportController.UtilizationReportValidationResult validateUtilizationReport(Id recordId) {
        return ComplianceUtilizationReportService.validateComplianceUtilizationReport(recordId);
    }

    @AuraEnabled
    public static UtilizationReportWrapper getUtilizationReport(Id recordId) {
        return getUtilizationReportBulk(new List<Id>{recordId})[0];
    }

    @AuraEnabled
    public static List<UtilizationReportWrapper> getUtilizationReportBulk(List<Id> recordIds) {
        List<UtilizationReportWrapper> UtilizationReportWrappers = new List<UtilizationReportWrapper>();
        Map<Id, List<Utilization_Commercial_Prods__c>> commercialProdsMap = new Map<Id, List<Utilization_Commercial_Prods__c>>();
        Map<Id, List<Utilization_Licensee__c>> licenseeMap = new Map<Id, List<Utilization_Licensee__c>>();
        Map<Id, List<Utilization_Manufacturing_Comm_Prod__c>> manufacturingCommProdMap = new Map<Id, List<Utilization_Manufacturing_Comm_Prod__c>>();

        List<CommProdWrapper> manufacturingCommProdsWrappers = new List<CommProdWrapper>();

        List<Utilization_Report__c> utilizationReports = [
                SELECT
                        Id,
                        Funding_Agency__c,
                        Latest_Stage_of_Development__c,
                        Commercialization_Plan_Id__c,
                        Notes__c,
                        Is_US_Manufacturing_Required_1__c,
                        Is_US_Manufacturing_Required_2__c,
                        Is_US_Manufacturing_Required_3__c,
                        New_Us_Companies__c,
                        New_Us_Jobs__c,
                        Utilization_Report_Status__c
                FROM Utilization_Report__c
                WHERE Id IN :recordIds
        ];

        List<Utilization_Report_Config__c> utilizationReportConfig = [
                SELECT
                        Id,
                        Name,
                        End_Date__c,
                        Fiscal_Year__c,
                        Start_Date__c
                FROM Utilization_Report_Config__c
                LIMIT 1
        ];

        List<Utilization_Commercial_Prods__c> commercialProds = [
                SELECT
                        Id,
                        Name,
                        Commercial_Name__c,
                        Fda_Approval_Number__c,
                        Fda_Approval_Type__c,
                        Govt_Review_Status__c,
                        Public_Ind__c,
                        Utilization_Report__c
                FROM Utilization_Commercial_Prods__c
                WHERE Utilization_Report__c IN :recordIds
        ];

        for (Utilization_Commercial_Prods__c commercialProd : commercialProds) {
            if (!commercialProdsMap.containsKey(commercialProd.Utilization_Report__c)) {
                commercialProdsMap.put(commercialProd.Utilization_Report__c, new List<Utilization_Commercial_Prods__c>());
            }
            commercialProdsMap.get(commercialProd.Utilization_Report__c).add(commercialProd);
        }

        List<Utilization_Licensee__c> licensees = new List<Utilization_Licensee__c>([
                SELECT
                        Id,
                        Licensee_Name__c,
                        Exclusive_Count__c,
                        Non_Exclusive_Count__c,
                        Small_Business__c,
                        Utilization_Report__c
                FROM Utilization_Licensee__c
                WHERE Utilization_Report__c IN :recordIds
        ]);

        for (Utilization_Licensee__c licensee : licensees) {
            if (!licenseeMap.containsKey(licensee.Utilization_Report__c)) {
                licenseeMap.put(licensee.Utilization_Report__c, new List<Utilization_Licensee__c>());
            }
            licenseeMap.get(licensee.Utilization_Report__c).add(licensee);
        }

        List<Utilization_Manufacturing_Comm_Prod__c> manufacturingCommProds = [
                SELECT
                        Id,
                        Product_Name__c,
                        Naics_Code__c,
                        Utilization_Report__c,
                        (
                                SELECT
                                        Id,
                                        Utilization_Licensee__c,
                                        Utilization_Manufacturing_Comm_Prod__c,
                                        (
                                                SELECT
                                                        Id,
                                                        Manufacturer_Name__c,
                                                        (
                                                                SELECT
                                                                        Id,
                                                                        Country__c,
                                                                        First_Date__c,
                                                                        First_Date_Type__c,
                                                                        State__c,
                                                                        Product_Quantity__c,
                                                                        Utilization_Manufacturer__c
                                                                FROM Utilization_Product_Locations__r
                                                        )
                                                FROM Utilization_Licensee_Man_Comm_Prods__r
                                        )
                                FROM Utilization_Manufacturing_Comm_Prods__r
                        )
                FROM Utilization_Manufacturing_Comm_Prod__c
                WHERE Utilization_Report__c IN :recordIds
        ];

        for (Utilization_Manufacturing_Comm_Prod__c manufacturingCommProd : manufacturingCommProds) {
            if (!manufacturingCommProdMap.containsKey(manufacturingCommProd.Utilization_Report__c)) {
                manufacturingCommProdMap.put(manufacturingCommProd.Utilization_Report__c, new List<Utilization_Manufacturing_Comm_Prod__c>());
            }
            manufacturingCommProdMap.get(manufacturingCommProd.Utilization_Report__c).add(manufacturingCommProd);
        }

        // Create UtilizationReportWrapper objects
        for (Utilization_Report__c utilizationReport : utilizationReports) {
            if (manufacturingCommProdMap.size() > 0) {
                for (Utilization_Manufacturing_Comm_Prod__c manufacturingCommProd : manufacturingCommProdMap.get(utilizationReport.Id)) {
                    CommProdWrapper commProdWrapper = new CommProdWrapper();

                    List<LicenseeProductWrapper> licenseeProductWrappers = new List<LicenseeProductWrapper>();
                    for (Utilization_Licensee_Man_Comm_Prod__c licenseeProduct : manufacturingCommProd.Utilization_Manufacturing_Comm_Prods__r) {
                        LicenseeProductWrapper licenseeProductWrapper = new LicenseeProductWrapper();

                        List<ManufacturerWrapper> manufacturerWrappers = new List<ManufacturerWrapper>();
                        for (Utilization_Manufacturers__c manufacturer : licenseeProduct.Utilization_Licensee_Man_Comm_Prods__r) {
                            ManufacturerWrapper manufacturerWrapper = new ManufacturerWrapper();

                            Utilization_Manufacturers__c manufacturerCopy = new Utilization_Manufacturers__c(Id = manufacturer.Id, Manufacturer_Name__c = manufacturer.Manufacturer_Name__c);
                            manufacturerWrapper.manufacturer = manufacturerCopy;
                            manufacturerWrapper.manufacturerProductLocations = manufacturer.Utilization_Product_Locations__r;
                            manufacturerWrappers.add(manufacturerWrapper);
                        }

                        Utilization_Licensee_Man_Comm_Prod__c licenseeProductCopy = new Utilization_Licensee_Man_Comm_Prod__c(Id = licenseeProduct.Id, Utilization_Licensee__c = licenseeProduct.Utilization_Licensee__c, Utilization_Manufacturing_Comm_Prod__c = licenseeProduct.Utilization_Manufacturing_Comm_Prod__c);
                        licenseeProductWrapper.licenseeProduct = licenseeProductCopy;
                        licenseeProductWrapper.licenseeManufacturers = manufacturerWrappers;
                        licenseeProductWrappers.add(licenseeProductWrapper);
                    }

                    Utilization_Manufacturing_Comm_Prod__c manufacturingCommProdCopy = new Utilization_Manufacturing_Comm_Prod__c(Id = manufacturingCommProd.Id, Product_Name__c = manufacturingCommProd.Product_Name__c, Naics_Code__c = manufacturingCommProd.Naics_Code__c, Utilization_Report__c = manufacturingCommProd.Utilization_Report__c);
                    commProdWrapper.commercialProd = manufacturingCommProdCopy;
                    commProdWrapper.licenseesProducts = licenseeProductWrappers;
                    manufacturingCommProdsWrappers.add(commProdWrapper);
                }
            }

            UtilizationReportWrapper utilizationReportWrapper = new UtilizationReportWrapper(utilizationReport,
                    utilizationReportConfig.size() == 1 ? utilizationReportConfig[0] : null,
                    commercialProdsMap.containsKey(utilizationReport.Id) ? commercialProdsMap.get(utilizationReport.Id) : new List<Utilization_Commercial_Prods__c>(),
                    licenseeMap.containsKey(utilizationReport.Id) ? licenseeMap.get(utilizationReport.Id): new List<Utilization_Licensee__c>(),
                    manufacturingCommProdsWrappers);

            UtilizationReportWrappers.add(utilizationReportWrapper);
        }

        return UtilizationReportWrappers;
    }

    @AuraEnabled
    public static ComplianceUtilizationReportController.UtilizationReportValidationResult saveUtilizationReport(UtilizationReportWrapper utilizationReport, Boolean doValidation) {
        if (utilizationReport.utilizationReport.Utilization_Report_Status__c == 'In Progress') {
            List<String> errorMessages = new List<String>();
            errorMessages.add('Utilization report in progress of being submitted');
            return new ComplianceUtilizationReportController.UtilizationReportValidationResult(false, errorMessages);
        }

        if (doValidation) {
            ComplianceUtilizationReportController.UtilizationReportValidationResult validationResult = ComplianceUtilizationReportService.validateUtilizationReport(utilizationReport);
            if (!validationResult.isValid) {
                return validationResult;
            }
        }

        if (utilizationReport.utilizationReport.Utilization_Report_Status__c == 'Completed' || utilizationReport.utilizationReport.Utilization_Report_Status__c == 'Error') {
            utilizationReport.utilizationReport.Utilization_Report_Status__c = 'New';
        }
        
        return ComplianceUtilizationReportService.saveUtilizationReport(utilizationReport);
    }

    @AuraEnabled(cacheable=true)
    public static List<Utilization_Report__c> getUtilizationReports(Id forresterCaseId) {
        // Retrieve CASE_RECID__c from Forrester_Case__x where Id matches the provided caseId
        Forrester_Case__x forresterCase = [
                SELECT CASE_RECID__c
                FROM Forrester_Case__x
                WHERE Id = :forresterCaseId
                LIMIT 1
        ];
        // Query Utilization_Report__c records where Case matches CASE_RECID__c
        return [
                SELECT Id, Name, Utilization_Report_Status__c, CreatedDate,
                        Reporting_Year__c, Invention_Report_Number__c
                FROM Utilization_Report__c
                WHERE Case_RecId__c = :forresterCase.CASE_RECID__c
        ];
    }


    // ------------------------------
    // Wrapper classes
    // ------------------------------
    public class UtilizationReportWrapper {
        public UtilizationReportWrapper() {
            this.commercialProds = new List<Utilization_Commercial_Prods__c>();
            this.commercialProdsToDelete = new List<Utilization_Commercial_Prods__c>();
            this.licensees = new List<Utilization_Licensee__c>();
            this.manufacturingCommProds = new List<CommProdWrapper>();
            this.manufacturingCommProdsToDelete = new List<CommProdWrapper>();
        }

        public UtilizationReportWrapper(Utilization_Report__c utilizationReport,
                Utilization_Report_Config__c utilizationReportConfig,
                List<Utilization_Commercial_Prods__c> commercialProds,
                List<Utilization_Licensee__c> licensees,
                List<CommProdWrapper> manufacturingCommProds
        ) {
            this.utilizationReport = utilizationReport;
            this.utilizationReportConfig = utilizationReportConfig;
            this.commercialProds = commercialProds;
            this.licensees = licensees;
            this.manufacturingCommProds = manufacturingCommProds;
        }

        @AuraEnabled
        public Utilization_Report__c utilizationReport { get; set; }
        @AuraEnabled
        public Utilization_Report_Config__c utilizationReportConfig { get; set; }
        @AuraEnabled
        public List<Utilization_Commercial_Prods__c> commercialProds { get; set; }
        @AuraEnabled
        public List<Utilization_Commercial_Prods__c> commercialProdsToDelete { get; set; }
        @AuraEnabled
        public List<Utilization_Licensee__c> licensees { get; set; }
        @AuraEnabled
        public List<CommProdWrapper> manufacturingCommProds { get; set; }
        @AuraEnabled
        public List<CommProdWrapper> manufacturingCommProdsToDelete { get; set; }
    }

    public class CommProdWrapper {
        public CommProdWrapper() {
            this.licenseesProducts = new List<LicenseeProductWrapper>();
            this.licenseesProductsToDelete = new List<LicenseeProductWrapper>();
        }
        public CommProdWrapper(Utilization_Manufacturing_Comm_Prod__c commercialProd, List<LicenseeProductWrapper> licenseesProducts, List<LicenseeProductWrapper> licenseesProductsToDelete) {
            this.commercialProd = commercialProd;
            this.licenseesProducts = licenseesProducts;
            this.licenseesProductsToDelete = licenseesProductsToDelete;
        }

        @AuraEnabled
        public Utilization_Manufacturing_Comm_Prod__c commercialProd { get; set; }
        @AuraEnabled
        public List<LicenseeProductWrapper> licenseesProducts { get; set; }
        @AuraEnabled
        public List<LicenseeProductWrapper> licenseesProductsToDelete { get; set; }
    }

    public class LicenseeProductWrapper {
        public LicenseeProductWrapper() {
            this.licenseeManufacturers = new List<ManufacturerWrapper>();
            this.licenseeManufacturersToDelete = new List<ManufacturerWrapper>();
        }
        public LicenseeProductWrapper(Utilization_Licensee_Man_Comm_Prod__c licenseeProduct, List<ManufacturerWrapper> licenseeManufacturers, List<ManufacturerWrapper> licenseeManufacturersToDelete) {
            this.licenseeProduct = licenseeProduct;
            this.licenseeManufacturers = licenseeManufacturers;
            this.licenseeManufacturersToDelete = licenseeManufacturersToDelete;
        }

        @AuraEnabled
        public Utilization_Licensee_Man_Comm_Prod__c licenseeProduct { get; set; }
        @AuraEnabled
        public List<ManufacturerWrapper> licenseeManufacturers { get; set; }
        @AuraEnabled
        public List<ManufacturerWrapper> licenseeManufacturersToDelete { get; set; }
    }

    public class ManufacturerWrapper {
        public ManufacturerWrapper() {
            this.manufacturerProductLocations = new List<Utilization_Product_Location__c>();
            this.manufacturerProductLocationsToDelete = new List<Utilization_Product_Location__c>();
        }
        public ManufacturerWrapper(Utilization_Manufacturers__c manufacturer, List<Utilization_Product_Location__c> manufacturerProductLocations, List<Utilization_Product_Location__c> manufacturerProductLocationsToDelete) {
            this.manufacturer = manufacturer;
            this.manufacturerProductLocations = manufacturerProductLocations;
            this.manufacturerProductLocationsToDelete = manufacturerProductLocationsToDelete;
        }

        @AuraEnabled
        public Utilization_Manufacturers__c manufacturer { get; set; }
        @AuraEnabled
        public List<Utilization_Product_Location__c> manufacturerProductLocations { get; set; }
        @AuraEnabled
        public List<Utilization_Product_Location__c> manufacturerProductLocationsToDelete { get; set; }
    }

    public class UtilizationReportValidationResult {
        public UtilizationReportValidationResult(Boolean isValid, List<String> errorMessage) {
            this.isValid = isValid;
            this.errorMessages = errorMessage;
        }
        @AuraEnabled
        public Boolean isValid { get; set; }
        @AuraEnabled
        public List<String> errorMessages { get; set; }
    }

    @AuraEnabled(cacheable=true)
    public static List<Forrester_Case__x> getCasesRelatedToUtilizationReport(Id utilizationReportId) {
        try {
            // Retrieve the Case_RecId__c from the provided Utilization_Report__c record
            Utilization_Report__c utilizationReport = [
                SELECT Case_RecId__c
                FROM Utilization_Report__c
                WHERE Id = :utilizationReportId
                LIMIT 1
            ];

            // Ensure Case_RecId__c is not null
            if (utilizationReport == null || utilizationReport.Case_RecId__c == null) {
                return new List<Forrester_Case__x>();
            }

            // Query all Forrester_Case__x records where CASE_RECID__c matches the Utilization Report's Case_RecId__c
            String recId = utilizationReport.Case_RecId__c;

                // Query all Forrester_Case__x records where CASE_RECID__c matches the Utilization Report's Case_RecId__c
                List<Forrester_Case__x> cases = [
                    SELECT Id, CASE_RECID__c, STATUS__c, DISCLOSURE_TITLE__c, CONTRACT_CASE_NUM__c,
                    OWNERSHIP_TYPE__c, OPEN_DATE__c, CLOSE_DATE__c, CASE_TYPE__c, TLO_NAME__c
                    FROM Forrester_Case__x
                    WHERE CASE_RECID__c = :recId
                ];

            return cases != null ? cases : new List<Forrester_Case__x>();
        } catch (Exception e) {
            // Log the exception and throw a meaningful message back to the client
            throw new AuraHandledException('An error occurred while fetching cases: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Integer getTotalCasesForUtilizationReports() {
        try {
            // Query all Utilization Reports meeting the criteria
            List<Utilization_Report__c> utilizationReports = [
                SELECT Case_RecId__c
                FROM Utilization_Report__c
                WHERE Case_RecId__c != null 
                AND Utilization_Report_Status__c = 'Include for Utilization'
            ];
    
            // Extract unique Case_RecId__c values into a Set
            Set<String> caseRecIds = new Set<String>();
            for (Utilization_Report__c report : utilizationReports) {
                caseRecIds.add(report.Case_RecId__c);
            }
    
            // If no Case_RecId__c values are found, return 0
            if (caseRecIds.isEmpty()) {
                return 0;
            }
    
            // Query Forrester_Case__x records matching the Case_RecId__c values
            Integer caseCount = [
                SELECT COUNT()
                FROM Forrester_Case__x
                WHERE CASE_RECID__c IN :caseRecIds
            ];
    
            // Return the total count
            return caseCount;
    
        } catch (Exception e) {
            // Log the exception and throw a meaningful message back to the client
            System.debug('Error fetching case count: ' + e.getMessage());
            throw new AuraHandledException('An error occurred while counting cases: ' + e.getMessage());
        }
    }
    


    @AuraEnabled
    public static String executeUtilizationReportBatch() {
        try {
            CreateUtilizationReportJob utilizationReportJob = new CreateUtilizationReportJob();
            Database.executeBatch(utilizationReportJob, 20);
            return 'Success';
        } catch (Exception e) {
            throw new AuraHandledException('Error submitting cases: ' + e.getMessage());
        }
    }

}