force-app/main/default/objects/Forrester_Case__x/Forrester_Case__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_VIEW</externalName>
    <label>Case</label>
    <pluralLabel>Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case RecId</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/Utilization_Licensee__c.object-meta.xml
<CustomObject>
    <description>Licensee with license counts</description>
    <label>Utilization Licensee</label>
    <nameField>
        <label>Licensee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee__c/fields/Exclusive_Count__c.field-meta.xml
<CustomField>
    <fullName>Exclusive_Count__c</fullName>
    <label>Exclusive Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/fields/Licensee_Name__c.field-meta.xml
<CustomField>
    <fullName>Licensee_Name__c</fullName>
    <label>Licensee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/fields/Non_Exclusive_Count__c.field-meta.xml
<CustomField>
    <fullName>Non_Exclusive_Count__c</fullName>
    <label>Non Exclusive Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/fields/Small_Business__c.field-meta.xml
<CustomField>
    <fullName>Small_Business__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Small Business</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipName>Utilization_Licensee_Counts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/Utilization_Licensee_Man_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>Junction box object to link (many to many) licensees with m Manufaturing Comm Prods</description>
    <label>Utilization Licensee Man Comm Prod</label>
    <nameField>
        <label>Utilization Licensee Man Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensee Man Comm Prod</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/fields/Utilization_Licensee__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Licensee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Licensee</label>
    <referenceTo>Utilization_Licensee__c</referenceTo>
    <relationshipName>Utilization_Licensees1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/fields/Utilization_Manufacturing_Comm_Prod__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Manufacturing_Comm_Prod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Manufacturing Comm Prod</label>
    <referenceTo>Utilization_Manufacturing_Comm_Prod__c</referenceTo>
    <relationshipName>Utilization_Manufacturing_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturers__c/Utilization_Manufacturers__c.object-meta.xml
<CustomObject>
    <description>The manufacturers for the manufacturing commercial product</description>
    <label>Utilization Manufacturer</label>
    <nameField>
        <label>Utilization Manufacturers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Manufacturers__c/fields/Manufacturer_Name__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Name__c</fullName>
    <label>Manufacturer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturers__c/fields/Utilization_Licensee_Man_Comm_Prod__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Licensee_Man_Comm_Prod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Manufaturing Comm Prod</label>
    <referenceTo>Utilization_Licensee_Man_Comm_Prod__c</referenceTo>
    <relationshipLabel>Utilization Licensee Man Comm Prod</relationshipLabel>
    <relationshipName>Utilization_Licensee_Man_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/Utilization_Manufacturing_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>The manufacturing commercial products</description>
    <label>Utilization Manufacturing Comm Prod</label>
    <nameField>
        <label>Utilization Manufacturing Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturing Comm Prods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/fields/Naics_Code__c.field-meta.xml
<CustomField>
    <fullName>Naics_Code__c</fullName>
    <label>Naics Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/fields/Utilization_Report__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Report</label>
    <referenceTo>Utilization_Report__c</referenceTo>
    <relationshipLabel>Utilization Manufacturing Comm Prods</relationshipLabel>
    <relationshipName>Utilization_Manufacturing_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Product_Location__c/Utilization_Product_Location__c.object-meta.xml
<CustomObject>
    <description>The manufacturing production location(s)</description>
    <label>Utilization Product Location</label>
    <nameField>
        <label>Utilization Product Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Product Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Product_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>OAPI</fullName>
                <label>African Manufacturer Intellectual Property Organization</label>
            </value>
            <value>
                <fullName>ARIPO</fullName>
                <label>African Regional Manufacturer Intellectual Property Organization</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AV</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AC</fullName>
                <label>Antigua/Barbud</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AA</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AJ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BK</fullName>
                <label>Bosnia/Herzeg</label>
            </value>
            <value>
                <fullName>BC</fullName>
                <label>Botswana</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>VI</fullName>
                <label>British Vi Iss</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Product_Location__c/fields/Utilization_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Manufacturer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Manufacturer</description>
    <label>Utilization Manufacturer</label>
    <referenceTo>Utilization_Manufacturers__c</referenceTo>
    <relationshipLabel>Utilization Product Locations</relationshipLabel>
    <relationshipName>Utilization_Product_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/Utilization_Report__c.object-meta.xml
<CustomObject>
    <description>Utilization items to drive iEdison reporting</description>
    <label>Utilization Report</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Utilization Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report__c/fields/Case_RecId__c.field-meta.xml
<CustomField>
    <fullName>Case_RecId__c</fullName>
    <label>Case</label>
    <length>24</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>Utilization Reports</relationshipLabel>
    <relationshipName>Utilization_Reports_Case</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Invention_Docket_Number__c.field-meta.xml
<CustomField>
    <fullName>Invention_Docket_Number__c</fullName>
    <description>Invention Docket Number</description>
    <label>Invention Docket Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Latest_Stage_of_Development__c.field-meta.xml
<CustomField>
    <fullName>Latest_Stage_of_Development__c</fullName>
    <label>Latest Stage of Development</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Commercialized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name(s)</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Utilization_Report__c/fields/Utilization_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Report_Status__c</fullName>
    <description>Status</description>
    <label>Utilization Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Include for Utilization</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization_Report_Config__c/Utilization_Report_Config__c.object-meta.xml
<CustomObject>
    <label>Utilization Reports FY Config</label>
    <nameField>
        <displayFormat>URC-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilization Reports FY Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Report_Config__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ComplianceUtilizationReportControlleTest.cls
/**
 * Created by Andreas du Preez on 2024/11/01.
 */

@IsTest
public with sharing class ComplianceUtilizationReportControlleTest {

    // Mock class for Forrester_Case__x
    class ForresterCaseMock extends ExternalObjectQuery {
        final List<Forrester_Case__x> externalRecords;

        ForresterCaseMock(List<Forrester_Case__x> externalRecords) {
            this.externalRecords = externalRecords;
        }

        protected override List<SObject> passThrough(List<SObject> records) {
            return externalRecords;
        }
    }

    @TestSetup
    public static void testSetup() {
        // Create a Utilization Report Config
        Utilization_Report_Config__c config = new Utilization_Report_Config__c();
        config.Fiscal_Year__c = '2024';
        config.Start_Date__c = Date.newInstance(2024, 1, 1);
        config.End_Date__c = Date.newInstance(2024, 12, 31);
        insert config;

        // Create a Utilization Report: Licensed
        List<Utilization_Report__c> reports = new List<Utilization_Report__c>();
        Utilization_Report__c reportLicensed = new Utilization_Report__c();
        reportLicensed.Invention_Docket_Number__c = '987654321';
        reportLicensed.Utilization_Report_Status__c = 'Include for Utilization';
        reportLicensed.Latest_Stage_of_Development__c = 'Licensed';
        reportLicensed.Notes__c = 'Licensed';
        reportLicensed.Case_RecId__c = '1574340';
        reports.add(reportLicensed);

        // Create a Utilization Report: Commercialized
        Utilization_Report__c reportCommercialized = new Utilization_Report__c();
        reportCommercialized.Invention_Docket_Number__c = '123456789';
        reportCommercialized.Latest_Stage_of_Development__c = 'Commercialized';
        reportCommercialized.Notes__c = 'Commercialized';
        reports.add(reportCommercialized);
        insert reports;

        // Create a Utilization Licensees:
        List<Utilization_Licensee__c> licensees = new List<Utilization_Licensee__c>();
        Utilization_Licensee__c licensee = new Utilization_Licensee__c();
        licensee.Utilization_Report__c = reportCommercialized.Id;
        licensee.Licensee_Name__c = 'Test Licensee 1';
        licensee.Exclusive_Count__c = 1;
        licensee.Non_Exclusive_Count__c = 1;
        licensee.Small_Business__c = true;
        licensees.add(licensee);

        Utilization_Licensee__c licensee2 = new Utilization_Licensee__c();
        licensee2.Utilization_Report__c = reportCommercialized.Id;
        licensee2.Licensee_Name__c = 'Test Licensee 2';
        licensee2.Exclusive_Count__c = 1;
        licensee2.Non_Exclusive_Count__c = 1;
        licensee2.Small_Business__c = true;
        licensees.add(licensee2);
        insert licensees;

        // Create a Utilization Manufacturing Comm Prod:
        List<Utilization_Manufacturing_Comm_Prod__c> manCommProds = new List<Utilization_Manufacturing_Comm_Prod__c>();
        Utilization_Manufacturing_Comm_Prod__c manCommProd = new Utilization_Manufacturing_Comm_Prod__c();
        manCommProd.Utilization_Report__c = reportCommercialized.Id;
        manCommProd.Naics_Code__c = '1234';
        manCommProd.Product_Name__c = 'Some Product 1';
        manCommProds.add(manCommProd);

        Utilization_Manufacturing_Comm_Prod__c manCommProd2 = new Utilization_Manufacturing_Comm_Prod__c();
        manCommProd2.Utilization_Report__c = reportCommercialized.Id;
        manCommProd2.Naics_Code__c = '4321';
        manCommProd2.Product_Name__c = 'Some Product 2';
        manCommProds.add(manCommProd2);
        insert manCommProds;

        // Create a Utilization Licensee Comm Prod Junction Object:
        List<Utilization_Licensee_Man_Comm_Prod__c> licenseeManCommProds = new List<Utilization_Licensee_Man_Comm_Prod__c>();
        Utilization_Licensee_Man_Comm_Prod__c licenseeManCommProd = new Utilization_Licensee_Man_Comm_Prod__c();
        licenseeManCommProd.Utilization_Licensee__c = licensee.Id;
        licenseeManCommProd.Utilization_Manufacturing_Comm_Prod__c = manCommProd.Id;
        licenseeManCommProds.add(licenseeManCommProd);

        Utilization_Licensee_Man_Comm_Prod__c licenseeManCommProd2 = new Utilization_Licensee_Man_Comm_Prod__c();
        licenseeManCommProd2.Utilization_Licensee__c = licensee2.Id;
        licenseeManCommProd2.Utilization_Manufacturing_Comm_Prod__c = manCommProd2.Id;
        licenseeManCommProds.add(licenseeManCommProd2);
        insert licenseeManCommProds;

        // Create Utilization Manufacturers:
        List<Utilization_Manufacturers__c> manufacturers = new List<Utilization_Manufacturers__c>();
        Utilization_Manufacturers__c manufacturer = new Utilization_Manufacturers__c();
        manufacturer.Utilization_Licensee_Man_Comm_Prod__c = licenseeManCommProd.Id;
        manufacturer.Manufacturer_Name__c = 'Test Manufacturer 1';
        manufacturers.add(manufacturer);

        Utilization_Manufacturers__c manufacturer2 = new Utilization_Manufacturers__c();
        manufacturer2.Utilization_Licensee_Man_Comm_Prod__c = licenseeManCommProd2.Id;
        manufacturer2.Manufacturer_Name__c = 'Test Manufacturer 2';
        manufacturers.add(manufacturer2);
        insert manufacturers;

        // Create Utilization Product Locations:
        List<Utilization_Product_Location__c> productLocations = new List<Utilization_Product_Location__c>();
        Utilization_Product_Location__c productLocation = new Utilization_Product_Location__c();
        productLocation.Utilization_Manufacturer__c = manufacturer.Id;
        productLocation.Country__c = 'US';
        productLocation.State__c = 'CA';
        productLocation.First_Date__c = System.today().addDays(-30);
        productLocation.First_Date_Type__c = 'Actual';
        productLocation.Product_Quantity__c = 100;
        productLocations.add(productLocation);

        Utilization_Product_Location__c productLocation2 = new Utilization_Product_Location__c();
        productLocation2.Utilization_Manufacturer__c = manufacturer.Id;
        productLocation2.Country__c = 'US';
        productLocation2.State__c = 'CA';
        productLocation2.First_Date__c = System.today().addDays(-30);
        productLocation2.First_Date_Type__c = 'Actual';
        productLocation2.Product_Quantity__c = 100;
        productLocations.add(productLocation2);

        Utilization_Product_Location__c productLocation3 = new Utilization_Product_Location__c();
        productLocation3.Utilization_Manufacturer__c = manufacturer2.Id;
        productLocation3.Country__c = 'US';
        productLocation3.State__c = 'CA';
        productLocation3.First_Date__c = System.today().addDays(-30);
        productLocation3.First_Date_Type__c = 'Actual';
        productLocation3.Product_Quantity__c = 100;
        productLocations.add(productLocation3);

        Utilization_Product_Location__c productLocation4 = new Utilization_Product_Location__c();
        productLocation4.Utilization_Manufacturer__c = manufacturer2.Id;
        productLocation4.Country__c = 'US';
        productLocation4.State__c = 'CA';
        productLocation4.First_Date__c = System.today().addDays(-30);
        productLocation4.First_Date_Type__c = 'Actual';
        productLocation4.Product_Quantity__c = 100;
        productLocations.add(productLocation4);
        insert productLocations;
    }

    @IsTest
    public static void testGetUtilizationReport() {
        Utilization_Report__c report = [SELECT Id FROM Utilization_Report__c WHERE Invention_Docket_Number__c = '123456789' LIMIT 1];

        Test.startTest();
        ComplianceUtilizationReportController.UtilizationReportWrapper result = ComplianceUtilizationReportController.getUtilizationReport(report.Id);
        Test.stopTest();

        System.assertEquals(report.Id, result.utilizationReport.Id);
        Assert.isNotNull(result.utilizationReportConfig.Id, 'Utilization Report Config should be populated');

        Assert.areEqual(result.utilizationReport.Id, report.Id, 'Utilization Report should be populated');
        Assert.areEqual(2, result.manufacturingCommProds.size(), 'Manufacturing Comm Prods should be populated');
        Assert.areEqual(2, result.licensees.size(), 'Licensees should be populated');
        Assert.isNotNull(result.manufacturingCommProds[0].commercialProd, 'Commercial Prod should be populated');
        Assert.areEqual(2, result.manufacturingCommProds[0].licenseesProducts[0].licenseeManufacturers[0].manufacturerProductLocations.size(), 'Product Locations should be populated');
        Assert.areEqual(2, result.manufacturingCommProds[1].licenseesProducts[0].licenseeManufacturers[0].manufacturerProductLocations.size(), 'Product Locations should be populated');
    }

    @IsTest
    public static void testInsertUtilizationReport() {
        ComplianceUtilizationReportController.UtilizationReportWrapper wrapper = buildUtilizationReportWrapper();

        Test.startTest();
        ComplianceUtilizationReportController.saveUtilizationReport(wrapper, false);
        Test.stopTest();

        ComplianceUtilizationReportController.UtilizationReportWrapper result = ComplianceUtilizationReportController.getUtilizationReport(wrapper.utilizationReport.Id);

        Assert.areEqual(2, result.manufacturingCommProds.size(), 'Manufacturing Comm Prods should be populated');
        Assert.areEqual(2, result.licensees.size(), 'Licensees should be populated');
        Assert.isNotNull(result.manufacturingCommProds[0].commercialProd, 'Commercial Prod should be populated');
        Assert.areEqual(2, result.manufacturingCommProds[0].licenseesProducts[0].licenseeManufacturers[0].manufacturerProductLocations.size(), 'Product Locations should be populated');
        Assert.areEqual(2, result.manufacturingCommProds[1].licenseesProducts[0].licenseeManufacturers[0].manufacturerProductLocations.size(), 'Product Locations should be populated');
    }

    // TODO: Add Update and Delete Tests

    public static ComplianceUtilizationReportController.UtilizationReportWrapper buildUtilizationReportWrapper() {
        // Create a Utilization Report: Commercialized
        Utilization_Report__c reportCommercialized = new Utilization_Report__c();
        reportCommercialized.Invention_Docket_Number__c = '123456789';
        reportCommercialized.Latest_Stage_of_Development__c = 'Commercialized';
        reportCommercialized.Notes__c = 'Commercialized';
        insert reportCommercialized;


        // Create a Utilization Licensees:
        List<Utilization_Licensee__c> licensees = new List<Utilization_Licensee__c>();
        Utilization_Licensee__c licensee = new Utilization_Licensee__c();
        licensee.Utilization_Report__c = reportCommercialized.Id;
        licensee.Licensee_Name__c = 'Test Licensee 1';
        licensee.Exclusive_Count__c = 1;
        licensee.Non_Exclusive_Count__c = 1;
        licensee.Small_Business__c = true;
        licensees.add(licensee);

        Utilization_Licensee__c licensee2 = new Utilization_Licensee__c();
        licensee2.Utilization_Report__c = reportCommercialized.Id;
        licensee2.Licensee_Name__c = 'Test Licensee 2';
        licensee2.Exclusive_Count__c = 1;
        licensee2.Non_Exclusive_Count__c = 1;
        licensee2.Small_Business__c = true;
        licensees.add(licensee2);
        insert licensees;

        // Create a Utilization Manufacturing Comm Prod:
        List<Utilization_Manufacturing_Comm_Prod__c> manCommProds = new List<Utilization_Manufacturing_Comm_Prod__c>();
        Utilization_Manufacturing_Comm_Prod__c manCommProd = new Utilization_Manufacturing_Comm_Prod__c();
        manCommProd.Utilization_Report__c = reportCommercialized.Id;
        manCommProd.Naics_Code__c = '1234';
        manCommProd.Product_Name__c = 'Some Product 1';

        Utilization_Manufacturing_Comm_Prod__c manCommProd2 = new Utilization_Manufacturing_Comm_Prod__c();
        manCommProd2.Utilization_Report__c = reportCommercialized.Id;
        manCommProd2.Naics_Code__c = '4321';
        manCommProd2.Product_Name__c = 'Some Product 2';
        manCommProds.add(manCommProd2);

        // Create a Utilization Licensee Comm Prod Junction Object:
        Utilization_Licensee_Man_Comm_Prod__c licenseeManCommProd = new Utilization_Licensee_Man_Comm_Prod__c();
        licenseeManCommProd.Utilization_Licensee__c = licensee.Id;

        Utilization_Licensee_Man_Comm_Prod__c licenseeManCommProd2 = new Utilization_Licensee_Man_Comm_Prod__c();
        licenseeManCommProd2.Utilization_Licensee__c = licensee2.Id;

        // Create Utilization Manufacturers:
        Utilization_Manufacturers__c manufacturer = new Utilization_Manufacturers__c();
        manufacturer.Utilization_Licensee_Man_Comm_Prod__c = licenseeManCommProd.Id;
        manufacturer.Manufacturer_Name__c = 'Test Manufacturer 1';

        Utilization_Manufacturers__c manufacturer2 = new Utilization_Manufacturers__c();
        manufacturer2.Utilization_Licensee_Man_Comm_Prod__c = licenseeManCommProd2.Id;
        manufacturer2.Manufacturer_Name__c = 'Test Manufacturer 2';

        // Create Utilization Product Locations:
        Utilization_Product_Location__c productLocation = new Utilization_Product_Location__c();
        productLocation.Utilization_Manufacturer__c = manufacturer.Id;
        productLocation.Country__c = 'US';
        productLocation.State__c = 'CA';
        productLocation.First_Date__c = System.today().addDays(-30);
        productLocation.First_Date_Type__c = 'Actual';
        productLocation.Product_Quantity__c = 100;

        Utilization_Product_Location__c productLocation2 = new Utilization_Product_Location__c();
        productLocation2.Utilization_Manufacturer__c = manufacturer.Id;
        productLocation2.Country__c = 'US';
        productLocation2.State__c = 'CA';
        productLocation2.First_Date__c = System.today().addDays(-30);
        productLocation2.First_Date_Type__c = 'Actual';
        productLocation2.Product_Quantity__c = 100;

        Utilization_Product_Location__c productLocation3 = new Utilization_Product_Location__c();
        productLocation3.Utilization_Manufacturer__c = manufacturer2.Id;
        productLocation3.Country__c = 'US';
        productLocation3.State__c = 'CA';
        productLocation3.First_Date__c = System.today().addDays(-30);
        productLocation3.First_Date_Type__c = 'Actual';
        productLocation3.Product_Quantity__c = 100;

        Utilization_Product_Location__c productLocation4 = new Utilization_Product_Location__c();
        productLocation4.Utilization_Manufacturer__c = manufacturer2.Id;
        productLocation4.Country__c = 'US';
        productLocation4.State__c = 'CA';
        productLocation4.First_Date__c = System.today().addDays(-30);
        productLocation4.First_Date_Type__c = 'Actual';
        productLocation4.Product_Quantity__c = 100;

        // Build the Wrapper
        ComplianceUtilizationReportController.ManufacturerWrapper manufacturerWrapper1 = new ComplianceUtilizationReportController.ManufacturerWrapper(manufacturer, new List<Utilization_Product_Location__c>{productLocation, productLocation2}, null);
        ComplianceUtilizationReportController.ManufacturerWrapper manufacturerWrapper2 = new ComplianceUtilizationReportController.ManufacturerWrapper(manufacturer2, new List<Utilization_Product_Location__c>{productLocation3, productLocation4}, null);

        ComplianceUtilizationReportController.LicenseeProductWrapper licenseeProductWrapper1 = new ComplianceUtilizationReportController.LicenseeProductWrapper(licenseeManCommProd, new List<ComplianceUtilizationReportController.ManufacturerWrapper>{manufacturerWrapper1}, null);
        ComplianceUtilizationReportController.LicenseeProductWrapper licenseeProductWrapper2 = new ComplianceUtilizationReportController.LicenseeProductWrapper(licenseeManCommProd2, new List<ComplianceUtilizationReportController.ManufacturerWrapper>{manufacturerWrapper2}, null);

        ComplianceUtilizationReportController.CommProdWrapper commProdWrapper1 = new ComplianceUtilizationReportController.CommProdWrapper(manCommProd, new List<ComplianceUtilizationReportController.LicenseeProductWrapper>{licenseeProductWrapper1}, null);
        ComplianceUtilizationReportController.CommProdWrapper commProdWrapper2 = new ComplianceUtilizationReportController.CommProdWrapper(manCommProd2, new List<ComplianceUtilizationReportController.LicenseeProductWrapper>{licenseeProductWrapper2}, null);

        ComplianceUtilizationReportController.UtilizationReportWrapper wrapper = new ComplianceUtilizationReportController.UtilizationReportWrapper();
        wrapper.utilizationReport = reportCommercialized;
        wrapper.licensees = licensees;
        wrapper.manufacturingCommProds = new List<ComplianceUtilizationReportController.CommProdWrapper>{commProdWrapper1, commProdWrapper2};

        return wrapper;
    }

    @isTest
    static void testGetUtilizationReports(){
        String searchTerm = '1574340';
		Utilization_Report__c report = [SELECT Id FROM Utilization_Report__c WHERE Invention_Docket_Number__c = '987654321' LIMIT 1];
        
        List<Forrester_Case__x> mockRecords = new List<Forrester_Case__x>();
        Forrester_Case__x mockRecord = new Forrester_Case__x();
        mockRecord.CASE_RECID__c = searchTerm;
        mockRecords.add(mockRecord);

        ExternalObjectQuery.setMock(new ForresterCaseMock(mockRecords));

        Test.startTest();
        List<Forrester_Case__x> forresterCaseResult =  ComplianceUtilizationReportController.getCasesRelatedToUtilizationReport(report.Id);
        Test.stopTest();

        Assert.areEqual(0, forresterCaseResult.size());
    }

    @isTest
    static void testGetTotalCasesForUtilizationReports(){
        String searchTerm = '1574340';
        Utilization_Report__c report = [SELECT Id FROM Utilization_Report__c WHERE Invention_Docket_Number__c = '987654321' LIMIT 1];
        
        List<Forrester_Case__x> mockRecords = new List<Forrester_Case__x>();
        Forrester_Case__x mockRecord = new Forrester_Case__x();
        mockRecord.CASE_RECID__c = searchTerm;
        mockRecords.add(mockRecord);
        
        ExternalObjectQuery.setMock(new ForresterCaseMock(mockRecords));
        
        Test.startTest();
        Integer totalCases =  ComplianceUtilizationReportController.getTotalCasesForUtilizationReports();
        Test.stopTest();
    }

}