force-app/main/default/objects/Invention_Disclosure__c/Invention_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Invention Disclosure</label>
    <nameField>
        <label>Invention Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invention_Disclosure__c/fields/Anticipated_Publication_Comment__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Publication_Comment__c</fullName>
    <label>Anticipated Publication Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Anticipated_Publication_Disclosure_Date__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Publication_Disclosure_Date__c</fullName>
    <label>Anticipated Publication Disclosure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Anticipated_Publication__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Anticipated_Publication__c</fullName>
    <label>Anticipated Publication Disclosure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Oral_Presentation__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Oral_Presentation__c</fullName>
    <label>Oral Presentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Published_Or_Disclosed__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Published_Or_Disclosed__c</fullName>
    <label>Published Or Disclosed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Disclosure_Reduced_To_Practice__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Reduced_To_Practice__c</fullName>
    <label>Reduced To Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/First_Oral_Disclosure_Comment__c.field-meta.xml
<CustomField>
    <fullName>First_Oral_Disclosure_Comment__c</fullName>
    <label>First Oral Disclosure Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/First_Publication_Comment__c.field-meta.xml
<CustomField>
    <fullName>First_Publication_Comment__c</fullName>
    <label>First Publication Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Oral_Disclosure_Date__c.field-meta.xml
<CustomField>
    <fullName>Oral_Disclosure_Date__c</fullName>
    <label>Oral Disclosure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Publication_Date__c.field-meta.xml
<CustomField>
    <fullName>Publication_Date__c</fullName>
    <label>Publication Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Reduced_To_Practice_Comment__c.field-meta.xml
<CustomField>
    <fullName>Reduced_To_Practice_Comment__c</fullName>
    <label>Reduced To Practice Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invention_Disclosure__c/fields/Reduced_To_Practice_Date__c.field-meta.xml
<CustomField>
    <fullName>Reduced_To_Practice_Date__c</fullName>
    <label>Reduced To Practice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InventionDisclosureFieldValidation.cls
public with sharing class InventionDisclosureFieldValidation {
    public static void validateInventionDisclosureFields(Invention_Disclosure__c inventionDisclosure) {
        validateAnticipatedPublication(inventionDisclosure);
        validateOralPresentation(inventionDisclosure);
        validatePublishedOrDisclosed(inventionDisclosure);
        validateReducedToPractice(inventionDisclosure);
    }

    public static Boolean validateInventionDisclosureFieldsDisclosureUpdate(Invention_Disclosure__c inventionDisclosure) {
        if (validateAnticipatedPublicationDisclosureUpdate(inventionDisclosure) &&
            validateReducedToPracticeDisclosureUpdate(inventionDisclosure) &&
            validateOralPresentationDisclosureUpdate(inventionDisclosure) &&
            validatePublishedOrDisclosedDisclosureUpdate(inventionDisclosure)) {
                return true;
        } else {
            return false;
        }
    }

    public static void validatePublishedOrDisclosed(Invention_Disclosure__c inventionDisclosure) {
        if (inventionDisclosure.Disclosure_Published_Or_Disclosed__c == 'Yes' && 
            (inventionDisclosure.Publication_Date__c == null || inventionDisclosure.First_Publication_Comment__c == null)) {
                inventionDisclosure.Publication_Date__c.addError('Must be present with Published_Or_Disclosed as true');
                inventionDisclosure.First_Publication_Comment__c.addError('Must be present with Published_Or_Disclosed as true');
        } else if (inventionDisclosure.Disclosure_Published_Or_Disclosed__c == 'No' && 
            (inventionDisclosure.Publication_Date__c != null || inventionDisclosure.First_Publication_Comment__c != null)) {
                inventionDisclosure.Disclosure_Published_Or_Disclosed__c.addError('Must be true to add Publication_Date and First_Publication_Comment');
        }
    }

    public static Boolean validatePublishedOrDisclosedDisclosureUpdate(Invention_Disclosure__c inventionDisclosure) {
        if (inventionDisclosure.Disclosure_Published_Or_Disclosed__c == 'Yes' && 
            (inventionDisclosure.Publication_Date__c == null || inventionDisclosure.First_Publication_Comment__c == null)) {
                return false;
        } else if (inventionDisclosure.Disclosure_Published_Or_Disclosed__c == 'No' && 
            (inventionDisclosure.Publication_Date__c != null || inventionDisclosure.First_Publication_Comment__c != null)) {
                return false;
        }

        return true;
    }

    public static void validateAnticipatedPublication(Invention_Disclosure__c inventionDisclosure) {
        if (inventionDisclosure.Disclosure_Anticipated_Publication__c == 'Yes' && 
            (inventionDisclosure.Anticipated_Publication_Disclosure_Date__c == null || inventionDisclosure.Anticipated_Publication_Comment__c == null)) {
                inventionDisclosure.Anticipated_Publication_Disclosure_Date__c.addError('Must be present with Anticipated_Publication_Disclosure as true');
                inventionDisclosure.Anticipated_Publication_Comment__c.addError('Must be present with Anticipated_Publication_Disclosure as true');
        } else if (inventionDisclosure.Disclosure_Anticipated_Publication__c == 'No' && 
            (inventionDisclosure.Anticipated_Publication_Disclosure_Date__c != null || inventionDisclosure.Anticipated_Publication_Comment__c != null)) {
                inventionDisclosure.Disclosure_Anticipated_Publication__c.addError('Must be true to add Anticipated_Publication_Disclosure_Date and Anticipated_Publication_Comment');
        }
    }

    public static Boolean validateAnticipatedPublicationDisclosureUpdate(Invention_Disclosure__c inventionDisclosure) {
        if (inventionDisclosure.Disclosure_Anticipated_Publication__c == 'Yes' && 
            (inventionDisclosure.Anticipated_Publication_Disclosure_Date__c == null || inventionDisclosure.Anticipated_Publication_Comment__c == null)) {
                return false;
        } else if (inventionDisclosure.Disclosure_Anticipated_Publication__c == 'No' && 
            (inventionDisclosure.Anticipated_Publication_Disclosure_Date__c != null || inventionDisclosure.Anticipated_Publication_Comment__c != null)) {
                return false;       
        }

        return true;
    }

    public static void validateOralPresentation(Invention_Disclosure__c inventionDisclosure) {
        if (inventionDisclosure.Disclosure_Oral_Presentation__c == 'Yes' && 
            (inventionDisclosure.Oral_Disclosure_Date__c == null || inventionDisclosure.First_Oral_Disclosure_Comment__c == null)) {
                inventionDisclosure.Anticipated_Publication_Disclosure_Date__c.addError('Must be present with Anticipated_Publication_Disclosure as true');
                inventionDisclosure.First_Oral_Disclosure_Comment__c.addError('Must be present with Anticipated_Publication_Disclosure as true');
        } else if (inventionDisclosure.Disclosure_Oral_Presentation__c == 'No' && 
        (inventionDisclosure.Oral_Disclosure_Date__c != null || inventionDisclosure.First_Oral_Disclosure_Comment__c != null)) {
            inventionDisclosure.Disclosure_Oral_Presentation__c.addError('Must be true to add Anticipated_Publication_Disclosure_Date and Anticipated_Publication_Comment');
        }
    }

    public static Boolean validateOralPresentationDisclosureUpdate(Invention_Disclosure__c inventionDisclosure) {
        if (inventionDisclosure.Disclosure_Oral_Presentation__c == 'Yes' && 
            (inventionDisclosure.Oral_Disclosure_Date__c == null || inventionDisclosure.First_Oral_Disclosure_Comment__c == null)) {
                return false;
        } else if (inventionDisclosure.Disclosure_Oral_Presentation__c == 'No' && 
        (inventionDisclosure.Oral_Disclosure_Date__c != null || inventionDisclosure.First_Oral_Disclosure_Comment__c != null)) {
            return false;
        }

        return true;
    }

    public static void validateReducedToPractice(Invention_Disclosure__c inventionDisclosure) {
        if (inventionDisclosure.Disclosure_Reduced_To_Practice__c == 'Yes' && 
            (inventionDisclosure.Reduced_To_Practice_Date__c == null || inventionDisclosure.Reduced_To_Practice_Comment__c == null)) {
                inventionDisclosure.Anticipated_Publication_Disclosure_Date__c.addError('Must be present with Anticipated_Publication_Disclosure as true');
                inventionDisclosure.Reduced_To_Practice_Comment__c.addError('Must be present with Anticipated_Publication_Disclosure as true');
        } else if (inventionDisclosure.Disclosure_Reduced_To_Practice__c == 'No' && 
            (inventionDisclosure.Reduced_To_Practice_Date__c != null || inventionDisclosure.Reduced_To_Practice_Comment__c != null)) {
                inventionDisclosure.Disclosure_Reduced_To_Practice__c.addError('Must be true to add Anticipated_Publication_Disclosure_Date and Anticipated_Publication_Comment');
        }
    }

    public static Boolean validateReducedToPracticeDisclosureUpdate(Invention_Disclosure__c inventionDisclosure) {
        if (inventionDisclosure.Disclosure_Reduced_To_Practice__c == 'Yes' && 
            (inventionDisclosure.Reduced_To_Practice_Date__c == null || inventionDisclosure.Reduced_To_Practice_Comment__c == null)) {
                return false;
        } else if (inventionDisclosure.Disclosure_Reduced_To_Practice__c == 'No' && 
            (inventionDisclosure.Reduced_To_Practice_Date__c != null || inventionDisclosure.Reduced_To_Practice_Comment__c != null)) {
                return false;
        }

        return true;
    }

}