force-app/main/default/objects/Invention_Disclosure__c/Invention_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Invention Disclosure</label>
    <nameField>
        <label>Invention Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Material__c/Third_Party_Material__c.object-meta.xml
<CustomObject>
    <label>Third Party Material</label>
    <nameField>
        <label>Third Party Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Material__c/fields/Invention_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Invention_Disclosure__c</fullName>
    <label>Invention Disclosure</label>
    <referenceTo>Invention_Disclosure__c</referenceTo>
    <relationshipLabel>Third Party Material</relationshipLabel>
    <relationshipName>Third_Party_Material</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InventionWrapper.cls
global class InventionWrapper {
    public InventionWrapper() {

    }

    global Invention_Disclosure__c invention;

    global Boolean anticipatedPublicationDisclosure;
    global String anticipatedPublicationDisclosureDate;
    global String conceptionDate;
    global String oralDisclosureDate;
    global Boolean oralPresentation;
    global Boolean partOfThesis;
    global String publicationDate;
    global Boolean publishedOrDisclosed;
    global Boolean reducedToPractice;
    global String reducedToPracticeDate;
    global Boolean thesisHold;
    
    global String materialsFromOtherLab;
    global String materialsFurtherComments;
    global List<Third_Party_Material__c> materials;

    global String thesisDefenseDate;
    global String thesisSubmittedDate;
    global String thesisDegreeDate;

    global List<String> typeOfPresentations;


}