force-app/main/default/objects/Utilization_Manufacturers__c/Utilization_Manufacturers__c.object-meta.xml
<CustomObject>
    <description>The manufacturers for the manufacturing commercial product</description>
    <label>Utilization Manufacturer</label>
    <nameField>
        <label>Utilization Manufacturers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Product_Location__c/Utilization_Product_Location__c.object-meta.xml
<CustomObject>
    <description>The manufacturing production location(s)</description>
    <label>Utilization Product Location</label>
    <nameField>
        <label>Utilization Product Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Product Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Product_Location__c/fields/Utilization_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Manufacturer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Manufacturer</description>
    <label>Utilization Manufacturer</label>
    <referenceTo>Utilization_Manufacturers__c</referenceTo>
    <relationshipLabel>Utilization Product Locations</relationshipLabel>
    <relationshipName>Utilization_Product_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilizationManufacturerTriggerHandler.cls
/**
 * Created by Andreas du Preez on 2024/11/18.
 */

public with sharing class UtilizationManufacturerTriggerHandler {
    public static void onBeforeDelete(
            List<Utilization_Manufacturers__c> utilizationManufacturers
    ) {
        // Future Todo:
        // Use the standard Salesforce Cascade Delete feature to delete related records:
        // https://help.salesforce.com/s/articleView?id=000382017&type=1
        // This feature first needs to be activated by Salesforce Support.
        // For now, we will manually delete the related records.
        deleteRelatedRecords(utilizationManufacturers);
    }

    private static void deleteRelatedRecords(List<Utilization_Manufacturers__c> utilizationManufacturersList) {
        Set<Id> utilizationManufacturerIds = new Set<Id>();
        for (
                Utilization_Manufacturers__c utilizationManufacturer : utilizationManufacturersList
        ) {
            utilizationManufacturerIds.add(utilizationManufacturer.Id);
        }

        List<Utilization_Product_Location__c> utilizationProductLocations = [
                SELECT Id
                FROM Utilization_Product_Location__c
                WHERE Utilization_Manufacturer__c = :utilizationManufacturerIds
        ];

        System.debug(JSON.serializePretty(utilizationProductLocations));

        delete utilizationProductLocations;
    }
}