force-app/main/default/objects/Case_CRDR__c/Case_CRDR__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE_CRDR)</description>
    <label>CRDR</label>
    <nameField>
        <label>Case CRDR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRDRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR__c/fields/Case_Recid__c.field-meta.xml
<CustomField>
    <fullName>Case_Recid__c</fullName>
    <label>Case Recid</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_CRDR__c/fields/ExternalCaseCRDRId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseCRDRId__c</fullName>
    <description>RecId from external object</description>
    <externalId>true</externalId>
    <label>ExternalCaseCRDRId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Entity_Recid__c.field-meta.xml
<CustomField>
    <fullName>Entity_Recid__c</fullName>
    <description>External Reference to Forrester Oracle RecIds for multiple tables. eg: Case table PK case_recid. Agreement table PK agreement_recid. The Record type with the classification need to be considered</description>
    <label>Entity Recid</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/CRDR.recordType-meta.xml
<RecordType>
    <fullName>CRDR</fullName>
    <active>true</active>
    <description>CRDR Worksheets, Correspondence and CRDR Finacial Documents</description>
    <label>CRDR</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/IPIA.recordType-meta.xml
<RecordType>
    <fullName>IPIA</fullName>
    <active>true</active>
    <label>IPIA</label>
</RecordType>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/Forrester_SHIR_CRDR_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CRDR_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CRDR_VIEW</externalName>
    <label>CRDR</label>
    <pluralLabel>CRDRs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CRDR RecId</label>
    <length>24</length>
    <referenceTargetField>Case_CRDR__c.ExternalCaseCRDRId__c</referenceTargetField>
    <referenceTo>Case_CRDR__c</referenceTo>
    <relationshipLabel>CRDRs</relationshipLabel>
    <relationshipName>CRDRs</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_NO_SUFFIX__c.field-meta.xml
<CustomField>
    <fullName>CASE_NO_SUFFIX__c</fullName>
    <description>CASE_NO_SUFFIX</description>
    <externalDeveloperName>CASE_NO_SUFFIX</externalDeveloperName>
    <inlineHelpText>Case without suffix: Q- J - H -B - R - W - DE -</inlineHelpText>
    <label>Org Case Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case</label>
    <length>24</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>CRDRs</relationshipLabel>
    <relationshipName>CRDRs</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CRDR_DATE__c.field-meta.xml
<CustomField>
    <fullName>CRDR_DATE__c</fullName>
    <description>CRDR_DATE</description>
    <externalDeveloperName>CRDR_DATE</externalDeveloperName>
    <label>CRDR Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Log_Document_Link__c/Log_Document_Link__c.object-meta.xml
<CustomObject>
    <label>Log Document Link Message</label>
    <nameField>
        <displayFormat>LCV-{000000}</displayFormat>
        <label>Log Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Document Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Document_Link__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Document_Link__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Document_Link__c/fields/PathOnClient__c.field-meta.xml
<CustomField>
    <fullName>PathOnClient__c</fullName>
    <label>PathOnClient</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Document_Link__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateDocumentLinkJob.cls
public with sharing class CreateDocumentLinkJob implements Queueable, Database.AllowsCallouts    {

    public final List<Id> cvIds;

    public CreateDocumentLinkJob() {
        this.cvIds = new List<Id>();
    }

    public CreateDocumentLinkJob(List<ContentVersion> cvList) {
        this.cvIds = new List<Id>();
        for (ContentVersion cv : cvList) {
            this.cvIds.add(cv.Id);
        }
    }

    public List<ContentVersion> start(QueueableContext ctx) {
        System.debug('CreateDocumentLinkJob:start');

        if (cvIds != null && !cvIds.isEmpty()) {
            return [ SELECT Id, Title, Description, PathOnClient, TagCsv,  Document_Classification__c, ContentSize, VersionNumber,
                                                                     IsLatest,
                                                                     RecordType.Name,
                                                                     ContentDocumentId,
                                                                     Entity_RecId__c
                                                        FROM ContentVersion WHERE Id IN :this.cvIds ];
        } else {
            return new List<ContentVersion>();
        }
    }

    public void execute(QueueableContext ctx) {

        try {
            List<ContentVersion> scope = start(ctx);
            this.cvIds.clear();
            if(scope != null && !scope.isEmpty()) {
                System.debug('CreateDocumentLinkJob:scope ' + scope.size() );
                List<ContentVersion> caseCRDRs = new List<ContentVersion>();
                List<ContentVersion> agreements = new List<ContentVersion>();
                List<ContentVersion> ipias = new List<ContentVersion>();
                for(ContentVersion contentVersion : scope) {
                    if (contentVersion.RecordType.Name == 'CRDR' && contentVersion.Document_Classification__c.contains('CRDR')) {
                        caseCRDRs.add(contentVersion);
                        this.cvIds.add(contentVersion.Id);
                    }
                    if (contentVersion.RecordType.Name.contains('Agreement') ) {
                        agreements.add(contentVersion);
                    }
                    if (contentVersion.RecordType.Name.contains('IPIA') ) {
                        ipias.add(contentVersion);
                    }
                }
                updateCaseCRDREntityRecIds(caseCRDRs);
                new AgreementDocumentLinkProcessor().execute(agreements);
                new IPIADocumentLinkProcessor().execute(ipias);
            }

        } catch(Exception ex) {
            HandleLogException.logException(ex);
            throw ex;
        }
    }

    private static Log_Document_Link__c getLogDocumentLinkInstance(Id id, String pathOnClient ,String logType, String message){
        Log_Document_Link__c log = new Log_Document_Link__c();
        log.ContentVersion_Id__c = String.valueOf(id);
        log.Type__c = logType;
        log.Message__c = message;
        log.PathOnClient__c = pathOnClient;
        return log;

    }

    private void updateCaseCRDREntityRecIds(List<ContentVersion> contentVersions) {
        if(contentVersions.isEmpty()) {
            return;
        }
        List<ContentVersion> contentVersionUpdateList = new List<ContentVersion>();
        List<ContentDocumentLink> contentDocumentLinkInsertList = new List<ContentDocumentLink>();
        List<Log_Document_Link__c> logs = new List<Log_Document_Link__c>();

        Map<Id, ContentVersion> cvMap = new Map<Id, ContentVersion>(contentVersions);
        Map<Id, FileNameDefinition> fileDefMap = new Map<Id, FileNameDefinition>();
        Map<Id, List<Forrester_SHIR_CRDR_VIEW__x> > externalViewMap = new Map<Id, List<Forrester_SHIR_CRDR_VIEW__x> >();

        // Parse all PathOnClient values
        for(ContentVersion contentVersion : contentVersions) {
            FileNameDefinition parsed = parseCRDRFileName(contentVersion.PathOnClient);
            if(parsed == null) {
                contentVersion.Entity_RecId__c = '-1' ; // will allow retry
                contentVersionUpdateList.add(contentVersion);
                logs.add(getLogDocumentLinkInstance(contentVersion.Id, contentVersion.PathOnClient,'Parsing-PathOnClient', 'Unable to parse'));
                continue;
            }
            fileDefMap.put(contentVersion.Id, parsed);
        }

        //Build the external object query filter sets
        Set<String> caseNumbers = new Set<String>();
        Set<String> financialYears = new Set<String>();
        for(ContentVersion contentVersion : contentVersions) {
            FileNameDefinition parsed = fileDefMap.get(contentVersion.Id);
            if(parsed == null) {
                continue;
            }
            caseNumbers.add(StringUtils.removeNonNumericCharacters(parsed.caseNumber));
            financialYears.add(parsed.financialYear);
        }

        // Bulk query external object
        List<Forrester_SHIR_CRDR_VIEW__x> crdrs = ExternalObjectQuery.records([SELECT Id, CASE_RECID__c, CASE_CRDR_RECID__c, CRDR_DATE__c, FY__c, CONTRACT_CASE_NUM__c, CASE_NO_SUFFIX__c FROM Forrester_SHIR_CRDR_VIEW__x
                   WHERE CASE_NO_SUFFIX__c in :caseNumbers AND FY__c in :financialYears]);
        // Group by is not supported for external objects

        // Attach Documents to Last CRDR Container object
        Map<String, Forrester_SHIR_CRDR_VIEW__x> lastCrdrMap = new Map<String, Forrester_SHIR_CRDR_VIEW__x>();
        for(Forrester_SHIR_CRDR_VIEW__x crdr :crdrs) {
            String key = crdr.CASE_NO_SUFFIX__c + '-' + crdr.FY__c;
            if (lastCrdrMap.containsKey(key)) {
                Forrester_SHIR_CRDR_VIEW__x lastCrdr = lastCrdrMap.get(key);
                DateTime crdrDate = crdr.CRDR_DATE__c;
                DateTime lastCrdrDate = lastCrdr.CRDR_DATE__c;
                // Add the newer Crdr to the Map
                if (crdrDate > lastCrdrDate ) {
                    lastCrdrMap.put(key, crdr);
                }
            } else {
                lastCrdrMap.put(key, crdr);
            }
        }
        List<Forrester_SHIR_CRDR_VIEW__x> crdrFilterList = lastCrdrMap.values();

        // Reconstruct ContentVersion to External Object mapping
        for(ContentVersion contentVersion : contentVersions) {
            FileNameDefinition parsed = fileDefMap.get(contentVersion.Id);
            if(parsed == null) {
                continue;
            }

            List<Forrester_SHIR_CRDR_VIEW__x> crdrList = new List<Forrester_SHIR_CRDR_VIEW__x>();
            for(Forrester_SHIR_CRDR_VIEW__x crdr :crdrFilterList) {
                if (crdr.CASE_NO_SUFFIX__c == StringUtils.removeNonNumericCharacters(parsed.caseNumber) && crdr.FY__c  == parsed.financialYear ){
                    crdrList.add(crdr);
                }
            }
            externalViewMap.put(contentVersion.Id, crdrList);

        }


        for(ContentVersion contentVersion : contentVersions) {
            FileNameDefinition parsed = fileDefMap.get(contentVersion.Id);
            if(parsed == null) {
                continue;
            }

            List<Forrester_SHIR_CRDR_VIEW__x> crdrList = externalViewMap.get(contentVersion.Id);

            if(crdrList.isEmpty()) {
                logs.add(getLogDocumentLinkInstance(contentVersion.Id, contentVersion.PathOnClient, 'External-Object-Query', 'No rows found for caseNumber ' + parsed.caseNumber));
            }
            List<String> externalIds = new List<String>();
            for(Forrester_SHIR_CRDR_VIEW__x crdr :crdrList) {
                externalIds.add(crdr.CASE_CRDR_RECID__c);
            }

            List<Case_CRDR__c> existingContainers = [Select Id, ExternalCaseCRDRId__c from Case_CRDR__c where ExternalCaseCRDRId__c =:externalIds];
            if(existingContainers.isEmpty()) {
                logs.add(getLogDocumentLinkInstance(contentVersion.Id, contentVersion.PathOnClient, 'Container-Object-Query', 'No rows found for ExternalCaseCRDRId__c ' + String.join(externalIds,',')));
            }

            String entityRecId = '';
            for (Case_CRDR__c container : existingContainers ) {
                ContentDocumentLink conDocLink = new ContentDocumentLink();
                conDocLink.LinkedEntityId = container.Id;
                conDocLink.ContentDocumentId = contentVersion.ContentDocumentId;
                // I = Inferred permission. The user’s permission is determined by the related record.
                // V = Viewer permission. The user can explicitly view but not edit the shared file.
                // C = Collaborator permission. The user can explicitly view and edit the shared file.
                conDocLink.ShareType = 'I';
                conDocLink.Visibility = 'AllUsers';
                contentDocumentLinkInsertList.add(conDocLink);
                if(entityRecId == '') {
                     entityRecId = container.ExternalCaseCRDRId__c;
                } else {
                    entityRecId += ',' + container.ExternalCaseCRDRId__c;
                }
            }
            Integer maxSize = 80;
            if(entityRecId.length() > maxSize ){
                entityRecId = entityRecId.substring(0, maxSize);
            }
            contentVersion.Entity_RecId__c = entityRecId != '' ? entityRecId : '-1'; // will allow retry

            contentVersionUpdateList.add(contentVersion);
        }
        if(!contentDocumentLinkInsertList.isEmpty()) {
            insert contentDocumentLinkInsertList;
        }
        if(!contentVersionUpdateList.isEmpty()) {
            update contentVersionUpdateList;
        }
        if(!logs.isEmpty()) {
            insert logs;
        }
    }


    @TestVisible
    private FileNameDefinition parseCRDRFileName(String pathOnClient) {
        List<Pattern> patterns = new List<Pattern>();
        patterns.add(Pattern.compile('^.([0-9]+).*-([0-9]+[A-Z]*)[ _]LLC-.*'));
        // All special cases where the standard naming convention was not used.
        patterns.add(Pattern.compile('^.([0-9]+).*-([0-9]+[A-Z]*)[ _]LLC_NG-.*'));
        patterns.add(Pattern.compile('^.([0-9]+).*-([0-9]+[A-Z]*)-[ ]?Ben Rockney.*'));
        patterns.add(Pattern.compile('^.([0-9]+).*-([0-9]+[A-Z]*)[ _-]equity-Ben Rockney.*'));
        patterns.add(Pattern.compile('^.([0-9]+).*-([0-9]+[A-Z]*)[ _-]equity-Deirdre.*'));
        patterns.add(Pattern.compile('^.([0-9]+).*LLC-([0-9]+[A-Z]*)[ _].*'));
        patterns.add(Pattern.compile('^.([0-9]+).*Broad Institute-([0-9]+[A-Z]*)[ _].*'));
        patterns.add(Pattern.compile('^.([0-9]+).*-([0-9]+[A-Z]*).pdf'));
        patterns.add(Pattern.compile('^.([0-9]+).*-([0-9]+[A-Z]*)[ ].*')); // This could be a problem!
        patterns.add(Pattern.compile('^.([0-9]+).*-[ ]?([0-9]{4,}+[A-Z]*)[ ]?-.*'));
        
        for(Pattern myPattern : patterns) {
            Matcher myMatcher = myPattern.matcher(pathOnClient);

            if (myMatcher.matches()) {
                FileNameDefinition parsed = new FileNameDefinition();
                parsed.financialYear = myMatcher.group(1) ;
                parsed.caseNumber = myMatcher.group(2) ;
                parsed.classification = pathOnClient.contains('Draft CRDR') ? ContentVersionClassification.DRAFT_CRDR : ContentVersionClassification.FINALISED_CRDR ;
                return parsed;
            }
        }
        return null;
    }

    @TestVisible
    private class FileNameDefinition {
        public String caseNumber;
        public String financialYear;
        public String classification;
    }

}