force-app/main/default/objects/Case_CRDR__c/Case_CRDR__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE_CRDR)</description>
    <label>CRDR</label>
    <nameField>
        <label>Case CRDR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRDRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR__c/fields/ExternalCaseCRDRId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseCRDRId__c</fullName>
    <description>RecId from external object</description>
    <externalId>true</externalId>
    <label>ExternalCaseCRDRId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_CRDR__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AWAITING_DRAFT</fullName>
                <label>Awaiting Draft</label>
            </value>
            <value>
                <fullName>DRAFT</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>IN_REVIEW</fullName>
                <label>In Review</label>
            </value>
            <value>
                <fullName>APPROVED</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>FINALIZED</fullName>
                <label>Finalized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_CRDR_Audit_Event__c/Case_CRDR_Audit_Event__c.object-meta.xml
<CustomObject>
    <label>Case CRDR Audit Event</label>
    <nameField>
        <label>Case CRDR Audit Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case CRDR Audit Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR_Audit_Event__c/fields/Case_CRDR__c.field-meta.xml
<CustomField>
    <fullName>Case_CRDR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case CRDR</label>
    <referenceTo>Case_CRDR__c</referenceTo>
    <relationshipLabel>Case CRDR Audit Events</relationshipLabel>
    <relationshipName>Case_CRDR_Audit_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CrdrControllerTest.cls
/**
 * Created by Andreas du Preez on 2024/03/19.
 */

@IsTest
public with sharing class CrdrControllerTest {

    @TestSetup
    static void setup() {
       TestSetup.defaultConfiguration();
    }

    private static final String TEST_CASE_CRDR_REC_ID_1 = '123456789';
    private static final String TEST_CASE_CRDR_REC_ID_2 = '1234567892';
    private static final String TEST_CASE_CRDR_NAME = 'Test Case CRDR Name';
    private static final String TEST_CASE_CONTRACT_NUMBER = '987654321';
    private static final String TEST_ACREEMENT_REC_ID = '456123789';

    public static CrdrController.RelatedCRDRs getRelatedCRDRTestData()
    {
        return new CrdrController.RelatedCRDRs(
                null,
                TEST_CASE_CRDR_REC_ID_1,
                TEST_CASE_CRDR_NAME,
                null,
                TEST_CASE_CONTRACT_NUMBER,
                null,
                TEST_ACREEMENT_REC_ID,
                false,
                null,
                null
        );
    }

    @IsTest
    public static void getRelatedCRDROpenTaskCountTest()
    {
        String testCaseCRDRRecId = TEST_CASE_CRDR_REC_ID_1;
        String groupDeveloperName = 'Test_Queue';
        Group testGroup = new Group(Name='Test Queue', DeveloperName=groupDeveloperName, Type='Queue');
        insert testGroup;

        Case_CRDR__c testCaseCRDR = new Case_CRDR__c(Name='Test Account');
        testCaseCRDR.ExternalCaseCRDRId__c = testCaseCRDRRecId;
        insert testCaseCRDR;

        String taskSubject = 'Test Subject';
        String taskRelatedTo = 'Case_CRDR__c';
        String taskPriority = 'Normal';
        String taskStatusNotStarted = 'Not Started';
        String taskStatusCompleted = 'Completed';
        String taskDescription = 'Test Comment';

        TaskHelper.createTask(testCaseCRDR.Id, taskSubject, taskRelatedTo, taskPriority, taskStatusNotStarted, taskDescription, null, groupDeveloperName, 'Queue');
        TaskHelper.createTask(testCaseCRDR.Id, taskSubject, taskRelatedTo, taskPriority, taskStatusNotStarted, taskDescription, null, groupDeveloperName, 'Queue');
        TaskHelper.createTask(testCaseCRDR.Id, taskSubject, taskRelatedTo, taskPriority, taskStatusCompleted, taskDescription, null, groupDeveloperName, 'Queue');

        Test.startTest();
        List<CrdrController.RelatedCRDRs> result = CrdrController.getRelatedCRDROpenTaskCount(testCaseCRDRRecId);
        Test.stopTest();

        System.assertEquals(2, result[0].OpenTaskCount);
        System.assertEquals(testCaseCRDR.Id, result[0].CaseCrdrId);
    }

    @IsTest
    public static void updateMultipleCaseCRDRStatusTest()
    {
        List<Case_CRDR__c> testCaseCRDRList = new List<Case_CRDR__c>();
        List<Id> testCaseCRDRIds = new List<Id>();

        Case_CRDR__c testCaseCRDR1 = new Case_CRDR__c(Name='Test CRDR 1');
        testCaseCRDR1.ExternalCaseCRDRId__c = TEST_CASE_CRDR_REC_ID_1;
        testCaseCRDR1.Status__c = 'AWAITING_DRAFT';

        Case_CRDR__c testCaseCRDR2 = new Case_CRDR__c(Name='Test CRDR 2');
        testCaseCRDR2.ExternalCaseCRDRId__c = TEST_CASE_CRDR_REC_ID_2;
        testCaseCRDR2.ExternalCaseCRDRId__c = 'IN_REVIEW';

        testCaseCRDRList.add(testCaseCRDR1);
        testCaseCRDRList.add(testCaseCRDR2);

        insert testCaseCRDRList;

        for (Case_CRDR__c testCaseCRDR : testCaseCRDRList)
        {
            testCaseCRDRIds.add(testCaseCRDR.Id);
        }

        Test.startTest();
        CrdrController.updateMultipleCaseCRDRStatus(testCaseCRDRIds, 'APPROVED');
        Test.stopTest();

        testCaseCRDRList = [SELECT Id, Status__c FROM Case_CRDR__c WHERE Id IN :testCaseCRDRIds];

        for (Case_CRDR__c testCaseCRDR : testCaseCRDRList)
        {
            System.assertEquals('APPROVED', testCaseCRDR.Status__c);
        }
    }

    @IsTest
    public static void getCaseCRDRAuditEventsTest()
    {
        Case_CRDR__c testCaseCRDR1 = new Case_CRDR__c(Name='Test CRDR 1');
        testCaseCRDR1.ExternalCaseCRDRId__c = TEST_CASE_CRDR_REC_ID_1;
        testCaseCRDR1.Status__c = 'AWAITING_DRAFT';

        insert testCaseCRDR1;

        testCaseCRDR1.Status__c = 'DRAFT';
        update testCaseCRDR1;
        testCaseCRDR1.Status__c = 'IN_REVIEW';
        update testCaseCRDR1;
        testCaseCRDR1.Status__c = 'AWAITING_DRAFT';
        update testCaseCRDR1;
        testCaseCRDR1.Status__c = 'DRAFT';
        update testCaseCRDR1;
        testCaseCRDR1.Status__c = 'IN_REVIEW';
        update testCaseCRDR1;
        testCaseCRDR1.Status__c = 'APPROVED';
        update testCaseCRDR1;
        testCaseCRDR1.Status__c = 'FINALIZED';
        update testCaseCRDR1;

        Test.startTest();
        List<Case_CRDR_Audit_Event__c> result = CrdrController.getCaseCRDRAuditEvents(testCaseCRDR1.Id);
        Test.stopTest();

        System.assertEquals(8, result.size());
    }
}