force-app/main/default/objects/Case_CRDR__c/Case_CRDR__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE_CRDR)</description>
    <label>CRDR</label>
    <nameField>
        <label>Case CRDR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRDRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR__c/fields/Case_Recid__c.field-meta.xml
<CustomField>
    <fullName>Case_Recid__c</fullName>
    <label>Case Recid</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_CRDR__c/fields/ExternalCaseCRDRId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseCRDRId__c</fullName>
    <description>RecId from external object</description>
    <externalId>true</externalId>
    <label>ExternalCaseCRDRId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_CRDR__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AWAITING_DRAFT</fullName>
                <label>Awaiting Draft</label>
            </value>
            <value>
                <fullName>DRAFT</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>IN_REVIEW</fullName>
                <label>In Review</label>
            </value>
            <value>
                <fullName>APPROVED</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>FINALIZED</fullName>
                <label>Finalized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_CRDR_Audit_Event__c/Case_CRDR_Audit_Event__c.object-meta.xml
<CustomObject>
    <label>Case CRDR Audit Event</label>
    <nameField>
        <label>Case CRDR Audit Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case CRDR Audit Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR_Audit_Event__c/fields/Case_CRDR__c.field-meta.xml
<CustomField>
    <fullName>Case_CRDR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case CRDR</label>
    <referenceTo>Case_CRDR__c</referenceTo>
    <relationshipLabel>Case CRDR Audit Events</relationshipLabel>
    <relationshipName>Case_CRDR_Audit_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/Forrester_Case__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_VIEW</externalName>
    <label>Case</label>
    <pluralLabel>Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case RecId</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/STATUS__c.field-meta.xml
<CustomField>
    <fullName>STATUS__c</fullName>
    <description>STATUS</description>
    <externalDeveloperName>STATUS</externalDeveloperName>
    <label>Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_EMAIL__c.field-meta.xml
<CustomField>
    <fullName>TLO_EMAIL__c</fullName>
    <description>TLO_EMAIL</description>
    <externalDeveloperName>TLO_EMAIL</externalDeveloperName>
    <label>TLO Officer Email</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_NAME__c.field-meta.xml
<CustomField>
    <fullName>TLO_NAME__c</fullName>
    <description>TLO_NAME</description>
    <externalDeveloperName>TLO_NAME</externalDeveloperName>
    <label>TLO Officer</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case_CRDR_Revenue__x/Forrester_Case_CRDR_Revenue__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case_CRDR_Revenue</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_Case_CRDR_Revenue</externalName>
    <label>Income</label>
    <pluralLabel>Income</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case_CRDR_Revenue__x/fields/AGREEMENT_RECID__c.field-meta.xml
<CustomField>
    <fullName>AGREEMENT_RECID__c</fullName>
    <description>AGREEMENT_RECID</description>
    <externalDeveloperName>AGREEMENT_RECID</externalDeveloperName>
    <label>Agreement</label>
    <length>24</length>
    <referenceTo>Forrester_SHIR_AGREEMENT_VIEW__x</referenceTo>
    <relationshipLabel>Forrester Case CRDR Revenues</relationshipLabel>
    <relationshipName>Forrester_Agreement_Details</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_Case_CRDR_Revenue__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CASE_CRDR_RECID</label>
    <length>24</length>
    <referenceTo>Forrester_SHIR_CRDR_VIEW__x</referenceTo>
    <relationshipLabel>Income</relationshipLabel>
    <relationshipName>Forrester_Case_CRDR_Revenues</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_AGREEMENT_VIEW__x/Forrester_SHIR_AGREEMENT_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_AGREEMENT_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_AGREEMENT_VIEW</externalName>
    <label>Agreement</label>
    <pluralLabel>Agreements</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_AGREEMENT_VIEW__x/fields/AGREEMENT_RECID__c.field-meta.xml
<CustomField>
    <fullName>AGREEMENT_RECID__c</fullName>
    <description>AGREEMENT_RECID</description>
    <externalDeveloperName>AGREEMENT_RECID</externalDeveloperName>
    <label>Agreement Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CRDR_RELATED_CRDRS_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CRDR_RELATED_CRDRS_VIEW</externalName>
    <label>Related CRDR</label>
    <pluralLabel>Related CRDRs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/AGREEMENT_RECID__c.field-meta.xml
<CustomField>
    <fullName>AGREEMENT_RECID__c</fullName>
    <description>AGREEMENT_RECID</description>
    <externalDeveloperName>AGREEMENT_RECID</externalDeveloperName>
    <label>Agreement</label>
    <length>12</length>
    <referenceTo>Forrester_SHIR_AGREEMENT_VIEW__x</referenceTo>
    <relationshipLabel>Related CRDRs</relationshipLabel>
    <relationshipName>Related_CRDRs</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CRDR</label>
    <length>12</length>
    <referenceTo>Forrester_SHIR_CRDR_VIEW__x</referenceTo>
    <relationshipLabel>Related CRDRs</relationshipLabel>
    <relationshipName>Related_CRDRs</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case</label>
    <length>12</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>Related CRDRs</relationshipLabel>
    <relationshipName>Related_CRDRs</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Contract Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/RELATED_CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>RELATED_CASE_CRDR_RECID__c</fullName>
    <description>RELATED_CASE_CRDR_RECID</description>
    <externalDeveloperName>RELATED_CASE_CRDR_RECID</externalDeveloperName>
    <label>Related CRDR</label>
    <length>12</length>
    <referenceTo>Forrester_SHIR_CRDR_VIEW__x</referenceTo>
    <relationshipLabel>DO_NOT_USE</relationshipLabel>
    <relationshipName>Related_CRDRs_Child</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x/fields/RELATED_HAS_OPEN_CHK_LIST__c.field-meta.xml
<CustomField>
    <fullName>RELATED_HAS_OPEN_CHK_LIST__c</fullName>
    <defaultValue>false</defaultValue>
    <description>RELATED_HAS_OPEN_CHK_LIST</description>
    <externalDeveloperName>RELATED_HAS_OPEN_CHK_LIST</externalDeveloperName>
    <label>Related Has Open Checklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/Forrester_SHIR_CRDR_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CRDR_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CRDR_VIEW</externalName>
    <label>CRDR</label>
    <pluralLabel>CRDRs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CRDR RecId</label>
    <length>24</length>
    <referenceTargetField>Case_CRDR__c.ExternalCaseCRDRId__c</referenceTargetField>
    <referenceTo>Case_CRDR__c</referenceTo>
    <relationshipLabel>CRDRs</relationshipLabel>
    <relationshipName>CRDRs</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case</label>
    <length>24</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>CRDRs</relationshipLabel>
    <relationshipName>CRDRs</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CRDR_NAME__c.field-meta.xml
<CustomField>
    <fullName>CRDR_NAME__c</fullName>
    <description>CRDR_NAME</description>
    <externalDeveloperName>CRDR_NAME</externalDeveloperName>
    <label>CRDR Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/HAS_OPEN_CHK_LIST__c.field-meta.xml
<CustomField>
    <fullName>HAS_OPEN_CHK_LIST__c</fullName>
    <defaultValue>false</defaultValue>
    <description>HAS_OPEN_CHK_LIST</description>
    <externalDeveloperName>HAS_OPEN_CHK_LIST</externalDeveloperName>
    <label>Has Open Checklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/TLO_EMAIL__c.field-meta.xml
<CustomField>
    <fullName>TLO_EMAIL__c</fullName>
    <description>TLO_EMAIL</description>
    <externalDeveloperName>TLO_EMAIL</externalDeveloperName>
    <label>TLO Email</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/CRDR.recordType-meta.xml
<RecordType>
    <fullName>CRDR</fullName>
    <active>true</active>
    <label>CRDR</label>
</RecordType>

force-app/main/default/classes/CrdrController.cls
/**
 * Created by Andreas du Preez on 2024/03/18.
 */

public with sharing class CrdrController {
    private static final String FINANCE_QUEUE = 'Finance_Queue';

    /**
     * This function retrieves related CRDRs and a count of open tasks for a given CRDR case.
     *
     * @param caseCrdrRecId The ID of the case for which related CRDR tasks are to be fetched.
     * @return List<RelatedCRDRTasks> A list of RelatedCRDRs objects, each representing a related CRDR.
     */
    @AuraEnabled
    public static List<RelatedCRDRs> getRelatedCRDROpenTaskCount(String caseCrdrRecId) {
        List<RelatedCRDRs> forresterRelatedCrdrsList = new List<RelatedCRDRs>();
        List<String> forresterRelatedCrdrsIds = new List<String>();

        // Do callout and fetch related CRDRs for the given case.
        if (Test.isRunningTest())
        {
            RelatedCRDRs testRelatedCRDR = CrdrControllerTest.getRelatedCRDRTestData();
            forresterRelatedCrdrsList.add(testRelatedCRDR);
            forresterRelatedCrdrsIds.add(testRelatedCRDR.ForresterCaseCrdrRecId);
        }
        else {
                for (Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x forresterCaseCrdr : [
                    SELECT
                            RELATED_CASE_CRDR_RECID__r.Id,
                            CASE_CRDR_RECID__c,
                            RELATED_CASE_CRDR_RECID__r.CRDR_NAME__c,
                            CASE_RECID__r.Id,
                            CASE_RECID__r.CONTRACT_CASE_NUM__c,
                            AGREEMENT_RECID__r.Id,
                            AGREEMENT_RECID__c,
                            HAS_OPEN_CHK_LIST__c,
                            RELATED_HAS_OPEN_CHK_LIST__c,
                            TLO_NAME__c,
                            RELATED_CASE_CRDR_RECID__r.TLO_EMAIL__c

                    FROM Forrester_SHIR_CRDR_RELATED_CRDRS_VIE__x
                    WHERE CASE_CRDR_RECID__c = :caseCrdrRecId //current CASE_CRDR_RECID that is being looked at                    
            ]) {
                    forresterRelatedCrdrsIds.add(forresterCaseCrdr.RELATED_CASE_CRDR_RECID__c);
                    forresterRelatedCrdrsList.add(
                            new RelatedCRDRs(
                                    forresterCaseCrdr.RELATED_CASE_CRDR_RECID__r.Id,
                                    forresterCaseCrdr.RELATED_CASE_CRDR_RECID__c,
                                    forresterCaseCrdr.RELATED_CASE_CRDR_RECID__r.CRDR_NAME__c,
                                    forresterCaseCrdr.CASE_RECID__r.Id,
                                    forresterCaseCrdr.CASE_RECID__r.CONTRACT_CASE_NUM__c,
                                    forresterCaseCrdr.AGREEMENT_RECID__r.Id,
                                    forresterCaseCrdr.AGREEMENT_RECID__c,
                                    forresterCaseCrdr.RELATED_HAS_OPEN_CHK_LIST__c,
                                    forresterCaseCrdr.TLO_NAME__c,
                                    forresterCaseCrdr.RELATED_CASE_CRDR_RECID__r.TLO_EMAIL__c
                            )
                    );
            }

            // Include the current CRDR in the list
            forresterRelatedCrdrsIds.add(caseCrdrRecId);
            Forrester_SHIR_CRDR_VIEW__x forresterCaseCrdr = [SELECT
                        Id,
                        CASE_CRDR_RECID__c,
                        CRDR_NAME__c,
                        CASE_RECID__c,
                        CONTRACT_CASE_NUM__c,
                        HAS_OPEN_CHK_LIST__c,
                        (SELECT AGREEMENT_RECID__r.Id, AGREEMENT_RECID__c FROM Forrester_Case_CRDR_Revenues__r),
                        TLO_NAME__c,
                        TLO_EMAIL__c
                    FROM Forrester_SHIR_CRDR_VIEW__x
                    WHERE CASE_CRDR_RECID__c = :caseCrdrRecId
                    LIMIT 1
            ];

            Forrester_Case__x forresterCase = [SELECT Id FROM Forrester_Case__x WHERE CASE_RECID__c = :forresterCaseCrdr.CASE_RECID__c LIMIT 1];

            RelatedCRDRs currentCRDR = new RelatedCRDRs(
                    forresterCaseCrdr.Id,
                    forresterCaseCrdr.CASE_CRDR_RECID__c,
                    forresterCaseCrdr.CRDR_NAME__c,
                    forresterCase.Id,
                    forresterCaseCrdr.CONTRACT_CASE_NUM__c,
                    null,
                    null,
                    forresterCaseCrdr.HAS_OPEN_CHK_LIST__c,
                    forresterCaseCrdr.TLO_NAME__c,
                    forresterCaseCrdr.TLO_EMAIL__c
            );

            // If the current CRDR does not have Revenue records, add it to the list without an Agreement.
            if (forresterCaseCrdr.Forrester_Case_CRDR_Revenues__r.isEmpty()) {
                forresterRelatedCrdrsList.add(currentCRDR);
            }
            else{
                for (Forrester_Case_CRDR_Revenue__x crdrRevenue : forresterCaseCrdr.Forrester_Case_CRDR_Revenues__r) {
                    RelatedCRDRs currentCRDRClone = currentCRDR.clone();
                    currentCRDRClone.AgreementId = crdrRevenue.AGREEMENT_RECID__r.Id;
                    currentCRDRClone.AgreementRecId = crdrRevenue.AGREEMENT_RECID__c;
                    forresterRelatedCrdrsList.add(currentCRDRClone);
                }
            }
        }

        // Fetch the related Case_CRDR__c, and populate the CaseCrdrId and Status fields in the forresterRelatedCrdrsMap.
        Map<Id, String> relatedCaseCrdrsIdsMap = new Map<Id, String>();
        for (Case_CRDR__c relatedCRDRContainer : [
                SELECT
                        Id,
                        Status__c,
                        ExternalCaseCRDRId__c
                FROM Case_CRDR__c
                WHERE ExternalCaseCRDRId__c IN :forresterRelatedCrdrsIds
        ]) {
            for (Integer i = (forresterRelatedCrdrsList.size()-1); i>= 0; i--){
                RelatedCRDRs relatedCRDR = forresterRelatedCrdrsList[i];
                if (relatedCRDR.ForresterCaseCrdrRecId == relatedCRDRContainer.ExternalCaseCRDRId__c.toString()) {
                    // Remove Finalized CRDRs from the result list
                    if (relatedCRDRContainer.Status__c == 'FINALIZED') {
                        forresterRelatedCrdrsList.remove(i);
                    }
                    else {
                        relatedCRDR.CaseCrdrId = relatedCRDRContainer.Id;
                        relatedCRDR.Status = relatedCRDRContainer.Status__c;
                    }
                }
            }

            if (relatedCRDRContainer.Status__c != 'FINALIZED') {
                relatedCaseCrdrsIdsMap.put(relatedCRDRContainer.Id, relatedCRDRContainer.ExternalCaseCRDRId__c);
            }
        }

        // Fetch the number of tasks for each related CRDR.
        for (AggregateResult taskCountRecord : [
                SELECT
                        COUNT(Id) TaskCount,
                        WhatId
                FROM Task
                WHERE WhatId IN :relatedCaseCrdrsIdsMap.keySet()
                AND Status != 'Completed'
                GROUP BY WhatId
        ]) {
            String recId = relatedCaseCrdrsIdsMap.get((Id) taskCountRecord.get('WhatId'));

            for (RelatedCRDRs relatedCRDR : forresterRelatedCrdrsList) {
                if (relatedCRDR.ForresterCaseCrdrRecId == recId) {
                    relatedCRDR.OpenTaskCount = (Integer) taskCountRecord.get('TaskCount');
                }
            }
        }

        return forresterRelatedCrdrsList;
    }


    @AuraEnabled
    public static void updateMultipleCaseCRDRStatus(List<String> caseCrdrIdList, String newStatus) {
        List<Case_CRDR__c> caseCrdrList = [SELECT Id, Status__c FROM Case_CRDR__c WHERE Id IN :caseCrdrIdList AND Status__c != 'FINALIZED'];
        List<Case_CRDR__c> caseCrdrListToUpdate = new List<Case_CRDR__c>();

        for (Case_CRDR__c caseCrdr : caseCrdrList) {
            if (caseCrdr.Status__c != newStatus) {
                caseCrdrListToUpdate.add(new Case_CRDR__c(Id = caseCrdr.Id, Status__c = newStatus));
            }
        }

        update caseCrdrListToUpdate;
    }

    @AuraEnabled(Cacheable=true)
    public static List<Case_CRDR_Audit_Event__c> getCaseCRDRAuditEvents(Id caseCrdrId) {
        return [SELECT Id, CreatedDate, Status__c, Subject__c, Message__c
                FROM Case_CRDR_Audit_Event__c
                WHERE Case_CRDR__c = :caseCrdrId
                ORDER BY CreatedDate ASC];
    }


     public class PermissionsCheckResult {
        @AuraEnabled
        public Boolean hasPermission { get; set; }
        @AuraEnabled
        public String userProfile { get; set; }
        @AuraEnabled
        public List<String> userPermissions { get; set; }
    }

     /**
     * This function retrieves checks if current user has the correct permissions to update a crdr record from review to approve
     *
     * @param recordId The ID of the Forrester_SHIR_CRDR_VIEW__x being edited.
     * @return  A list of objects, each representing a the users permsiions and if they have rights to modify the record to approve.
     */
    @AuraEnabled(cacheable=true)
    public static PermissionsCheckResult checkPermissions(String recordId) {
        PermissionsCheckResult result = new PermissionsCheckResult();
        // Retrieve the record
        Forrester_SHIR_CRDR_VIEW__x record = [SELECT Id, TLO_EMAIL__c FROM Forrester_SHIR_CRDR_VIEW__x WHERE Id = :recordId LIMIT 1];

        // Get the logged in user's information
        User currentUser = [SELECT Id, Email, Profile.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];

        // Query all permission set assignments for the current user
        Set<String> permissionSetDeveloperNames = new Set<String>();
        for (PermissionSetAssignment assignment : [SELECT PermissionSetGroup.DeveloperName FROM PermissionSetAssignment WHERE AssigneeId = :UserInfo.getUserId()]) {
            permissionSetDeveloperNames.add(assignment.PermissionSetGroup.DeveloperName);
        }

        // Set the userProfile attribute
        result.userProfile = currentUser.Profile.Name;

        // Set the userPermissions attribute
        result.userPermissions = new List<String>(permissionSetDeveloperNames);

        // Check if the user is a System Administrator
        if (currentUser.Profile.Name == 'System Administrator' || permissionSetDeveloperNames.contains('Finance_Manager')) {
            result.hasPermission = true;
        }
        // Check if the user has TLO General permission set and email matches
        else if (permissionSetDeveloperNames.contains('TLO_Officer') && currentUser.Email == record.TLO_EMAIL__c) {
            result.hasPermission = true;
        }
        // If none of the above conditions are met, set hasPermission to false
        else {
            result.hasPermission = false;
        }

        return result;
    }

    // Inner class representing a related CRDR task.
    // Currently these fields' names are confusing.
    // The `CaseCrdrId` field is the current CRDR.
    // All other fields are related CRDRs fields.
    // TODO: Rename this class's fields to match the field names from DB view SHIR_CRDR_RELATED_CRDRS_VIEW after the view's fields is renamed.
    public class RelatedCRDRs {
        @AuraEnabled
        public Id CaseCrdrId { get; set; }
        @AuraEnabled
        public Id ForresterCaseCrdrId { get; set; }
        @AuraEnabled
        public String ForresterCaseCrdrRecId { get; set; }
        @AuraEnabled
        public String ForresterCaseCrdrName { get; set; }
        @AuraEnabled
        public Id CaseId { get; set; }
        @AuraEnabled
        public String CaseContractNumber { get; set; }
        @AuraEnabled
        public Id AgreementId { get; set; }
        @AuraEnabled
        public String AgreementRecId { get; set; }
        @AuraEnabled
        public String Status { get; set; }
        @AuraEnabled
        public Integer OpenTaskCount { get; set; }
        @AuraEnabled
        public Boolean RelatedHasOpenChecklist { get; set; }
        @AuraEnabled
        public String TLOOfficer { get; set; }
        @AuraEnabled
        public String TLOOfficerEmail { get; set; }

        public RelatedCRDRs(Id forresterCaseCrdrId, String forresterCaseCrdrRecId, String ForresterCaseCrdrName, Id caseId, String caseContractNumber, Id agreementId, String agreementRecId, Boolean relatedHasOpenChecklist, String tloOfficer, String tloOfficerEmail) {
            this.ForresterCaseCrdrId = forresterCaseCrdrId;
            this.ForresterCaseCrdrRecId = forresterCaseCrdrRecId;
            this.ForresterCaseCrdrName = ForresterCaseCrdrName;
            this.CaseId = caseId;
            this.CaseContractNumber = caseContractNumber;
            this.AgreementId = agreementId;
            this.AgreementRecId = agreementRecId;
            this.Status = '';
            this.OpenTaskCount = 0;
            this.RelatedHasOpenChecklist = relatedHasOpenChecklist;
            this.TLOOfficer = tloOfficer;
            this.TLOOfficerEmail = tloOfficerEmail;
        }
    }
}