force-app/main/default/objects/Case_CRDR__c/Case_CRDR__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE_CRDR)</description>
    <label>CRDR</label>
    <nameField>
        <label>Case CRDR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRDRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR__c/fields/ExternalCaseCRDRId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseCRDRId__c</fullName>
    <description>RecId from external object</description>
    <externalId>true</externalId>
    <label>ExternalCaseCRDRId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Task/recordTypes/CRDR.recordType-meta.xml
<RecordType>
    <fullName>CRDR</fullName>
    <active>true</active>
    <label>CRDR</label>
</RecordType>

force-app/main/default/classes/EmailNotificationTest.cls
@IsTest
public with sharing class EmailNotificationTest {
    
    @IsTest
    static void testConvertTasksToEmailNotifications(){
        Case_CRDR__C crdr = new Case_CRDR__c();
        crdr.ExternalCaseCRDRId__c = '12334';
        crdr.Name = 'Unit Test CRDR';
        insert crdr;

        Case_CRDR__C savedCrdr = [SELECT Id, Name FROM Case_CRDR__c WHERE ExternalCaseCRDRId__c = '12334'];

        String subject = 'Unit Testing EmailNotification';
        List<Task> tasks = new List<Task>(); 
        Task testTsk = new Task();
        testTsk.Subject = subject;
        testTsk.WhatId = savedCrdr.Id;
        tasks.add(testTsk);
        insert tasks;

        Task savedTask = [SELECT Id, Subject, CreatedById, LastModifiedById, Description, Priority, Related_Type__c FROM Task WHERE Subject = :subject];
        savedTask.Description = 'Description Added';
        update savedTask;
        
        List<Task> tasksToTest = [SELECT Id, Subject, CreatedById, LastModifiedById, Description, Priority, Related_Type__c FROM Task WHERE Subject = :subject];

        List<Notification> emailNotifications = EmailNotification.convertTasksToEmailNotifications(tasksToTest);
        
        EmailNotification notificationToTest = (EmailNotification) emailNotifications.get(0);

        System.assert(notificationToTest.replyTo == 'noreply@salesforce.com', 'noreply@salesforce.com');
        
        System.assert(notificationToTest.subject == savedTask.Subject, 'subject: should match the tasks Subject');
        System.assert(notificationToTest.body == savedTask.Description, 'body: should match the tasks Body');
        System.assert(notificationToTest.targetId == savedTask.Id, 'targetId: should match the tasks Id');
        System.assert(notificationToTest.assignedTo.Id == savedTask.CreatedById, 'assignedTo: should match the tasks CreatedById');
        System.assert(notificationToTest.actionedBy.Id == savedTask.LastModifiedById, 'actionedBy: should match the tasks CreatedById');

        
        System.assert(notificationToTest.variables.size() > 1, 'Variables are setup');
        System.assert(notificationToTest.variables.get('Priority') == savedTask.Priority, 'Variables are setup');
        System.assert(notificationToTest.variables.get('Related_Type__c') == savedTask.Related_Type__c, 'Variables are setup');

    }
}