force-app/main/default/objects/Case_CRDR__c/Case_CRDR__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE_CRDR)</description>
    <label>CRDR</label>
    <nameField>
        <label>Case CRDR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRDRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR__c/fields/ExternalCaseCRDRId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseCRDRId__c</fullName>
    <description>RecId from external object</description>
    <externalId>true</externalId>
    <label>ExternalCaseCRDRId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Note_level__c.field-meta.xml
<CustomField>
    <fullName>Note_level__c</fullName>
    <label>Note level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Level A</fullName>
            </value>
            <value>
                <fullName>Level B</fullName>
            </value>
            <value>
                <fullName>Level C</fullName>
            </value>
            <value>
                <fullName>Level D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/CRDR.recordType-meta.xml
<RecordType>
    <fullName>CRDR</fullName>
    <active>true</active>
    <description>CRDR Worksheets, Correspondence and CRDR Finacial Documents</description>
    <label>CRDR</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <label>Note</label>
</RecordType>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/Forrester_SHIR_CRDR_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CRDR_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CRDR_VIEW</externalName>
    <label>CRDR</label>
    <pluralLabel>CRDRs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CRDR RecId</label>
    <length>24</length>
    <referenceTargetField>Case_CRDR__c.ExternalCaseCRDRId__c</referenceTargetField>
    <referenceTo>Case_CRDR__c</referenceTo>
    <relationshipLabel>CRDRs</relationshipLabel>
    <relationshipName>CRDRs</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/DISCLOSURE_TITLE__c.field-meta.xml
<CustomField>
    <fullName>DISCLOSURE_TITLE__c</fullName>
    <description>DISCLOSURE_TITLE</description>
    <externalDeveloperName>DISCLOSURE_TITLE</externalDeveloperName>
    <label>Case Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CrdrDao.cls
public with sharing class CrdrDao {

    public static Forrester_SHIR_CRDR_VIEW__x getCrdrWithAllFields(String crdrIdStr) {

        // Get all of the fields on the object
        Map<String, Schema.SObjectField> fieldMap = Forrester_SHIR_CRDR_VIEW__x.sObjectType.getDescribe().fields.getMap();
        Set<String> setFieldNames = fieldMap.keySet();
        List<String> lstFieldNames = new List<String>(setFieldNames);
        String qryString = 'SELECT ' + String.join(lstFieldNames, ',') + ' FROM Forrester_SHIR_CRDR_VIEW__x WHERE Id = \'' + crdrIdStr + '\'';
        List<Forrester_SHIR_CRDR_VIEW__x> crdrs = ExternalObjectQuery.records(Database.query(qryString));
        if (!crdrs.isEmpty()) {
            return crdrs[0];
        }
        return null;
    }

    public static List<CrdrNoteWrapper> getCrdrNotes(String caseCrdrRecId) {
        List<CrdrNoteWrapper> notes = new List<CrdrNoteWrapper>();

        List<Case_CRDR__c> parentObjects = [SELECT ID from Case_CRDR__c WHERE ExternalCaseCRDRId__c = :caseCrdrRecId];
        if (!parentObjects.isEmpty()) {
            List<CreateNoteRecord.NotesWrapper> noteRecords = CreateNoteRecord.getNoteRecords(parentObjects[0].Id);
            for (CreateNoteRecord.NotesWrapper document : noteRecords) {
                CrdrNoteWrapper note = new CrdrNoteWrapper();
                note.title = document.Title;
                note.createdDate = document.CreatedDate;
                note.createdBy = document.CreatedByName ;
                note.text = document.Content;
                note.noteLevel = document.noteLevel;
                notes.add(note);
            }
        }
        return notes;
    }

    public static CrdrWrapper getCrdrWrapperById(String crdrIdStr) {

        Forrester_SHIR_CRDR_VIEW__x crdr = getCrdrWithAllFields(crdrIdStr);
        List<CrdrNoteWrapper> notes = getCrdrNotes(crdr.CASE_CRDR_RECID__c);

        Map<String, CrdrNoteLevelWrapper> levelMap = new Map<String, CrdrNoteLevelWrapper> ();

        // The Figma require Empty Level [x] sections. It is not guaranteed that all the Level notes will exist.
        Schema.DescribeFieldResult fieldDetail = ContentVersion.Note_level__c.getDescribe();
        List<Schema.PicklistEntry> validApplicationValues = fieldDetail.getPicklistValues();
        for (Schema.PicklistEntry pickListVal : validApplicationValues ) {
            String value =  pickListVal.getValue();
            levelMap.put(value, new CrdrNoteLevelWrapper(value));
        }


        for (CrdrNoteWrapper note : notes ) {
            String key = !String.isEmpty(note.noteLevel) ? note.noteLevel : '';
            if (!levelMap.containsKey(key)) {
                levelMap.put(key, new CrdrNoteLevelWrapper(note.noteLevel));
            }
            CrdrNoteLevelWrapper noteLevel = levelMap.get(key);
            noteLevel.notes.add(note);

        }
        List<CrdrNoteLevelWrapper> levels = levelMap.values();
        levels.sort(); // Sort by levelName

        CrdrWrapper crdrWrapper = new CrdrWrapper();
        crdrWrapper.caseNumber = crdr.CONTRACT_CASE_NUM__c;
        crdrWrapper.financialYear = crdr.FY__c;
        crdrWrapper.disclosureTitle = crdr.DISCLOSURE_TITLE__c;
        crdrWrapper.levels = levels;


        String strJSON = JSON.serialize(crdrWrapper);
        System.debug(strJSON);
       
        return crdrWrapper;
    }


}