force-app/main/default/objects/Case_CRDR__c/Case_CRDR__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE_CRDR)</description>
    <label>CRDR</label>
    <nameField>
        <label>Case CRDR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRDRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR__c/fields/ExternalCaseCRDRId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseCRDRId__c</fullName>
    <description>RecId from external object</description>
    <externalId>true</externalId>
    <label>ExternalCaseCRDRId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_CRDR__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AWAITING_DRAFT</fullName>
                <label>Awaiting Draft</label>
            </value>
            <value>
                <fullName>DRAFT</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>IN_REVIEW</fullName>
                <label>In Review</label>
            </value>
            <value>
                <fullName>APPROVED</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>FINALIZED</fullName>
                <label>Finalized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/CRDR.recordType-meta.xml
<RecordType>
    <fullName>CRDR</fullName>
    <active>true</active>
    <description>CRDR Worksheets, Correspondence and CRDR Finacial Documents</description>
    <label>CRDR</label>
</RecordType>

force-app/main/default/objects/Forrester_SHIR_CASE_CRDR_STATUS__x/Forrester_SHIR_CASE_CRDR_STATUS__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CASE_CRDR_STATUS</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_CRDR_STATUS</externalName>
    <label>Forrester_SHIR_CASE_CRDR_STATUS</label>
    <pluralLabel>Forrester_SHIR_CASE_CRDR_STATUS</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CASE_CRDR_STATUS__x/fields/CRDR_STATUS__c.field-meta.xml
<CustomField>
    <fullName>CRDR_STATUS__c</fullName>
    <description>CRDR_STATUS</description>
    <externalDeveloperName>CRDR_STATUS</externalDeveloperName>
    <label>CRDR_STATUS</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/Forrester_SHIR_CRDR_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CRDR_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CRDR_VIEW</externalName>
    <label>CRDR</label>
    <pluralLabel>CRDRs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CRDR RecId</label>
    <length>24</length>
    <referenceTargetField>Case_CRDR__c.ExternalCaseCRDRId__c</referenceTargetField>
    <referenceTo>Case_CRDR__c</referenceTo>
    <relationshipLabel>CRDRs</relationshipLabel>
    <relationshipName>CRDRs</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_NO_SUFFIX__c.field-meta.xml
<CustomField>
    <fullName>CASE_NO_SUFFIX__c</fullName>
    <description>CASE_NO_SUFFIX</description>
    <externalDeveloperName>CASE_NO_SUFFIX</externalDeveloperName>
    <inlineHelpText>Case without suffix: Q- J - H -B - R - W - DE -</inlineHelpText>
    <label>Org Case Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CRDR_STATUS__c.field-meta.xml
<CustomField>
    <fullName>CRDR_STATUS__c</fullName>
    <description>CRDR_STATUS</description>
    <externalDeveloperName>CRDR_STATUS</externalDeveloperName>
    <label>CRDR Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Draft</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CRDRDocumentUploadJobTest.cls
@isTest
public with sharing class CRDRDocumentUploadJobTest {
    
    @TestSetup
    static void makeData(){
        TestSetup.defaultConfiguration();
    }
    

   @isTest
   public static void testCRDRUploadDraftEvent() {
        String caseCrdrId = '1574340';
        Case_CRDR__c crdr = new Case_CRDR__c();
        crdr.Name = '5783HGQJ';
        crdr.ExternalCaseCRDRId__c = caseCrdrId;
        crdr.Status__c = 'WAITING_DRAFT';
        insert crdr;
        String fileName = '4906435-Jackson-5783HGQJ LLC-Nestor Franco.pdf';
        String pathOnClient = '/2024\\' + fileName;

        List<Forrester_SHIR_CRDR_VIEW__x > mockRecords = new List<Forrester_SHIR_CRDR_VIEW__x >();
        Forrester_SHIR_CRDR_VIEW__x mockRecord = new Forrester_SHIR_CRDR_VIEW__x();
        mockRecord.CASE_CRDR_RECID__c = '1574340' ;
        mockRecord.CASE_NO_SUFFIX__c = '5783';
        mockRecord.FY__c = '2024';
        mockRecords.add(mockRecord);

        List<Forrester_SHIR_CASE_CRDR_STATUS__x> mockStatusRecords = new List<Forrester_SHIR_CASE_CRDR_STATUS__x>();
        Forrester_SHIR_CASE_CRDR_STATUS__x mockStatusRecord = new Forrester_SHIR_CASE_CRDR_STATUS__x();
        mockStatusRecord.CASE_CRDR_RECID__c = '1574340';
        mockStatusRecord.CRDR_STATUS__c = 'WAITING_DRAFT';
        mockStatusRecords.add(mockStatusRecord);

        StackExternalMock crdrExternalMock = new StackExternalMock();
        crdrExternalMock.push(mockStatusRecords);
        crdrExternalMock.push(mockRecords);

        ExternalObjectQuery.setMock(crdrExternalMock);
        

        Test.startTest();
            String entityRecId = '-1'; //Flag Special Dataloader ContentVersion
            ContentVersion cv = FileRepositoryTest.insertEntityRecIdFile('CRDR', ContentVersionClassification.Draft_CRDR, pathOnClient, fileName, entityRecId) ;
        Test.stopTest();

        List<ContentDocumentLink> cdl =[ SELECT ContentDocumentId,LinkedEntityId
                               FROM ContentDocumentLink WHERE LinkedEntityId =: crdr.Id
                                AND ContentDocumentId IN (SELECT ContentDocumentId
                                    FROM ContentVersion
                                    WHERE Id = :cv.Id )];

        System.assert(cdl.isEmpty() == false, 'Expecting ContentDocumentLink Created');
    }

    @isTest
    public static void testCRDRUploadFinalizedEvent() {
        String caseCrdrId = '1574340';
        Case_CRDR__c crdr = new Case_CRDR__c();
        crdr.Name = '5783HGQJ';
        crdr.ExternalCaseCRDRId__c = caseCrdrId;
        crdr.Status__c = 'IN_REVIEW';
        insert crdr;
        String fileName = '4906435-Jackson-5783HGQJ LLC-Nestor Franco.pdf';
        String pathOnClient = '/2024\\' + fileName;

        List<Forrester_SHIR_CRDR_VIEW__x > mockRecords = new List<Forrester_SHIR_CRDR_VIEW__x >();
        Forrester_SHIR_CRDR_VIEW__x mockRecord = new Forrester_SHIR_CRDR_VIEW__x();
        mockRecord.CASE_CRDR_RECID__c = '1574340' ;
        mockRecord.CASE_NO_SUFFIX__c = '5783';
        mockRecord.FY__c = '2024';
        mockRecords.add(mockRecord);

        List<Forrester_SHIR_CASE_CRDR_STATUS__x> mockStatusRecords = new List<Forrester_SHIR_CASE_CRDR_STATUS__x>();
        Forrester_SHIR_CASE_CRDR_STATUS__x mockStatusRecord = new Forrester_SHIR_CASE_CRDR_STATUS__x();
        mockStatusRecord.CASE_CRDR_RECID__c = '1574340';
        mockStatusRecord.CRDR_STATUS__c = 'IN_REVIEW';
        mockStatusRecords.add(mockStatusRecord);

        StackExternalMock crdrExternalMock = new StackExternalMock();
        crdrExternalMock.push(mockStatusRecords);
        crdrExternalMock.push(mockRecords);

        ExternalObjectQuery.setMock(crdrExternalMock);

        Test.startTest();
            String entityRecId = '-1'; //Flag Special Dataloader ContentVersion
            ContentVersion cv = FileRepositoryTest.insertEntityRecIdFile('CRDR', ContentVersionClassification.Finalised_CRDR, pathOnClient, fileName, entityRecId) ;
        Test.stopTest();

        List<ContentDocumentLink> cdl =[ SELECT ContentDocumentId,LinkedEntityId
                               FROM ContentDocumentLink WHERE LinkedEntityId =: crdr.Id
                                AND ContentDocumentId IN (SELECT ContentDocumentId
                                    FROM ContentVersion
                                    WHERE Id = :cv.Id )];

       System.assert(cdl.isEmpty() == false, 'Expecting ContentDocumentLink Created');
    }



}