force-app/main/default/objects/Case_CRDR__c/Case_CRDR__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE_CRDR)</description>
    <label>CRDR</label>
    <nameField>
        <label>Case CRDR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRDRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR__c/fields/ExternalCaseCRDRId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseCRDRId__c</fullName>
    <description>RecId from external object</description>
    <externalId>true</externalId>
    <label>ExternalCaseCRDRId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_CRDR__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AWAITING_DRAFT</fullName>
                <label>Awaiting Draft</label>
            </value>
            <value>
                <fullName>DRAFT</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>IN_REVIEW</fullName>
                <label>In Review</label>
            </value>
            <value>
                <fullName>APPROVED</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>FINALIZED</fullName>
                <label>Finalized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/CRDR.recordType-meta.xml
<RecordType>
    <fullName>CRDR</fullName>
    <active>true</active>
    <label>CRDR</label>
</RecordType>

force-app/main/default/classes/TaskTriggerHandlerTest.cls
@isTest
public with sharing class TaskTriggerHandlerTest {
    
    @TestSetup
    static void makeData(){
        TestSetup.defaultConfiguration();
    }
    
    @isTest
    public static void testOnBeforeInsert() {
        Case_CRDR__c crdr = new Case_CRDR__c();
        crdr.Name = '1234';
        crdr.ExternalCaseCRDRId__c = '1234';
        insert crdr;

        Task task = new Task();
        task.WhatId = crdr.Id;
        task.Subject = 'New Task';
        insert task;

        Task taskToTest = [SELECT Id, Subject, Related_Type__c from Task WHERE Id = :task.Id];

        System.assertEquals('New Task', taskToTest.Subject, 'The tasks subject shoudl be New Task');
        System.assertEquals(Case_CRDR__c.getSObjectType().getDescribe().getLabel(), taskToTest.Related_Type__c, 'Related_Type__c should be the same value as label for Case_CRDR__c');
    }

    @isTest
    public static void testOnBeforeUpdate() {
        Case_CRDR__c crdr = new Case_CRDR__c();
        crdr.Name = '1234';
        crdr.ExternalCaseCRDRId__c = '1234';
        insert crdr;

        Task task = new Task();
        task.WhatId = crdr.Id;
        task.Subject = 'New Task';
        insert task;

        Task taskToTest = [SELECT Id, Subject, Related_Type__c from Task WHERE Id = :task.Id];
        taskToTest.Subject = 'Updated Task';

        System.assertEquals('Updated Task', taskToTest.Subject, 'The tasks subject shoudl be New Task');
        System.assertEquals(Case_CRDR__c.getSObjectType().getDescribe().getLabel(), taskToTest.Related_Type__c, 'Related_Type__c should be the same value as label for Case_CRDR__c');
    }

    @isTest
    public static void testOnAfterInsertDraftCRDR() {
        Case_CRDR__c crdr = new Case_CRDR__c();
        crdr.Name = '1234';
        crdr.ExternalCaseCRDRId__c = '1234';
        crdr.Status__c = 'DRAFT';
        insert crdr;

        Test.startTest();
            Task task = new Task();
            task.WhatId = crdr.Id;
            task.Subject = 'New Task';
            insert task;
        Test.stopTest();

        Case_CRDR__c crdrToTest = [SELECT Id, Status__c from Case_CRDR__c WHERE ID = :crdr.Id];

        System.assertEquals('IN_REVIEW', crdrToTest.Status__c, 'The CRDR Status should be IN_REVIEW');
    }

    @isTest
    public static void testOnAfterInsertInReviewCRDR() {
        Case_CRDR__c crdr = new Case_CRDR__c();
        crdr.Name = '1234';
        crdr.ExternalCaseCRDRId__c = '1234';
        crdr.Status__c = 'IN_REVIEW';
        insert crdr;
        
        Test.startTest();
            Task task = new Task();
            task.WhatId = crdr.Id;
            task.Subject = 'New Task';
            insert task;
        Test.stopTest();
        Case_CRDR__c crdrToTest = [SELECT Id, Status__c from Case_CRDR__c WHERE ID = :crdr.Id];

        System.assertEquals('IN_REVIEW', crdrToTest.Status__c, 'The CRDR Status should remain IN_REVIEW');
    }
    
}