force-app/main/default/objects/Case_CRDR__c/Case_CRDR__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE_CRDR)</description>
    <label>CRDR</label>
    <nameField>
        <label>Case CRDR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRDRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_CRDR__c/fields/ExternalCaseCRDRId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseCRDRId__c</fullName>
    <description>RecId from external object</description>
    <externalId>true</externalId>
    <label>ExternalCaseCRDRId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Note_level__c.field-meta.xml
<CustomField>
    <fullName>Note_level__c</fullName>
    <label>Note level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Level A</fullName>
            </value>
            <value>
                <fullName>Level B</fullName>
            </value>
            <value>
                <fullName>Level C</fullName>
            </value>
            <value>
                <fullName>Level D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/CRDR.recordType-meta.xml
<RecordType>
    <fullName>CRDR</fullName>
    <active>true</active>
    <description>CRDR Worksheets, Correspondence and CRDR Finacial Documents</description>
    <label>CRDR</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <label>Note</label>
</RecordType>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/Forrester_SHIR_CRDR_VIEW__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CRDR_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CRDR_VIEW</externalName>
    <label>CRDR</label>
    <pluralLabel>CRDRs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CRDR_VIEW__x/fields/CASE_CRDR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_CRDR_RECID__c</fullName>
    <description>CASE_CRDR_RECID</description>
    <externalDeveloperName>CASE_CRDR_RECID</externalDeveloperName>
    <label>CRDR RecId</label>
    <length>24</length>
    <referenceTargetField>Case_CRDR__c.ExternalCaseCRDRId__c</referenceTargetField>
    <referenceTo>Case_CRDR__c</referenceTo>
    <relationshipLabel>CRDRs</relationshipLabel>
    <relationshipName>CRDRs</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/classes/DocumentGenerationServiceTest.cls
@isTest
public with sharing class DocumentGenerationServiceTest {

    @TestSetup
    static void setupTestData() {
        TestSetup.defaultConfiguration();

        SampleDataFactory.createStyleDocumentTemplate();
        SampleDataFactory.createCrdrCoverPageDocumentTemplate();
    }


    @IsTest
    static void testCreateCrdrNotes() {
        DocuSignApiMock docuSignApiMock = new DocuSignApiMock();
        Test.setMock(HttpCalloutMock.class, docuSignApiMock);

        Case_CRDR__C crdr = new Case_CRDR__c();
        crdr.ExternalCaseCRDRId__c = '12334';
        crdr.Name = 'Unit Test CRDR';
        insert crdr;

        ContentVersion note = new ContentVersion(
            Title = 'Test Note',
            VersionData = Blob.valueOf(EncodingUtil.base64Encode(Blob.valueOf('Test Content'))),
            Note_level__c='Level A'
        );
        CreateNoteRecord.createRecord(note, crdr.Id);

        List<Forrester_SHIR_CRDR_VIEW__x> mockRecords = new List<Forrester_SHIR_CRDR_VIEW__x>();
        Forrester_SHIR_CRDR_VIEW__x mockRecord = new Forrester_SHIR_CRDR_VIEW__x();
        mockRecord.CASE_CRDR_RECID__c = '12334';
        mockRecord.FY__c = '2023';
        mockRecord.Id = TestUtility.getFakeId(Forrester_SHIR_CRDR_VIEW__x.sObjectType);
        mockRecords.add(mockRecord);

        ExternalObjectQuery.setMock(new CrdrViewExternalMock(mockRecords));

        Test.startTest();
         String pdf = DocumentGenerationService.getCrdrNotesPdfFileAsBase64String(mockRecord.Id);
         System.assert(pdf != null, 'CrdrNotes not created');
        Test.stopTest();

    }

}