force-app/main/default/objects/Tlo_Contact_Email_Event__e/Tlo_Contact_Email_Event__e.object-meta.xml
<CustomObject>
    <label>Tlo_Contact_Email_Event</label>
    <pluralLabel>Tlo_Contact_Email_Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tlo_Contact_Email_Event__e/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tlo_Contact_Email_Event__e/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <label>Event_Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tlo_Contact_Email_Event__e/fields/TloContactId__c.field-meta.xml
<CustomField>
    <fullName>TloContactId__c</fullName>
    <label>TloContactId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TloContactEmailEventProducer.cls
public with sharing class TloContactEmailEventProducer {
    public TloContactEmailEventProducer() {
    }

    public static void onTloContactEmailChanged(
        List<Account> contactChangedList
    ) {
        if (contactChangedList != null && !contactChangedList.isEmpty()) {
            List<Tlo_Contact_Email_Event__e> events = new List<Tlo_Contact_Email_Event__e>();
            for (Account contact : contactChangedList) {
                Tlo_Contact_Email_Event__e event = new Tlo_Contact_Email_Event__e(
                    Event_Name__c = 'onEmailUpdated',
                    TloContactId__c = contact.Id,
                    Email__c = contact.PersonEmail
                );
                events.add(event);
            }
            if (events != null && !events.isEmpty()) {
                List<Database.SaveResult> results = EventBus.publish(events);
                validateEventBusPublish(results);
            }
        }
    }

    public static void validateEventBusPublish(
        List<Database.SaveResult> results
    ) {
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                EventBusException ex;
                for (Database.Error err : sr.getErrors()) {
                    System.debug(
                        'Error returned: ' +
                        err.getStatusCode() +
                        ' - ' +
                        err.getMessage()
                    );
                    if (ex == null) {
                        ex = new EventBusException(err.getMessage());
                    }
                }
                throw ex;
            }
        }
    }
    public class EventBusException extends Exception {
    }
}