force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/Utilization_Licensee_Man_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>Junction box object to link (many to many) licensees with m Manufaturing Comm Prods</description>
    <label>Utilization Licensee Man Comm Prod</label>
    <nameField>
        <label>Utilization Licensee Man Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensee Man Comm Prod</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/fields/Utilization_Manufacturing_Comm_Prod__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Manufacturing_Comm_Prod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Manufacturing Comm Prod</label>
    <referenceTo>Utilization_Manufacturing_Comm_Prod__c</referenceTo>
    <relationshipName>Utilization_Manufacturing_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utilization_Manufacturing_Comm_Prod__c/Utilization_Manufacturing_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>The manufacturing commercial products</description>
    <label>Utilization Manufacturing Comm Prod</label>
    <nameField>
        <label>Utilization Manufacturing Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturing Comm Prods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UtilizationManCommProdTriggerHandler.cls
/**
 * Created by Andreas du Preez on 2024/11/18.
 */

public with sharing class UtilizationManCommProdTriggerHandler {
    public static void onBeforeDelete(
            List<Utilization_Manufacturing_Comm_Prod__c> utilizationManCommProdList
    ) {
        // Future Todo:
        // Use the standard Salesforce Cascade Delete feature to delete related records:
        // https://help.salesforce.com/s/articleView?id=000382017&type=1
        // This feature first needs to be activated by Salesforce Support.
        // For now, we will manually delete the related records.
        deleteRelatedRecords(utilizationManCommProdList);
    }

    private static void deleteRelatedRecords(List<Utilization_Manufacturing_Comm_Prod__c> utilizationManCommProdList) {
        Set<Id> utilizationManCommProdIds = new Set<Id>();
        for (
                Utilization_Manufacturing_Comm_Prod__c utilizationManCommProd : utilizationManCommProdList
        ) {
            utilizationManCommProdIds.add(utilizationManCommProd.Id);
        }

        List<Utilization_Licensee_Man_Comm_Prod__c> utilizationLicenseeManCommProdList = [
                SELECT Id
                FROM Utilization_Licensee_Man_Comm_Prod__c
                WHERE Utilization_Manufacturing_Comm_Prod__c = :utilizationManCommProdIds
        ];

        System.debug(JSON.serializePretty(utilizationLicenseeManCommProdList));

        delete utilizationLicenseeManCommProdList;
    }
}