force-app/main/default/objects/Utilization_Licensee_Man_Comm_Prod__c/Utilization_Licensee_Man_Comm_Prod__c.object-meta.xml
<CustomObject>
    <description>Junction box object to link (many to many) licensees with m Manufaturing Comm Prods</description>
    <label>Utilization Licensee Man Comm Prod</label>
    <nameField>
        <label>Utilization Licensee Man Comm Prod Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Licensee Man Comm Prod</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Manufacturers__c/Utilization_Manufacturers__c.object-meta.xml
<CustomObject>
    <description>The manufacturers for the manufacturing commercial product</description>
    <label>Utilization Manufacturer</label>
    <nameField>
        <label>Utilization Manufacturers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilization Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization_Manufacturers__c/fields/Utilization_Licensee_Man_Comm_Prod__c.field-meta.xml
<CustomField>
    <fullName>Utilization_Licensee_Man_Comm_Prod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utilization Manufaturing Comm Prod</label>
    <referenceTo>Utilization_Licensee_Man_Comm_Prod__c</referenceTo>
    <relationshipLabel>Utilization Licensee Man Comm Prod</relationshipLabel>
    <relationshipName>Utilization_Licensee_Man_Comm_Prods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilizationLicManCommProdTriggerHandler.cls
/**
 * Created by Andreas du Preez on 2024/11/18.
 */

public with sharing class UtilizationLicManCommProdTriggerHandler {

    public static void onBeforeDelete(
            List<Utilization_Licensee_Man_Comm_Prod__c> utilizationLicenseeManCommProdList
    ) {
        // Future Todo:
        // Use the standard Salesforce Cascade Delete feature to delete related records:
        // https://help.salesforce.com/s/articleView?id=000382017&type=1
        // This feature first needs to be activated by Salesforce Support.
        // For now, we will manually delete the related records.
        deleteRelatedRecords(utilizationLicenseeManCommProdList);
    }

    private static void deleteRelatedRecords(List<Utilization_Licensee_Man_Comm_Prod__c> utilizationLicenseeManCommProdList) {
        Set<Id> utilizationLicenseeManCommProdIds = new Set<Id>();
        for (
                Utilization_Licensee_Man_Comm_Prod__c utilizationLicenseeManCommProd : utilizationLicenseeManCommProdList
        ) {
            utilizationLicenseeManCommProdIds.add(utilizationLicenseeManCommProd.Id);
        }

        List<Utilization_Manufacturers__c> utilizationManufacturersList = [
                SELECT Id
                FROM Utilization_Manufacturers__c
                WHERE Utilization_Licensee_Man_Comm_Prod__c = :utilizationLicenseeManCommProdIds
        ];

        System.debug(JSON.serializePretty(utilizationManufacturersList));

        delete utilizationManufacturersList;
    }
}