force-app/main/default/objects/Contact/fields/Contact_Recid__c.field-meta.xml
<CustomField>
    <fullName>Contact_Recid__c</fullName>
    <externalId>true</externalId>
    <label>Forrester Contact RecID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <externalId>true</externalId>
    <label>MIT ID</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/Forrester_CONTACT__x.object-meta.xml
<CustomObject>
    <description>Forrester_CONTACT</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_CONTACT</externalName>
    <label>Forrester_CONTACT</label>
    <pluralLabel>Forrester_CONTACT</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_CONTACT__x/fields/IPIA_SIGNED_FLAG__c.field-meta.xml
<CustomField>
    <fullName>IPIA_SIGNED_FLAG__c</fullName>
    <description>IPIA_SIGNED_FLAG</description>
    <externalDeveloperName>IPIA_SIGNED_FLAG</externalDeveloperName>
    <label>IPIA_SIGNED_FLAG</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_CONTACT__x/fields/MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>MIT_ID__c</fullName>
    <description>MIT_ID</description>
    <externalDeveloperName>MIT_ID</externalDeveloperName>
    <label>MIT_ID</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Record__c/fields/Contact_Recid__c.field-meta.xml
<CustomField>
    <fullName>Contact_Recid__c</fullName>
    <label>Forrester Contact RecID</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/FormName__c.field-meta.xml
<CustomField>
    <fullName>FormName__c</fullName>
    <label>Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <label>MIT ID</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/SignDatetime__c.field-meta.xml
<CustomField>
    <fullName>SignDatetime__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/IPIAForresterSyncTest.cls
@isTest
private class IPIAForresterSyncTest {
    @TestSetup
    static void setup() {
        TestSetup.defaultConfiguration();
        ExternalQueryMock.getInstance().clearCache();
    }

    @IsTest
    static void testExistingForresterContactSync() {
        // Add mock data
        IPIA_Record__c ipiaRecord1 = new IPIA_Record__c(FormName__c = 'Test 1', MitId__c = '912345671', SignDatetime__c = Date.today().addDays(-2));
        List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>{ipiaRecord1 };

        insert ipiaRecords;

        // Create mock database instance for external data
        ExternalQueryMock mock = ExternalQueryMock.getInstance();

        // Mock Forrester Contact data
        List<Forrester_CONTACT__x> mockForresterContacts = new List<Forrester_CONTACT__x>();
        Forrester_CONTACT__x mockForresterContact = new Forrester_CONTACT__x(
            MIT_ID__c = '912345671',
            CONTACT_RECID__c = '12345',
            IPIA_SIGNED_FLAG__c = 'N'
        );
        mockForresterContacts.add(mockForresterContact);

        mock.setDataStore('Forrester_CONTACT__x:ids', mockForresterContacts);
        Id jobId;
        Test.startTest();
        try {
            Integer delayInMinutes = 0;
            IPIARecordUpsertJob upsertContactJob = new IPIARecordUpsertJob(
                new Set<Id>{ ipiaRecord1.Id }
            );
            jobId = System.enqueueJob(upsertContactJob, delayInMinutes);
        } catch (Exception e) {
            System.assert(false, 'An exception was thrown: ' + e.getMessage());
        }
        Test.stopTest();
    }

  
}