force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/Parent_BIP__c.field-meta.xml
<CustomField>
    <fullName>Parent_BIP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent BIP</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Requests</relationshipLabel>
    <relationshipName>BIP_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Primary_PI_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Requests (Primary PI Lookup)</relationshipLabel>
    <relationshipName>BIP_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Project_Title__c.field-meta.xml
<CustomField>
    <fullName>Project_Title__c</fullName>
    <label>Proposal/Research Project Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Proposal_Number__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Number__c</fullName>
    <label>Proposal Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Expedited</fullName>
            </value>
            <value>
                <fullName>Non-MIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/GetEmailData_Test.cls
@isTest
public class GetEmailData_Test {
    
    @testSetup
    static void setupTestData() {
        Account personAccount = new Account(
            FirstName = 'John',
            LastName = 'Doe',
            RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'PersonAccount' LIMIT 1].Id,
            PersonEmail = 'johndoe@example.com'
        );
        insert personAccount;

        BIP_Request__c bipRequest = new BIP_Request__c(
            Account_Number__c = '12345',
            Primary_PI_Lookup__c = personAccount.Id,
            Proposal_Number__c = '2387512',
            Request_Type__c = 'Standard',
            Due_Date__c = Date.today(),
            Comments__c = 'Test comments',
            Project_Title__c = 'Test Proposal'
        );
        
        
        
        
    BIP_Request__c childBipRequest = new BIP_Request__c(
        Parent_Bip__c = bipRequest.Id,
     Primary_PI_Lookup__c = personAccount.Id
        );
        
        List<sObject> lst = new List<sObject>{bipRequest,childBipRequest};
        insert lst;
    }

    @isTest
    static void testGetEmailInfo() {
        BIP_Request__c testRequest = [Select Id From BIP_Request__c LIMIT 1];


        Test.startTest();
        Map<String, Object> result = getEmailData.getEmailInfo(testRequest.Id);
        Test.stopTest();
         system.debug('result --'+result);
        // Assert the results
        System.assert(result != null, 'Result should not be null');
        System.assert(result.containsKey('to'), 'Result should contain the "to" key');
        System.assert(result.containsKey('cc'), 'Result should contain the "cc" key');
        System.assert(result.containsKey('templateBody'), 'Result should contain the "templateBody" key');
     
    }
}