force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/Primary_PI_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Requests (Primary PI Lookup)</relationshipLabel>
    <relationshipName>BIP_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewBipRequestController.cls
/**
 * @description       : 
 * @author            : 
 * @group             : 
 * @last modified on  : 12-12-2024
 * @last modified by  : 
**/
public with sharing class NewBipRequestController {
        
    @AuraEnabled
    public static string createBIPReq(BIP_Request__c bipRequest, String recordType){
        try {
            system.debug('bip req ---'+bipRequest.Primary_PI_Lookup__c);
            String kcProposalTypeId = Schema.SObjectType.BIP_Request__c.getRecordTypeInfosByName().get('KC Proposal').getRecordTypeId();
            String nonKCProposalTypeId = Schema.SObjectType.BIP_Request__c.getRecordTypeInfosByName().get('Non-KC Proposal').getRecordTypeId();
            if (recordType == 'KC Proposal') {
                bipRequest.RecordTypeId = kcProposalTypeId;
            }else{
                bipRequest.RecordTypeId = nonKCProposalTypeId;
            }
            insert bipRequest;
            return bipRequest.Id;   
        } catch (Exception e) {
            System.debug('----- '+e.getStackTraceString());
            System.debug('----- '+e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
}