force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/Primary_PI__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI__c</fullName>
    <label>Primary PI Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Primary_PI_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Requests (Primary PI Lookup)</relationshipLabel>
    <relationshipName>BIP_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/TLO_Case__c/TLO_Case__c.object-meta.xml
<CustomObject>
    <description>Container for external object (Forrester CASE)</description>
    <label>TLO Case</label>
    <nameField>
        <label>TLO Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TLO Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TLO_Case__c/fields/ExternalCaseId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseId__c</fullName>
    <description>RecId from external object</description>
    <label>ExternalCaseId</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BipRequestHelperTest.cls
@isTest
public class BipRequestHelperTest {
    
    @testSetup
    static void setupTestData() {
        // Create test data for Primary_PI_Lookup__c (Person Account)
        Account personAccount = new Account(
            FirstName = 'John',
            LastName = 'Doe',
            RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'PersonAccount' LIMIT 1].Id,
            MitId__pc = '900047159'
        );
        insert personAccount;
    

              
    }

    @isTest
    static void testAfterBipRequestInsert() {
        // Fetch the test data
        Account testPersonAccount = [SELECT Id FROM Account LIMIT 1];
     

        Test.startTest();
     BIP_Request__c  testBipRequest = new BIP_Request__c(Primary_PI_Lookup__c = testPersonAccount.Id);
        insert testBipRequest;
        Test.stopTest();
      system.debug('testBipRequest.Id'+testBipRequest.Id);
        // Assert that TLO_Case__c records were created
        //List<TLO_Case__c> tloCases = [SELECT Primary_PI__c, BIP_Request__c, ExternalCaseId__c FROM TLO_Case__c];
        //System.assert(tloCases.size()!=0);
        
    }


}