force-app/main/default/objects/Log_Exception__c/Log_Exception__c.object-meta.xml
<CustomObject>
    <label>Log Exception</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Log Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Exception__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Variables__c.field-meta.xml
<CustomField>
    <fullName>Variables__c</fullName>
    <label>Variables</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CleanupRecordBatchTest.cls
@isTest
public with sharing class CleanupRecordBatchTest {
    
    @TestSetup
    static void makeData(){
        TestSetup.defaultConfiguration();
    }

   @isTest
   public static void testCleanupRecord() {
        DateTime theDate = DateTime.now().addDays(-365);
        Log_Exception__c log = new Log_Exception__c();
        log.Class_Name__c = '';
        log.Method_Name__c = '';
        insert log;

        Test.setCreatedDate(log.Id, theDate);

        Test.startTest();
            Database.executeBatch(new CleanupRecordBatch('Log_Exception__c', 250, 'Days'), 200);
            CleanupRecordBatchSchedule.scheduleMeForCleanup();
        Test.stopTest();

        // ASSERT
        List<Log_Exception__c> logException = [Select Id From Log_Exception__c];
        System.assertEquals(logException.size(), 0, 'Log Table Should be Empty');
    }

    @isTest
   public static void testCleanupDoesNotRemoveEntriesNewerThan() {
        DateTime theDate = DateTime.now().addDays(-90);
        Log_Exception__c log = new Log_Exception__c();
        log.Class_Name__c = '';
        log.Method_Name__c = '';
        insert log;

        Test.setCreatedDate(log.Id, theDate);

        Test.startTest();
            Database.executeBatch(new CleanupRecordBatch('Log_Exception__c', 180, 'Days'), 200);
            CleanupRecordBatchSchedule.scheduleMeForCleanup();
        Test.stopTest();

        // ASSERT
        List<Log_Exception__c> logException = [Select Id From Log_Exception__c];
        System.assertEquals(logException.size(), 1, 'Log Table Should Not be Empty, log entry not old enough yet');
    }
    
    @isTest
    public static void testCleanupNotificationRecord() {
	DateTime theDate = DateTime.now().addHours(-1100);
        Notification__c notification = new Notification__c();
        notification.To__c = 'testuser@user.com';
        notification.Variables__c = '{"to":"testuser@user.com"}';
        notification.Template__c = 'TestTemplate';
        insert notification;
        Test.setCreatedDate(notification.Id, theDate);

        DateTime newDate = DateTime.now().addHours(-90);
        Notification__c notificationUndelete = new Notification__c();
        notificationUndelete.To__c = 'testuser1@user.com';
        notificationUndelete.Variables__c = '{"to":"testuser1@user.com"}';
        notificationUndelete.Template__c = 'TestTemplate11';
        insert notificationUndelete;
        Test.setCreatedDate(notificationUndelete.Id, newDate);

        Test.startTest();
            Database.executeBatch(new CleanupRecordBatch('Notification__c', 100, 'Hours'), 200);
            CleanupRecordBatchSchedule.scheduleMeForCleanup();
        Test.stopTest();

        // ASSERT
        List<Notification__c> notificationRecord = [SELECT Id FROM Notification__c];
        System.assertEquals(notificationRecord.size(), 1, 'Notification Table only have 1 entry, as 2 created one old enough for deletion and other not');
    }

}