force-app/main/default/objects/Copyright_Disclosure__c/Copyright_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Copyright Disclosure</label>
    <nameField>
        <label>Copyright Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copyright Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Creators_Request_Distrib_Open_Source_YN__c.field-meta.xml
<CustomField>
    <fullName>Creators_Request_Distrib_Open_Source_YN__c</fullName>
    <label>Creators Request Distribute Open Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Source__c/Open_Source__c.object-meta.xml
<CustomObject>
    <label>Open Source</label>
    <nameField>
        <label>Open Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Source__c/fields/Copyright_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Copyright_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copyright Disclosure</label>
    <referenceTo>Copyright_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CopyrightDisclosureTriggerHandler.cls
public class CopyrightDisclosureTriggerHandler {
    public static void onAfterUpdate(List<Copyright_Disclosure__c> copyrightList, Map<Id, Copyright_Disclosure__c> oldCopyrightMap) {
        // If the Creators_Request_Distrib_Open_Source_YN__c field is No, delete the related Open_Source__c object
        List<Open_Source__c> openSourceDeleteList = new List<Open_Source__c>();
        for(Copyright_Disclosure__c copyright : copyrightList) {
            if(
                copyright.Creators_Request_Distrib_Open_Source_YN__c == 'No' &&
                oldCopyrightMap.get(copyright.Id).Creators_Request_Distrib_Open_Source_YN__c == 'Yes'
            ) {
                openSourceDeleteList.addAll(DisclosureRecordFetch.getOpenSourceByCopyrightId(copyright.Id));
            }
        }

        if(!openSourceDeleteList.isEmpty()) {
            delete openSourceDeleteList;
        }
    }
}