force-app/main/default/objects/Copyright_Disclosure__c/Copyright_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Copyright Disclosure</label>
    <nameField>
        <label>Copyright Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copyright Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Creators_Request_Distrib_Open_Source_YN__c.field-meta.xml
<CustomField>
    <fullName>Creators_Request_Distrib_Open_Source_YN__c</fullName>
    <label>Creators Request Distribute Open Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Copyright Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Copyright_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Copyright Disclosures</relationshipLabel>
    <relationshipName>Copyright_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Source__c/Open_Source__c.object-meta.xml
<CustomObject>
    <label>Open Source</label>
    <nameField>
        <label>Open Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Source__c/fields/Copyright_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Copyright_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copyright Disclosure</label>
    <referenceTo>Copyright_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/fields/Software_Code_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Software_Code_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Software Code Disclosure</label>
    <referenceTo>Software_Code_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Software_Code_Disclosure__c/Software_Code_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Software Code Disclosure</label>
    <nameField>
        <label>Software Code Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Code Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Software Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Software_Code_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Software Code Disclosures</relationshipLabel>
    <relationshipName>Software_Code_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Is_Open_Source_YN__c.field-meta.xml
<CustomField>
    <fullName>Is_Open_Source_YN__c</fullName>
    <label>Is Open Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpenSourceTriggerHandler.cls
public class OpenSourceTriggerHandler {
    /**
     * Trigger handler for Open_Source__c before insert events
     * @param openSourceList List of new Open_Source__c objects to be processed
     */
    public static void onBeforeInsert(List<Open_Source__c> openSourceList) {
        validateOneToOne(openSourceList);
    }

    /**
     * Trigger handler for Open_Source__c before update events
     * @param openSourceList List of new Open_Source__c objects to be processed
     */
    public static void onBeforeUpdate(List<Open_Source__c> openSourceList) {
        validateOneToOne(openSourceList);
    }

    /**
     * Trigger handler for Open_Source__c after delete events
     * @param openSourceList List of new Open_Source__c objects to be processed
     */
    public static void onAfterDelete(List<Open_Source__c> openSourceList) {
        deleteRelatedDeptHeads(openSourceList);
    }

    /**
     * Validate that an Open_Source__c object is only assigned to either a
     * Software_Code_Disclosure__c object or a Copyright_Disclosure__c, but not
     * both
     * @param openSourceList List of Open_Source__c objects to be processed
     */
    private static void validateOneToOne(List<Open_Source__c> openSourceList) {
        for (Open_Source__c openSource : openSourceList) {
            if (openSource.Copyright_Disclosure__c != null && openSource.Software_Code_Disclosure__c != null) {
                openSource.addError('Open source may only be added to one of either a Copyright Disclosure or a Software Code Disclosure');
            }
        }
    }

    /**
     * Delete any Department_Head__c objects that are related to the parent if
     * the parent has the corresponding "Is Open Source" flag set to false
     * Disclosure__c objects
     * @param openSourceList List of Open_Source__c objects to be processed
     */
    private static void deleteRelatedDeptHeads(List<Open_Source__c> openSourceList) {
        List<Disclosure__c> discList = new List<Disclosure__c>();
        List<Id> softwareCodeDiscList = new List<Id>();
        List<Id> copyrightDiscList = new List<Id>();

        for(Open_Source__c openSource : openSourceList) {
            if(openSource.Copyright_Disclosure__c != null) {
                copyrightDiscList.add(openSource.Copyright_Disclosure__c);
            }
            if(openSource.Software_Code_Disclosure__c != null) {
                softwareCodeDiscList.add(openSource.Software_Code_Disclosure__c);
            }
        }

        discList.addAll([
            SELECT Id
            FROM Disclosure__c
            WHERE Id IN (
                SELECT Disclosure__c
                FROM Software_Code_Disclosure__c
                WHERE
                    Id IN :softwareCodeDiscList AND
                    Is_Open_Source_YN__c = 'No'
            )
        ]);

        discList.addAll([
            SELECT Id
            FROM Disclosure__c
            WHERE Id IN (
                SELECT Disclosure__c
                FROM Copyright_Disclosure__c
                WHERE
                    Id IN :copyrightDiscList AND
                    Creators_Request_Distrib_Open_Source_YN__c = 'No'
            )
        ]);

        List<Department_Head__c> deptHeadList = [
            SELECT Id
            FROM Department_Head__c
            WHERE Disclosure__c IN :discList
        ];

        delete deptHeadList;
    }
}