force-app/main/default/objects/Copyright_Disclosure__c/Copyright_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Copyright Disclosure</label>
    <nameField>
        <label>Copyright Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copyright Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Copyright Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Copyright_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Copyright Disclosures</relationshipLabel>
    <relationshipName>Copyright_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Delegated_To__c.field-meta.xml
<CustomField>
    <fullName>Delegated_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegated To</label>
    <referenceTo>Department_Head__c</referenceTo>
    <relationshipLabel>Delegated By</relationshipLabel>
    <relationshipName>Delegated_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/SubmittedOnBehalf__c.field-meta.xml
<CustomField>
    <fullName>SubmittedOnBehalf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted on behalf of someone else</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PrimaryInventor__c.field-meta.xml
<CustomField>
    <fullName>PrimaryInventor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Review_Draft_Watcher__c.field-meta.xml
<CustomField>
    <fullName>Review_Draft_Watcher__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Review Draft Disclosure</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Source__c/Open_Source__c.object-meta.xml
<CustomObject>
    <label>Open Source</label>
    <nameField>
        <label>Open Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Source__c/fields/Open_Source_Licensing__c.field-meta.xml
<CustomField>
    <fullName>Open_Source_Licensing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open Source Licensing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/fields/Open_Source_Licensing_Type__c.field-meta.xml
<CustomField>
    <fullName>Open_Source_Licensing_Type__c</fullName>
    <label>Open Source License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BSD License</fullName>
            </value>
            <value>
                <fullName>GPL v2 License</fullName>
            </value>
            <value>
                <fullName>LGPL v2 License</fullName>
            </value>
            <value>
                <fullName>AttributionCC BY</fullName>
            </value>
            <value>
                <fullName>Attribution-ShareAlikeCC BY-SA</fullName>
            </value>
            <value>
                <fullName>Attribution-NoDerivsCC BY-ND</fullName>
            </value>
            <value>
                <fullName>Attribution-NonCommercialCC BY-NC</fullName>
            </value>
            <value>
                <fullName>Attribution-NonCommercial-ShareAlikeCC BY-NC-SA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Source__c/fields/Open_Source_Other_Comments__c.field-meta.xml
<CustomField>
    <fullName>Open_Source_Other_Comments__c</fullName>
    <label>Open Source Other Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/fields/Software_Code_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Software_Code_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Software Code Disclosure</label>
    <referenceTo>Software_Code_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright_Disclosure</label>
</RecordType>

force-app/main/default/objects/Open_Source__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software_Code_Disclosure</label>
</RecordType>

force-app/main/default/objects/Software_Code_Disclosure__c/Software_Code_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Software Code Disclosure</label>
    <nameField>
        <label>Software Code Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Code Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Software Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Software_Code_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Software Code Disclosures</relationshipLabel>
    <relationshipName>Software_Code_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/TLO_Contact_Update_Request__c.object-meta.xml
<CustomObject>
    <description>Holds requested / recommended updates for a TLO Contact</description>
    <label>TLO Contact Update Request</label>
    <nameField>
        <displayFormat>CRU-{000000}</displayFormat>
        <label>TLO Contact Update Requests ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TLO_Contact Update Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>TLO_Contact_Update_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipName>Contact_Requested_Updates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Update_Status__c.field-meta.xml
<CustomField>
    <fullName>Update_Status__c</fullName>
    <description>Status indication whether TLO Ops has updated the Contact details or not. Defaults to Pending</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisclosureValidation.cls
public with sharing class DisclosureValidation {
    public static final string INITIATOR_ERROR_MSG = 'A disclosure can only be deleted by the Initiator (ie: the person who submitted the disclosure)';
    public static final string DRAFT_ERROR_MSG = 'Only Draft disclosures can be deleted.';

    public static void onBeforeDelete(List<Disclosure__c> disclosures) {
        string uid = userinfo.getUserId();
        System.debug(uid);

        for (Disclosure__c disclosure : disclosures) {
            System.debug(disclosure.Submitting_Contact__c);

            if (
                disclosure.Status__c != null &&
                disclosure.Status__c != 'Draft'
            ) {
                System.debug(DRAFT_ERROR_MSG);
                disclosure.addError(DRAFT_ERROR_MSG);
                //! TODO: This will need to be replaced ASAP
                // }else if (disclosure.Submitting_Contact__c != null && disclosure.Submitting_Contact__c != uid) {
                //     System.debug(INITIATOR_ERROR_MSG);
                //     disclosure.addError(INITIATOR_ERROR_MSG);
            } else {
                System.debug('Successful');
                if (disclosure.Id != null) {
                    if (disclosure.Name__c != 'Test Disclosure Deletion') {
                        List<DisclosureInventor__c> inventorList = DisclosureRecordFetch.getDisclosureInventorByDisclosureId(
                            disclosure.Id
                        );
                        String emailList = '';
                        for (DisclosureInventor__c inventor : inventorList) {
                            if (
                                inventor.PrimaryInventor__c == false &&
                                inventor.Review_Draft_Watcher__c == false
                            ) {
                                continue;
                            }
                            Account contact = DisclosureRecordFetch.getContactById(
                                inventor.Contact__c
                            );
                            if (
                                contact != null &&
                                contact.PersonEmail != null
                            ) {
                                emailList += contact.PersonEmail + ',';
                            } else if (
                                contact != null &&
                                contact.AltEmail__pc != null
                            ) {
                                emailList += contact.AltEmail__pc + ',';
                            }
                        }
                        if (emailList != '') {
                            Map<String, String> variables = new Map<String, String>();
                            variables.put(
                                'disclosure_title',
                                disclosure.Name__c
                            );
                            variables.put('disclosure_name', disclosure.Name);
                            variables.put(
                                'submitter_name',
                                DisclosureRecordFetch.getContactById(
                                        disclosure.Submitting_Contact__c
                                    )
                                    .Name
                            );
                            Notification__c newNotification = NotificationBuilder.buildNotificationEmail(
                                emailList.removeEnd(','),
                                NotificationBuilder.TEMPLATE_DISCLOSURE_PRIMARY_INVENTORS_DRAFT_DELETION,
                                variables
                            );

                            insert newNotification;
                        }
                    }
                }
            }
        }
    }

    public static Boolean statusEditableValidation(
        Disclosure__c oldDisclosure
    ) {
        // TODO if (oldDisclosure.Status__c == 'Approved' || oldDisclosure.Status__c == 'Rejected' || oldDisclosure.Status__c == 'Archived'  ) {
        // TODO refactor triggers because in this case:
        // TODO: Disclosure should never be editable by anyone unless its in a Draft status. Other than sys-admin being able to move from Archived to Draft.

        if (
            oldDisclosure.Status__c == 'Rejected' &&
            !PersonAccountMigrationHelpers.isPersonAccountMigrationInProgress() // TODO: Refactor - Remove post AC migration
        ) {
            oldDisclosure.addError(label.Disclosure_Error_Editable_State);
            return false;
        }
        return true;
    }

    public static void onDraftStatusChange(List<Disclosure__c> disclosures) {
        DisclosureValidation.DisclosureContext disclosureContext = DisclosureValidation.getDisclosureContext(
            disclosures
        );
        for (Disclosure__c disclosure : disclosures) {
            onDraftStatusChange(disclosure, disclosureContext);
        }

        onBehalfOfInventorValidation(disclosureContext.disclosureInventorMap);
    }
    private static void onDraftStatusChange(
        Disclosure__c disclosure,
        DisclosureValidation.DisclosureContext disclosureContext
    ) {
        if (disclosure.Status__c != null && disclosure.Status__c != 'Draft') {
            Id recordTypeIdCopyright = disclosureContext.recordTypeIdCopyright;
            Id recordTypeIdSoftware = disclosureContext.recordTypeIdSoftware;

            List<DisclosureInventor__c> inventors = onePrimaryInventorValidation(
                disclosure,
                disclosureContext.disclosureInventorMap.get(disclosure)
            );

            Boolean validateDepartmentHead = false;
            if (
                disclosure.RecordTypeId == recordTypeIdCopyright ||
                disclosure.RecordTypeId == recordTypeIdSoftware
            ) {
                List<Open_Source__c> openSources = disclosureContext.disclosureOpenSourceMap.get(
                    disclosure
                );
                if (
                    !openSources.isEmpty() &&
                    openSources[0].Open_Source_Licensing__c
                ) {
                    // The ERD Intention is a one to one Mapping
                    validateDepartmentHead = true;
                }
            }
            // DEPT HEAD VALIDATIONS
            if (validateDepartmentHead) {
                Department_Head__c departmentHead = oneDepartmentHeadValidation(
                    disclosure,
                    disclosureContext.disclosureDeptHeadMap.get(disclosure)
                );

                for (DisclosureInventor__c inventor : inventors) {
                    if (
                        departmentHead != null &&
                        inventor.Contact__c == departmentHead.Contact__c
                    ) {
                        disclosure.addError(
                            label.Disclosure_Error_Department_Head_Inventor
                        );
                    }
                }

                if (
                    departmentHead != null &&
                    !Helpers.isActiveKerb(
                        departmentHead.Contact__r.MoiraStatus__pc
                    )
                ) {
                    disclosure.addError(
                        label.Disclosure_Error_Department_Head_Non_Staff
                    );
                }
            }

            // PRIMARY INVENTOR VALIDATIONS
            for (DisclosureInventor__c inventor : inventors) {
                if (
                    !Helpers.isActiveKerb(
                        inventor.Contact__r.MoiraStatus__pc
                    ) && inventor.PrimaryInventor__c == true
                ) {
                    disclosure.addError(
                        label.Disclosure_Error_Primary_Inventor_Non_Staff
                    );
                }
            }
        }
    }

    public static List<DisclosureInventor__c> onePrimaryInventorValidation(
        Disclosure__c disclosure,
        List<DisclosureInventor__c> existingInventors
    ) {
        Boolean found = false;
        for (DisclosureInventor__c inventor : existingInventors) {
            if (inventor.PrimaryInventor__c == true) {
                found = true;
            }
        }
        if (!found) {
            if (!System.isBatch())
                disclosure.addError(
                    label.Disclosure_Error_Primary_Inventor_Count
                );
        }
        return existingInventors;
    }

    public static Department_Head__c oneDepartmentHeadValidation(
        Disclosure__c disclosure,
        List<Department_Head__c> existingDepartmentHead
    ) {
        if (existingDepartmentHead.size() == 1) {
            return existingDepartmentHead.get(0);
        } else {
            if (!System.isBatch()) {
                disclosure.addError(
                    label.Disclosure_Error_Department_Head_Count
                );
            }
            return null;
        }
    }

    public static void onBehalfOfInventorValidation(
        Map<Disclosure__c, List<DisclosureInventor__c>> disclosureInventorMap
    ) {
        for (Disclosure__c disclosure : disclosureInventorMap.keySet()) {
            List<DisclosureInventor__c> inventors = disclosureInventorMap.get(
                disclosure
            );
            Id submittingContactId = disclosure.Submitting_Contact__c;

            if (disclosure.SubmittedOnBehalf__c == true) {
                for (DisclosureInventor__c inv : inventors) {
                    if (inv.Contact__c == submittingContactId) {
                        //SOB cannot add themselves as an inventor either
                        disclosure.addError(
                            label.Disclosure_Error_Submitting_OnBehalfOf_Inventor
                        );
                    }
                }
            } else {
                Boolean foundInventor = false;
                for (DisclosureInventor__c inv : inventors) {
                    if (inv.Contact__c == submittingContactId) {
                        foundInventor = true;
                    }
                }
                if (!foundInventor) {
                    disclosure.addError(
                        label.Disclosure_Error_Submitting_Inventor
                    );
                }
            }
        }
    }

    public static boolean onBeforeApproveValidationByDisclosureId(
        Map<Id, Disclosure__c> lookup,
        List<Id> approvedDisclosureIds
    ) {
        // Check if any pending Contact Update Requests exist
        List<TLO_Contact_Update_Request__c> tloContactReqList = [
            SELECT Id, Update_Status__c, Disclosure__c, Contact__r.Name
            FROM TLO_Contact_Update_Request__c
            WHERE
                Disclosure__r.Id IN :approvedDisclosureIds
                AND Update_Status__c = 'Pending'
        ];
        for (TLO_Contact_Update_Request__c cur : tloContactReqList) {
            // Pending Contact Update Request exists, add error
            if (lookup != null) {
                Disclosure__c disclosure = lookup.get(cur.Disclosure__c);
                disclosure.addError(
                    label.PendingContactUpdateReq +
                    ' ' +
                    cur.Contact__r.Name
                );
            } else {
                throw new AuraHandledException(
                    label.PendingContactUpdateReq +
                    ' ' +
                    cur.Contact__r.Name
                );
            }
        }

        // Check if any Disclosure Inventors (Contacts) are missing PersonEmail values
        List<DisclosureInventor__c> inventors = [
            SELECT Id, Contact__r.Name, Disclosure__c
            FROM DisclosureInventor__c
            WHERE
                Disclosure__r.Id IN :approvedDisclosureIds
                AND Contact__r.PersonEmail = NULL
        ];
        for (DisclosureInventor__c inventor : inventors) {
            // Contact does not have an PersonEmail value, throw an error
            if (lookup != null) {
                Disclosure__c disclosure = lookup.get(inventor.Disclosure__c);
                disclosure.addError(
                    label.ChangedContactUpdateReqStatusValidation +
                    ': ' +
                    inventor.Contact__r.Name
                );
            } else {
                throw new AuraHandledexception(
                    label.ChangedContactUpdateReqStatusValidation +
                    ': ' +
                    inventor.Contact__r.Name
                );
            }
        }

        return true;
    }

    @TestVisible
    private static DisclosureContext getDisclosureContext(
        List<Disclosure__c> disclosures
    ) {
        Id recordTypeIdCopyright = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Copyright_Disclosure')
            .getRecordTypeId();
        Id recordTypeIdSoftware = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();

        Map<Disclosure__c, List<DisclosureInventor__c>> disclosureInventorMap = new Map<Disclosure__c, List<DisclosureInventor__c>>();
        Map<Disclosure__c, List<Department_Head__c>> disclosureDeptHeadMap = new Map<Disclosure__c, List<Department_Head__c>>();
        Map<Disclosure__c, List<Open_Source__c>> disclosureOpenSourceMap = new Map<Disclosure__c, List<Open_Source__c>>();

        Set<String> disclosureIds = new Set<String>();
        Map<String, Disclosure__c> disclosureMap = new Map<String, Disclosure__c>();

        Boolean queryCopyrightType = false;
        Boolean querySoftwareType = false;

        for (Disclosure__c disclosure : disclosures) {
            disclosureIds.add(disclosure.Id);
            disclosureMap.put(disclosure.Id, disclosure);
            disclosureInventorMap.put(
                disclosure,
                new List<DisclosureInventor__c>()
            );
            disclosureDeptHeadMap.put(
                disclosure,
                new List<Department_Head__c>()
            );
            disclosureOpenSourceMap.put(disclosure, new List<Open_Source__c>());
            if (disclosure.RecordTypeId == recordTypeIdCopyright) {
                queryCopyrightType = true;
            }
            if (disclosure.RecordTypeId == recordTypeIdSoftware) {
                querySoftwareType = true;
            }
        }

        // Inventors
        List<DisclosureInventor__c> inventors = [
            SELECT
                Id,
                PrimaryInventor__c,
                Contact__c,
                Contact__r.MoiraStatus__pc,
                Disclosure__c
            FROM DisclosureInventor__c
            WHERE Disclosure__c IN :disclosureIds
        ];

        for (DisclosureInventor__c inventor : inventors) {
            Disclosure__c contactDisclosure = disclosureMap.get(
                inventor.Disclosure__c
            );
            if (contactDisclosure == null) {
                throw new AuraHandledException('Existing Disclosure not found');
            }
            disclosureInventorMap.get(contactDisclosure).add(inventor);
        }

        // Department head
        List<Department_Head__c> existingDepartmentHeads = [
            SELECT
                Id,
                Contact__c,
                Contact__r.MoiraStatus__pc,
                Delegated_To__r.Contact__r.Id,
                Disclosure__c
            FROM Department_Head__c
            WHERE Disclosure__c IN :disclosureIds AND Delegated_To__c = NULL
        ];
        for (Department_Head__c deptHead : existingDepartmentHeads) {
            Disclosure__c contactDisclosure = disclosureMap.get(
                deptHead.Disclosure__c
            );
            if (contactDisclosure == null) {
                throw new AuraHandledException('Existing Disclosure not found');
            }
            disclosureDeptHeadMap.get(contactDisclosure).add(deptHead);
        }

        // Open_Source__c Software
        if (querySoftwareType) {
            List<Software_Code_Disclosure__c> disclosureSoftware = [
                SELECT
                    Id,
                    Name,
                    Disclosure__c,
                    (
                        SELECT
                            Id,
                            Name,
                            Open_Source_Licensing_Type__c,
                            Open_Source_Licensing__c,
                            Open_Source_Other_Comments__c,
                            Publicly_Available_Details__c
                        FROM Open_Sources__r
                    )
                FROM Software_Code_Disclosure__c
                WHERE Disclosure__c IN :disclosureIds
            ];

            for (Software_Code_Disclosure__c sc : disclosureSoftware) {
                Disclosure__c contactDisclosure = disclosureMap.get(
                    sc.Disclosure__c
                );
                if (contactDisclosure == null) {
                    throw new AuraHandledException(
                        'Existing Disclosure not found'
                    );
                }
                for (Open_Source__c opensource : sc.Open_Sources__r) {
                    disclosureOpenSourceMap.get(contactDisclosure)
                        .add(opensource);
                }
            }
        }

        // Open_Source__c Copyright_Disclosure__c
        if (queryCopyrightType) {
            List<Copyright_Disclosure__c> disclosureCopyright = [
                SELECT
                    Id,
                    Name,
                    Disclosure__c,
                    (
                        SELECT
                            Id,
                            Name,
                            Open_Source_Licensing_Type__c,
                            Open_Source_Licensing__c,
                            Open_Source_Other_Comments__c
                        FROM Open_Sources__r
                    )
                FROM Copyright_Disclosure__c
                WHERE Disclosure__c IN :disclosureIds
            ];

            for (Copyright_Disclosure__c cr : disclosureCopyright) {
                Disclosure__c contactDisclosure = disclosureMap.get(
                    cr.Disclosure__c
                );
                if (contactDisclosure == null) {
                    throw new AuraHandledException(
                        'Existing Disclosure not found'
                    );
                }
                for (Open_Source__c opensource : cr.Open_Sources__r) {
                    disclosureOpenSourceMap.get(contactDisclosure)
                        .add(opensource);
                }
            }
        }

        DisclosureContext context = new DisclosureContext();
        context.disclosures = disclosures;
        context.disclosureInventorMap = disclosureInventorMap;
        context.disclosureDeptHeadMap = disclosureDeptHeadMap;
        context.disclosureOpenSourceMap = disclosureOpenSourceMap;
        context.recordTypeIdCopyright = recordTypeIdCopyright;
        context.recordTypeIdSoftware = recordTypeIdSoftware;

        return context;
    }

    @TestVisible
    private class DisclosureContext {
        @TestVisible
        private Id recordTypeIdCopyright;
        @TestVisible
        private Id recordTypeIdSoftware;

        @TestVisible
        private List<Disclosure__c> disclosures;
        @TestVisible
        private Map<Disclosure__c, List<DisclosureInventor__c>> disclosureInventorMap;
        @TestVisible
        private Map<Disclosure__c, List<Department_Head__c>> disclosureDeptHeadMap;
        @TestVisible
        private Map<Disclosure__c, List<Open_Source__c>> disclosureOpenSourceMap;
    }
}