force-app/main/default/objects/Copyright_Disclosure__c/Copyright_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Copyright Disclosure</label>
    <nameField>
        <label>Copyright Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copyright Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Creators_Request_Distrib_Open_Source_YN__c.field-meta.xml
<CustomField>
    <fullName>Creators_Request_Distrib_Open_Source_YN__c</fullName>
    <label>Creators Request Distribute Open Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Copyright_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Copyright Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Copyright_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Copyright Disclosures</relationshipLabel>
    <relationshipName>Copyright_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>TLO Case Number</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/recordTypes/Invention_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Invention_Disclosure</fullName>
    <active>true</active>
    <label>Invention</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/Disclosure_Action__c/Disclosure_Action__c.object-meta.xml
<CustomObject>
    <label>Disclosure Action</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Action__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Disclosure__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Variables__c.field-meta.xml
<CustomField>
    <fullName>Variables__c</fullName>
    <label>Variables</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/Open_Source__c.object-meta.xml
<CustomObject>
    <label>Open Source</label>
    <nameField>
        <label>Open Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Source__c/fields/Copyright_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Copyright_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copyright Disclosure</label>
    <referenceTo>Copyright_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/fields/Software_Code_Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Software_Code_Disclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Software Code Disclosure</label>
    <referenceTo>Software_Code_Disclosure__c</referenceTo>
    <relationshipLabel>Open Sources</relationshipLabel>
    <relationshipName>Open_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Open_Source__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright_Disclosure</label>
</RecordType>

force-app/main/default/objects/Open_Source__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software_Code_Disclosure</label>
</RecordType>

force-app/main/default/objects/Software_Code_Disclosure__c/Software_Code_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Software Code Disclosure</label>
    <nameField>
        <label>Software Code Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Code Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Software Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Software_Code_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Software Code Disclosures</relationshipLabel>
    <relationshipName>Software_Code_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Is_Open_Source_YN__c.field-meta.xml
<CustomField>
    <fullName>Is_Open_Source_YN__c</fullName>
    <label>Is Open Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Open_Source_Comment__c.field-meta.xml
<CustomField>
    <fullName>Open_Source_Comment__c</fullName>
    <label>Open Source Comment</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/TLO_Contact_Update_Request__c.object-meta.xml
<CustomObject>
    <description>Holds requested / recommended updates for a TLO Contact</description>
    <label>TLO Contact Update Request</label>
    <nameField>
        <displayFormat>CRU-{000000}</displayFormat>
        <label>TLO Contact Update Requests ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TLO_Contact Update Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>TLO_Contact_Update_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TLO_Contact_Update_Request__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipName>Contact_Requested_Updates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DisclosuresTriggerHandlerTest.cls
@isTest
public class DisclosuresTriggerHandlerTest {
    @TestSetup
    static void setup() {
        TestSetup.defaultConfiguration();
    }

    /**
     * If an Open Source object is deleted, but the parent Copyright/Software Code
     * has the corresponding "Is Open Source" flag set to true, the Department
     * Head should not be deleted
     */
    @isTest
    public static void testOpenSourceDeleteDeptHead() {
        // Set up data
        ContactSampleDataFactory.createSampleContacts();
        Disclosure__c copyrightDisc = DisclosureSampleDataFactory.createCopyrightDisclosureWithDeptHeadAsInventor(
            'Open Source Delete Copyright',
            false
        );
        Disclosure__c softwareDisc = DisclosureSampleDataFactory.createDraftSoftwareDisclosureFullyPopulated(
            'Open Source Delete Software',
            false
        );

        Test.startTest();
        try {
            // Test Copyright
            // Check that Department Head exists
            List<Department_Head__c> copyrightDeptHeadList = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
                copyrightDisc.Id
            );
            System.assert(
                copyrightDeptHeadList.isEmpty() == false,
                'Department Head was not created for Copyright'
            );

            // Check that Open Source exists
            Copyright_Disclosure__c copyright = DisclosureRecordFetch.getCopyrightByDisclosureId(
                copyrightDisc.Id
            )[0];
            List<Open_Source__c> copyrightOpenSourceList = DisclosureRecordFetch.getOpenSourceByCopyrightId(
                copyright.Id
            );
            System.assert(
                copyrightOpenSourceList.isEmpty() == false,
                'Open Source was not created for Copyright'
            );

            // Delete Open Source from Disclosure
            Open_Source__c copyrightOpenSource = copyrightOpenSourceList[0];
            delete copyrightOpenSource;

            // Check that Department Head was not deleted
            copyrightDeptHeadList = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
                copyrightDisc.Id
            );
            System.assert(
                copyrightDeptHeadList.isEmpty() == false,
                'Department Head was not expected to be deleted for Copyright, but it was'
            );

            // Test Software Code
            // Check that Department Head exists
            List<Department_Head__c> softwareCodeDeptHeadList = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
                softwareDisc.Id
            );
            System.assert(
                softwareCodeDeptHeadList.isEmpty() == false,
                'Department Head was not created for Software Code'
            );

            // Check that Open Source exists
            Software_Code_Disclosure__c softwareCode = DisclosureRecordFetch.getSoftwareCodeByDisclosureId(
                softwareDisc.Id
            )[0];
            List<Open_Source__c> openSourceList = DisclosureRecordFetch.getOpenSourceBySoftwareCodeId(
                softwareCode.Id
            );
            System.assert(
                openSourceList.isEmpty() == false,
                'Open Source was not created for Software Code'
            );

            // Delete Open Source from Disclosure
            Open_Source__c openSource = openSourceList[0];
            delete openSource;

            // Check that Department Head was deleted
            softwareCodeDeptHeadList = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
                softwareDisc.Id
            );
            System.assert(
                softwareCodeDeptHeadList.isEmpty() == false,
                'Department Head was not expected to be deleted for Software Code, but it was'
            );
        } catch (Exception e) {
            System.assert(false, 'Exception was thrown: ' + e.getMessage());
        }

        Test.stopTest();
    }

    /**
     * If a Software Code or Copyright Disclosure has the corresponding "Is Open
     * Source" flag set to false, then any related Open Source and Department
     * Head objects should be deleted
     */
    @isTest
    public static void testOpenSourceUncheck() {
        // Set up Data
        ContactSampleDataFactory.createSampleContacts();
        Disclosure__c copyrightDisc = DisclosureSampleDataFactory.createCopyrightDisclosureWithDeptHeadAsInventor(
            'Open Source Delete Copyright',
            false
        );
        Disclosure__c softwareDisc = DisclosureSampleDataFactory.createDraftSoftwareDisclosureFullyPopulated(
            'Open Source Delete Software',
            false
        );

        Test.startTest();
        try {
            // Test Copyright
            // Check that Department Head exists
            List<Department_Head__c> copyrightDeptHeadList = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
                copyrightDisc.Id
            );
            System.assert(
                copyrightDeptHeadList.isEmpty() == false,
                'Department Head was not created for Copyright'
            );

            // Check that Open Source exists
            Copyright_Disclosure__c copyright = DisclosureRecordFetch.getCopyrightByDisclosureId(
                copyrightDisc.Id
            )[0];
            List<Open_Source__c> copyrightOpenSourceList = DisclosureRecordFetch.getOpenSourceByCopyrightId(
                copyright.Id
            );
            System.assert(
                copyrightOpenSourceList.isEmpty() == false,
                'Open Source was not created for Copyright'
            );

            // Uncheck Open Source from Copyright
            copyright.Creators_Request_Distrib_Open_Source_YN__c = 'No';
            update copyright;

            // Check that Open Source was deleted
            copyrightOpenSourceList = DisclosureRecordFetch.getOpenSourceByCopyrightId(
                copyright.Id
            );
            System.assert(
                copyrightOpenSourceList.isEmpty() == true,
                'Open Source was expected deleted for Copyright, but was not'
            );

            // Check that Department Head was deleted
            copyrightDeptHeadList = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
                copyrightDisc.Id
            );
            System.assert(
                copyrightDeptHeadList.isEmpty() == true,
                'Department Head was expected to be deleted for Copyright, but was not'
            );

            // Test Software Code
            // Check that Department Head exists
            List<Department_Head__c> softwareCodeDeptHeadList = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
                softwareDisc.Id
            );
            System.assert(
                softwareCodeDeptHeadList.isEmpty() == false,
                'Department Head was not created for Software Code'
            );

            // Check that Open Source exists
            Software_Code_Disclosure__c softwareCode = DisclosureRecordFetch.getSoftwareCodeByDisclosureId(
                softwareDisc.Id
            )[0];
            List<Open_Source__c> openSourceList = DisclosureRecordFetch.getOpenSourceBySoftwareCodeId(
                softwareCode.Id
            );
            System.assert(
                openSourceList.isEmpty() == false,
                'Open Source was not created for Software Code'
            );

            // Uncheck Open Source from Software
            softwareCode.Is_Open_Source_YN__c = 'No';
            softwareCode.Open_Source_Comment__c = 'GitHub';
            update softwareCode;

            // Check that Open Source was deleted
            openSourceList = DisclosureRecordFetch.getOpenSourceBySoftwareCodeId(
                softwareCode.Id
            );
            System.assert(
                openSourceList.isEmpty() == true,
                'Open Source was expected deleted for Software, but was not'
            );

            // Check that Department Head was deleted
            softwareCodeDeptHeadList = DisclosureRecordFetch.getDepartmentHeadByDisclosureId(
                softwareDisc.Id
            );
            System.assert(
                softwareCodeDeptHeadList.isEmpty() == true,
                'Department Head was expected to be deleted, but was not'
            );
        } catch (Exception e) {
            System.assert(false, 'Exception was thrown: ' + e.getMessage());
        }

        Test.stopTest();
    }

    @isTest
    public static void validateOnBeforeDelete() {
        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Copyright_Disclosure')
            .getRecordTypeId();
        Account contact = SampleDataFactory.createContact(
            'Donald1',
            true,
            '12345678'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(
            recordTypeId,
            'Sample Draft Disclosure for Copyright',
            'Draft',
            contact
        );
        Account pointOfContact = null;
        Copyright_Disclosure__c copyright = SampleDataFactory.createCopyright(
            'TestCopy',
            disclosure,
            pointOfContact
        );
        delete disclosure;

        Id recordTypeId1 = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account contact1 = SampleDataFactory.createContact(
            'Donald2',
            true,
            '12345671'
        );
        Disclosure__c disclosure1 = SampleDataFactory.createDisclosure(
            recordTypeId1,
            'Sample Draft Disclosure for SoftwareCode1',
            'Draft',
            contact1
        );
        Software_Code_Disclosure__c software = SampleDataFactory.createSoftwareCode(
            'TestSoft',
            disclosure1
        );
        SampleDataFactory.createOpenSource('name', null, software);
        delete disclosure1;
    }

    @isTest
    public static void validateBeforeUpdate() {
        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Invention_Disclosure')
            .getRecordTypeId();
        Account contact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account contactHead = SampleDataFactory.createContact(
            'Donald1',
            true,
            '123456781'
        );
        Account submittingContact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '11345678'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
            recordTypeId,
            'Sample Draft Disclosure for Invention',
            'Draft',
            submittingContact
        );
        DisclosureInventor__c disclosureInventor = SampleDataFactory.createInventor(
            disclosure,
            true,
            contact
        );

        Department_Head__c departmentHead = SampleDataFactory.createDepartmentHead(
            disclosure,
            contactHead
        );

        disclosure.Status__c = 'Draft';
        update disclosure;

        disclosure.Status__c = 'Inventor Submitted';
        update disclosure;
    }

    @isTest
    public static void validateAfterUpdate() {
        try {
            Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Invention_Disclosure')
                .getRecordTypeId();
            Account contact = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account contactHead = SampleDataFactory.createContact(
                'Donald1',
                true,
                '123456781'
            );
            Disclosure__c disclosure = SampleDataFactory.createDisclosure(
                recordTypeId,
                'Sample Draft Disclosure for Invention',
                'Draft',
                contact
            );
            DisclosureInventor__c disclosureInventor = SampleDataFactory.createInventor(
                disclosure,
                true,
                contact
            );

            Department_Head__c departmentHead = SampleDataFactory.createDepartmentHead(
                disclosure,
                contactHead
            );
            disclosure.Status__c = 'Rejected';
            update disclosure;
            System.assert(false, 'Exception not thrown');
        } catch (Exception ex) {
            String errorMessage = ex.getMessage();
            System.assertEquals(
                errorMessage.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                true
            );
            //Please review the Rejection Reason before rejecting the disclosure
        }
    }
    @isTest
    public static void validateUnarchivedContactActionCreation() {
        try {
            Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
                .get('Invention_Disclosure')
                .getRecordTypeId();
            Account contact = SampleDataFactory.createContact(
                'Donald',
                true,
                '12345678'
            );
            Account contactHead = SampleDataFactory.createContact(
                'Donald1',
                true,
                '123456781'
            );
            Disclosure__c disclosure = SampleDataFactory.createDisclosure(
                recordTypeId,
                'Sample Draft Disclosure for Invention',
                'Draft',
                contact
            );
            DisclosureInventor__c disclosureInventor = SampleDataFactory.createInventor(
                disclosure,
                true,
                contact
            );

            Department_Head__c departmentHead = SampleDataFactory.createDepartmentHead(
                disclosure,
                contactHead
            );
            disclosure.Status__c = 'Archived';
            update disclosure;

            disclosure.Status__c = 'Draft';
            update disclosure;

            List<Disclosure_Action__c> disclosureActions = [
                SELECT Id, Name, Disclosure__c, RecordTypeId
                FROM Disclosure_Action__c
                WHERE Disclosure__c = :disclosure.Id
            ];

            System.assertEquals(disclosureActions.size(), 2);
        } catch (Exception ex) {
            String errorMessage = ex.getMessage();
            System.assertEquals(
                errorMessage.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                true
            );
            //Please review the Rejection Reason before rejecting the disclosure
        }
    }

    @isTest
    public static void validateAfterUpdatev1() {
        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Invention_Disclosure')
            .getRecordTypeId();
        Account contact = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account contactHead = SampleDataFactory.createContact(
            'Donald1',
            true,
            '123456781'
        );
        Account submittingContact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '11345678'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
            recordTypeId,
            'Sample Draft Disclosure for Invention',
            'Draft',
            submittingContact
        );
        DisclosureInventor__c disclosureInventor = SampleDataFactory.createInventor(
            disclosure,
            true,
            contact
        );

        Department_Head__c departmentHead = SampleDataFactory.createDepartmentHead(
            disclosure,
            contactHead
        );

        disclosure.Status__c = 'Inventor Submitted';
        update disclosure;

        disclosure.Status__c = 'Approved';
        update disclosure;
        system.assertEquals('Approved', disclosure.Status__c);
    }

    @IsTest
    public static void validateAllInventorSignedNotifications() {
        String disclosureTitle = 'Sample Draft Disclosure for Invention to be signed 1';

        Id recordTypeId = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Invention_Disclosure')
            .getRecordTypeId();
        Account contactInventor1 = SampleDataFactory.createContact(
            'James',
            true,
            '12345678'
        );
        Account contactInventor2 = SampleDataFactory.createContact(
            'Henry',
            true,
            '123456781'
        );
        Account submittingContact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '11345678'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
            recordTypeId,
            disclosureTitle,
            'Draft',
            submittingContact
        );

        DisclosureInventor__c disclosureInventor1 = SampleDataFactory.createInventor(
            disclosure,
            true,
            contactInventor1
        );
        DisclosureInventor__c disclosureInventor2 = SampleDataFactory.createInventor(
            disclosure,
            true,
            contactInventor2
        );

        disclosure.Case_Number__c = '1234';
        update disclosure;

        disclosureInventor1.Signed_Status__c = 'Yes';
        update disclosureInventor1;

        List<Notification__c> notifications = [
            SELECT Id, Template__c, Variables__c
            FROM Notification__c
            WHERE
                Template__c = :NotificationBuilder.TEMPLATE_DISCLOSURE_ALL_SIGNED
        ];
        System.assertEquals(
            0,
            notifications.size(),
            'There should be no notifications for TEMPLATE_DISCLOSURE_ALL_SIGNED yet, not all inventors have signed.'
        );

        disclosureInventor2.Signed_Status__c = 'Yes';
        update disclosureInventor2;

        // get data to run checks against
        Disclosure__c disclosureToTest = getDisclosureToTest(disclosureTitle);
        Notification__c notification = [
            SELECT Id, Template__c, Variables__c
            FROM Notification__c
            WHERE
                Template__c = :NotificationBuilder.TEMPLATE_DISCLOSURE_ALL_SIGNED
            LIMIT 1
        ];
        Map<String, Object> jsonVal = (Map<String, Object>) JSON.deserializeUntyped(
            notification.Variables__c
        );
        RecordType inventionRecordType = [
            SELECT Name
            FROM RecordType
            WHERE ID = :recordTypeId
            LIMIT 1
        ];

        // ASSERT
        System.assertEquals(
            NotificationBuilder.TEMPLATE_DISCLOSURE_ALL_SIGNED,
            notification.Template__c,
            'Template name should be for TEMPLATE_DISCLOSURE_ALL_SIGNED'
        );
        System.assertEquals(
            disclosureToTest.Submitting_Contact__r.Name,
            String.valueOf(jsonVal.get('submitter_name')),
            'submitter_name variables should match that of the Submitted By person on disclosure'
        );
        System.assertEquals(
            inventionRecordType.Name,
            String.valueOf(jsonVal.get('disclosure_type')),
            'disclosure_type should be the Name of Invention_Disclosure'
        );
        System.assertEquals(
            disclosureToTest.Name__c,
            String.valueOf(jsonVal.get('disclosure_title')),
            'disclosure_title should be the Name__c of Disclosure'
        );
        System.assertEquals(
            disclosureToTest.Case_Number__c,
            String.valueOf(jsonVal.get('case_number')),
            'case_number should be the Case_Number__c of Disclosure'
        );
        System.assertEquals(
            URL.getSalesforceBaseUrl().toExternalForm() +
            '/lightning/r/Disclosure__c/' +
            disclosureToTest.Id +
            '/view',
            String.valueOf(jsonVal.get('link')),
            'link to be to disclosure view by id'
        );
    }

    @isTest
    public static void validateBeforeUpdateContactUpdateRequest() {
        ContactSampleDataFactory.createSampleContacts();
        String disclosureTitle = 'ContactUpdateRequest';
        Disclosure__c d = DisclosureSampleDataFactory.createDraftSoftwareDisclosureFullyPopulated(
            disclosureTitle,
            true
        );

        Account contact = [
            SELECT Id
            FROM Account
            WHERE MitId__pc = '900047497'
        ];

        TLO_Contact_Update_Request__c cur = new TLO_Contact_Update_Request__c(
            Disclosure__c = d.Id,
            Contact__c = contact.Id,
            Email__c = 'test@gmail.com'
        );
        insert (cur);

        Disclosure__c disclosure = [
            SELECT Id, Name__c
            FROM Disclosure__c
            WHERE Name__c = :disclosureTitle
            LIMIT 1
        ];

        Test.startTest();
        try {
            disclosure.Status__c = 'Approved';
            update disclosure;
            System.assert(
                false,
                'Pending Contact Update request exist not thrown'
            );
        } catch (Exception error) {
            System.assert(true, error.getMessage());
        }
        Test.stopTest();
    }

    private static Disclosure__c getDisclosureToTest(String title) {
        Disclosure__c disclosureToTest = [
            SELECT
                Id,
                Status__c,
                Name__c,
                Case_Number__c,
                SubmittedOnBehalf__c,
                Submitting_Contact__c,
                Submitting_Contact__r.Id,
                Submitting_Contact__r.Name,
                Submitting_Contact__r.PersonEmail,
                Submitting_Contact__r.AltEmail__pc
            FROM Disclosure__c
            WHERE Name__c = :title
            LIMIT 1
        ];
        return disclosureToTest;
    }
}