force-app/main/default/objects/DocuSign_Settings__c/DocuSign_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Per Environment Settings for DocuSign</description>
    <label>DocuSign Settings</label>
</CustomObject>

force-app/main/default/objects/DocuSign_Settings__c/fields/DocuSign_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Account_Id__c</fullName>
    <label>DocuSign Account Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DocuSign_Settings__c/fields/DocuSign_Disclosure_Signing_TemplateId__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Disclosure_Signing_TemplateId__c</fullName>
    <label>DocuSign Disclosure Signing TemplateId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DocuSignEnvelopeApiTest.cls
@IsTest 
public with sharing class DocuSignEnvelopeApiTest {
    @IsTest 
    public static void getDocumentByRecipientId() {
        DocuSign_Settings__c docuSignConfig = new DocuSign_Settings__c(DocuSign_Account_Id__c = '5529b715-7cb3-4661-b86f-529c9c8571f9', 
                                                                       DocuSign_Disclosure_Signing_TemplateId__c = '123');
        insert docuSignConfig;

        DocuSignEnvelopeApi docuSignApi = new DocuSignEnvelopeApi();

        String envelopeId = '130381d7-b403-466a-9872-2106d362d66d';
        String recipientId = '1';

        Test.startTest();
            DocuSignApiMock docuSignApiMock = new DocuSignApiMock();
            Test.setMock(HttpCalloutMock.class, docuSignApiMock);

            Blob docBlob = docuSignApi.getDocumentByRecipientId(envelopeId, recipientId);
            String base64Pdf = EncodingUtil.base64Encode(docBlob);
            System.debug('\n\nbase64Pdf:- \n\n' + base64Pdf);
        Test.stopTest();

        System.assert(base64Pdf != null, 'This should not be null');
    }
}