force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/IPIA_Record__c.field-meta.xml
<CustomField>
    <fullName>IPIA_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IPIA</label>
    <referenceTo>IPIA_Record__c</referenceTo>
    <relationshipLabel>IPIAs</relationshipLabel>
    <relationshipName>IPIAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Record__c/fields/FormName__c.field-meta.xml
<CustomField>
    <fullName>FormName__c</fullName>
    <label>Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <label>MIT ID</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/SignDatetime__c.field-meta.xml
<CustomField>
    <fullName>SignDatetime__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DisclosureInventorServiceTest.cls
/**
 * Created by Andreas du Preez on 2024/08/06.
 */

@IsTest
public with sharing class DisclosureInventorServiceTest {

    @IsTest
    public static void returnsDisclosureInventorsWithUpdatedIPIALookup() {
        List<DisclosureInventor__c> disclosureInventors = new List<DisclosureInventor__c>{
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345123' )),
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345456' ))
        };
        List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>{
                new IPIA_Record__c(MitId__c = '912345123' , FormName__c = 'TestForm1', SignDatetime__c = Date.today().addDays(-2)),
                new IPIA_Record__c(MitId__c = '912345123' , FormName__c = 'TestForm2', SignDatetime__c = Date.today().addDays(-1)),
                new IPIA_Record__c(MitId__c = '912345456' , FormName__c = 'TestForm3', SignDatetime__c = Date.today().addDays(-3)),
                new IPIA_Record__c(MitId__c = '912345456' , FormName__c = 'TestForm4', SignDatetime__c = Date.today())
        };
        insert ipiaRecords;

        Test.startTest();
        List<DisclosureInventor__c> updatedInventors = DisclosureInventorService.linkDisclosureInventorToIPIARecords(disclosureInventors);
        Test.stopTest();

        Assert.areEqual(ipiaRecords[1].Id, updatedInventors[0].IPIA_Record__c, 'First inventor should be linked to the latest IPIA record');
        Assert.areEqual(ipiaRecords[3].Id, updatedInventors[1].IPIA_Record__c, 'Second inventor should be linked to the latest IPIA record');
    }

    @IsTest
    public static void returnsDisclosureInventorsWithNoIPIALookupWhenNoMatchingIPIARecords() {
        List<DisclosureInventor__c> disclosureInventors = new List<DisclosureInventor__c>{
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345120' )),
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345450' ))
        };
        List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>{
                new IPIA_Record__c(MitId__c = '912345123' , FormName__c = 'TestForm1', SignDatetime__c = Date.today().addDays(-2)),
                new IPIA_Record__c(MitId__c = '912345456' , FormName__c = 'TestForm2', SignDatetime__c = Date.today().addDays(-1))
        };
        insert ipiaRecords;

        Test.startTest();
        List<DisclosureInventor__c> updatedInventors = DisclosureInventorService.linkDisclosureInventorToIPIARecords(disclosureInventors);
        Test.stopTest();

        Assert.isNull(updatedInventors[0].IPIA_Record__c, 'First inventor should not be linked to any IPIA record');
        Assert.isNull(updatedInventors[1].IPIA_Record__c, 'Second inventor should not be linked to any IPIA record');
    }

    @IsTest
    public static void handlesEmptyDisclosureInventorsList() {
        List<DisclosureInventor__c> disclosureInventors = new List<DisclosureInventor__c>();
        List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>{
                new IPIA_Record__c(MitId__c = '912345123' , FormName__c= 'TestForm1', SignDatetime__c = Date.today().addDays(-2)),
                new IPIA_Record__c(MitId__c = '912345123' , FormName__c= 'TestForm2', SignDatetime__c = Date.today().addDays(-1))
        };
        insert ipiaRecords;

        Test.startTest();
        List<DisclosureInventor__c> updatedInventors = DisclosureInventorService.linkDisclosureInventorToIPIARecords(disclosureInventors);
        Test.stopTest();

        Assert.areEqual(0, updatedInventors.size(), 'No inventors should be updated');
    }

    @IsTest
    public static void handlesEmptyIPIARecordsList() {
        List<DisclosureInventor__c> disclosureInventors = new List<DisclosureInventor__c>{
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345123' )),
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345456' ))
        };

        Test.startTest();
        List<DisclosureInventor__c> updatedInventors = DisclosureInventorService.linkDisclosureInventorToIPIARecords(disclosureInventors);
        Test.stopTest();

        Assert.isNull(updatedInventors[0].IPIA_Record__c, 'First inventor should not be linked to any IPIA record');
        Assert.isNull(updatedInventors[1].IPIA_Record__c, 'Second inventor should not be linked to any IPIA record');
    }

    @IsTest
    public static void returnsProcessDisclosureInventorsWithUpdatedIPIALookup() {
        List<DisclosureInventor__c> disclosureInventors = new List<DisclosureInventor__c>{
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345123' )),
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345456' ))
        };
        List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>{
                new IPIA_Record__c(FormName__c = 'Test 1', MitId__c = '912345123' , SignDatetime__c = Date.today().addDays(-2)),
                new IPIA_Record__c(FormName__c = 'Test 2', MitId__c = '912345123' , SignDatetime__c = Date.today().addDays(-1)),
                new IPIA_Record__c(FormName__c = 'Test 1', MitId__c = '912345456' , SignDatetime__c = Date.today().addDays(-3)),
                new IPIA_Record__c(FormName__c = 'Test 1', MitId__c = '912345456' , SignDatetime__c = Date.today())
        };

        List<DisclosureInventor__c> updatedInventors = DisclosureInventorService.processIPIARecordToDisclosureInventorLink(disclosureInventors, ipiaRecords);

        Assert.areEqual(ipiaRecords[1].Id, updatedInventors[0].IPIA_Record__c, 'First inventor should be linked to the latest IPIA record');
        Assert.areEqual(ipiaRecords[3].Id, updatedInventors[1].IPIA_Record__c, 'Second inventor should be linked to the latest IPIA record');
    }

    @IsTest
    public static void returnsProcessDisclosureInventorsWithNoIPIALookupWhenNoMatchingIPIARecords() {
        List<DisclosureInventor__c> disclosureInventors = new List<DisclosureInventor__c>{
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345123' )),
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345456' ))
        };
        List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>{
                new IPIA_Record__c(FormName__c = 'Test 1', MitId__c = '912345789' , SignDatetime__c = Date.today().addDays(-2)),
                new IPIA_Record__c(FormName__c = 'Test 1', MitId__c = '912345789' , SignDatetime__c = Date.today().addDays(-1))
        };

        List<DisclosureInventor__c> updatedInventors = DisclosureInventorService.processIPIARecordToDisclosureInventorLink(disclosureInventors, ipiaRecords);

        Assert.isNull(updatedInventors[0].IPIA_Record__c, 'First inventor should not be linked to any IPIA record');
        Assert.isNull(updatedInventors[1].IPIA_Record__c, 'Second inventor should not be linked to any IPIA record');
    }

    @IsTest
    public static void handlesProcessEmptyDisclosureInventorsList() {
        List<DisclosureInventor__c> disclosureInventors = new List<DisclosureInventor__c>();
        List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>{
                new IPIA_Record__c(FormName__c = 'Test 1', MitId__c = '912345123' , SignDatetime__c = Date.today().addDays(-2)),
                new IPIA_Record__c(FormName__c = 'Test 1', MitId__c = '912345123' , SignDatetime__c = Date.today().addDays(-1))
        };

        List<DisclosureInventor__c> updatedInventors = DisclosureInventorService.processIPIARecordToDisclosureInventorLink(disclosureInventors, ipiaRecords);

        Assert.areEqual(0, updatedInventors.size(), 'No inventors should be updated');
    }

    @IsTest
    public static void handlesProcessEmptyIPIARecordsList() {
        List<DisclosureInventor__c> disclosureInventors = new List<DisclosureInventor__c>{
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345123' )),
                new DisclosureInventor__c(Contact__r = new Account(MitId__pc = '912345456' ))
        };
        List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>();

        List<DisclosureInventor__c> updatedInventors = DisclosureInventorService.processIPIARecordToDisclosureInventorLink(disclosureInventors, ipiaRecords);

        Assert.isNull(updatedInventors[0].IPIA_Record__c, 'First inventor should not be linked to any IPIA record');
        Assert.isNull(updatedInventors[1].IPIA_Record__c, 'Second inventor should not be linked to any IPIA record');
    }
}