force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Delegated_To__c.field-meta.xml
<CustomField>
    <fullName>Delegated_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegated To</label>
    <referenceTo>Department_Head__c</referenceTo>
    <relationshipLabel>Delegated By</relationshipLabel>
    <relationshipName>Delegated_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PrimaryInventor__c.field-meta.xml
<CustomField>
    <fullName>PrimaryInventor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DepartmentHeadValidation.cls
public with sharing class DepartmentHeadValidation {
    public static void validateDepartmentHead(
        List<Department_Head__c> departmentHeads
    ) {
        //Before Insert new map is null

        Map<ID, Set<ID>> disclosureContacts = new Map<ID, Set<ID>>();
        Set<ID> disclosureSet = new Set<Id>();

        for (Department_Head__c departmentHead : departmentHeads) {
            disclosureSet.add(departmentHead.Disclosure__c);
            if (
                disclosureContacts.containsKey(departmentHead.Disclosure__c) ==
                false
            ) {
                Set<ID> contactList = new Set<ID>();
                disclosureContacts.put(
                    departmentHead.Disclosure__c,
                    contactList
                );
            }
            disclosureContacts.get(departmentHead.Disclosure__c)
                .add(departmentHead.Contact__c);
        }

        List<Department_Head__c> existingDepartmentHead = [
            SELECT
                Id,
                Contact__r.Id,
                Contact__r.MoiraStatus__pc,
                Delegated_To__r.Contact__r.Id,
                Disclosure__r.Id
            FROM Department_Head__c
            WHERE Disclosure__c IN :disclosureSet
        ];

        List<DisclosureInventor__c> existingInventors = [
            SELECT
                Id,
                PrimaryInventor__c,
                Contact__c,
                Contact__r.Id,
                Contact__r.MoiraStatus__pc,
                Disclosure__r.Id
            FROM DisclosureInventor__c
            WHERE Disclosure__c IN :disclosureSet
        ];

        for (DisclosureInventor__c existingInventor : existingInventors) {
            if (
                disclosureContacts.containsKey(
                    existingInventor.Disclosure__r.Id
                )
            ) {
                Set<Id> contactSet = disclosureContacts.get(
                    existingInventor.Disclosure__r.Id
                );
                if (contactSet.contains(existingInventor.Contact__r.Id)) {
                    findDepartmentHead(
                            departmentHeads,
                            existingInventor.Disclosure__r.Id,
                            existingInventor.Contact__r.Id
                        )
                        .addError(label.Disclosure_Error_Unique_TLO_Contact);
                }
            }
        }
    }

    private static Department_Head__c findDepartmentHead(
        List<Department_Head__c> newDeptHead,
        ID disclosureId,
        ID contact
    ) {
        for (Department_Head__c deptHead : newDeptHead) {
            if (
                deptHead.Disclosure__c == disclosureId &&
                deptHead.Contact__c == contact
            ) {
                return deptHead;
            }
        }
        return null;
    }
}