force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/Collaboration__c.field-meta.xml
<CustomField>
    <fullName>Collaboration__c</fullName>
    <label>4. Research part of a collaboration?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/CollaborationDetails__c.field-meta.xml
<CustomField>
    <fullName>CollaborationDetails__c</fullName>
    <label>4a. Collab. details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/ConsultantOrContract__c.field-meta.xml
<CustomField>
    <fullName>ConsultantOrContract__c</fullName>
    <label>5. Research done by consultant/CRO?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/ConsultantOrContractDetails__c.field-meta.xml
<CustomField>
    <fullName>ConsultantOrContractDetails__c</fullName>
    <label>5a. Consultant/CRO details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/HHMI_At_Time_of_Invention__c.field-meta.xml
<CustomField>
    <fullName>HHMI_At_Time_of_Invention__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HHMI affiliation during invention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/HHMI_tenure_date_from__c.field-meta.xml
<CustomField>
    <fullName>HHMI_tenure_date_from__c</fullName>
    <label>HHMI Date of Tenure (from)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/HHMI_tenure_date_to__c.field-meta.xml
<CustomField>
    <fullName>HHMI_tenure_date_to__c</fullName>
    <label>HHMI Date of Tenure (to)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/IPIA_Record__c.field-meta.xml
<CustomField>
    <fullName>IPIA_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IPIA</label>
    <referenceTo>IPIA_Record__c</referenceTo>
    <relationshipLabel>IPIAs</relationshipLabel>
    <relationshipName>IPIAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PrimaryInventor__c.field-meta.xml
<CustomField>
    <fullName>PrimaryInventor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/SalaryWages__c.field-meta.xml
<CustomField>
    <fullName>SalaryWages__c</fullName>
    <label>1. Who pays your salary/wages?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>Non-MIT</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/SalaryWagesDetails__c.field-meta.xml
<CustomField>
    <fullName>SalaryWagesDetails__c</fullName>
    <label>1a. Salary/Wages details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/ThirdPartyMaterials__c.field-meta.xml
<CustomField>
    <fullName>ThirdPartyMaterials__c</fullName>
    <label>10. Other  materials or datasets?</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/WorkDoneAtMIT__c.field-meta.xml
<CustomField>
    <fullName>WorkDoneAtMIT__c</fullName>
    <label>2. Relevant work done @ MIT?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/WorkDoneOutsideMIT__c.field-meta.xml
<CustomField>
    <fullName>WorkDoneOutsideMIT__c</fullName>
    <label>3. Relevant work @ other organization?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/WorkDoneOutsideMITDetails__c.field-meta.xml
<CustomField>
    <fullName>WorkDoneOutsideMITDetails__c</fullName>
    <label>3a. Other Org. details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/IPIA_Record__c.object-meta.xml
<CustomObject>
    <label>IPIA</label>
    <nameField>
        <displayFormat>IPIA-{000000000}</displayFormat>
        <label>IPIA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPIAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IPIA_Record__c/fields/FormName__c.field-meta.xml
<CustomField>
    <fullName>FormName__c</fullName>
    <label>Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/MitId__c.field-meta.xml
<CustomField>
    <fullName>MitId__c</fullName>
    <label>MIT ID</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IPIA_Record__c/fields/SignDatetime__c.field-meta.xml
<CustomField>
    <fullName>SignDatetime__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Software_Code_Disclosure__c/Software_Code_Disclosure__c.object-meta.xml
<CustomObject>
    <label>Software Code Disclosure</label>
    <nameField>
        <label>Software Code Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Code Disclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Code_Disclosure__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Disclosure record type must match Software Disclosure type</errorMessage>
        <filterItems>
            <field>Disclosure__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Software_Code_Disclosure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Software Code Disclosures</relationshipLabel>
    <relationshipName>Software_Code_Disclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DisclosureInventorTriggerHandlerTest.cls
@isTest
public class DisclosureInventorTriggerHandlerTest {
    @TestSetup
    static void setup() {
        TestSetup.defaultConfiguration();
    }

    @isTest
    public static void testInsertDisclosureInventor() {
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Disclosure__c d = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            cont
        );

        Account cont1 = SampleDataFactory.createContact(
            'Donald1',
            true,
            '12345671'
        );
        update cont1;

        List<Disclosure__c> ddList = new List<Disclosure__c>();
        ddList.add(d);

        Department_head__c dh = new Department_Head__c();
        dh.Contact__c = cont1.ID;
        dh.Disclosure__c = d.Id;

        insert dh;

        DisclosureInventor__c di = new DisclosureInventor__c();
        di.Disclosure__c = d.Id;
        di.PrimaryInventor__c = false;
        di.Contact__c = cont.Id;
        di.Signed_Status__c = 'Yes';
        insert di;

        try {
            di.WorkDoneOutsideMIT__c = 'Yes';
            di.Collaboration__c = 'Yes';
            update di;
        } catch (Exception ex) {
            String msg = ex.getMessage();
            system.assert(msg.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }
    }

    @isTest
    public static void testSignDisclosureAfterApproval() {
        // Setup variables
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account contact1 = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Account contact2 = SampleDataFactory.createContact(
            'James',
            false,
            '12345679'
        );
        Disclosure__c d = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            contact1
        );
        Software_Code_Disclosure__c softwareCode = SampleDataFactory.createSoftwareCode(
            'Sample Draft Software Code',
            d
        );

        Account dhContact = SampleDataFactory.createContact(
            'Donald1',
            true,
            '12345671'
        );
        update dhContact;

        Department_head__c dh = new Department_Head__c();
        dh.Contact__c = dhContact.ID;
        dh.Disclosure__c = d.Id;
        insert dh;

        DisclosureInventor__c di1 = SampleDataFactory.createInventor(
            d,
            true,
            contact1
        );
        DisclosureInventor__c di2 = SampleDataFactory.createInventor(
            d,
            false,
            contact2
        );

        di1.Signed_Status__c = 'Yes';
        update di1;

        d.Status__c = 'Inventor Submitted';
        update d;

        d.Status__c = 'Approved';
        update d;

        // Try to sign Disclosure after Approved
        try {
            di2.Signed_Status__c = 'Yes';
            update di2;
        } catch (Exception e) {
            System.assert(false, 'Error thrown: ' + e.getMessage());
        }
    }

    @isTest
    public static void callToForrester() {
        Test.setMock(HttpCalloutMock.class, new ForresterMock());
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Disclosure__c d = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            cont
        );

        Account cont1 = SampleDataFactory.createContact(
            'Donald1',
            true,
            '12345671'
        );

        List<Disclosure__c> ddList = new List<Disclosure__c>();
        ddList.add(d);

        Department_head__c dh = new Department_Head__c();
        dh.Contact__c = cont1.ID;
        dh.Disclosure__c = d.Id;

        insert dh;

        DisclosureInventor__c di = new DisclosureInventor__c();
        di.Disclosure__c = d.Id;
        di.PrimaryInventor__c = false;
        di.Contact__c = cont.Id;
        di.Signed_Status__c = 'Yes';
        insert di;

        di.WorkDoneOutsideMIT__c = 'Yes';
        di.Collaboration__c = 'Yes';
        di.CollaborationDetails__c = 'Test Forrester';
        di.WorkDoneOutsideMITDetails__c = 'Test Forrester';
        di.SalaryWages__c = 'MIT';
        di.SalaryWagesDetails__c = 'Test';
        di.ThirdPartyMaterials__c = 'test';
        di.CollaborationDetails__c = 'TEST';
        di.WorkDoneAtMIT__c = 'Yes';
        di.ConsultantOrContract__c = 'No';
        update di;

        system.assertNotEquals(di.CollaborationDetails__c, '');
        system.assertNotEquals(di.WorkDoneOutsideMITDetails__c, '');
        system.assertEquals(di.ConsultantOrContractDetails__c, null);

        String jobId = Database.executeBatch(
            new DisclosureInventorSignedToForrester(),
            1
        );
        DisclosureInventorSignedForresterSch.scheduleMe();
        System.Assert(jobId != null);
    }

    @isTest
    public static void onBeforeTest() {
        Test.setMock(HttpCalloutMock.class, new ForresterMock());
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Disclosure__c d = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            cont
        );

        Account cont1 = SampleDataFactory.createContact(
            'Donald1',
            true,
            '12345671'
        );

        List<Disclosure__c> ddList = new List<Disclosure__c>();
        ddList.add(d);

        Department_head__c dh = new Department_Head__c();
        dh.Contact__c = cont1.ID;
        dh.Disclosure__c = d.Id;

        insert dh;

        DisclosureInventor__c di = new DisclosureInventor__c();
        di.Disclosure__c = d.Id;
        di.PrimaryInventor__c = false;
        di.Contact__c = cont.Id;
        di.Signed_Status__c = 'Yes';
        insert di;

        di.WorkDoneOutsideMIT__c = 'Yes';
        di.Collaboration__c = 'Yes';
        di.CollaborationDetails__c = 'Test Forrester';
        di.WorkDoneOutsideMITDetails__c = 'Test Forrester';
        di.SalaryWages__c = 'MIT';
        di.SalaryWagesDetails__c = 'Test';
        di.ThirdPartyMaterials__c = 'test';
        di.CollaborationDetails__c = 'TEST';
        di.WorkDoneAtMIT__c = 'Yes';
        update di;

        DisclosureInventor__c disInv = [
            SELECT Id, SalaryWages__c, SalaryWagesDetails__c
            FROM DisclosureInventor__c
            WHERE Id = :di.Id
        ];
        system.assertEquals(disInv.SalaryWagesDetails__c, null);
    }

    @isTest
    public static void onBeforeQuestionUpdatetoNoTest() {
        Test.setMock(HttpCalloutMock.class, new ForresterMock());
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account cont = SampleDataFactory.createContact(
            'Donald',
            true,
            '12345678'
        );
        Disclosure__c d = SampleDataFactory.createDisclosure(
            recordTypeIdSoftwareCode,
            'Sample Draft Disclosure for Software Code',
            'Draft',
            cont
        );

        Account cont1 = SampleDataFactory.createContact(
            'Donald1',
            true,
            '12345671'
        );

        List<Disclosure__c> ddList = new List<Disclosure__c>();
        ddList.add(d);

        Department_head__c dh = new Department_Head__c();
        dh.Contact__c = cont1.ID;
        dh.Disclosure__c = d.Id;

        insert dh;

        DisclosureInventor__c di = new DisclosureInventor__c();
        di.Disclosure__c = d.Id;
        di.PrimaryInventor__c = false;
        di.Contact__c = cont.Id;
        di.Signed_Status__c = 'Yes';
        insert di;

        di.WorkDoneOutsideMIT__c = 'Yes';
        di.Collaboration__c = 'Yes';
        di.CollaborationDetails__c = 'Test Forrester';
        di.WorkDoneOutsideMITDetails__c = 'Test Forrester';
        di.SalaryWages__c = 'MIT';
        di.SalaryWagesDetails__c = 'Test';
        di.ThirdPartyMaterials__c = 'test';
        di.CollaborationDetails__c = 'TEST';
        di.WorkDoneAtMIT__c = 'Yes';
        update di;

        DisclosureInventor__c disInv = [
            SELECT Id, SalaryWages__c, SalaryWagesDetails__c
            FROM DisclosureInventor__c
            WHERE Id = :di.Id
        ];
        system.assertEquals(disInv.SalaryWagesDetails__c, null);
        di.ConsultantOrContract__c = 'No';
        di.HHMI_At_Time_of_Invention__c = false;
        update di;

        system.assertNotEquals(di.CollaborationDetails__c, '');
        system.assertNotEquals(di.WorkDoneOutsideMITDetails__c, '');

        system.assertEquals(di.ConsultantOrContractDetails__c, null);

        system.assertEquals(di.ConsultantOrContractDetails__c, null);
        system.assertEquals(di.HHMI_tenure_date_from__c, null);
        system.assertEquals(di.HHMI_tenure_date_to__c, null);
    }

    @IsTest
    public static void testAssignIPIALookup() {
        // Constants
        Id recordTypeIdSoftwareCode = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName().get('Software_Code_Disclosure').getRecordTypeId();

        // IPIA Records
        IPIA_Record__c ipiaRecord1 = new IPIA_Record__c(FormName__c = 'Test 1', MitId__c = '912345781' , SignDatetime__c = Date.today().addDays(-2));
        IPIA_Record__c ipiaRecord2 = new IPIA_Record__c(FormName__c = 'Test 2', MitId__c = '912345781' , SignDatetime__c = Date.today().addDays(-1));
        IPIA_Record__c ipiaRecord3 = new IPIA_Record__c(FormName__c = 'Test 3', MitId__c = '912123654' , SignDatetime__c = Date.today());
        List<IPIA_Record__c> ipiaRecords = new List<IPIA_Record__c>{ipiaRecord1, ipiaRecord2, ipiaRecord3};
        insert ipiaRecords;

        // Contacts
        Account contact1 = SampleDataFactory.createContact('Bob', true, '912345781' );
        Account contact2 = SampleDataFactory.createContact('Donald', true, '912123654' );

        // Disclosure
        Disclosure__c disclosure = SampleDataFactory.createDisclosure(recordTypeIdSoftwareCode, 'Test Inventor Actions on Signing', 'Draft', contact1);

        // Inventors On Disclosure
        DisclosureInventor__c inventor1 = SampleDataFactory.createInventor(disclosure, true, contact1);
        DisclosureInventor__c inventor2 = SampleDataFactory.createInventor(disclosure, true, contact2);
        List<DisclosureInventor__c> disclosureInventors = new List<DisclosureInventor__c>{inventor1, inventor2};

        Test.startTest();
        List<DisclosureInventor__c> result = DisclosureInventorTriggerHandler.assignIPIALookup(disclosureInventors);
        Test.stopTest();

        Integer countDisclosureInventors = 0;
        for (DisclosureInventor__c disclosureInventor : result) {
            if (disclosureInventor.Id == inventor1.Id) {
                Assert.areEqual('912345781' , disclosureInventor.Contact__r.MitId__pc, 'Disclosure Inventor should be linked to IPIA Record with MitId 123456781');
                Assert.areEqual(ipiaRecord2.Id, disclosureInventor.IPIA_Record__c, 'Disclosure Inventor should be linked to IPIA Record 2');
            }
            else if (disclosureInventor.Id == inventor2.Id) {
                Assert.areEqual('912123654' , disclosureInventor.Contact__r.MitId__pc, 'Disclosure Inventor should be linked to IPIA Record with MitId 123654');
                Assert.areEqual(ipiaRecord3.Id, disclosureInventor.IPIA_Record__c, 'Disclosure Inventor should be linked to IPIA Record 3');
            }
            countDisclosureInventors++;
        }
        Assert.areEqual(2, countDisclosureInventors, 'Should have linked 2 Disclosure Inventors to IPIA Records');
    }

    public class ForresterMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            if (req.getEndpoint().containsignorecase('inventor')) {
                String responsebody = '{"status": "SUCCESS","message": "Success","dataObject":[{}]}';
                HTTPResponse res = new HTTPResponse();
                res.setBody(responsebody);
                res.setStatusCode(201);
                return res;
            }
            return null;
        }
    }
}