force-app/main/default/objects/Department_Head__c/Department_Head__c.object-meta.xml
<CustomObject>
    <label>Department Head</label>
    <nameField>
        <displayFormat>DH-{000000}</displayFormat>
        <label>Department Head Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Heads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department_Head__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department_Head__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Department Heads</relationshipLabel>
    <relationshipName>Department_Heads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>TLO Case Number</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/SubmittedOnBehalf__c.field-meta.xml
<CustomField>
    <fullName>SubmittedOnBehalf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted on behalf of someone else</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/DisclosureInventor__c.object-meta.xml
<CustomObject>
    <label>Disclosure Inventor</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Disclosure Inventor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Inventors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisclosureInventor__c/fields/AdditionalComments__c.field-meta.xml
<CustomField>
    <fullName>AdditionalComments__c</fullName>
    <label>11. Additional Comments</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Disclosure__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Collaboration__c.field-meta.xml
<CustomField>
    <fullName>Collaboration__c</fullName>
    <label>4. Research part of a collaboration?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/CollaborationDetails__c.field-meta.xml
<CustomField>
    <fullName>CollaborationDetails__c</fullName>
    <label>4a. Collab. details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/ConsultantOrContract__c.field-meta.xml
<CustomField>
    <fullName>ConsultantOrContract__c</fullName>
    <label>5. Research done by consultant/CRO?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/ConsultantOrContractDetails__c.field-meta.xml
<CustomField>
    <fullName>ConsultantOrContractDetails__c</fullName>
    <label>5a. Consultant/CRO details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Disclosure_Inventors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Current_date_of_Tenure_from__c.field-meta.xml
<CustomField>
    <fullName>Current_date_of_Tenure_from__c</fullName>
    <formula>Contact__r.HHMI_Current_Date_From__pc</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current date of Tenure (from)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Currently_affiliated_with_HHMI__c.field-meta.xml
<CustomField>
    <fullName>Currently_affiliated_with_HHMI__c</fullName>
    <formula>Contact__r.HHMI_Current__pc</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currently affiliated with HHMI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure ID</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Inventors</relationshipLabel>
    <relationshipName>Inventors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Disclosure_Title__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_Title__c</fullName>
    <formula>Disclosure__r.Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Disclosure Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/DocuSign_Recipient_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Recipient_StatusCode__c</fullName>
    <description>This field will hold the value of DocuSign&apos;s Status Code for this Inventor. (That will be used to map back to Signed flag) 
DocuSign events are send for all inventors on a Disclosure at the same time. Needing to ensure status code is mapped correctly for each.</description>
    <label>DocuSign Recipient StatusCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/HHMI_At_Time_of_Invention__c.field-meta.xml
<CustomField>
    <fullName>HHMI_At_Time_of_Invention__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HHMI affiliation during invention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/HHMI_tenure_date_from__c.field-meta.xml
<CustomField>
    <fullName>HHMI_tenure_date_from__c</fullName>
    <label>HHMI Date of Tenure (from)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/HHMI_tenure_date_to__c.field-meta.xml
<CustomField>
    <fullName>HHMI_tenure_date_to__c</fullName>
    <label>HHMI Date of Tenure (to)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Inventor_Name__c.field-meta.xml
<CustomField>
    <fullName>Inventor_Name__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/&quot; &amp; Id &amp; &quot;/view&quot;, IF( ISBLANK( Contact__r.PreferredName__pc ), TRIM( Contact__r.FirstName + &apos; &apos; + Contact__r.MiddleName + &apos; &apos; + Contact__r.LastName ), TRIM( Contact__r.PreferredName__pc + &apos; &apos; +  Contact__r.LastName ) ), &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PartOfClass__c.field-meta.xml
<CustomField>
    <fullName>PartOfClass__c</fullName>
    <label>9. Conceived in MIT class?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/PartOfClassDetails__c.field-meta.xml
<CustomField>
    <fullName>PartOfClassDetails__c</fullName>
    <label>9a. MIT Class details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/SalaryWages__c.field-meta.xml
<CustomField>
    <fullName>SalaryWages__c</fullName>
    <label>1. Who pays your salary/wages?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>Non-MIT</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/SalaryWagesDetails__c.field-meta.xml
<CustomField>
    <fullName>SalaryWagesDetails__c</fullName>
    <label>1a. Salary/Wages details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Comment__c.field-meta.xml
<CustomField>
    <fullName>Signed_Comment__c</fullName>
    <description>Signed Comment -&gt; only used when Inventor Opt&apos;s out of Disclosure</description>
    <label>Signed Comment</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Disclosure_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Disclosure_Date__c</fullName>
    <label>Signed Disclosure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Signed_Status__c.field-meta.xml
<CustomField>
    <fullName>Signed_Status__c</fullName>
    <description>Status indication whether inventor has signed the Disclosure or not. Defaults to Pending</description>
    <label>Signed Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <formula>Contact__r.PersonTitle</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/WorkDoneOutsideMIT__c.field-meta.xml
<CustomField>
    <fullName>WorkDoneOutsideMIT__c</fullName>
    <label>3. Relevant work @ other organization?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_U</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DisclosureInventor__c/fields/WorkDoneOutsideMITDetails__c.field-meta.xml
<CustomField>
    <fullName>WorkDoneOutsideMITDetails__c</fullName>
    <label>3a. Other Org. details</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Y_N_U.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown Picklist</description>
    <masterLabel>Y_N_U</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DisclosureInventorTriggerHandler.cls
public with sharing class DisclosureInventorTriggerHandler {
    public static void onBeforeInsert(
        List<DisclosureInventor__c> disInventors
    ) {
        validateDisclosureInventor(disInventors);
        validationQuestion(disInventors);
        validateInventorEmail(disInventors);
        for (DisclosureInventor__c disinv : disInventors) {
            // EMPTY IF ANSWER MIT
            if (disinv.SalaryWages__c == 'MIT') {
                disinv.SalaryWagesDetails__c = '';
            }
        }
        assignIPIALookup(disInventors);
    }

    public static void onBeforeUpdate(
        List<DisclosureInventor__c> disInventors,
        Map<Id, DisclosureInventor__c> oldDisInventors
    ) {
        validationQuestion(disInventors);
        validateInventorEmail(disInventors);

        for (DisclosureInventor__c disinv : disInventors) {
            // Map DocuSign Recipient Statuses (ie: Inventor Signed Status on DocuSign to Salesforce Object)
            if (disinv.DocuSign_Recipient_StatusCode__c == 'Completed') {
                disinv.Signed_Status__c = 'Yes';
            }

            if (disinv.Signed_Status__c == 'Opted Out') {
                disinv.Signed_Disclosure_Date__c = Datetime.now();
            }

            // EMPTY IF ANSWER MIT
            if (disinv.SalaryWages__c == 'MIT') {
                disinv.SalaryWagesDetails__c = '';
            }

            // EMPTY IF ANSWER NO
            if (disinv.WorkDoneOutsideMIT__c == 'No') {
                disinv.WorkDoneOutsideMITDetails__c = '';
            }

            if (disinv.Collaboration__c == 'No') {
                disinv.CollaborationDetails__c = '';
            }

            if (disinv.ConsultantOrContract__c == 'No') {
                disinv.ConsultantOrContractDetails__c = '';
            }

            if (disinv.PartOfClass__c == 'No') {
                disinv.PartOfClassDetails__c = '';
            }

            // FIXME: Can this be removed?
            // 3170 Changes
            if (!disinv.Currently_affiliated_with_HHMI__c) {
                //Below Field Cannot be updated Because its a formula field
                //disinv.Current_date_of_Tenure_from__c = null;
            }

            if (!disinv.HHMI_At_Time_of_Invention__c) {
                disinv.HHMI_tenure_date_from__c = null;
                disinv.HHMI_tenure_date_to__c = null;
            }
        }
    }

    public static void onAfterInsert(
        List<DisclosureInventor__c> disclosureInventorList
    ) {
        // Add "Sign Disclosure" actions where necessary
        initInventorSignAction(disclosureInventorList);

        List<String> disclosureInventorIds = new List<String>();

        for (DisclosureInventor__c disinv : disclosureInventorList) {
            disclosureInventorIds.add(disinv.Id);
        }

        if (disclosureInventorIds != null && !disclosureInventorIds.isEmpty()) {
            List<DisclosureInventor__c> inventorList = DisclosureRecordFetch.getDisclosureInventorsByIds(
                disclosureInventorIds
            );

            // Replacing DisclosureInventorNotification onApprovedInventorAdded
            DisclosureInventorEventProducer.onApprovedInventorAdded(
                inventorList
            );
        }
    }

    public static void onBeforeDelete(
        List<DisclosureInventor__c> disclosureInventorList
    ) {
        List<String> disclosureInventorId = new List<String>();

        for (DisclosureInventor__c disinv : disclosureInventorList) {
            disclosureInventorId.add(disinv.Id);
        }

        if (!disclosureInventorId.isEmpty()) {
            List<DisclosureInventor__c> inventorList = DisclosureRecordFetch.getDisclosureInventorsByIds(
                disclosureInventorId
            );
            DisclosureInventorNotification.onInventorDeleted(inventorList);
        }
    }

    public static void onAfterUpdate(
        List<DisclosureInventor__c> currDisclosureInventorList,
        Map<Id, DisclosureInventor__c> oldDisclosureInventorList
    ) {
        List<String> disclosureInventorIds = new List<String>();
        Set<String> signedInventorIds = new Set<String>();
        Set<String> optedOutInventorIds = new Set<String>();

        for (DisclosureInventor__c currInventor : currDisclosureInventorList) {
            disclosureInventorIds.add(currInventor.Id);

            DisclosureInventor__c prevInventor = (oldDisclosureInventorList !=
                null &&
                oldDisclosureInventorList.get(currInventor.Id) != null)
                ? oldDisclosureInventorList.get(currInventor.Id)
                : null;
            String newSignedStatus = currInventor.Signed_Status__c;
            String prevSignedStatus = prevInventor != null
                ? prevInventor.Signed_Status__c
                : null;
            Boolean inventorMadeSigningDecision = (newSignedStatus == 'Yes' ||
            newSignedStatus == 'Opted Out');

            // If the inventor has just signed (or opted out) the Disclosure
            if (
                inventorMadeSigningDecision &&
                newSignedStatus != prevSignedStatus
            ) {
                signedInventorIds.add(currInventor.Id);
            }
        }

        if (!signedInventorIds.isEmpty()) {
            List<DisclosureInventor__c> signedInventorDetails = [
                SELECT
                    Id,
                    AdditionalComments__c,
                    Contact__r.Name,
                    Contact__r.PersonEmail,
                    Disclosure__r.Case_Number__c,
                    Disclosure__r.Name__c,
                    Disclosure__r.Name,
                    Disclosure__r.SubmittedOnBehalf__c,
                    Disclosure__r.Submitting_Contact__r.Name,
                    Disclosure__r.Submitting_Contact__c,
                    Disclosure_Title__c,
                    Inventor_Name__c,
                    Signed_Comment__c,
                    Signed_Status__c,
                    Title__c,
                    Contact__c
                FROM DisclosureInventor__c
                WHERE Id IN :(signedInventorIds)
            ];

            DisclosureOpsNotification.sendNotificationEachSignedInventor(
                signedInventorDetails
            );

            DisclosureCreateAuditEvent.createInventorSignatureAudit(
                signedInventorDetails
            );

            ContactActionHandler.completeSignDisclosureActions(
                signedInventorDetails
            );

            DisclosureInventorSignedHandler.handleInventorSigned(
                signedInventorDetails
            );
        }

        if (disclosureInventorIds != null && !disclosureInventorIds.isEmpty()) {
            List<DisclosureInventor__c> queryInventors = DisclosureRecordFetch.getDisclosureInventorsByIds(
                disclosureInventorIds
            );
            DisclosureInventorNotification.onPrimaryInventorRemoved(
                queryInventors,
                oldDisclosureInventorList
            );
        }
    }

    /**
     * Create "Sign Disclosure" actions for inventors where applicable
     * @param disclosureInventorList List of Disclosure Inventors to be processed
     */
    public static void initInventorSignAction(
        List<DisclosureInventor__c> disclosureInventorList
    ) {
        // Lists to be used
        List<DisclosureInventor__c> inventorProcessList = new List<DisclosureInventor__c>();
        Map<Id, Disclosure__c> disclosureMap = DisclosureRecordFetch.getDisclosuresByInventors(
            disclosureInventorList
        );

        // Loop over Disclosure Inventors
        for (DisclosureInventor__c inventor : disclosureInventorList) {
            // If the inventor has not signed, but the Disclosure is "Approved" or "Inventor Submitted"...
            String status = disclosureMap.get(inventor.Disclosure__c).Status__c;

            if (
                inventor.Signed_Status__c != 'Yes' &&
                (status == 'Approved' ||
                status == 'Inventor Submitted')
            ) {
                // Add to list
                inventorProcessList.add(inventor);
            }
        }

        // Process lists
        if (!inventorProcessList.isEmpty()) {
            ContactActionHandler.initDisclosureContactAction(
                inventorProcessList,
                ContactActionHandler.recordTypeIdSignDisclosure
            );
        }
    }

    public static void validateDisclosureInventor(
        List<DisclosureInventor__c> disinventor
    ) {
        Set<String> contactIds = new Set<String>();
        Set<String> disclosureIds = new Set<String>();
        Set<String> inventorIds = new Set<String>();

        for (DisclosureInventor__c inventor : disinventor) {
            contactIds.add(inventor.Contact__c);
            disclosureIds.add(inventor.Disclosure__c);
            inventorIds.add(inventor.Id);
        }

        if (!contactIds.isEmpty() && !disclosureIds.isEmpty()) {
            List<DisclosureInventor__c> existingInventors = [
                SELECT Id, Contact__c, Disclosure__c
                FROM DisclosureInventor__c
                WHERE
                    Contact__c IN :contactIds
                    AND Disclosure__c IN :disclosureIds
                    AND Id NOT IN :(inventorIds)
            ];

            List<Department_Head__c> existingDepartmentHeads = [
                SELECT Id, Contact__c, Disclosure__c
                FROM Department_Head__c
                WHERE
                    Contact__c IN :contactIds
                    AND Disclosure__c IN :disclosureIds
                    AND Id NOT IN :(inventorIds)
            ];

            if (existingInventors != null && !existingInventors.isEmpty()) {
                for (DisclosureInventor__c inventor : disinventor) {
                    inventor.addError(
                        label.Disclosure_Error_Duplicate_Inventor
                    );
                }
            }

            if (
                existingDepartmentHeads != null &&
                !existingDepartmentHeads.isEmpty()
            ) {
                for (DisclosureInventor__c inventor : disinventor) {
                    inventor.addError(
                        label.Disclosure_Error_Unique_TLO_Contact
                    );
                }
            }
        }
    }

    private static void validateInventorEmail(
        List<DisclosureInventor__c> disInventors
    ) {
        // Only run email validations if...
        if (
            !PersonAccountMigrationHelpers.isPersonAccountMigrationInProgress() && // TODO: Refactor - Remove post AC migration
            UserInfo.getProfileId() != ShirleyConstants.COMMUNITY_PROFILE_ID && // the current user is not a community user (i.e. Native App user)
            UserInfo.getProfileId() != ShirleyConstants.INTEGRATION_PROFILE_ID // the current user is not an Integration user
        ) {
            // Get list of Contacts
            List<Id> contactIds = new List<Id>();

            for (DisclosureInventor__c disInventor : disInventors) {
                contactIds.add(disInventor.Contact__c);
            }

            List<Account> contacts = [
                SELECT Id, PersonEmail, MoiraStatus__pc, IsAlumni__pc
                FROM Account
                WHERE Id IN :contactIds AND IsPersonAccount = TRUE
            ];

            Map<Id, Account> contactsMap = new Map<Id, Account>(contacts);

            // For each inventor
            for (DisclosureInventor__c disInventor : disInventors) {
                // If matching contact is has an inactive kerb and is not Alumni, the email cannot end in mit.edu
                Account contact = contactsMap.get(disInventor.Contact__c);

                if (
                    (!Helpers.isActiveKerb(contact.MoiraStatus__pc) && // Inactive kerb
                    (contact.IsAlumni__pc != true)) && // Not Alumni
                    (contact.PersonEmail != null &&
                    contact.PersonEmail.endsWith('mit.edu'))
                ) {
                    disInventor.addError(Label.GuestEmailAddressValidation);
                }
            }
        }
    }

    public static void validationQuestion(
        List<DisclosureInventor__c> disinventor
    ) {
        for (DisclosureInventor__c disinv : disinventor) {
            if (
                disinv.WorkDoneOutsideMIT__c == 'Yes' &&
                disinv.WorkDoneOutsideMITDetails__c == null
            ) {
                disinv.addError(Label.MIT_WorkOutside);
            }

            if (
                disinv.Collaboration__c == 'Yes' &&
                disinv.CollaborationDetails__c == null
            ) {
                disinv.addError(Label.MIT_CollaborationDetails);
            }

            if (
                disinv.ConsultantOrContract__c == 'Yes' &&
                disinv.ConsultantOrContractDetails__c == null
            ) {
                disinv.addError(Label.MIT_ConsultantOrContractDetails);
            }

            if (
                disinv.PartOfClass__c == 'Yes' &&
                disinv.PartOfClassDetails__c == null
            ) {
                disinv.addError(Label.MIT_PartofClassDetails);
            }
        }
    }

    /**
     * Assign the IPIA Lookup to the Disclosure Inventor
     * @param disclosureInventors List of Disclosure Inventors
     * @return List of Disclosure Inventors with the IPIA Lookup assigned
     */
    @TestVisible
    private static List<DisclosureInventor__c> assignIPIALookup(List<DisclosureInventor__c> disclosureInventors) {
        // Since the Contact__r field is not populated in the trigger context, we need to query the Contacts
        List<Id> contactIds = new List<Id>();
        for (DisclosureInventor__c disinv : disclosureInventors) {
            contactIds.add(disinv.Contact__c);
        }

        Map<Id, Account> contacts = new Map<Id, Account>([SELECT Id, MitId__pc FROM Account WHERE Id IN :contactIds]);

        // Assign the Contact__r field with the populated MitId__pc field
        for (DisclosureInventor__c disinv : disclosureInventors) {
            if (contacts.containsKey(disinv.Contact__c)) {
                disinv.Contact__r = contacts.get(disinv.Contact__c);
            }
        }

        return DisclosureInventorService.linkDisclosureInventorToIPIARecords(disclosureInventors);
    }
}