force-app/main/default/objects/BIP_Case_Junction__c/BIP_Case_Junction__c.object-meta.xml
<CustomObject>
    <label>BIP Case Junction</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP Case Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Case Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Case_Junction__c/fields/BIP_PI__c.field-meta.xml
<CustomField>
    <fullName>BIP_PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BIP PI</label>
    <referenceTo>BIP_PI__c</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Case_Junction__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Case_Junction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <length>20</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/BIP_PI__c.object-meta.xml
<CustomObject>
    <label>BIP PI</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP PI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Pis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_PI__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/PI__c.field-meta.xml
<CustomField>
    <fullName>PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/PI_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>PI_MIT_ID__c</fullName>
    <formula>PI__r.PersonContact.MitId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PI MIT ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary PI</fullName>
            </value>
            <value>
                <fullName>Additional PI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Received</fullName>
                <default>true</default>
                <label>Request Received</label>
            </value>
            <value>
                <fullName>Assigned to TLO</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Assigned to PI</fullName>
            </value>
            <value>
                <fullName>PI Review Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Classification__c.field-meta.xml
<CustomField>
    <fullName>Document_Classification__c</fullName>
    <description>Classify record type documents. The Record type with the classification uniquely identify external Entity_RecId field</description>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Disclosure</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>Publication/Manuscripts</fullName>
            </value>
            <value>
                <fullName>Software Code</fullName>
            </value>
            <value>
                <fullName>Third Party Agreements</fullName>
            </value>
            <value>
                <fullName>Third Party Code</fullName>
            </value>
            <value>
                <fullName>Finalised_CRDR</fullName>
                <label>Finalised CRDR</label>
            </value>
            <value>
                <fullName>Draft_CRDR</fullName>
                <label>Draft CRDR</label>
            </value>
            <value>
                <fullName>Original_Document</fullName>
                <label>Original Document</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Agreement_Amendment</fullName>
                <label>Agreement Amendment</label>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>Memo_of_Signatory</fullName>
                <label>Memo of Signatory</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>IPIA_Type_Template</fullName>
                <label>IPIA Type Template</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <label>Note</label>
</RecordType>

force-app/main/default/objects/Forrester_Case__x/Forrester_Case__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_VIEW</externalName>
    <label>Case</label>
    <pluralLabel>Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case RecId</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_STATUS__c.field-meta.xml
<CustomField>
    <fullName>CASE_STATUS__c</fullName>
    <description>CASE STATUS</description>
    <externalDeveloperName>CASE_STATUS</externalDeveloperName>
    <label>Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CASE_TYPE__c</fullName>
    <description>CASE_TYPE</description>
    <externalDeveloperName>CASE_TYPE</externalDeveloperName>
    <label>Case Type</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/DISCLOSURE_TITLE__c.field-meta.xml
<CustomField>
    <fullName>DISCLOSURE_TITLE__c</fullName>
    <description>DISCLOSURE_TITLE</description>
    <externalDeveloperName>DISCLOSURE_TITLE</externalDeveloperName>
    <label>Disclosure Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/FIRST_PUBLISH_DATE__c.field-meta.xml
<CustomField>
    <fullName>FIRST_PUBLISH_DATE__c</fullName>
    <description>FIRST_PUBLISH_DATE</description>
    <externalDeveloperName>FIRST_PUBLISH_DATE</externalDeveloperName>
    <label>Published</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/STATUS__c.field-meta.xml
<CustomField>
    <fullName>STATUS__c</fullName>
    <description>STATUS</description>
    <externalDeveloperName>STATUS</externalDeveloperName>
    <label>Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_EMAIL__c.field-meta.xml
<CustomField>
    <fullName>TLO_EMAIL__c</fullName>
    <description>TLO_EMAIL</description>
    <externalDeveloperName>TLO_EMAIL</externalDeveloperName>
    <label>TLO Officer Email</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_ID__c.field-meta.xml
<CustomField>
    <fullName>TLO_ID__c</fullName>
    <description>TLO_ID</description>
    <externalDeveloperName>TLO_ID</externalDeveloperName>
    <label>TLO Id</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>TLO_MIT_ID__c</fullName>
    <description>TLO_MIT_ID</description>
    <externalDeveloperName>TLO_MIT_ID</externalDeveloperName>
    <label>TLO MIT Id</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_NAME__c.field-meta.xml
<CustomField>
    <fullName>TLO_NAME__c</fullName>
    <description>TLO_NAME</description>
    <externalDeveloperName>TLO_NAME</externalDeveloperName>
    <label>TLO Officer</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x.object-meta.xml
<CustomObject>
    <description>Forrester_SHIR_CASE_INVENTOR_SHARE_VIEW</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_INVENTOR_SHARE_VIEW</externalName>
    <label>Case Inventor Share</label>
    <pluralLabel>Case Inventor Shares</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/CASE_INVENTOR_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_INVENTOR_RECID__c</fullName>
    <description>CASE_INVENTOR_RECID</description>
    <externalDeveloperName>CASE_INVENTOR_RECID</externalDeveloperName>
    <label>Case Inventor Recid</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case Recid</label>
    <length>12</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>Inventors</relationshipLabel>
    <relationshipName>Case_Inventor_Share</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/INVENTOR_ASSOCIATION_TYPE__c.field-meta.xml
<CustomField>
    <fullName>INVENTOR_ASSOCIATION_TYPE__c</fullName>
    <description>INVENTOR_ASSOCIATION_TYPE</description>
    <externalDeveloperName>INVENTOR_ASSOCIATION_TYPE</externalDeveloperName>
    <label>Inventor Association Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/INVENTOR_NAME__c.field-meta.xml
<CustomField>
    <fullName>INVENTOR_NAME__c</fullName>
    <description>INVENTOR_NAME</description>
    <externalDeveloperName>INVENTOR_NAME</externalDeveloperName>
    <label>Name</label>
    <length>84</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x/fields/INVENTOR_RECID__c.field-meta.xml
<CustomField>
    <fullName>INVENTOR_RECID__c</fullName>
    <description>INVENTOR_RECID</description>
    <externalDeveloperName>INVENTOR_RECID</externalDeveloperName>
    <label>Inventor Recid</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BipRequestController.cls
public with sharing class BipRequestController {
    @AuraEnabled
    public static string createBIPReq(BIP_Request__c bipRequest, String recordType,List<Map<String,String>> bipPis,Map<String,String> accountData,String fileBase64, String fileName ){
        try {
            String kcProposalTypeId = Schema.SObjectType.BIP_Request__c.getRecordTypeInfosByName().get('KC Proposal').getRecordTypeId();
            String nonKCProposalTypeId = Schema.SObjectType.BIP_Request__c.getRecordTypeInfosByName().get('Non-KC Proposal').getRecordTypeId();
            if (recordType == 'KC Proposal') {
                bipRequest.RecordTypeId = kcProposalTypeId;
            } else {
                bipRequest.RecordTypeId = nonKCProposalTypeId;
            }
            insert bipRequest;
            Id bipRequestId = bipRequest.Id;   
            List<Bip_Pi__c> bipPiList = new List<Bip_Pi__c>();
            for(Map<String,String> bipMap:bipPis){
                Bip_Pi__c bipPi=new Bip_Pi__c();
                if(bipMap.containsKey('personRole')){
                   if('PI'==bipMap.get('personRole')){
                       bipPi.Role__c='Primary PI';
                   } else {
                       bipPi.Role__c='Additional PI'; 
                   }
               }
                bipPi.PI__c=accountData.get(bipMap.get('mitId'));
                bipPI.Status__c='Pending Assignment';
                bipPi.BIP_Request__c=bipRequestId;
                bipPiList.add(bipPi);
            }
           
          
            insert bipPiList;
         
    if(fileBase64!='' && fileName!=''){
        ContentVersion cv = createContentVersion(fileBase64, fileName);
        ContentDocumentLink cdl = createContentLink(cv.Id, bipRequestId);
    }
          
    BipRequestController.getCases(bipRequestId);


     return bipRequestId;

        } catch (Exception e) {
            System.debug('----- ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @future(callout=true)
    public static void getCases(String recId) {
        Bip_Request__c bipReq = [Select Id , (Select Id , BIP_Request__c, PI_MIT_ID__c,PI__c from Bip_Pis__r) from Bip_Request__c where Id = :recId LIMIT 1];
            List<BIP_PI__c> vBIPPIList = bipReq.Bip_Pis__r;
        
        Map<String,BIP_PI__c> vBIPPIMap = new Map<String,BIP_PI__c>();

        List<Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x> recordList = new List<Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x>();
        Map<String,Forrester_Case__x> caseMap = new Map<String,Forrester_Case__x>();
            for(BIP_PI__c vBIPPI :  vBIPPIList ){
                vBIPPIMap.put(vBIPPI.PI_MIT_ID__c, vBIPPI);
            }
            
            List<String> caseRecIds = new List<String>();         
            recordList = [SELECT CASE_INVENTOR_RECID__c, CASE_RECID__c,INVENTOR_NAME__c,INVENTOR_RECID__c,MIT_ID__c 
                          FROM Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x 
                          WHERE MIT_ID__c= :vBIPPIMap.keySet() 
                          AND INVENTOR_ASSOCIATION_TYPE__c NOT IN ('Non-Inventor', 'Non-Inv-Removed') 
                          AND CASE_STATUS__c NOT IN ('Closed', 'Dormant', 'Archive')];
            
            for(Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x rec:recordList){
                caseRecIds.add(rec.CASE_RECID__c);
            }  
        
            Integer batchSize = 50;
            List<Forrester_Case__x> caseList = ExternalObjectQuery.records(
                ExternalObjectRepository.fetchSObjectsByExternalRecIds(caseRecIds, 
                    'Forrester_Case__x', 
                    'CASE_RECID__c', 
                    new List<String> {'DISCLOSURE_TITLE__c', 'STATUS__c', 'CASE_RECID__c', 'ADD_DATE__c', 'FIRST_PUBLISH_DATE__c', 'TLO_MIT_ID__c',
                                    'TLO_NAME__c', 'TLO_EMAIL__c', 'TLO_ID__c', 'CASE_TYPE__c', 'CONTRACT_CASE_NUM__c'}, 
                    batchSize)
            );

            for(Forrester_Case__x vCase : caseList){
                caseMap.put(vCase.CASE_RECID__c,vCase);
            }
            
           if (Test.isRunningTest()) {
            // Simulate query results during test execution
            recordList = new List<Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x>();
            recordList.add(new Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x(CASE_INVENTOR_RECID__c = '39782', CASE_RECID__c = '12345',INVENTOR_NAME__c='Steven R. H Barrett', INVENTOR_RECID__c=12904 ,MIT_ID__c='995864713'));
            system.debug('rec===='+recordList);            
            for(Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x rec:recordList){
                caseRecIds.add(rec.CASE_RECID__c);
              
            }
            system.debug('caseRecIds===='+caseRecIds);
           
            Forrester_Case__x caseInstance = new Forrester_Case__x(DISCLOSURE_TITLE__c='Test',STATUS__c='Active',ADD_DATE__c= date.today(),CASE_RECID__c='12345',FIRST_PUBLISH_DATE__c= date.today().addDays(-1),CASE_TYPE__c='Copyright' );
              
        
            caseMap.put(caseInstance.CASE_RECID__c,caseInstance);
             system.debug('caseMap===='+caseMap);
            
        }
        
        
        
        
      List<BIP_Case_Junction__c> tloCaseList = new List<BIP_Case_Junction__c>();
         system.debug('tloCaseList');
        for(Forrester_SHIR_CASE_INVENTOR_SHARE_VI__x rec:recordList){
            BIP_Case_Junction__c vCaseJunction = new BIP_Case_Junction__c(); 
            if(vBIPPIMap.containsKey(rec.MIT_ID__c)){
                     vCaseJunction.BIP_PI__c = vBIPPIMap.get(rec.MIT_ID__c).Id;
                     vCaseJunction.BIP_Request__c = vBIPPIMap.get(rec.MIT_ID__c).BIP_Request__c;
            }
      
            vCaseJunction.Case__c = rec.CASE_RECID__c;

            tloCaseList.add(vCaseJunction);
        }
        insert tloCaseList;
        system.debug('tloCaseList '+tloCaseList);
   }


    private static ContentVersion createContentVersion(String base64, String filename) {
        ContentVersion cv = new ContentVersion();
        String cvRecordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByName().get('Note').getRecordTypeId();
        cv.RecordTypeId = cvRecordTypeId;
        cv.VersionData = EncodingUtil.base64Decode(base64);
        cv.Title = filename;
        cv.Document_Classification__c = 'Original_Document';
        cv.PathOnClient = filename;
        try {
            insert cv;
            return cv;
        } catch (DMLException e) {
            System.debug(e);
            return null;
        }
    }

    private static ContentDocumentLink createContentLink(String contentVersionId, String recordId) {
        if (contentVersionId == null || recordId == null) {
            return null;
        }
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersionId].ContentDocumentId;
        cdl.LinkedEntityId = recordId;
        cdl.ShareType = 'V';
        try {
            insert cdl;
            return cdl;
        } catch (DMLException e) {
            System.debug(e);
            return null;
        }
    }

    @AuraEnabled
    public static Map<String, Object> getKualiResponseByProposalId(String proposalId) {
        String jsonString = json.serialize(BIPUtils.getKualiDataByProposalId(proposalId));
        Map<String, Object> mappedResponse = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
        return mappedResponse;
    }

}