force-app/main/default/objects/BIP_Case_Junction__c/BIP_Case_Junction__c.object-meta.xml
<CustomObject>
    <label>BIP Case Junction</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP Case Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Case Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Case_Junction__c/fields/BIP_PI__c.field-meta.xml
<CustomField>
    <fullName>BIP_PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BIP PI</label>
    <referenceTo>BIP_PI__c</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Case_Junction__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Case_Junction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <length>20</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/BIP_PI__c.object-meta.xml
<CustomObject>
    <label>BIP PI</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP PI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Pis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_PI__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary PI</fullName>
            </value>
            <value>
                <fullName>Additional PI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/TLO_Officer_Email__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Email__c</fullName>
    <label>TLO Officer Email`</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/TLO_Officer_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_MIT_ID__c</fullName>
    <label>TLO Officer MIT ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/TLO_Officer_Name__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Name__c</fullName>
    <label>TLO Officer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Received</fullName>
                <default>true</default>
                <label>Request Received</label>
            </value>
            <value>
                <fullName>Assigned to TLO</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Assigned to PI</fullName>
            </value>
            <value>
                <fullName>PI Review Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/TLO_Officer_Email__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Email__c</fullName>
    <label>Primary TLO Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/TLO_Officer_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_MIT_ID__c</fullName>
    <label>Primary TLO MIT ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/TLO_Officer_Name__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Name__c</fullName>
    <label>Primary TLO</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/Forrester_Case__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_VIEW</externalName>
    <label>Case</label>
    <pluralLabel>Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case__x/fields/STATUS__c.field-meta.xml
<CustomField>
    <fullName>STATUS__c</fullName>
    <description>STATUS</description>
    <externalDeveloperName>STATUS</externalDeveloperName>
    <label>Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_EMAIL__c.field-meta.xml
<CustomField>
    <fullName>TLO_EMAIL__c</fullName>
    <description>TLO_EMAIL</description>
    <externalDeveloperName>TLO_EMAIL</externalDeveloperName>
    <label>TLO Officer Email</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>TLO_MIT_ID__c</fullName>
    <description>TLO_MIT_ID</description>
    <externalDeveloperName>TLO_MIT_ID</externalDeveloperName>
    <label>TLO MIT Id</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_NAME__c.field-meta.xml
<CustomField>
    <fullName>TLO_NAME__c</fullName>
    <description>TLO_NAME</description>
    <externalDeveloperName>TLO_NAME</externalDeveloperName>
    <label>TLO Officer</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BIPController.cls
/**
 * Created by Andreas du Preez on 2025/02/06.
 */

public with sharing class BIPController {

    // Get BIP PIs, available TLO Officers and recommended TLO Officer for TLO Assignment
    @AuraEnabled
    public static List<BIPPITLOAssignment> getBipPisForTLOAssignment(String bipRequestRecordId) {
        List<BIPPITLOAssignment> result = new List<BIPPITLOAssignment>();
        List<String> recordIds = new List<String>();
        for (BIP_PI__c bipPi : [SELECT Id FROM BIP_PI__c WHERE BIP_Request__c = :bipRequestRecordId]) {
            recordIds.add(bipPi.Id);
        }

        // Get BIP PIs with Cases
        List<BIP_PI__c> bipPis = GetBipWithCases.getBipInfo(recordIds, 'child');

        for (BIP_PI__c bipPi : bipPis) {
            if (bipPi.Role__c == 'Additional PI' && bipPi.BIP_Case_Junctions__r.size() == 0) {
                continue;
            }

            BIPPITLOAssignment bipPiTloAssignment = new BIPPITLOAssignment(bipPi, new List<TLOOfficer>(), new TLOOfficer());

            // Get the TLO Officers for each BIP PI and assign the recommended TLO Officer based on the number of cases
            Integer maxCases = 0;
            TLOOfficer recommendedTloOfficer = new TLOOfficer();
            for (BIP_Case_Junction__c caseJunction : bipPi.BIP_Case_Junctions__r) {
                if (caseJunction.Case__r != null && caseJunction.Case__r.TLO_MIT_ID__c != null && caseJunction.Case__r.TLO_NAME__c != null) {
                    TLOOfficer tloOfficer = new TLOOfficer(caseJunction.Case__r.TLO_NAME__c, caseJunction.Case__r.TLO_EMAIL__c, caseJunction.Case__r.TLO_MIT_ID__c);
                    Integer casesForTloOfficer = 1;
                    for (TLOOfficer availableTloOfficer : bipPiTloAssignment.availableTloOfficers) {
                        if (availableTloOfficer.mitId == tloOfficer.mitId) {
                            casesForTloOfficer++;
                        }
                    }

                    if (casesForTloOfficer > maxCases) {
                        maxCases = casesForTloOfficer;
                        recommendedTloOfficer = tloOfficer;
                    }

                    if (casesForTloOfficer == 1) {
                        bipPiTloAssignment.availableTloOfficers.add(tloOfficer);
                    }
                }
            }
            bipPiTloAssignment.recommendedTloOfficer = recommendedTloOfficer;

            result.add(bipPiTloAssignment);
        }

        return result;
    }

    @AuraEnabled
    public static Boolean updateBipPiTLOAssignment(List<BIP_PI__c> bipPis) {
        try {
            List<BIP_PI__c> bipPisToUpdate = new List<BIP_PI__c>();
            List<BIP_Request__c> bipRequestsToUpdate = new List<BIP_Request__c>();

            for (BIP_PI__c bipPi : bipPis) {
                BIP_PI__c bipPiToUpdate = new BIP_PI__c(
                        Id = bipPi.Id,
                        TLO_Officer_Email__c = bipPi.TLO_Officer_Email__c,
                        TLO_Officer_MIT_ID__c = bipPi.TLO_Officer_MIT_ID__c,
                        TLO_Officer_Name__c = bipPi.TLO_Officer_Name__c);
                bipPisToUpdate.add(bipPiToUpdate);

                if (bipPi.Role__c == 'Primary PI') {
                    BIP_Request__c bipRequestToUpdate = new BIP_Request__c(
                            Id = bipPi.BIP_Request__c,
                            TLO_Officer_Email__c = bipPi.TLO_Officer_Email__c,
                            TLO_Officer_MIT_ID__c = bipPi.TLO_Officer_MIT_ID__c,
                            TLO_Officer_Name__c = bipPi.TLO_Officer_Name__c,
                            Status__c = 'Assigned to TLO');
                    bipRequestsToUpdate.add(bipRequestToUpdate);
                }
            }

            update bipPisToUpdate;
            update bipRequestsToUpdate;

            return true;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    // DTO Objects
    public class BIPPITLOAssignment {
        @AuraEnabled
        public BIP_PI__c bipPi { get; set; }
        @AuraEnabled
        public List<TLOOfficer> availableTloOfficers { get; set; }
        @AuraEnabled
        public TLOOfficer recommendedTloOfficer { get; set; }

        public BIPPITLOAssignment(BIP_PI__c bipPi, List<TLOOfficer> availableTloOfficers, TLOOfficer recommendedTloOfficer) {
            this.bipPi = bipPi;
            this.availableTloOfficers = availableTloOfficers;
            this.recommendedTloOfficer = recommendedTloOfficer;
        }
    }

    public class TLOOfficer {
        @AuraEnabled
        public String name { get; set; }
        @AuraEnabled
        public String email { get; set; }
        @AuraEnabled
        public String mitId { get; set; }

        public TLOOfficer() {
        }

        public TLOOfficer(String name, String email, String mitId) {
            this.name = name;
            this.email = email;
            this.mitId = mitId;
        }
    }
}