force-app/main/default/objects/BIP_Case_Junction__c/BIP_Case_Junction__c.object-meta.xml
<CustomObject>
    <label>BIP Case Junction</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP Case Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Case Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Case_Junction__c/fields/BIP_PI__c.field-meta.xml
<CustomField>
    <fullName>BIP_PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BIP PI</label>
    <referenceTo>BIP_PI__c</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Case_Junction__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Case_Junction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <length>20</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/BIP_PI__c.object-meta.xml
<CustomObject>
    <label>BIP PI</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP PI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Pis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_PI__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary PI</fullName>
            </value>
            <value>
                <fullName>Additional PI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/TLO_Officer_Email__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Email__c</fullName>
    <label>TLO Officer Email`</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/TLO_Officer_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_MIT_ID__c</fullName>
    <label>TLO Officer MIT ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/TLO_Officer_Name__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Name__c</fullName>
    <label>TLO Officer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <label>Project Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Received</fullName>
                <default>true</default>
                <label>Request Received</label>
            </value>
            <value>
                <fullName>Assigned to TLO</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Assigned to PI</fullName>
            </value>
            <value>
                <fullName>PI Review Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/TLO_Officer_Email__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Email__c</fullName>
    <label>Primary TLO Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/TLO_Officer_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_MIT_ID__c</fullName>
    <label>Primary TLO MIT ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/TLO_Officer_Name__c.field-meta.xml
<CustomField>
    <fullName>TLO_Officer_Name__c</fullName>
    <label>Primary TLO</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/Forrester_Case__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_VIEW</externalName>
    <label>Case</label>
    <pluralLabel>Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case RecId</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/STATUS__c.field-meta.xml
<CustomField>
    <fullName>STATUS__c</fullName>
    <description>STATUS</description>
    <externalDeveloperName>STATUS</externalDeveloperName>
    <label>Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_EMAIL__c.field-meta.xml
<CustomField>
    <fullName>TLO_EMAIL__c</fullName>
    <description>TLO_EMAIL</description>
    <externalDeveloperName>TLO_EMAIL</externalDeveloperName>
    <label>TLO Officer Email</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>TLO_MIT_ID__c</fullName>
    <description>TLO_MIT_ID</description>
    <externalDeveloperName>TLO_MIT_ID</externalDeveloperName>
    <label>TLO MIT Id</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_NAME__c.field-meta.xml
<CustomField>
    <fullName>TLO_NAME__c</fullName>
    <description>TLO_NAME</description>
    <externalDeveloperName>TLO_NAME</externalDeveloperName>
    <label>TLO Officer</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BIPControllerTest.cls
/**
 * Created by Andreas du Preez on 2025/02/07.
 */

@IsTest
public with sharing class BIPControllerTest {
    // Mock class for Forrester_Case__x
    class CaseMock extends ExternalObjectQuery {
        final List<Forrester_Case__x> externalRecords;

        CaseMock(List<Forrester_Case__x> externalRecords) {
            this.externalRecords = externalRecords;
        }

        protected override List<SObject> passThrough(List<SObject> records) {
            return externalRecords;
        }
    }

    @TestSetup
    public static void testSetup() {
        // Insert Mock Data
        // Mock BIP_Request__c record
        BIP_Request__c bipRequest = new BIP_Request__c();
        bipRequest.Status__c = 'Request Received';
        bipRequest.Project_Description__c = 'UNIQUE_TEST_COMMENT1';

        insert bipRequest;

        // Mock BIP_PI__c record
        List<BIP_PI__c> bipPis = new List<BIP_PI__c>();
        BIP_PI__c bipPi1 = new BIP_PI__c();
        bipPi1.Role__c = 'Primary PI';
        bipPi1.Status__c = 'Pending Assignment';
        bipPi1.BIP_Request__c = bipRequest.Id;
        bipPis.add(bipPi1);

        BIP_PI__c bipPi2 = new BIP_PI__c();
        bipPi2.Role__c = 'Additional PI';
        bipPi2.Status__c = 'Pending Assignment';
        bipPi2.BIP_Request__c = bipRequest.Id;
        bipPis.add(bipPi2);

        insert bipPis;

        // Mock BIP_Case_Junction__c records
        List<BIP_Case_Junction__c> bipCaseJunctions = new List<BIP_Case_Junction__c>();
        BIP_Case_Junction__c bipCaseJunction = new BIP_Case_Junction__c();
        bipCaseJunction.BIP_PI__c = bipPi1.Id;
        bipCaseJunction.Case__c = 'testRecId1';
        bipCaseJunctions.add(bipCaseJunction);

        BIP_Case_Junction__c bipCaseJunction2 = new BIP_Case_Junction__c();
        bipCaseJunction2.BIP_PI__c = bipPi1.Id;
        bipCaseJunction2.Case__c = 'testRecId2';
        bipCaseJunctions.add(bipCaseJunction2);

        BIP_Case_Junction__c bipCaseJunction3 = new BIP_Case_Junction__c();
        bipCaseJunction3.BIP_PI__c = bipPi1.Id;
        bipCaseJunction3.Case__c = 'testRecId3';
        bipCaseJunctions.add(bipCaseJunction3);

        BIP_Case_Junction__c bipCaseJunction4 = new BIP_Case_Junction__c();
        bipCaseJunction4.BIP_PI__c = bipPi2.Id;
        bipCaseJunction4.Case__c = 'testRecId4';
        bipCaseJunctions.add(bipCaseJunction4);

        insert bipCaseJunctions;
    }

    private static void setExternalMockData(){
        // Mock Forrester_Case__x records
        List<Forrester_Case__x> mockRecords = new List<Forrester_Case__x>();
        Forrester_Case__x mockRecord1 = new Forrester_Case__x();
        mockRecord1.CASE_RECID__c = 'testRecId1';
        mockRecord1.TLO_NAME__c = 'Test TLO Name 1';
        mockRecord1.TLO_MIT_ID__c = '123';
        mockRecord1.TLO_EMAIL__c = 'test1@email.com';
        mockRecords.add(mockRecord1);

        Forrester_Case__x mockRecord2 = new Forrester_Case__x();
        mockRecord2.CASE_RECID__c = 'testRecId2';
        mockRecord2.TLO_NAME__c = 'Test TLO Name 1';
        mockRecord2.TLO_MIT_ID__c = '123';
        mockRecord2.TLO_EMAIL__c = 'test1@email.com';
        mockRecords.add(mockRecord2);

        Forrester_Case__x mockRecord3 = new Forrester_Case__x();
        mockRecord3.CASE_RECID__c = 'testRecId3';
        mockRecord3.TLO_NAME__c = 'Test TLO Name 3';
        mockRecord3.TLO_MIT_ID__c = '789';
        mockRecord3.TLO_EMAIL__c = 'test3@email.com';
        mockRecords.add(mockRecord3);

        Forrester_Case__x mockRecord4 = new Forrester_Case__x();
        mockRecord4.CASE_RECID__c = 'testRecId4';
        mockRecord4.TLO_NAME__c = 'Test TLO Name 4';
        mockRecord4.TLO_MIT_ID__c = '147';
        mockRecord4.TLO_EMAIL__c = 'test4@email.com';
        mockRecords.add(mockRecord4);

        ExternalObjectQuery.setMock(new CaseMock(mockRecords));
    }

    @IsTest
    public static void testGetBipPisForTLOAssignment() {
        setExternalMockData();
        BIP_Request__c bipRequest = [SELECT Id FROM BIP_Request__c WHERE Project_Description__c = 'UNIQUE_TEST_COMMENT1' LIMIT 1];

        Test.startTest();
        List<BIPController.BIPPITLOAssignment> result = BIPController.getBipPisForTLOAssignment(bipRequest.Id);
        Test.stopTest();

        // Assert
        System.assertEquals(2, result.size());
        for (BIPController.BIPPITLOAssignment bipPiTloAssignment : result) {
            if (bipPiTloAssignment.bipPi.Role__c == 'Primary PI') {
                System.assertEquals(2, bipPiTloAssignment.availableTloOfficers.size());
                System.assertEquals('123', bipPiTloAssignment.recommendedTloOfficer.mitId);
                System.assertEquals('Test TLO Name 1', bipPiTloAssignment.recommendedTloOfficer.name);
            } else {
                System.assertEquals(1, bipPiTloAssignment.availableTloOfficers.size());
                System.assertEquals('147', bipPiTloAssignment.recommendedTloOfficer.mitId);
                System.assertEquals('Test TLO Name 4', bipPiTloAssignment.recommendedTloOfficer.name);
            }
        }
    }

    @IsTest
    public static void testUpdateBipPiTLOAssignment() {
        setExternalMockData();
        BIP_Request__c bipRequest = [SELECT Id FROM BIP_Request__c WHERE Project_Description__c = 'UNIQUE_TEST_COMMENT1' LIMIT 1];
        List<BIPController.BIPPITLOAssignment> result = BIPController.getBipPisForTLOAssignment(bipRequest.Id);

        List<BIP_PI__c> bipPisToUpdate = new List<BIP_PI__c>();
        for (BIPController.BIPPITLOAssignment bipPiTloAssignment : result) {
            bipPiTloAssignment.bipPi.TLO_Officer_MIT_ID__c = bipPiTloAssignment.recommendedTloOfficer.mitId;
            bipPiTloAssignment.bipPi.TLO_Officer_Name__c = bipPiTloAssignment.recommendedTloOfficer.name;
            bipPiTloAssignment.bipPi.TLO_Officer_Email__c = bipPiTloAssignment.recommendedTloOfficer.email;
            bipPisToUpdate.add(bipPiTloAssignment.bipPi);
        }

        Test.startTest();
        Boolean isUpdated = BIPController.updateBipPiTLOAssignment(bipPisToUpdate);
        Test.stopTest();

        List<BIP_PI__c> updatedBipPis = [SELECT Id, TLO_Officer_MIT_ID__c, TLO_Officer_Name__c, TLO_Officer_Email__c, Role__c FROM BIP_PI__c WHERE Id IN :bipPisToUpdate];
        BIP_Request__c updatedBipRequest = [SELECT Id, Status__c FROM BIP_Request__c WHERE Project_Description__c = 'UNIQUE_TEST_COMMENT1' LIMIT 1];

        System.assertEquals(true, isUpdated);
        System.assertEquals(2, updatedBipPis.size());
        System.assertEquals('Assigned to TLO', updatedBipRequest.Status__c);
        for (BIP_PI__c updatedBipPi : updatedBipPis) {
            if (updatedBipPi.Role__c == 'Primary PI') {
                System.assertEquals('123', updatedBipPi.TLO_Officer_MIT_ID__c);
                System.assertEquals('Test TLO Name 1', updatedBipPi.TLO_Officer_Name__c);
                System.assertEquals('test1@email.com', updatedBipPi.TLO_Officer_Email__c);
            } else {
                System.assertEquals('147', updatedBipPi.TLO_Officer_MIT_ID__c);
                System.assertEquals('Test TLO Name 4', updatedBipPi.TLO_Officer_Name__c);
                System.assertEquals('test4@email.com', updatedBipPi.TLO_Officer_Email__c);
            }
        }
    }
}