force-app/main/default/objects/BIP_Case_Junction__c/BIP_Case_Junction__c.object-meta.xml
<CustomObject>
    <label>BIP Case Junction</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP Case Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Case Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Case_Junction__c/fields/BIP_PI__c.field-meta.xml
<CustomField>
    <fullName>BIP_PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BIP PI</label>
    <referenceTo>BIP_PI__c</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Case_Junction__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Case_Junction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <length>20</length>
    <referenceTo>Forrester_Case__x</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/BIP_Case_Junction__c/fields/Primary_PI__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Case Junctions</relationshipLabel>
    <relationshipName>BIP_Case_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/BIP_PI__c.object-meta.xml
<CustomObject>
    <label>BIP PI</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>BIP PI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Pis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_PI__c/fields/BIP_Request__c.field-meta.xml
<CustomField>
    <fullName>BIP_Request__c</fullName>
    <label>BIP Request</label>
    <referenceTo>BIP_Request__c</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/PI__c.field-meta.xml
<CustomField>
    <fullName>PI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Pis</relationshipLabel>
    <relationshipName>BIP_Pis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/PI_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>PI_MIT_ID__c</fullName>
    <formula>PI__r.PersonContact.MitId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PI MIT ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Requested_Action__c.field-meta.xml
<CustomField>
    <fullName>Requested_Action__c</fullName>
    <label>Requested Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request background case review from proposal</fullName>
            </value>
            <value>
                <fullName>Report undisclosed background IP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary PI</fullName>
            </value>
            <value>
                <fullName>Additional PI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_PI__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BIP_Request__c/BIP_Request__c.object-meta.xml
<CustomObject>
    <label>BIP Request</label>
    <nameField>
        <displayFormat>BIP-{0000}</displayFormat>
        <label>BIP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BIP Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIP_Request__c/fields/Primary_PI_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Primary_PI_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary PI</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BIP Requests (Primary PI Lookup)</relationshipLabel>
    <relationshipName>BIP_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIP_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Received</fullName>
                <default>true</default>
                <label>Request Received</label>
            </value>
            <value>
                <fullName>Assigned to TLO</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Assigned to PI</fullName>
            </value>
            <value>
                <fullName>PI Review Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Pending Feedback</fullName>
            </value>
            <value>
                <fullName>Feedback Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/Forrester_Case__x.object-meta.xml
<CustomObject>
    <description>Forrester_Case</description>
    <externalDataSource>Forrester</externalDataSource>
    <externalName>Forrester_SHIR_CASE_VIEW</externalName>
    <label>Case</label>
    <pluralLabel>Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Forrester_Case__x/fields/ANTIC_PUBLISH_DATE__c.field-meta.xml
<CustomField>
    <fullName>ANTIC_PUBLISH_DATE__c</fullName>
    <description>ANTIC_PUBLISH_DATE</description>
    <externalDeveloperName>ANTIC_PUBLISH_DATE</externalDeveloperName>
    <label>Anticipate Published</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_RECID__c.field-meta.xml
<CustomField>
    <fullName>CASE_RECID__c</fullName>
    <description>CASE_RECID</description>
    <externalDeveloperName>CASE_RECID</externalDeveloperName>
    <label>Case RecId</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_SPONSOR_NAMES__c.field-meta.xml
<CustomField>
    <fullName>CASE_SPONSOR_NAMES__c</fullName>
    <description>CASE_SPONSOR_NAMES</description>
    <externalDeveloperName>CASE_SPONSOR_NAMES</externalDeveloperName>
    <label>Sponsor Names</label>
    <length>4000</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CASE_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CASE_TYPE__c</fullName>
    <description>CASE_TYPE</description>
    <externalDeveloperName>CASE_TYPE</externalDeveloperName>
    <label>Case Type</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CO_INVENTORS__c.field-meta.xml
<CustomField>
    <fullName>CO_INVENTORS__c</fullName>
    <description>INVENTOR_S_LN</description>
    <externalDeveloperName>INVENTOR_S_LN</externalDeveloperName>
    <label>Co Inventors</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/CONTRACT_CASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT_CASE_NUM__c</fullName>
    <description>CONTRACT_CASE_NUM</description>
    <externalDeveloperName>CONTRACT_CASE_NUM</externalDeveloperName>
    <label>Case Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/DISCLOSURE_TITLE__c.field-meta.xml
<CustomField>
    <fullName>DISCLOSURE_TITLE__c</fullName>
    <description>DISCLOSURE_TITLE</description>
    <externalDeveloperName>DISCLOSURE_TITLE</externalDeveloperName>
    <label>Disclosure Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/OPEN_DATE__c.field-meta.xml
<CustomField>
    <fullName>OPEN_DATE__c</fullName>
    <description>OPEN_DATE</description>
    <externalDeveloperName>OPEN_DATE</externalDeveloperName>
    <label>Opened</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/PATENT_COUNT__c.field-meta.xml
<CustomField>
    <fullName>PATENT_COUNT__c</fullName>
    <description>PATENT_COUNT</description>
    <externalDeveloperName>PATENT_COUNT</externalDeveloperName>
    <label>Patent Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/STATUS__c.field-meta.xml
<CustomField>
    <fullName>STATUS__c</fullName>
    <description>STATUS</description>
    <externalDeveloperName>STATUS</externalDeveloperName>
    <label>Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_EMAIL__c.field-meta.xml
<CustomField>
    <fullName>TLO_EMAIL__c</fullName>
    <description>TLO_EMAIL</description>
    <externalDeveloperName>TLO_EMAIL</externalDeveloperName>
    <label>TLO Officer Email</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_MIT_ID__c.field-meta.xml
<CustomField>
    <fullName>TLO_MIT_ID__c</fullName>
    <description>TLO_MIT_ID</description>
    <externalDeveloperName>TLO_MIT_ID</externalDeveloperName>
    <label>TLO MIT Id</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forrester_Case__x/fields/TLO_NAME__c.field-meta.xml
<CustomField>
    <fullName>TLO_NAME__c</fullName>
    <description>TLO_NAME</description>
    <externalDeveloperName>TLO_NAME</externalDeveloperName>
    <label>TLO Officer</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetBipWithCases.cls
public with sharing class GetBipWithCases {
    @AuraEnabled
    public static List<SObject> getBipInfo(List<String> recordIds, String reqFrom) {
        try {
            System.debug('recordId-----' + recordIds);
            if (reqFrom == 'parent') {
                BIP_Request__c bipRequest = [
                        SELECT Id, Name, Status__c, Comments__c, Owner.Name, Primary_PI_Lookup__r.Name, (SELECT Case__c FROM BIP_Case_Junctions__r)
                        FROM BIP_Request__c
                        WHERE Id = :recordIds[0]
                        LIMIT 1
                ];

                if(bipRequest.Comments__c!=null){
                    bipRequest.Comments__c = bipRequest.Comments__c.stripHtmlTags();
                }

                // We need to get the Forrester Cases related to the BIP via the External Object:
                Set<String> forresterCaseIds = new Set<String>();
                for (BIP_Case_Junction__c caseJunction : bipRequest.BIP_Case_Junctions__r) {
                    forresterCaseIds.add(caseJunction.Case__c);
                }

                for(Forrester_Case__x forresterCase : getCaseRows(forresterCaseIds)) {
                    for (BIP_Case_Junction__c caseJunction : bipRequest.BIP_Case_Junctions__r) {
                        if (caseJunction.Case__c == forresterCase.CASE_RECID__c) {
                            caseJunction.Case__r = forresterCase;
                        }
                    }
                }

                return new List<SObject>{bipRequest};
            } else {
                List<BIP_PI__c> bipPis = [
                        SELECT Id, Name, Role__c, BIP_Request__c, Status__c, CreatedBy.Name, PI__r.Name, PI_MIT_ID__c, 
                               Comment__c, Requested_Action__c, 
                               (SELECT Case__c FROM BIP_Case_Junctions__r)
                        FROM BIP_PI__c
                        WHERE Id IN :recordIds
                ];

                Set<String> forresterCaseIds = new Set<String>();

                for (BIP_PI__c bipPi : bipPis) {
                    // We need to get the Forrester Cases related to the BIP via the External Object:
                    for (BIP_Case_Junction__c caseJunction : bipPi.BIP_Case_Junctions__r) {
                        forresterCaseIds.add(caseJunction.Case__c);
                    }
                }

                for (Forrester_Case__x forresterCase : getCaseRows(forresterCaseIds)) {

                    for (BIP_PI__c bipPi : bipPis) {
                        for (BIP_Case_Junction__c caseJunction : bipPi.BIP_Case_Junctions__r) {
                            if (caseJunction.Case__c == forresterCase.CASE_RECID__c) {
                                caseJunction.Case__r = forresterCase;
                            }
                        }
                    }
                }

                return bipPis;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static List<Forrester_Case__x> getCaseRows(Set<String> caseRecIds) {
        // Comments are the Column names in the childDetail LWC
        List<Forrester_Case__x> caseList = ExternalObjectQuery.records([
                SELECT Id,
                        CASE_RECID__c,
                        CONTRACT_CASE_NUM__c, // Case Button Label
                        DISCLOSURE_TITLE__c, //Case Title
                        STATUS__c, //Case Status
                        OPEN_DATE__c, //Open Date
                        ANTIC_PUBLISH_DATE__c, //Anticipated Publish Date
                        TLO_NAME__c, //TLO Officer
                        TLO_EMAIL__c, //TLO Email
                        TLO_MIT_ID__c, //TLO MIT ID
                        CASE_TYPE__c, //Case Type
                        CASE_SPONSOR_NAMES__c, //Sponsor Names
                        PATENT_COUNT__c, //Patents/Patent Count
                        CO_INVENTORS__c// Co-Inventors
                FROM Forrester_Case__x
                WHERE CASE_RECID__c IN :caseRecIds
        ]);

        if (caseList.size() > 0) {
            return caseList;
        } else {
            return new List<Forrester_Case__x>();
        }
    }
}