force-app/main/default/objects/Log_Document_Link__c/Log_Document_Link__c.object-meta.xml
<CustomObject>
    <label>Log Document Link Message</label>
    <nameField>
        <displayFormat>LCV-{000000}</displayFormat>
        <label>Log Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Document Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Document_Link__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Document_Link__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Document_Link__c/fields/PathOnClient__c.field-meta.xml
<CustomField>
    <fullName>PathOnClient__c</fullName>
    <label>PathOnClient</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Document_Link__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocumentLinkProcessor.cls
public with sharing virtual class DocumentLinkProcessor {

    public void execute(List<ContentVersion> scope) {
        try {
            if(scope != null && !scope.isEmpty()) {
                createDocumentLink(scope);
            }
        } catch(Exception ex) {
            HandleLogException.logException(ex);
            throw ex;
        }
    }

    protected virtual Log_Document_Link__c getLogDocumentLinkInstance(Id id, String pathOnClient ,String logType, String message){
        Log_Document_Link__c log = new Log_Document_Link__c();
        log.ContentVersion_Id__c = String.valueOf(id);
        log.Type__c = logType;
        log.Message__c = message;
        log.PathOnClient__c = pathOnClient;
        return log;

    }

    @TestVisible
    protected virtual void createDocumentLink(List<ContentVersion> contentVersions) {}

    @TestVisible
    protected virtual FileNameDefinition parsePathOnClient(String pathOnClient) {
        return null;
    }

    @TestVisible
    protected virtual FileNameDefinition parsePathOnClient(String pathOnClient, String entityRecId) {
        return null;
    }

    @TestVisible
    public class FileNameDefinition {
        public String caseNumber;
        public String agreementNumber;
        public String financialYear;
        public String classification;
        public String mitId;
        public DateTime fileWriteDate;
    }

}