force-app/main/default/objects/Configurations__c/Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for storing Configuration Value</description>
    <label>Configurations</label>
</CustomObject>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/BCC__c.field-meta.xml
<CustomField>
    <fullName>BCC__c</fullName>
    <label>BCC</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/CC__c.field-meta.xml
<CustomField>
    <fullName>CC__c</fullName>
    <label>CC</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Failure_Count__c.field-meta.xml
<CustomField>
    <fullName>Failure_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Failure Count</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Variables__c.field-meta.xml
<CustomField>
    <fullName>Variables__c</fullName>
    <label>Variables</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DraftDisclosureReminderTest.cls
@IsTest
public with sharing class DraftDisclosureReminderTest {
    private static Integer firstReminderInDays { get; set; }
    private static Integer secondReminderInDays { get; set; }
    private static Integer thirdReminderInDays { get; set; }

    @TestSetup
    static void setupTestData() {
        TestSetup.defaultConfiguration();
    }

    static void setupReminderValues() {
        Configurations__c reminder1Config = Configurations__c.getInstance(
            'DraftDisclosureReminder_1'
        );
        Configurations__c reminder2Config = Configurations__c.getInstance(
            'DraftDisclosureReminder_2'
        );
        Configurations__c reminder3Config = Configurations__c.getInstance(
            'DraftDisclosureReminder_3'
        );
        firstReminderInDays = Integer.valueOf(reminder1Config.Value__c);
        secondReminderInDays = Integer.valueOf(reminder2Config.Value__c);
        thirdReminderInDays = Integer.valueOf(reminder3Config.Value__c);
    }

    static void setupDraftDisclosure(Integer daysSinceDraftCreated) {
        Id recordTypeIdSoftware = Schema.SObjectType.Disclosure__c.getRecordTypeInfosByDeveloperName()
            .get('Software_Code_Disclosure')
            .getRecordTypeId();
        Account submittingContact = SampleDataFactory.createContact(
            'Jeff',
            true,
            '11345678'
        );
        Disclosure__c disclosure = SampleDataFactory.createDisclosureSOB(
            recordTypeIdSoftware,
            'Sample Draft Software',
            'Draft',
            submittingContact
        );

        // Mock the creation date in the Past
        Date pastedDate = Date.today().addDays(-daysSinceDraftCreated);
        Test.setCreatedDate(disclosure.Id, pastedDate);

        disclosure.Draft_Date__c = pastedDate; // because Archived disclosure's can be moved back to Draft by sys admin
        update disclosure;
    }

    @IsTest
    static void draftDisclosureReminderScheduleTest() {
        setupReminderValues();
        setupDraftDisclosure(thirdReminderInDays);
        Test.startTest();
        // Code Coverage only
        DraftDisclosureReminderSchedule.scheduleMe();
        DraftDisclosureReminderSchedule.abortSchedule();
        Test.stopTest();
    }

    @IsTest
    static void draftDisclosureReminder90DaysTest() {
        setupReminderValues();
        setupDraftDisclosure(thirdReminderInDays);

        Test.startTest();
        assertNotificationCountEquals(0);

        // First Reminder
        mockDatabaseExecuteBatch(new DraftDisclosureReminderBatch());
        assertNotificationCountEquals(1);

        // Second Reminder
        mockDatabaseExecuteBatch(new DraftDisclosureReminderBatch());
        assertNotificationCountEquals(2);

        // Third Reminder, using actual Batch job
        Database.executeBatch(new DraftDisclosureReminderBatch(), 200);

        // This should not create any new Reminders
        mockDatabaseExecuteBatch(new DraftDisclosureReminderBatch());
        Test.stopTest();
        assertNotificationCountEquals(3);
    }

    @IsTest
    static void draftDisclosureReminder60DaysTest() {
        setupReminderValues();
        setupDraftDisclosure(secondReminderInDays);

        Test.startTest();
        assertNotificationCountEquals(0);

        // First Reminder
        mockDatabaseExecuteBatch(new DraftDisclosureReminderBatch());
        assertNotificationCountEquals(1);

        // Second Reminder
        mockDatabaseExecuteBatch(new DraftDisclosureReminderBatch());
        assertNotificationCountEquals(2);

        // Third Reminder, using actual Batch job
        Database.executeBatch(new DraftDisclosureReminderBatch(), 200);

        // This should not create any new Reminders
        mockDatabaseExecuteBatch(new DraftDisclosureReminderBatch());
        Test.stopTest();
        assertNotificationCountEquals(2);
    }

    @IsTest
    static void draftDisclosureReminder30DaysTest() {
        setupReminderValues();
        setupDraftDisclosure(firstReminderInDays);

        Test.startTest();
        assertNotificationCountEquals(0);
        Database.executeBatch(new DraftDisclosureReminderBatch(), 200);
        // This should not create any new Reminders
        mockDatabaseExecuteBatch(new DraftDisclosureReminderBatch());
        Test.stopTest();
        assertNotificationCountEquals(1);

        Date draftDate = Date.today().addDays(-firstReminderInDays);
        String olderThanNDays = ConfigurationBuilder.getConfigurationToString(
            'archiveDraftOlderThan'
        );
        System.debug(draftDate.format() + ' olderThanNDays:' + olderThanNDays);
        Integer nDays = Integer.valueOf(olderThanNDays);
        Date archiveDate = draftDate.addDays(nDays);
        assertNotificationArchiveDate(archiveDate);
    }

    @IsTest
    static void draftDisclosureNoReminderTest() {
        setupReminderValues();
        setupDraftDisclosure(firstReminderInDays - 1);

        Test.startTest();
        assertNotificationCountEquals(0);
        Database.executeBatch(new DraftDisclosureReminderBatch(), 200);
        Test.stopTest();
        assertNotificationCountEquals(0);
    }

    private static void assertNotificationCountEquals(Integer expectedCount) {
        List<Notification__c> testAllNotificationsCreated = [
            SELECT
                Id,
                Name,
                BCC__c,
                CC__c,
                Failure_Count__c,
                Status__c,
                Template__c,
                To__c,
                Variables__c
            FROM Notification__c
            WHERE
                Template__c = :NotificationBuilder.TEMPLATE_DISCLOSURE_DRAFT_REMINDER
        ];
        System.Assert(
            testAllNotificationsCreated.size() == expectedCount,
            expectedCount + ' reminder notifications should have been created'
        );
    }

    private static void assertNotificationArchiveDate(Date expectedDate) {
        List<Notification__c> draftReminderNotifications = [
            SELECT
                Id,
                Name,
                BCC__c,
                CC__c,
                Failure_Count__c,
                Status__c,
                Template__c,
                To__c,
                Variables__c
            FROM Notification__c
            WHERE
                Template__c = :NotificationBuilder.TEMPLATE_DISCLOSURE_DRAFT_REMINDER
        ];

        Map<String, Object> jsonVar = (Map<String, Object>) JSON.deserializeUntyped(
            draftReminderNotifications[0].Variables__c
        );
        System.assertEquals(
            Helpers.formatDate(expectedDate, 'MMM dd, yyyy'),
            String.valueOf(jsonVar.get('archive_date')),
            'archive_date not calculated'
        );
    }

    private static void mockDatabaseExecuteBatch(
        DraftDisclosureReminderBatch batch
    ) {
        Database.QueryLocatorIterator it = batch.start(null).iterator();
        List<Disclosure__c> scopes = new List<Disclosure__c>();
        while (it.hasNext()) {
            Disclosure__c disclosure = (Disclosure__c) it.next();
            scopes.add(disclosure);
        }
        batch.execute(null, scopes);
    }
}