force-app/main/default/objects/Configurations__c/Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for storing Configuration Value</description>
    <label>Configurations</label>
</CustomObject>

force-app/main/default/objects/Configurations__c/fields/Email_Interval_Flag_Field__c.field-meta.xml
<CustomField>
    <fullName>Email_Interval_Flag_Field__c</fullName>
    <label>Email Interval Flag Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Action__c/Contact_Action__c.object-meta.xml
<CustomObject>
    <label>Contact Action</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Contact Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Actions</relationshipLabel>
    <relationshipName>Contact_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Submitting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SubmittedDisclosures</relationshipLabel>
    <relationshipName>SubmittedDisclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/Disclosure_Action__c.object-meta.xml
<CustomObject>
    <label>Disclosure Action</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Action__c/fields/Contact_Action__c.field-meta.xml
<CustomField>
    <fullName>Contact_Action__c</fullName>
    <label>Contact Action</label>
    <referenceTo>Contact_Action__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_1__c.field-meta.xml
<CustomField>
    <fullName>Reminder_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_2__c.field-meta.xml
<CustomField>
    <fullName>Reminder_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_3__c.field-meta.xml
<CustomField>
    <fullName>Reminder_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/recordTypes/Endorse_or_Delegate_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Endorse_or_Delegate_Disclosure</fullName>
    <active>true</active>
    <label>Endorse or Delegate Disclosure</label>
</RecordType>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisclosureDeptHeadEndorseReminder.cls
public with sharing class DisclosureDeptHeadEndorseReminder implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    CreatedDate,
                    Contact_Action__r.Name,
                    Contact_Action__r.Status__c,
                    Contact_Action__c,
                    RecordType.DeveloperName,
                    RecordType.name,
                    Disclosure__c,
                    Disclosure__r.Name,
                    Disclosure__r.Name__c,
                    Disclosure__r.RecordType.Name,
                    Disclosure__r.Submitting_Contact__c,
                    Disclosure__r.Submitting_Contact__r.Id,
                    Disclosure__r.Submitting_Contact__r.Name,
                    Disclosure__r.Submitting_Contact__r.PersonEmail,
                    Disclosure__r.Submitting_Contact__r.AltEmail__pc,
                    Contact_Action__r.Contact__r.PersonEmail,
                    Contact_Action__r.Contact__r.Name,
                    Reminder_1__c,
                    Reminder_2__c,
                    Reminder_3__c
                FROM Disclosure_Action__c
                WHERE
                    Contact_Action__r.Status__c = 'Pending'
                    AND CreatedDate = LAST_N_DAYS:30
            ]
        );
    }

    public void execute(
        Database.BatchableContext bc,
        List<Disclosure_Action__c> scope
    ) {
        Set<String> disclosureIds = new Set<String>();
        try {
            List<Notification__c> sendNotificationEmail = new List<Notification__c>();
            List<Disclosure_Action__c> updateDisclosureAction = new List<Disclosure_Action__c>();

            for (Disclosure_Action__c action : scope) {
                Datetime nowdate = Util.now();

                Datetime cdate = action.CreatedDate;
                Integer daysBetween = cdate.Date().daysBetween(nowdate.Date());
                String configInstance =
                    'DisclosureDeptHeadEndtReminder_' +
                    daysBetween +
                    '_Days';

                if (
                    action.RecordType.DeveloperName ==
                    'Endorse_or_Delegate_Disclosure'
                ) {
                    Configurations__c config = Configurations__c.getInstance(
                        configInstance
                    );
                    if (config == null) {
                        // We dont have a reminder configured for this time period
                        continue;
                    }

                    Boolean hasReminderEmailBeenSent = (Boolean) action.get(
                        config.Email_Interval_Flag_Field__c
                    );
                    if (
                        daysBetween == Integer.valueOf(config.Value__c) &&
                        !hasReminderEmailBeenSent
                    ) {
                        Map<String, String> variables = new Map<String, String>();
                        variables.put(
                            'disclosure_name',
                            action.Disclosure__r.Name
                        );
                        variables.put(
                            'disclosure_title',
                            action.Disclosure__r.Name__c
                        );
                        variables.put(
                            'dlc_name',
                            action.Contact_Action__r.Contact__r.Name
                        );
                        variables.put(
                            'disclosure_type',
                            action.Disclosure__r.RecordType.Name
                        );
                        variables.put(
                            'outstanding',
                            String.valueOf(daysBetween)
                        );
                        variables.put(
                            'submitter_name',
                            action.Disclosure__r.Submitting_Contact__r.Name
                        );

                        sendNotificationEmail.add(
                            NotificationBuilder.buildNotificationEmail(
                                action.Contact_Action__r.Contact__r.PersonEmail,
                                NotificationBuilder.TEMPLATE_DEPT_HEAD_ENDORSEMENT_REMINDER,
                                variables
                            )
                        );

                        action.put(config.Email_Interval_Flag_Field__c, true);
                        updateDisclosureAction.add(action);
                    }
                }
            }

            if (
                sendNotificationEmail != null &&
                !sendNotificationEmail.isEmpty()
            ) {
                insert sendNotificationEmail;
            }

            if (
                updateDisclosureAction != null &&
                !updateDisclosureAction.isEmpty()
            ) {
                update updateDisclosureAction;
            }
        } catch (Exception ex) {
            HandleLogException.logException(ex);
        }
    }

    public void finish(Database.BatchableContext bc) {
        system.debug('IN FINISH METHOD');
    }
}