force-app/main/default/objects/Configurations__c/Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for storing Configuration Value</description>
    <label>Configurations</label>
</CustomObject>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/BCC__c.field-meta.xml
<CustomField>
    <fullName>BCC__c</fullName>
    <label>BCC</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/CC__c.field-meta.xml
<CustomField>
    <fullName>CC__c</fullName>
    <label>CC</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Failure_Count__c.field-meta.xml
<CustomField>
    <fullName>Failure_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Failure Count</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Variables__c.field-meta.xml
<CustomField>
    <fullName>Variables__c</fullName>
    <label>Variables</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SendEmailJob.cls
public with sharing class SendEmailJob implements Queueable, Database.AllowsCallouts  {

    public final Id notificationId;

    public SendEmailJob(Id notificationId) {
        this.notificationId = notificationId;
    }

    public List<Notification__c> start(QueueableContext ctx) {
        System.debug('SendEmailJob:start ' + ctx.getJobId());
        // Ensure we still have a Pending Notification.
        return [ SELECT To__c, BCC__c, CC__c, Template__c, Variables__c, Status__c, Failure_Count__c
                                         FROM Notification__c
                                         WHERE Status__c = 'Pending' AND Id = :notificationId  ];

    }

    public void execute(QueueableContext ctx) {
         List<Notification__c> scope = start(ctx);

         try {
            if(scope != null && !scope.isEmpty()) {
                // You have uncommitted work pending. Please commit or rollback before calling out
                Notification__c notification = scope[0];
                Email.sendEmail(notification.To__c.split(','), notification.Template__c,
                                NotificationBuilder.deserializeVariables(notification.Variables__c),
                                (notification.CC__c != null) ? notification.CC__c.split(',') : null,
                                (notification.BCC__c != null) ?  notification.BCC__c.split(',') : null,
                                notification.Id);
            }
        } catch (Exception e) {
            Configurations__c config = Configurations__c.getInstance('Notification_Retry');
            if(config != null) {
                Integer count = config.Value__c != null ? Integer.valueOf(config.Value__c) : 0;
                Notification__c notification = scope[0];
                if (notification.Failure_Count__c < count) {
                    update new Notification__c(Id = notification.Id, Failure_Count__c = (notification.Failure_Count__c + 1));
                } else {
                    update new Notification__c(Id = notification.Id, Status__c = 'Failed');
                }
            }
        }
    }

}