force-app/main/default/objects/Configurations__c/Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for storing Configuration Value</description>
    <label>Configurations</label>
</CustomObject>

force-app/main/default/objects/Configurations__c/fields/Email_Interval_Flag_Field__c.field-meta.xml
<CustomField>
    <fullName>Email_Interval_Flag_Field__c</fullName>
    <label>Email Interval Flag Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Action__c/Contact_Action__c.object-meta.xml
<CustomObject>
    <label>Contact Action</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Contact Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Account must be a Person Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Actions</relationshipLabel>
    <relationshipName>Contact_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/Disclosure__c.object-meta.xml
<CustomObject>
    <label>Disclosure</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Disclosure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>TLO Case Number</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Disclosure Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disclosure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventor Submitted</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Department Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disclosure__c/recordTypes/BioTang_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>BioTang_Disclosure</fullName>
    <active>true</active>
    <label>Biological and Tangible Property</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/recordTypes/Copyright_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Copyright_Disclosure</fullName>
    <active>true</active>
    <label>Copyright</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/recordTypes/Invention_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Invention_Disclosure</fullName>
    <active>true</active>
    <label>Invention</label>
</RecordType>

force-app/main/default/objects/Disclosure__c/recordTypes/Software_Code_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Software_Code_Disclosure</fullName>
    <active>true</active>
    <label>Software Code</label>
</RecordType>

force-app/main/default/objects/Disclosure_Action__c/Disclosure_Action__c.object-meta.xml
<CustomObject>
    <label>Disclosure Action</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>Disclosure Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disclosure Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disclosure_Action__c/fields/Contact_Action__c.field-meta.xml
<CustomField>
    <fullName>Contact_Action__c</fullName>
    <label>Contact Action</label>
    <referenceTo>Contact_Action__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Disclosure__c.field-meta.xml
<CustomField>
    <fullName>Disclosure__c</fullName>
    <label>Disclosure</label>
    <referenceTo>Disclosure__c</referenceTo>
    <relationshipLabel>Disclosure Actions</relationshipLabel>
    <relationshipName>Disclosure_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_1__c.field-meta.xml
<CustomField>
    <fullName>Reminder_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_2__c.field-meta.xml
<CustomField>
    <fullName>Reminder_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/fields/Reminder_3__c.field-meta.xml
<CustomField>
    <fullName>Reminder_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Disclosure_Action__c/recordTypes/Sign_Disclosure.recordType-meta.xml
<RecordType>
    <fullName>Sign_Disclosure</fullName>
    <active>true</active>
    <label>Sign Disclosure</label>
</RecordType>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisclosureInventorSignReminder.cls
public with sharing class DisclosureInventorSignReminder implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Configurations__c config = Configurations__c.getInstance(
            'InventorLast_N_Days'
        );
        Integer numberOfDays = 31;
        Integer maximumNumberOfDays = 120;
        if (config != null) {
            numberOfDays = Integer.valueOf(config.Value__c) - 1;
        }
        Date dateFrom = System.today().addDays(-numberOfDays);
        Date maximumDateFrom = System.today().addDays(-maximumNumberOfDays);
        String status = 'Pending';

        Database.QueryLocator queryLocator = Database.getQueryLocator(
            [
                SELECT
                    Id,
                    CreatedDate,
                    Reminder_1__c,
                    Reminder_2__c,
                    Reminder_3__c,
                    Contact_Action__c,
                    Contact_Action__r.Name,
                    Contact_Action__r.Status__c,
                    Contact_Action__r.Contact__r.InvitationCode__pc,
                    Contact_Action__r.Contact__r.MoiraStatus__pc,
                    Contact_Action__r.Contact__r.IsAlumni__pc,
                    Contact_Action__r.Contact__r.Name,
                    Contact_Action__r.Contact__r.PersonEmail,
                    Disclosure__c,
                    Disclosure__r.RecordTypeId,
                    Disclosure__r.RecordType.name,
                    Disclosure__r.Name,
                    Disclosure__r.Name__c,
                    Disclosure__r.Case_Number__c,
                    RecordType.DeveloperName,
                    RecordType.name
                FROM Disclosure_Action__c
                WHERE
                    Contact_Action__r.Status__c = :status
                    AND CreatedDate < :dateFrom
                    AND CreatedDate > :maximumDateFrom
                    AND Reminder_3__c = FALSE
            ]
        );

        System.debug(queryLocator.getQuery() + '--' + numberOfDays);
        return queryLocator;
    }

    public void execute(
        Database.BatchableContext bc,
        List<Disclosure_Action__c> scope
    ) {
        Set<String> disclosureIds = new Set<String>();
        try {
            List<Notification__c> sendNotificationEmail = new List<Notification__c>();
            List<Disclosure_Action__c> updateDisclosureAction = new List<Disclosure_Action__c>();
            Configurations__c lastReminderConfig = Configurations__c.getInstance('DisclosureInventorSignReminder_30_Days');
            Integer lastReminderInDays = Integer.valueOf(lastReminderConfig.Value__c); // Throw exception if null

            for (Disclosure_Action__c action : scope) {
                Datetime nowdate = Util.now();

                Datetime cdate = action.CreatedDate;
                Integer daysBetween = cdate.Date().daysBetween(nowdate.Date());
                String configInstance =
                    'DisclosureInventorSignReminder_' +
                    daysBetween +
                    '_Days';

                System.debug('Record Type:' + action.recordType.DeveloperName);
                if (action.RecordType.DeveloperName == 'Sign_Disclosure') {
                    Configurations__c config;
                    // If the days between is greater or equal to the last reminder days, use the last reminder config
                    if (daysBetween >= lastReminderInDays) {
                        config = lastReminderConfig;
                    }
                    else {
                        config = Configurations__c.getInstance(configInstance);
                    }

                    if (config == null) {
                        // We dont have a reminder configured for this time period
                        continue;
                    }
                    String emailTemplateName = NotificationBuilder.TEMPLATE_DISCLOSURE_SIGNATURE_REMINDER;

                    Boolean hasReminderEmailBeenSent = (Boolean) action.get(
                        config.Email_Interval_Flag_Field__c
                    );
                    if (
                        (daysBetween == Integer.valueOf(config.Value__c) || daysBetween >= lastReminderInDays) &&
                        !hasReminderEmailBeenSent
                    ) {
                        Map<String, Object> variables = new Map<String, Object>();
                        variables.put(
                            'disclosure_name',
                            action.Disclosure__r.Name
                        );
                         if (action.Disclosure__r.Case_Number__c != null) {
                            variables.put(
                                'case_number',
                                action.Disclosure__r.Case_Number__c
                            );
                        }
                        variables.put(
                            'disclosure_title',
                            action.Disclosure__r.Name__c
                        );
                        variables.put(
                            'inventor_name',
                            action.Contact_Action__r.Contact__r.Name
                        );
                        variables.put(
                            'inventor_email',
                            action.Contact_Action__r.Contact__r.PersonEmail
                        );
                        variables.put(
                            'outstanding',
                            String.valueOf(daysBetween)
                        );
                        if (
                            action.Contact_Action__r.Contact__r.InvitationCode__pc !=
                            null
                        ) {
                            variables.put(
                                'invitation_code',
                                action.Contact_Action__r.Contact__r.InvitationCode__pc
                            );
                        }
                        Boolean isActiveKerb = Helpers.isActiveKerb(
                            action.Contact_Action__r.Contact__r.MoiraStatus__pc
                        );
                        variables.put('isActiveKerb', isActiveKerb);
                        variables.put('isAlumni', action.Contact_Action__r.Contact__r.IsAlumni__pc);
                        variables.put(
                            'disclosure_type',
                            getDisclosureTypeName(action)
                        );
                        variables.put(
                            'inventor_description_copy',
                            getContributorInventorAuthorName(action)
                        );

                        sendNotificationEmail.add(
                            NotificationBuilder.buildNotificationEmail(
                                action.Contact_Action__r.Contact__r.PersonEmail,
                                emailTemplateName,
                                variables
                            )
                        );

                        action.put(config.Email_Interval_Flag_Field__c, true);
                        updateDisclosureAction.add(action);
                    }
                }
            }
            if (
                sendNotificationEmail != null &&
                !sendNotificationEmail.isEmpty()
            ) {
                insert sendNotificationEmail;
            }
            if (
                updateDisclosureAction != null &&
                !updateDisclosureAction.isEmpty()
            ) {
                update updateDisclosureAction;
            }
        } catch (Exception ex) {
            HandleLogException.logException(ex);
        }
    }

    public void finish(Database.BatchableContext bc) {
    }

    // The template does not use BioTang but 'Tangible'
    public static String getDisclosureTypeName(Disclosure_Action__c action) {
        if (action.Disclosure__r.recordTypeId != null) {
            String recordTypeName = Schema.getGlobalDescribe()
                .get('Disclosure__c')
                .getDescribe()
                .getRecordTypeInfosById()
                .get(action.Disclosure__r.recordTypeId)
                .getDeveloperName();

            if (recordTypeName != null) {
                if (recordTypeName == 'BioTang_Disclosure') {
                    return Label.Disclosure_Type_Notify_BioTang;
                }
            }
        }
        return action.Disclosure__r.RecordType.Name;
    }

    // TLOS-3548
    public static String getContributorInventorAuthorName(
        Disclosure_Action__c action
    ) {
        if (action.Disclosure__r.recordTypeId != null) {
            String recordTypeName = Schema.getGlobalDescribe()
                .get('Disclosure__c')
                .getDescribe()
                .getRecordTypeInfosById()
                .get(action.Disclosure__r.recordTypeId)
                .getDeveloperName();

            if (recordTypeName != null) {
                if (recordTypeName == 'BioTang_Disclosure') {
                    return Label.Disclosure_Notify_Inventor_Desc_Copy_BioTang;
                } else if (recordTypeName == 'Invention_Disclosure') {
                    return Label.Disclosure_Notify_Inventor_Desc_Copy_Invention;
                } else if (
                    recordTypeName == 'Copyright_Disclosure' ||
                    recordTypeName == 'Software_Code_Disclosure'
                ) {
                    return Label.Disclosure_Notify_Inventor_Desc_Copy_Copyright;
                } else if (
                    recordTypeName == 'Copyright_Disclosure' ||
                    recordTypeName == 'Software_Code_Disclosure'
                ) {
                    return Label.Disclosure_Notify_Inventor_Desc_Copy_Software;
                }
            }
        }
        return 'co-inventor/author';
    }
}